In [41]:
import sklearn
from sklearn.datasets import load_iris 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [42]:
import pandas as pd

iris = load_iris()

iris_data = iris.data # 피처 : 꽃받힘의 너비 길이 , 꽃잎의 너비 길이
iris_label = iris.target # 아이리스 품종 : 정답

print("iris target: " , iris_label)
print("iris target 명 : ", iris.target_names)

iris target:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 :  ['setosa' 'versicolor' 'virginica']

In [43]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [44]:
from sklearn.datasets import load_iris

iris = load_iris()

print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), 'frame': None, 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'), 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...', 'feature_names': ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'], 'filename': 'iris.csv', 'data_module': 'sklearn.datasets.data'}

In [45]:
import pandas as pd

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["target"] = iris.target

print(df.head(10))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

   target
0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0

In [46]:
iris_df = pd . DataFrame(data=iris_data,columns=iris.feature_names)
iris_df["label"] = iris.target

iris_df.head()

## iris 데이터의 형태 : 150개의 샘플과 4개의 특성

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [47]:
print(iris.data[0])
print(iris.target[0])
print(iris.target_names[iris.target[0]])

# 샘플 1번의 붓꽃의 특징

[5.1 3.5 1.4 0.2]
0
setosa

train_test_split() : 머신러닝에서 데이터를 학습용 데이터와 테스트용 데이터로 나누는 함수

> 훈련 데이터(Train): 문제와 정답을 보면서 공부하는 데이터
> 테스트 데이터(Test): 공부에 사용하지 않고, 실력을 평가하는 데이터

>> test_size = 0.2 ==> 전체의 20%를 테스트용으로 사용

>> random_state = 아무 숫자 ==>	실행할 때마다 같은 방식으로 분할하도록 설정

>>>X_train :훈련용 문제 (모델이 학습할 꽃의 특징 데이터)

>>>X_test : 테스트용 문제 (학습에 사용하지 않고 평가할 꽃의 특징 데이터)

>>>y_train : 훈련용 정답 (훈련 데이터에 대응하는 품종 번호)

>>>y_test : 테스트용 정답 (모델의 예측 결과가 맞는지 비교할 실제 정답)


x는 문제, y는 정답


((대문자 X는 여러 특징을 가진 2차원 데이터, 소문자 y는 보통 1차원 정답 데이터)) ##근데 이미 난 대문자 Y로 해버려서,,,

In [48]:
# 학습셋과 테스트 셋으로 나누기

X_train, X_test, Y_train, Y_test = train_test_split(iris_data, iris_label, test_size=0.2,train_size=0.8, random_state=1)

In [49]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)

DecisionTreeClassifier :  의사결정나무(Decision Tree) 알고리즘을 이용해 데이터를 분류하는 머신러닝 모델
fit() : 모델을 학습시키는 함수
predict() : 학습된 모델에 새로운 특징 데이터를 넣어서 예측 결과를 반환하는 메서드

In [50]:
dt_clf = DecisionTreeClassifier(random_state=1)

In [51]:
dt_clf.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=1)

In [52]:
pred = dt_clf.predict(X_test)

In [53]:
pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

pred 값이 30개인 이유 
> X_test의 예측값, 전체 데이터의 0.2% == 30개
> 학습이 끝난 모델의 테스트 데이터가 30개


accuracy_score : 분류 모델이 예측한 결과가 실제 정답과 얼마나 일치하는지 계산하는 함수 (예측 정확도)

In [54]:
from sklearn.metrics import accuracy_score
print("예측 정확도 : ", accuracy_score(Y_test, pred))

예측 정확도 :  0.9666666666666667

KFold : 데이터를 여러 묶음으로 나누어 모델을 반복적으로 학습하고 평가할 수 있게 해주는 도구

>> KFold(n_splits = 5)  n_splits = 의 수만큼 묶음을 만듬
>> cv_accuracy = []	각 반복에서 측정한 정확도를 저장할 빈 리스트

구분	        train_test_split()     	  KFold--> 결과적으로 모든 데이터가 테스트데이터로 사용됨
분할 방식     	한 번 나눔	             여러 번 나눔
테스트 데이터	 보통 한 번 사용     	각 묶음이 한 번씩 사용
목적	       기본적인 학습·평가    	평가 결과의 안정성 확인
결과	       한 번의 평가 결과        	여러 평가 결과

In [55]:
from sklearn.model_selection import KFold
import numpy as np

Kfold = KFold(n_splits = 5)
cv_accuracy = []

In [56]:
n_iter = 0  # 반복 횟수를 세기 위한 변수
features = iris.data #붓꽃의 4가지 측정값
label = iris.target #붓꽃의 실제 품종 번호
cv_accuracy = [] #각 반복의 정확도를 저장할 빈 리스트

# Kfold.split(features)--> 인덱스 배열 2개를 반환
# train_index: 학습에 사용할 데이터의 행 번호 
# test_index: 검증에 사용할 데이터의 행 번호 
# # 만약 10개의 데이터가 있다면 
# # train_index: 학습에 사용할 8개의 데이터 위치
# # test_index: 검증에 사용할 2개의 데이터 위치


for train_index, test_index in Kfold.split(features):  #데이터를 학습용과 검증용으로 나눌 때마다 두 개의 인덱스 목록
    X_train, X_test = features[train_index],features[test_index] #X_train, Y_train: 모델을 학습시킬 입력과 모델의 예측이 맞는 지 확인할 입력
    Y_train, Y_test = label[train_index],label[test_index] #X_test, Y_test: 모델을 학습시킬 정답과 학습에 사용하지 않고, 모델의 예측이 얼마나 맞는지 확인할 정답

    dt_clf.fit(X_train,Y_train) #결정 트리 모델이 학습 데이터를 보고 입력과 정답의 관계를 학습
    pred = dt_clf.predict(X_test) #학습된 모델에 검증용 문제 X_test를 보여주고 예측 결과를 받아 pred에는 모델이 예상한 정답들 저장
    n_iter += 1

    accuracy = np.round(accuracy_score(Y_test,pred),4) #예측 pred와 실제 정답 Y_test를 비교해 정확도를 계산

    train_size = X_train.shape[0] #.shape[0]은 배열의 행 개수, 즉 데이터 샘플 수
    test_size =X_test.shape[0]
    print("교차검증 정확도 : ",accuracy)
    print("학습 데이터 크기 : ",train_size)
    print("검증데이터크기 : ",test_size)
    cv_accuracy.append(accuracy)
     
print("평균 검증 정확도",np.mean(cv_accuracy)) #모든 반복이 끝난 뒤 정확도들의 평균을 계산.이게 이 교차검증 실행에서 모델이 보인 평균 검증 정확도

교차검증 정확도 :  1.0
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정확도 :  1.0
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정확도 :  0.9
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정확도 :  0.9333
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정확도 :  0.7333
학습 데이터 크기 :  120
검증데이터크기 :  30
평균 검증 정확도 0.91332

In [57]:
iris_df["label"].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [58]:
# stratifiedKFold -->각 데이터 묶음에 품종별 비율이 비슷하게 유지되도록 나두면서 데이터를 나눔

In [59]:
#####################

from sklearn.model_selection import StratifiedKFold

# 레이블 비율을 유지하는 3-Fold 교차 검증
skf = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=1
)

# n_splits=3: 데이터를 3개의 Fold로 나눕니다. 매 반복마다 2개 Fold는 학습에, 나머지 1개 Fold는 검증에 사용합니다.
# shuffle=True: 분할하기 전에 데이터 순서를 섞습니다. 원래 데이터가 레이블별로 정렬돼 있을 때, 그 순서의 영향을 줄이는 데 도움이 됩니다.
# random_state=1: 섞는 순서를 고정합니다. 같은 데이터와 설정으로 실행하면 같은 방식으로 나뉘어 결과를 재현할 수 있습니다. 숫자 1 자체가 특별한 의미를 갖는 것은 아닙니다.

n_iter = 0

for train_index, test_index in skf.split(iris_df.drop(columns=["label"]),iris_df["label"]):

# skf.split(X, y)에 두 가지를 전달
# iris_df.drop(columns=["label"]): label 열을 뺀 특성 데이터 X입니다. 모델에 입력할 꽃의 측정값 등이 여기에 들어갑니다.
# iris_df["label"]: 각 행의 레이블 y, 즉 정답입니다.
# split은 각 반복에서 train_index와 test_index를 만들어 줍니다. 이 값들은 데이터 자체가 아니라, 각 부분에 들어갈 행의 위치 번호입니다.
# Stratified K-Fold는 y의 레이블 비율을 참고해 데이터를 나눕니다. 각 레이블이 학습용과 검증용에 골고루 들어가도록 하려는 것입니다.

    n_iter += 1

    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df["label"].iloc[test_index]
#     train_index와 test_index를 이용해 학습용과 검증용 레이블만 가져옵니다.
#     여기서 .iloc[...]은 행 이름이 아니라 행의 위치 번호로 선택한다는 뜻입니다. 
#     이 코드에서는 레이블 분포만 출력하므로 특성 데이터는 실제로 가져오지 않습니다.

    print(f"\n[{n_iter}번째 Fold]")
    print("학습 레이블 데이터 분포:")
    print(label_train.value_counts().sort_index())

    print("검증 레이블 데이터 분포:")
    print(label_test.value_counts().sort_index())

[1번째 Fold]
학습 레이블 데이터 분포:
0    33
1    33
2    34
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
1    17
2    16
Name: label, dtype: int64

[2번째 Fold]
학습 레이블 데이터 분포:
0    33
1    34
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
1    16
2    17
Name: label, dtype: int64

[3번째 Fold]
학습 레이블 데이터 분포:
0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    16
1    17
2    17
Name: label, dtype: int64

In [60]:
from IPython.display import display

features = iris_df.drop(columns=["label"])

n_iter = 0

for train_index, test_index in skf.split(features, iris_df["label"]):
    n_iter += 1

    # 해당 Fold의 실제 데이터 행 선택
    train_samples = iris_df.iloc[train_index].copy()
    test_samples = iris_df.iloc[test_index].copy()

    print(f"\n[{n_iter}번째 Fold] 학습 샘플 앞 5개")
    display(train_samples.head())

    print(f"[{n_iter}번째 Fold] 검증 샘플 앞 5개")
    display(test_samples.head())

[1번째 Fold] 학습 샘플 앞 5개

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
6,4.6,3.4,1.4,0.3,0

[1번째 Fold] 검증 샘플 앞 5개

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
19,5.1,3.8,1.5,0.3,0
25,5.0,3.0,1.6,0.2,0
27,5.2,3.5,1.5,0.2,0

[2번째 Fold] 학습 샘플 앞 5개

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0

[2번째 Fold] 검증 샘플 앞 5개

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
7,5.0,3.4,1.5,0.2,0
9,4.9,3.1,1.5,0.1,0
10,5.4,3.7,1.5,0.2,0
12,4.8,3.0,1.4,0.1,0

[3번째 Fold] 학습 샘플 앞 5개

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
4,5.0,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
7,5.0,3.4,1.5,0.2,0
9,4.9,3.1,1.5,0.1,0

[3번째 Fold] 검증 샘플 앞 5개

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
6,4.6,3.4,1.4,0.3,0
8,4.4,2.9,1.4,0.2,0

In [61]:
##Iris 꽃 데이터를 3개 Fold로 나누어 결정 트리를 학습하고, 각 Fold의 정확도와 평균 정확도를 구하는 코드

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import numpy as np

n_iter = 0
cv_accuracy = []

features = iris.data #features: 꽃받침 길이·너비와 꽃잎 길이·너비처럼 모델이 참고할 값들
label = iris.target #label: 각 꽃이 어느 품종인지 나타내는 정답입니다. Iris 데이터에서는 보통 0, 1, 2로 표현

dt_clf = DecisionTreeClassifier(random_state=1) # 결정 트리 분류기를 만듬. 아직 학습은 하지 않은 상태

for train_index, test_index in skf.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    Y_train, Y_test = label[train_index], label[test_index]

    # 모델 학습
    dt_clf.fit(X_train, Y_train) # 결정 트리가 학습용 데이터의 특성과 정답을 보고 분류 규칙을 학습

    # 검증 데이터 예측
    pred = dt_clf.predict(X_test) # 학습한 모델에 검증용 특성 X_test를 넣고 품종을 예측

    # 정확도 계산
    accuracy = accuracy_score(Y_test, pred)
    cv_accuracy.append(accuracy)

    n_iter += 1
    print(f"{n_iter}번째 Fold 정확도: {accuracy:.4f}")

print(f"\n평균 교차 검증 정확도: {np.mean(cv_accuracy):.4f}")

1번째 Fold 정확도: 0.9600
2번째 Fold 정확도: 0.9400
3번째 Fold 정확도: 0.9200

평균 교차 검증 정확도: 0.9400

In [62]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dt_clf, features, label, scoring = "accuracy",cv = skf)

print("교차 검증별 정확도 : ", np.round(scores , 4))
print("평균 검증 정확도 : ", np.round(np.mean(scores) , 4))

교차 검증별 정확도 :  [0.96 0.94 0.92]
평균 검증 정확도 :  0.94

In [ ]:
# Iris 데이터를 학습용과 테스트용으로 나누고 결정 트리의 여러 설정 후보를 딕셔너리에 저장합니다.
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    iris.data,
    iris.target,
    test_size=0.2,
    random_state=121,
    stratify=iris.target
)
#이 딕셔너리에는 결정 트리에서 시험해 볼 설정값 후보가 들어 있습니다.
# - max_depth: 나무가 얼마나 깊게 자랄 수 있는지 제한합니다. 값이 작으면 나무가 단순해지고, 값이 크면 더 복잡한 규칙을 만들 수 있습니다.
# - min_samples_split: 어떤 노드를 더 나눌 때 필요한 최소 샘플 수입니다. 예를 들어 3이면, 노드에 샘플이 3개 미만일 때는 그 노드를 더 분할하지 않습니다.
parameters = {
    "max_depth": [1, 2, 3], # 의사결정나무의 최대 깊이 후보
    "min_samples_split": [2, 3]# 노드를 분할하기 위한 최소 샘플 수 후보
}
#두 설정을 모든 조합으로 시험한다면 총 3 × 2 = 6가지 조합

In [64]:
# 앞에서 만든 하이퍼파라미터 후보를 하나씩 시험해서 가장 좋은 결정 트리 설정을 찾고, 각 설정의 교차검증 결과를 표로 보여줌
from sklearn.model_selection import GridSearchCV

# 의사결정나무 분류 모델 생성
dtree = DecisionTreeClassifier(random_state=156) # 결정 트리 분류

# GridSearchCV : 지정한 설정 후보들의 모든 조합을 시험하고, 교차검증 점수를 비교하는 도구

grid_dtree = GridSearchCV(
    estimator=dtree,
    param_grid=parameters,
    cv=3,
    scoring="accuracy",
    refit=True
)
# estimator=dtree: 시험할 모델로 위에서 만든 결정 트리를 사용합니다.
# param_grid=parameters: 앞에서 만든 후보값을 사용합니다.
# max_depth 3가지와 min_samples_split 2가지의 조합, 총 6가지를 시험합니다.
# cv=3: 학습 데이터를 3개 조각으로 나누는 3-Fold 교차검증을 사용합니다.
# 한 조각씩 검증에 쓰고 나머지 두 조각으로 학습하는 과정을 각 설정마다 세 번 반복합니다.
# scoring="accuracy": 조합을 비교할 때 정확도를 기준으로 삼습니다.
# refit=True: 교차검증으로 가장 좋은 설정을 찾은 뒤, 그 설정을 사용해 전체 학습 데이터 X_train, Y_train으로 모델을 다시 학습합니다.
# 이 최종 모델은 grid_dtree.best_estimator_에서 확인할 수 있습니다.

grid_dtree.fit(X_train, Y_train)

# 각 하이퍼파라미터 조합의 교차 검증 결과를 데이터프레임으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)

scores_df[
    [
        "params",
        "mean_test_score",
        "rank_test_score",
        "split0_test_score",
        "split1_test_score",
        "split2_test_score"
    ]
]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.658333,5,0.650,0.675,0.65
1,"{'max_depth': 1, 'min_samples_split': 3}",0.658333,5,0.650,0.675,0.65
2,"{'max_depth': 2, 'min_samples_split': 2}",0.925000,3,0.975,0.950,0.85
3,"{'max_depth': 2, 'min_samples_split': 3}",0.925000,3,0.975,0.950,0.85
4,"{'max_depth': 3, 'min_samples_split': 2}",0.933333,1,1.000,0.950,0.85
5,"{'max_depth': 3, 'min_samples_split': 3}",0.933333,1,1.000,0.950,0.85

In [65]:
# 조합을 교차 검증으로 평가하는 GridSearchCV 불러오기
from sklearn.model_selection import GridSearchCV

dtree = DecisionTreeClassifier(random_state=156)
# 조합별 모델 성능을 비교하도록 설정
grid_dtree = GridSearchCV(
    estimator=dtree,
    param_grid=parameters,
    cv=3,
    scoring="accuracy",
    refit=True
)

grid_dtree.fit(X_train, Y_train) # 후보들을 실제로 실험하


# 탐색 및 교차 검증 실행
scores_df = pd.DataFrame(grid_dtree.cv_results_)

# cv_results_에는 각 조합의 교차검증 결과

scores_df[
    [
        "params",
        "mean_test_score",
        "rank_test_score",
        "split0_test_score",
        "split1_test_score",
        "split2_test_score"
    ]
]

# params: 해당 행에서 시험한 하이퍼파라미터 조합
# mean_test_score: 세 번의 Fold 정확도 평균
# rank_test_score: 평균 점수 순위. 1이 가장 좋은 조합입니다.
# split0_test_score: 첫 번째 Fold의 정확도
# split1_test_score: 두 번째 Fold의 정확도
# split2_test_score: 세 번째 Fold의 정확도

# 하이퍼파라미터는 모델이 데이터를 학습하기 전에 사람이 정해 주는 설정값

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.658333,5,0.650,0.675,0.65
1,"{'max_depth': 1, 'min_samples_split': 3}",0.658333,5,0.650,0.675,0.65
2,"{'max_depth': 2, 'min_samples_split': 2}",0.925000,3,0.975,0.950,0.85
3,"{'max_depth': 2, 'min_samples_split': 3}",0.925000,3,0.975,0.950,0.85
4,"{'max_depth': 3, 'min_samples_split': 2}",0.933333,1,1.000,0.950,0.85
5,"{'max_depth': 3, 'min_samples_split': 3}",0.933333,1,1.000,0.950,0.85

In [66]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [67]:
grid_dtree.best_score_

0.9333333333333332

In [68]:
estimator=grid_dtree.best_estimator_

pred = estimator.predict(X_test)
print(accuracy_score(Y_test, pred))

0.9666666666666667

In [69]:
# 문자열로 된 제품 이름을 컴퓨터가 다루기 쉬운 숫자 레이블로 바꾸는 예시

from sklearn.preprocessing import LabelEncoder

items = ["tv","냉장고","전자레인지", "컴퓨터", "선풍기" , "믹서","믹서","믹서"]

encoder = LabelEncoder() #레이블 인코더 객체를 만듭니다.

# 데이터에 어떤 종류의 문자열이 있는지 학습 

encoder.fit(items) # 목록에 어떤 문자열 종류가 있는지 살펴보고, 각각을 어떤 숫자로 표현할지 학습합니다. 같은 문자열은 하나의 종류

labels = encoder.transform(items)
print(labels)

[2 3 5 1 0 4 4 4]

In [70]:
encoder.classes_

array([' 선풍기', ' 컴퓨터', 'tv', '냉장고', '믹서', '전자레인지'], dtype='<U5')

In [71]:
# 제품 이름을 One-Hot 인코딩에 넣기 좋은 모양으로 준비

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ["tv","냉장고","전자레인지", "컴퓨터", "선풍기" , "선풍기","믹서","믹서"]

items = np.array(items).reshape(-1,1)
# neHotEncoder는 각 데이터 샘플을 행으로, 인코딩할 특성을 열로 받습니다. 여기서는 제품 이름 하나가 각 샘플의 범주이므로 입력 모양이 행 8개 × 열 1개여야 해요.
#  -1: 행의 개수는 데이터에 맞춰 NumPy가 계산하라는 뜻입니다. 여기서는 8입니다.
#   1: 열을 1개로 만들라는 뜻입니다.
items

# items의 현재 값을 화면에 보여주는 표현

array([['tv'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [72]:
# 원-핫 인코딩 객체 생성
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
# 학습한 기준에 따라 상품 이름을 원-핫 인코딩
oh_labels = oh_encoder.transform(items)

# oh_labels는 보통 **희소 행렬(sparse matrix)
print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)

In [73]:
df = pd.DataFrame({'items':["tv","냉장고","전자레인지", " 컴퓨터", "선풍기" , "선풍기","믹서","믹서"]})
df

   items
0     tv
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [74]:
pd.get_dummies(df)

   items_ 컴퓨터  items_tv  items_냉장고  items_믹서  items_선풍기  items_전자레인지
0           0         1          0         0          0            0
1           0         0          1         0          0            0
2           0         0          0         0          0            1
3           1         0          0         0          0            0
4           0         0          0         0          1            0
5           0         0          0         0          1            0
6           0         0          0         1          0            0
7           0         0          0         1          0            0

In [75]:
# Iris 꽃 데이터의 특성별 평균과 분산을 계산

from sklearn.datasets import load_iris
iris = load_iris()

iris_data = iris.data
# 특성 데이터를 판다스 DataFrame으로 변환하고 열 이름 지정
iris_df = pd.DataFrame(data = iris_data,columns=iris.feature_names)

print (iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [76]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns= iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [77]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

print(iris_df_scaled.min())

print(iris_df_scaled.max())

sepal length (cm)   -1.870024
sepal width (cm)    -2.433947
petal length (cm)   -1.567576
petal width (cm)    -1.447076
dtype: float64
sepal length (cm)    2.492019
sepal width (cm)     3.090775
petal length (cm)    1.785832
petal width (cm)     1.712096
dtype: float64