In [51]:
import sklearn
from sklearn.datasets import load_iris 
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [52]:
import pandas as pd

iris = load_iris()

iris_data = iris.data # 피처 : 꽃받힘의 너비 길이 , 꽃잎의 너비 길이
iris_label = iris.target # 아이리스 품종 : 정답

print("iris target: " , iris_label)
print("iris target 명 : ", iris.target_names)

iris target:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명 :  ['setosa' 'versicolor' 'virginica']

In [53]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [54]:
from sklearn.datasets import load_iris

iris = load_iris()

print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), 'frame': None, 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'), 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...', 'feature_names': ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'], 'filename': 'iris.csv', 'data_module': 'sklearn.datasets.data'}

In [55]:
import pandas as pd

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["target"] = iris.target

print(df.head(10))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

   target
0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0

In [56]:
iris_df = pd . DataFrame(data=iris_data,columns=iris.feature_names)
iris_df["label"] = iris.target

iris_df.head()

## iris 데이터의 형태 : 150개의 샘플과 4개의 특성

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [57]:
print(iris.data[0])
print(iris.target[0])
print(iris.target_names[iris.target[0]])

# 샘플 1번의 붓꽃의 특징

[5.1 3.5 1.4 0.2]
0
setosa

train_test_split() : 머신러닝에서 데이터를 학습용 데이터와 테스트용 데이터로 나누는 함수

> 훈련 데이터(Train): 문제와 정답을 보면서 공부하는 데이터
> 테스트 데이터(Test): 공부에 사용하지 않고, 실력을 평가하는 데이터

>> test_size = 0.2 ==> 전체의 20%를 테스트용으로 사용

>> random_state = 아무 숫자 ==>	실행할 때마다 같은 방식으로 분할하도록 설정

>>>X_train :훈련용 문제 (모델이 학습할 꽃의 특징 데이터)
>>>X_test : 테스트용 문제 (학습에 사용하지 않고 평가할 꽃의 특징 데이터)
>>>y_train : 훈련용 정답 (훈련 데이터에 대응하는 품종 번호)
>>>y_test : 테스트용 정답 (모델의 예측 결과가 맞는지 비교할 실제 정답)

((대문자 X는 여러 특징을 가진 2차원 데이터, 소문자 y는 보통 1차원 정답 데이터)) ##근데 이미 난 대문자 Y로 해버려서,,,

In [58]:
# 학습셋과 테스트 셋으로 나누기

X_train, X_test, Y_train, Y_test = train_test_split(iris_data, iris_label, test_size=0.2,train_size=0.8, random_state=1)

In [59]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)

DecisionTreeClassifier :  의사결정나무(Decision Tree) 알고리즘을 이용해 데이터를 분류하는 머신러닝 모델
fit() : 모델을 학습시키는 함수
predict() : 학습된 모델에 새로운 특징 데이터를 넣어서 예측 결과를 반환하는 메서드

In [60]:
dt_clf = DecisionTreeClassifier(random_state=1)

In [61]:
dt_clf.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=1)

In [62]:
pred = dt_clf.predict(X_test)

In [63]:
pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

pred 값이 30개인 이유 
> X_test의 예측값, 전체 데이터의 0.2% == 30개
> 학습이 끝난 모델의 테스트 데이터가 30개


accuracy_score : 분류 모델이 예측한 결과가 실제 정답과 얼마나 일치하는지 계산하는 함수 (예측 정확도)

In [64]:
from sklearn.metrics import accuracy_score
print("예측 정확도 : ", accuracy_score(Y_test, pred))

예측 정확도 :  0.9666666666666667

KFold : 데이터를 여러 묶음으로 나누어 모델을 반복적으로 학습하고 평가할 수 있게 해주는 도구

>> KFold(n_splits = 5)  n_splits = 의 수만큼 묶음을 만듬
>> cv_accuracy = []	각 반복에서 측정한 정확도를 저장할 빈 리스트

구분	        train_test_split()     	  KFold--> 결과적으로 모든 데이터가 테스트데이터로 사용됨
분할 방식     	한 번 나눔	             여러 번 나눔
테스트 데이터	 보통 한 번 사용     	각 묶음이 한 번씩 사용
목적	       기본적인 학습·평가    	평가 결과의 안정성 확인
결과	       한 번의 평가 결과        	여러 평가 결과

In [65]:
from sklearn.model_selection import KFold
import numpy as np

Kfold = KFold(n_splits = 5)
cv_accuracy = []

In [66]:
n_iter = 0  # 반복 횟수를 세기 위한 변수
features = iris.data #붓꽃의 4가지 측정값
label = iris.target #붓꽃의 실제 품종 번호
cv_accuracy = [] #각 반복의 정확도를 저장할 빈 리스트

# Kfold.split(features)--> 인덱스 배열 2개를 반환
# train_index: 학습에 사용할 데이터의 행 번호
# test_index: 검증에 사용할 데이터의 행 번호


for train_index, test_index in Kfold.split(features):
    X_train, X_test = features[train_index],features[test_index]
    Y_train, Y_test = label[train_index],label[test_index]

    dt_clf.fit(X_train,Y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    accuracy = np.round(accuracy_score(Y_test,pred),4)

    train_size = X_train.shape[0]
    test_size =X_test.shape[0]
    print("교차검증 정확도 : ",accuracy)
    print("학습 데이터 크기 : ",train_size)
    print("검증데이터크기 : ",test_size)
    cv_accuracy.append(accuracy)
    
print("평균 검증 정확도",np.mean(cv_accuracy))

교차검증 정확도 :  1.0
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정확도 :  1.0
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정확도 :  0.9
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정확도 :  0.9333
학습 데이터 크기 :  120
검증데이터크기 :  30
교차검증 정확도 :  0.7333
학습 데이터 크기 :  120
검증데이터크기 :  30
평균 검증 정확도 0.91332

In [67]:
iris_df["label"].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [68]:
# stratifiedKFold -->각 데이터 묶음에 품종별 비율이 비슷하게 유지되도록 나두면서 데이터를 나눔

In [69]:
#####################

from sklearn.model_selection import StratifiedKFold

# 레이블 비율을 유지하는 3-Fold 교차 검증
skf = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=1
)

n_iter = 0

for train_index, test_index in skf.split(
    iris_df.drop(columns=["label"]),
    iris_df["label"]
):
    n_iter += 1

    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df["label"].iloc[test_index]

    print(f"\n[{n_iter}번째 Fold]")
    print("학습 레이블 데이터 분포:")
    print(label_train.value_counts().sort_index())

    print("검증 레이블 데이터 분포:")
    print(label_test.value_counts().sort_index())

[1번째 Fold]
학습 레이블 데이터 분포:
0    33
1    33
2    34
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
1    17
2    16
Name: label, dtype: int64

[2번째 Fold]
학습 레이블 데이터 분포:
0    33
1    34
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
1    16
2    17
Name: label, dtype: int64

[3번째 Fold]
학습 레이블 데이터 분포:
0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    16
1    17
2    17
Name: label, dtype: int64

In [70]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import numpy as np

n_iter = 0
cv_accuracy = []

features = iris.data
label = iris.target

dt_clf = DecisionTreeClassifier(random_state=1)

for train_index, test_index in skf.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    Y_train, Y_test = label[train_index], label[test_index]

    # 모델 학습
    dt_clf.fit(X_train, Y_train)

    # 검증 데이터 예측
    pred = dt_clf.predict(X_test)

    # 정확도 계산
    accuracy = accuracy_score(Y_test, pred)
    cv_accuracy.append(accuracy)

    n_iter += 1
    print(f"{n_iter}번째 Fold 정확도: {accuracy:.4f}")

print(f"\n평균 교차 검증 정확도: {np.mean(cv_accuracy):.4f}")

1번째 Fold 정확도: 0.9600
2번째 Fold 정확도: 0.9400
3번째 Fold 정확도: 0.9200

평균 교차 검증 정확도: 0.9400

In [71]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(dt_clf, features, label, scoring = "accuracy",cv = skf)

print("교차 검증별 정확도 : ", np.round(scores , 4))
print("평균 검증 정확도 : ", np.round(np.mean(scores) , 4))

교차 검증별 정확도 :  [0.96 0.94 0.92]
평균 검증 정확도 :  0.94

In [ ]:

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    iris.data,
    iris.target,
    test_size=0.2,
    random_state=121,
    stratify=iris.target
)

parameters = {
    "max_depth": [1, 2, 3], # 의사결정나무의 최대 깊이 후보
    "min_samples_split": [2, 3]# 노드를 분할하기 위한 최소 샘플 수 후보
}

In [ ]:

from sklearn.model_selection import GridSearchCV

# 의사결정나무 분류 모델 생성
dtree = DecisionTreeClassifier(random_state=156)

grid_dtree = GridSearchCV(
    estimator=dtree,
    param_grid=parameters,
    cv=3,
    scoring="accuracy",
    refit=True
)

grid_dtree.fit(X_train, Y_train)

# 각 하이퍼파라미터 조합의 교차 검증 결과를 데이터프레임으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)

scores_df[
    [
        "params",
        "mean_test_score",
        "rank_test_score",
        "split0_test_score",
        "split1_test_score",
        "split2_test_score"
    ]
]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.658333,5,0.650,0.675,0.65
1,"{'max_depth': 1, 'min_samples_split': 3}",0.658333,5,0.650,0.675,0.65
2,"{'max_depth': 2, 'min_samples_split': 2}",0.925000,3,0.975,0.950,0.85
3,"{'max_depth': 2, 'min_samples_split': 3}",0.925000,3,0.975,0.950,0.85
4,"{'max_depth': 3, 'min_samples_split': 2}",0.933333,1,1.000,0.950,0.85
5,"{'max_depth': 3, 'min_samples_split': 3}",0.933333,1,1.000,0.950,0.85

In [ ]:
# 조합을 교차 검증으로 평가하는 GridSearchCV 불러오기
from sklearn.model_selection import GridSearchCV

dtree = DecisionTreeClassifier(random_state=156)
# 조합별 모델 성능을 비교하도록 설정
grid_dtree = GridSearchCV(
    estimator=dtree,
    param_grid=parameters,
    cv=3,
    scoring="accuracy",
    refit=True
)

grid_dtree.fit(X_train, Y_train)
# 탐색 및 교차 검증 실행
scores_df = pd.DataFrame(grid_dtree.cv_results_)

scores_df[
    [
        "params",
        "mean_test_score",
        "rank_test_score",
        "split0_test_score",
        "split1_test_score",
        "split2_test_score"
    ]
]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.658333,5,0.650,0.675,0.65
1,"{'max_depth': 1, 'min_samples_split': 3}",0.658333,5,0.650,0.675,0.65
2,"{'max_depth': 2, 'min_samples_split': 2}",0.925000,3,0.975,0.950,0.85
3,"{'max_depth': 2, 'min_samples_split': 3}",0.925000,3,0.975,0.950,0.85
4,"{'max_depth': 3, 'min_samples_split': 2}",0.933333,1,1.000,0.950,0.85
5,"{'max_depth': 3, 'min_samples_split': 3}",0.933333,1,1.000,0.950,0.85

In [75]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [76]:
grid_dtree.best_score_

0.9333333333333332

In [77]:
estimator=grid_dtree.best_estimator_

pred = estimator.predict(X_test)
print(accuracy_score(Y_test, pred))

0.9666666666666667

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ["tv","냉장고","전자레인지", " 컴퓨터", " 선풍기" , "믹서","믹서","믹서"]

encoder = LabelEncoder()
# 데이터에 어떤 종류의 문자열이 있는지 학습
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[2 3 5 1 0 4 4 4]

In [79]:
encoder.classes_

array([' 선풍기', ' 컴퓨터', 'tv', '냉장고', '믹서', '전자레인지'], dtype='<U5')

In [80]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ["tv","냉장고","전자레인지", "컴퓨터", "선풍기" , "선풍기","믹서","믹서"]

items = np.array(items).reshape(-1,1)
items

array([['tv'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']], dtype='<U5')

In [ ]:
# 원-핫 인코딩 객체 생성
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
# 학습한 기준에 따라 상품 이름을 원-핫 인코딩
oh_labels = oh_encoder.transform(items)

print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)

In [82]:
df = pd.DataFrame({'items':["tv","냉장고","전자레인지", " 컴퓨터", "선풍기" , "선풍기","믹서","믹서"]})
df

   items
0     tv
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [83]:
pd.get_dummies(df)

   items_ 컴퓨터  items_tv  items_냉장고  items_믹서  items_선풍기  items_전자레인지
0           0         1          0         0          0            0
1           0         0          1         0          0            0
2           0         0          0         0          0            1
3           1         0          0         0          0            0
4           0         0          0         0          1            0
5           0         0          0         0          1            0
6           0         0          0         1          0            0
7           0         0          0         1          0            0

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()

iris_data = iris.data
# 특성 데이터를 판다스 DataFrame으로 변환하고 열 이름 지정
iris_df = pd.DataFrame(data = iris_data,columns=iris.feature_names)

print (iris_df.mean())
print(iris_df.var())

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [85]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data = iris_scaled, columns= iris.feature_names)
print(iris_df_scaled.mean())
print(iris_df_scaled.var())

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [86]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

print(iris_df_scaled.min())

print(iris_df_scaled.max())

sepal length (cm)   -1.870024
sepal width (cm)    -2.433947
petal length (cm)   -1.567576
petal width (cm)    -1.447076
dtype: float64
sepal length (cm)    2.492019
sepal width (cm)     3.090775
petal length (cm)    1.785832
petal width (cm)     1.712096
dtype: float64