In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("./santander_train.csv")
df.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [2]:
df["TARGET"].value_counts()

0    73012
1     3008
Name: TARGET, dtype: int64

In [3]:
df.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

In [4]:
df["var3"].value_counts()

 2         74165
 8           138
-999999      116
 9           110
 3           108
           ...
 231           1
 188           1
 168           1
 135           1
 87            1
Name: var3, Length: 208, dtype: int64

In [5]:
df["var3"].replace(-999999,2,inplace=True)
df.drop("ID",axis = 1 , inplace= True)

x_features = df.iloc[ : , :-1]
y_label = df.iloc [ :, -1]
x_features.shape

(76020, 369)

In [6]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(x_features,y_label, test_size=0.2 , random_state  =0 , stratify = y_label)

train_cnt = y_train.count()
test_cnt = y_test .count()

print(y_train. value_counts() / train_cnt)
print(y_test . value_counts() / train_cnt)

0    0.960438
1    0.039562
Name: TARGET, dtype: float64
0    0.240101
1    0.009899
Name: TARGET, dtype: float64

In [7]:
X_tr, X_val, y_tr,y_val = train_test_split(X_train , y_train, test_size= 0.3, random_state= 0 )

In [8]:
from xgboost import XGBClassifier
from sklearn.metrics import roc_auc_score

xgb_clf = XGBClassifier(n_estimators = 500, learning_rate = 0.05, random_state = 156)

xgb_clf.fit(X_tr, y_tr, early_stopping_rounds = 100 , eval_metric = "auc", eval_set = [(X_tr,y_tr),(X_val,y_val)])

xgb_auc = roc_auc_score(y_test , xgb_clf.predict_proba(X_test)[:,1])
print(xgb_clf)

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83155	validation_1-auc:0.80088
[1]	validation_0-auc:0.83330	validation_1-auc:0.80089
[2]	validation_0-auc:0.83749	validation_1-auc:0.80303
[3]	validation_0-auc:0.83661	validation_1-auc:0.80251
[4]	validation_0-auc:0.83739	validation_1-auc:0.80252
[5]	validation_0-auc:0.83841	validation_1-auc:0.80237
[6]	validation_0-auc:0.84131	validation_1-auc:0.80673
[7]	validation_0-auc:0.84135	validation_1-auc:0.80660
[8]	validation_0-auc:0.84304	validation_1-auc:0.80861
[9]	validation_0-auc:0.84550	validation_1-auc:0.81139
[10]	validation_0-auc:0.84620	validation_1-auc:0.81104
[11]	validation_0-auc:0.84641	validation_1-auc:0.81080
[12]	validation_0-auc:0.84760	validation_1-auc:0.81181
[13]	validation_0-auc:0.84804	validation_1-auc:0.81205
[14]	validation_0-auc:0.84865	validation_1-auc:0.81232
[15]	validation_0-auc:0.84912	validation_1-auc:0.81239
[16]	validation_0-auc:0.85052	validation_1-auc:0.81365
[17]	validation_0-auc:0.85165	validation_1-auc:0.81489
[18]	validation_0-auc:0.85204	validation_1-auc:0.81510
[19]	validation_0-auc:0.85234	validation_1-auc:0.81529
[20]	validation_0-auc:0.85302	validation_1-auc:0.81595
[21]	validation_0-auc:0.85323	validation_1-auc:0.81594
[22]	validation_0-auc:0.85347	validation_1-auc:0.81624
[23]	validation_0-auc:0.85364	validation_1-auc:0.81648
[24]	validation_0-auc:0.85387	validation_1-auc:0.81648
[25]	validation_0-auc:0.85557	validation_1-auc:0.81770
[26]	validation_0-auc:0.85588	validation_1-auc:0.81805
[27]	validation_0-auc:0.85700	validation_1-auc:0.81905
[28]	validation_0-auc:0.85724	validation_1-auc:0.81933
[29]	validation_0-auc:0.85846	validation_1-auc:0.81999
[30]	validation_0-auc:0.85886	validation_1-auc:0.82012
[31]	validation_0-auc:0.86059	validation_1-auc:0.82112
[32]	validation_0-auc:0.86112	validation_1-auc:0.82142
[33]	validation_0-auc:0.86169	validation_1-auc:0.82178
[34]	validation_0-auc:0.86227	validation_1-auc:0.82161
[35]	validation_0-auc:0.86278	validation_1-auc:0.82142
[36]	validation_0-auc:0.86325	validation_1-auc:0.82131
[37]	validation_0-auc:0.86399	validation_1-auc:0.82150
[38]	validation_0-auc:0.86445	validation_1-auc:0.82140
[39]	validation_0-auc:0.86488	validation_1-auc:0.82139
[40]	validation_0-auc:0.86584	validation_1-auc:0.82153
[41]	validation_0-auc:0.86694	validation_1-auc:0.82221
[42]	validation_0-auc:0.86762	validation_1-auc:0.82262
[43]	validation_0-auc:0.86873	validation_1-auc:0.82353
[44]	validation_0-auc:0.86945	validation_1-auc:0.82374
[45]	validation_0-auc:0.87001	validation_1-auc:0.82405
[46]	validation_0-auc:0.87071	validation_1-auc:0.82422
[47]	validation_0-auc:0.87143	validation_1-auc:0.82438
[48]	validation_0-auc:0.87196	validation_1-auc:0.82465
[49]	validation_0-auc:0.87266	validation_1-auc:0.82515
[50]	validation_0-auc:0.87318	validation_1-auc:0.82549
[51]	validation_0-auc:0.87370	validation_1-auc:0.82575
[52]	validation_0-auc:0.87430	validation_1-auc:0.82593
[53]	validation_0-auc:0.87482	validation_1-auc:0.82615
[54]	validation_0-auc:0.87538	validation_1-auc:0.82651
[55]	validation_0-auc:0.87605	validation_1-auc:0.82686
[56]	validation_0-auc:0.87654	validation_1-auc:0.82720
[57]	validation_0-auc:0.87725	validation_1-auc:0.82744
[58]	validation_0-auc:0.87777	validation_1-auc:0.82797
[59]	validation_0-auc:0.87838	validation_1-auc:0.82822
[60]	validation_0-auc:0.87864	validation_1-auc:0.82850
[61]	validation_0-auc:0.87940	validation_1-auc:0.82853
[62]	validation_0-auc:0.87982	validation_1-auc:0.82860
[63]	validation_0-auc:0.88000	validation_1-auc:0.82866
[64]	validation_0-auc:0.88090	validation_1-auc:0.82869
[65]	validation_0-auc:0.88152	validation_1-auc:0.82921
[66]	validation_0-auc:0.88188	validation_1-auc:0.82938
[67]	validation_0-auc:0.88246	validation_1-auc:0.82915
[68]	validation_0-auc:0.88298	validation_1-auc:0.82941
[69]	validation_0-auc:0.88362	validation_1-auc:0.82955
[70]	validation_0-auc:0.88405	validation_1-auc:0.82977
[71]	validation_0-auc:0.88456	validation_1-auc:0.82996
[72]	validation_0-auc:0.88496	validation_1-auc:0.83003
[73]	validation_0-auc:0.88536	validation_1-auc:0.83014
[74]	validation_0-auc:0.88600	validation_1-auc:0.83029
[75]	validation_0-auc:0.88663	validation_1-auc:0.83032
[76]	validation_0-auc:0.88722	validation_1-auc:0.83047
[77]	validation_0-auc:0.88764	validation_1-auc:0.83052
[78]	validation_0-auc:0.88816	validation_1-auc:0.83057
[79]	validation_0-auc:0.88849	validation_1-auc:0.83058
[80]	validation_0-auc:0.88906	validation_1-auc:0.83091
[81]	validation_0-auc:0.88950	validation_1-auc:0.83064
[82]	validation_0-auc:0.88986	validation_1-auc:0.83059
[83]	validation_0-auc:0.89037	validation_1-auc:0.83062
[84]	validation_0-auc:0.89080	validation_1-auc:0.83085
[85]	validation_0-auc:0.89137	validation_1-auc:0.83081
[86]	validation_0-auc:0.89173	validation_1-auc:0.83083
[87]	validation_0-auc:0.89213	validation_1-auc:0.83112
[88]	validation_0-auc:0.89246	validation_1-auc:0.83114
[89]	validation_0-auc:0.89279	validation_1-auc:0.83117
[90]	validation_0-auc:0.89315	validation_1-auc:0.83098
[91]	validation_0-auc:0.89347	validation_1-auc:0.83093
[92]	validation_0-auc:0.89373	validation_1-auc:0.83075
[93]	validation_0-auc:0.89394	validation_1-auc:0.83081
[94]	validation_0-auc:0.89410	validation_1-auc:0.83065
[95]	validation_0-auc:0.89444	validation_1-auc:0.83075
[96]	validation_0-auc:0.89473	validation_1-auc:0.83095
[97]	validation_0-auc:0.89515	validation_1-auc:0.83076
[98]	validation_0-auc:0.89535	validation_1-auc:0.83090
[99]	validation_0-auc:0.89586	validation_1-auc:0.83088
[100]	validation_0-auc:0.89613	validation_1-auc:0.83071
[101]	validation_0-auc:0.89632	validation_1-auc:0.83078
[102]	validation_0-auc:0.89660	validation_1-auc:0.83083
[103]	validation_0-auc:0.89691	validation_1-auc:0.83095
[104]	validation_0-auc:0.89709	validation_1-auc:0.83102
[105]	validation_0-auc:0.89742	validation_1-auc:0.83131
[106]	validation_0-auc:0.89783	validation_1-auc:0.83131
[107]	validation_0-auc:0.89810	validation_1-auc:0.83113
[108]	validation_0-auc:0.89851	validation_1-auc:0.83125
[109]	validation_0-auc:0.89872	validation_1-auc:0.83109
[110]	validation_0-auc:0.89901	validation_1-auc:0.83108
[111]	validation_0-auc:0.89918	validation_1-auc:0.83112
[112]	validation_0-auc:0.89943	validation_1-auc:0.83115
[113]	validation_0-auc:0.89961	validation_1-auc:0.83105
[114]	validation_0-auc:0.89988	validation_1-auc:0.83118
[115]	validation_0-auc:0.90008	validation_1-auc:0.83115
[116]	validation_0-auc:0.90055	validation_1-auc:0.83138
[117]	validation_0-auc:0.90089	validation_1-auc:0.83137
[118]	validation_0-auc:0.90109	validation_1-auc:0.83144
[119]	validation_0-auc:0.90120	validation_1-auc:0.83139
[120]	validation_0-auc:0.90161	validation_1-auc:0.83143
[121]	validation_0-auc:0.90176	validation_1-auc:0.83146
[122]	validation_0-auc:0.90208	validation_1-auc:0.83151
[123]	validation_0-auc:0.90220	validation_1-auc:0.83142
[124]	validation_0-auc:0.90258	validation_1-auc:0.83141
[125]	validation_0-auc:0.90266	validation_1-auc:0.83149
[126]	validation_0-auc:0.90292	validation_1-auc:0.83140
[127]	validation_0-auc:0.90299	validation_1-auc:0.83139
[128]	validation_0-auc:0.90331	validation_1-auc:0.83141
[129]	validation_0-auc:0.90344	validation_1-auc:0.83145
[130]	validation_0-auc:0.90367	validation_1-auc:0.83158
[131]	validation_0-auc:0.90400	validation_1-auc:0.83161
[132]	validation_0-auc:0.90407	validation_1-auc:0.83162
[133]	validation_0-auc:0.90436	validation_1-auc:0.83160
[134]	validation_0-auc:0.90461	validation_1-auc:0.83168
[135]	validation_0-auc:0.90473	validation_1-auc:0.83170
[136]	validation_0-auc:0.90477	validation_1-auc:0.83181
[137]	validation_0-auc:0.90483	validation_1-auc:0.83190
[138]	validation_0-auc:0.90503	validation_1-auc:0.83182
[139]	validation_0-auc:0.90517	validation_1-auc:0.83175
[140]	validation_0-auc:0.90533	validation_1-auc:0.83168
[141]	validation_0-auc:0.90564	validation_1-auc:0.83176
[142]	validation_0-auc:0.90572	validation_1-auc:0.83180
[143]	validation_0-auc:0.90583	validation_1-auc:0.83175
[144]	validation_0-auc:0.90596	validation_1-auc:0.83171
[145]	validation_0-auc:0.90609	validation_1-auc:0.83166
[146]	validation_0-auc:0.90654	validation_1-auc:0.83176
[147]	validation_0-auc:0.90684	validation_1-auc:0.83193
[148]	validation_0-auc:0.90703	validation_1-auc:0.83205
[149]	validation_0-auc:0.90709	validation_1-auc:0.83208
[150]	validation_0-auc:0.90722	validation_1-auc:0.83204
[151]	validation_0-auc:0.90726	validation_1-auc:0.83208
[152]	validation_0-auc:0.90755	validation_1-auc:0.83209
[153]	validation_0-auc:0.90770	validation_1-auc:0.83218
[154]	validation_0-auc:0.90781	validation_1-auc:0.83214
[155]	validation_0-auc:0.90807	validation_1-auc:0.83214
[156]	validation_0-auc:0.90822	validation_1-auc:0.83213
[157]	validation_0-auc:0.90828	validation_1-auc:0.83213
[158]	validation_0-auc:0.90836	validation_1-auc:0.83224
[159]	validation_0-auc:0.90849	validation_1-auc:0.83224
[160]	validation_0-auc:0.90873	validation_1-auc:0.83237
[161]	validation_0-auc:0.90887	validation_1-auc:0.83242
[162]	validation_0-auc:0.90911	validation_1-auc:0.83240
[163]	validation_0-auc:0.90916	validation_1-auc:0.83243
[164]	validation_0-auc:0.90925	validation_1-auc:0.83245
[165]	validation_0-auc:0.90933	validation_1-auc:0.83242
[166]	validation_0-auc:0.90947	validation_1-auc:0.83252
[167]	validation_0-auc:0.90957	validation_1-auc:0.83248
[168]	validation_0-auc:0.90970	validation_1-auc:0.83243
[169]	validation_0-auc:0.90973	validation_1-auc:0.83253
[170]	validation_0-auc:0.90977	validation_1-auc:0.83261
[171]	validation_0-auc:0.90986	validation_1-auc:0.83255
[172]	validation_0-auc:0.90999	validation_1-auc:0.83256
[173]	validation_0-auc:0.91019	validation_1-auc:0.83248
[174]	validation_0-auc:0.91028	validation_1-auc:0.83248
[175]	validation_0-auc:0.91055	validation_1-auc:0.83242
[176]	validation_0-auc:0.91068	validation_1-auc:0.83238
[177]	validation_0-auc:0.91075	validation_1-auc:0.83235
[178]	validation_0-auc:0.91099	validation_1-auc:0.83232
[179]	validation_0-auc:0.91126	validation_1-auc:0.83234
[180]	validation_0-auc:0.91139	validation_1-auc:0.83228
[181]	validation_0-auc:0.91146	validation_1-auc:0.83221
[182]	validation_0-auc:0.91150	validation_1-auc:0.83224
[183]	validation_0-auc:0.91156	validation_1-auc:0.83220
[184]	validation_0-auc:0.91198	validation_1-auc:0.83226
[185]	validation_0-auc:0.91202	validation_1-auc:0.83223
[186]	validation_0-auc:0.91226	validation_1-auc:0.83222
[187]	validation_0-auc:0.91229	validation_1-auc:0.83224
[188]	validation_0-auc:0.91237	validation_1-auc:0.83227
[189]	validation_0-auc:0.91240	validation_1-auc:0.83229
[190]	validation_0-auc:0.91250	validation_1-auc:0.83224
[191]	validation_0-auc:0.91283	validation_1-auc:0.83219
[192]	validation_0-auc:0.91285	validation_1-auc:0.83223
[193]	validation_0-auc:0.91307	validation_1-auc:0.83226
[194]	validation_0-auc:0.91319	validation_1-auc:0.83215
[195]	validation_0-auc:0.91334	validation_1-auc:0.83215
[196]	validation_0-auc:0.91352	validation_1-auc:0.83201
[197]	validation_0-auc:0.91356	validation_1-auc:0.83209
[198]	validation_0-auc:0.91362	validation_1-auc:0.83208
[199]	validation_0-auc:0.91369	validation_1-auc:0.83207
[200]	validation_0-auc:0.91379	validation_1-auc:0.83202
[201]	validation_0-auc:0.91383	validation_1-auc:0.83205
[202]	validation_0-auc:0.91408	validation_1-auc:0.83211
[203]	validation_0-auc:0.91433	validation_1-auc:0.83210
[204]	validation_0-auc:0.91441	validation_1-auc:0.83209
[205]	validation_0-auc:0.91448	validation_1-auc:0.83202
[206]	validation_0-auc:0.91468	validation_1-auc:0.83199
[207]	validation_0-auc:0.91473	validation_1-auc:0.83197
[208]	validation_0-auc:0.91489	validation_1-auc:0.83197
[209]	validation_0-auc:0.91495	validation_1-auc:0.83195
[210]	validation_0-auc:0.91498	validation_1-auc:0.83194
[211]	validation_0-auc:0.91509	validation_1-auc:0.83200
[212]	validation_0-auc:0.91513	validation_1-auc:0.83197
[213]	validation_0-auc:0.91516	validation_1-auc:0.83205
[214]	validation_0-auc:0.91521	validation_1-auc:0.83198
[215]	validation_0-auc:0.91523	validation_1-auc:0.83202
[216]	validation_0-auc:0.91531	validation_1-auc:0.83196
[217]	validation_0-auc:0.91564	validation_1-auc:0.83186
[218]	validation_0-auc:0.91568	validation_1-auc:0.83183
[219]	validation_0-auc:0.91573	validation_1-auc:0.83182
[220]	validation_0-auc:0.91579	validation_1-auc:0.83174
[221]	validation_0-auc:0.91595	validation_1-auc:0.83175
[222]	validation_0-auc:0.91598	validation_1-auc:0.83177
[223]	validation_0-auc:0.91599	validation_1-auc:0.83174
[224]	validation_0-auc:0.91606	validation_1-auc:0.83171
[225]	validation_0-auc:0.91613	validation_1-auc:0.83167
[226]	validation_0-auc:0.91614	validation_1-auc:0.83171
[227]	validation_0-auc:0.91647	validation_1-auc:0.83179
[228]	validation_0-auc:0.91653	validation_1-auc:0.83172
[229]	validation_0-auc:0.91654	validation_1-auc:0.83171
[230]	validation_0-auc:0.91660	validation_1-auc:0.83169
[231]	validation_0-auc:0.91666	validation_1-auc:0.83168
[232]	validation_0-auc:0.91669	validation_1-auc:0.83170
[233]	validation_0-auc:0.91682	validation_1-auc:0.83178
[234]	validation_0-auc:0.91692	validation_1-auc:0.83175
[235]	validation_0-auc:0.91695	validation_1-auc:0.83170
[236]	validation_0-auc:0.91714	validation_1-auc:0.83181
[237]	validation_0-auc:0.91721	validation_1-auc:0.83180
[238]	validation_0-auc:0.91728	validation_1-auc:0.83169
[239]	validation_0-auc:0.91734	validation_1-auc:0.83173
[240]	validation_0-auc:0.91738	validation_1-auc:0.83176
[241]	validation_0-auc:0.91742	validation_1-auc:0.83179
[242]	validation_0-auc:0.91761	validation_1-auc:0.83172
[243]	validation_0-auc:0.91764	validation_1-auc:0.83173
[244]	validation_0-auc:0.91768	validation_1-auc:0.83173
[245]	validation_0-auc:0.91784	validation_1-auc:0.83167
[246]	validation_0-auc:0.91786	validation_1-auc:0.83162
[247]	validation_0-auc:0.91789	validation_1-auc:0.83157
[248]	validation_0-auc:0.91805	validation_1-auc:0.83142
[249]	validation_0-auc:0.91832	validation_1-auc:0.83148
[250]	validation_0-auc:0.91837	validation_1-auc:0.83141
[251]	validation_0-auc:0.91843	validation_1-auc:0.83132
[252]	validation_0-auc:0.91873	validation_1-auc:0.83114
[253]	validation_0-auc:0.91875	validation_1-auc:0.83113
[254]	validation_0-auc:0.91878	validation_1-auc:0.83115
[255]	validation_0-auc:0.91906	validation_1-auc:0.83118
[256]	validation_0-auc:0.91908	validation_1-auc:0.83120
[257]	validation_0-auc:0.91921	validation_1-auc:0.83122
[258]	validation_0-auc:0.91921	validation_1-auc:0.83115
[259]	validation_0-auc:0.91932	validation_1-auc:0.83121
[260]	validation_0-auc:0.91937	validation_1-auc:0.83118
[261]	validation_0-auc:0.91942	validation_1-auc:0.83115
[262]	validation_0-auc:0.91945	validation_1-auc:0.83111
[263]	validation_0-auc:0.91947	validation_1-auc:0.83113
[264]	validation_0-auc:0.91962	validation_1-auc:0.83108
[265]	validation_0-auc:0.91964	validation_1-auc:0.83109
[266]	validation_0-auc:0.91971	validation_1-auc:0.83115
[267]	validation_0-auc:0.91978	validation_1-auc:0.83109
[268]	validation_0-auc:0.91980	validation_1-auc:0.83111
[269]	validation_0-auc:0.91991	validation_1-auc:0.83102
[270]	validation_0-auc:0.91993	validation_1-auc:0.83104
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=500, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=156, ...)

In [17]:
from hyperopt import hp

xgb_search_space = {"max_depth": hp.quniform("max_depth",5,15,1),
                    "min_child_weight": hp.quniform("min_child_weight",1,6,1),
                    "colsample_bytree": hp.uniform("colsample_bytree",0.5, 0.95),
                    "learning_rate": hp.uniform ("learning_rate",0.1, 0.2)}

In [18]:
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score

def objective_func(search_space):
    xgb_clf = XGBClassifier(n_estimators = 100,
                            max_depth = int(search_space [ "max_depth"]),
                            min_child_weight = int(search_space["min_child_weight"]),
                            colsample_bytree = search_space [ "colsample_bytree"],
                            learning_rate = search_space["learning_rate"])

    roc_auc = []

    kf = KFold(n_splits = 3)
    for tr_index, val_index in kf.split(X_train):
        X_tr, y_tr = X_train.iloc[tr_index],y_train.iloc[tr_index]
        X_val, y_val = X_train.iloc[val_index], y_train.iloc[val_index]
        xgb_clf.fit(X_tr, y_tr, early_stopping_rounds = 30 , 
                    eval_metric = "auc", eval_set = [(X_tr , y_tr), (X_val, y_val)])

        score = roc_auc_score(y_val, xgb_clf.predict_proba(X_val)[:,1])
        roc_auc.append(score)
    return -1 * np.mean(roc_auc)

In [19]:
from hyperopt import fmin, tpe, Trials

trials = Trials()

best = fmin(fn = objective_func , space = xgb_search_space,
            algo = tpe.suggest, max_evals = 50 , trials = trials, 
            rstate = np.random.default_rng (seed = 30))

print(best)

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82975	validation_1-auc:0.81182
[1]	validation_0-auc:0.83315	validation_1-auc:0.81354
[2]	validation_0-auc:0.84088	validation_1-auc:0.81967
[3]	validation_0-auc:0.84497	validation_1-auc:0.82138
[4]	validation_0-auc:0.84759	validation_1-auc:0.82070
[5]	validation_0-auc:0.84980	validation_1-auc:0.82213
[6]	validation_0-auc:0.85102	validation_1-auc:0.82246
[7]	validation_0-auc:0.85203	validation_1-auc:0.82195
[8]	validation_0-auc:0.85496	validation_1-auc:0.82436
[9]	validation_0-auc:0.85852	validation_1-auc:0.82871
[10]	validation_0-auc:0.85827	validation_1-auc:0.82969
[11]	validation_0-auc:0.85796	validation_1-auc:0.82894
[12]	validation_0-auc:0.86222	validation_1-auc:0.83162
[13]	validation_0-auc:0.86499	validation_1-auc:0.83400
[14]	validation_0-auc:0.86645	validation_1-auc:0.83656
[15]	validation_0-auc:0.86835	validation_1-auc:0.83711
[16]	validation_0-auc:0.87018	validation_1-auc:0.83721
[17]	validation_0-auc:0.87165	validation_1-auc:0.83741
[18]	validation_0-auc:0.87217	validation_1-auc:0.83828
[19]	validation_0-auc:0.87322	validation_1-auc:0.83901
[20]	validation_0-auc:0.87435	validation_1-auc:0.83907
[21]	validation_0-auc:0.87544	validation_1-auc:0.84010
[22]	validation_0-auc:0.87696	validation_1-auc:0.84046
[23]	validation_0-auc:0.87843	validation_1-auc:0.84074
[24]	validation_0-auc:0.88001	validation_1-auc:0.84130
[25]	validation_0-auc:0.88049	validation_1-auc:0.84144
[26]	validation_0-auc:0.88209	validation_1-auc:0.84213
[27]	validation_0-auc:0.88328	validation_1-auc:0.84256
[28]	validation_0-auc:0.88431	validation_1-auc:0.84254
[29]	validation_0-auc:0.88564	validation_1-auc:0.84235
[30]	validation_0-auc:0.88648	validation_1-auc:0.84316
[31]	validation_0-auc:0.88772	validation_1-auc:0.84357
[32]	validation_0-auc:0.88828	validation_1-auc:0.84389
[33]	validation_0-auc:0.88927	validation_1-auc:0.84454
[34]	validation_0-auc:0.89000	validation_1-auc:0.84387
[35]	validation_0-auc:0.89083	validation_1-auc:0.84395
[36]	validation_0-auc:0.89164	validation_1-auc:0.84344
[37]	validation_0-auc:0.89204	validation_1-auc:0.84353
[38]	validation_0-auc:0.89327	validation_1-auc:0.84325
[39]	validation_0-auc:0.89394	validation_1-auc:0.84358
[40]	validation_0-auc:0.89431	validation_1-auc:0.84352
[41]	validation_0-auc:0.89494	validation_1-auc:0.84361
[42]	validation_0-auc:0.89588	validation_1-auc:0.84371
[43]	validation_0-auc:0.89623	validation_1-auc:0.84388
[44]	validation_0-auc:0.89678	validation_1-auc:0.84389
[45]	validation_0-auc:0.89713	validation_1-auc:0.84388
[46]	validation_0-auc:0.89758	validation_1-auc:0.84402
[47]	validation_0-auc:0.89796	validation_1-auc:0.84390
[48]	validation_0-auc:0.89820	validation_1-auc:0.84386
[49]	validation_0-auc:0.89865	validation_1-auc:0.84371
[50]	validation_0-auc:0.89883	validation_1-auc:0.84396
[51]	validation_0-auc:0.89906	validation_1-auc:0.84406
[52]	validation_0-auc:0.90039	validation_1-auc:0.84357
[53]	validation_0-auc:0.90052	validation_1-auc:0.84374
[54]	validation_0-auc:0.90107	validation_1-auc:0.84383
[55]	validation_0-auc:0.90202	validation_1-auc:0.84410
[56]	validation_0-auc:0.90244	validation_1-auc:0.84434
[57]	validation_0-auc:0.90302	validation_1-auc:0.84434
[58]	validation_0-auc:0.90344	validation_1-auc:0.84435
[59]	validation_0-auc:0.90377	validation_1-auc:0.84434
[60]	validation_0-auc:0.90397	validation_1-auc:0.84429
[61]	validation_0-auc:0.90404	validation_1-auc:0.84428
[62]	validation_0-auc:0.90414	validation_1-auc:0.84427
[63]	validation_0-auc:0.90485	validation_1-auc:0.84420
  0%|          | 0/50 [00:03<?, ?trial/s, best loss=?]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82633	validation_1-auc:0.80738
[1]	validation_0-auc:0.83210	validation_1-auc:0.81196
[2]	validation_0-auc:0.83906	validation_1-auc:0.81814
[3]	validation_0-auc:0.84224	validation_1-auc:0.82081
[4]	validation_0-auc:0.84549	validation_1-auc:0.82252
[5]	validation_0-auc:0.84628	validation_1-auc:0.82299
[6]	validation_0-auc:0.84923	validation_1-auc:0.82367
[7]	validation_0-auc:0.85220	validation_1-auc:0.82458
[8]	validation_0-auc:0.85322	validation_1-auc:0.82454
[9]	validation_0-auc:0.85763	validation_1-auc:0.82605
[10]	validation_0-auc:0.85830	validation_1-auc:0.82564
[11]	validation_0-auc:0.86003	validation_1-auc:0.82588
[12]	validation_0-auc:0.86433	validation_1-auc:0.82842
[13]	validation_0-auc:0.86674	validation_1-auc:0.83043
[14]	validation_0-auc:0.86813	validation_1-auc:0.83251
[15]	validation_0-auc:0.87103	validation_1-auc:0.83330
[16]	validation_0-auc:0.87308	validation_1-auc:0.83468
[17]	validation_0-auc:0.87345	validation_1-auc:0.83453
[18]	validation_0-auc:0.87468	validation_1-auc:0.83423
[19]	validation_0-auc:0.87662	validation_1-auc:0.83434
[20]	validation_0-auc:0.87814	validation_1-auc:0.83577
[21]	validation_0-auc:0.87895	validation_1-auc:0.83530
[22]	validation_0-auc:0.88021	validation_1-auc:0.83544
[23]	validation_0-auc:0.88206	validation_1-auc:0.83549
[24]	validation_0-auc:0.88378	validation_1-auc:0.83598
[25]	validation_0-auc:0.88455	validation_1-auc:0.83653
[26]	validation_0-auc:0.88608	validation_1-auc:0.83651
[27]	validation_0-auc:0.88735	validation_1-auc:0.83647
[28]	validation_0-auc:0.88878	validation_1-auc:0.83648
[29]	validation_0-auc:0.89000	validation_1-auc:0.83656
[30]	validation_0-auc:0.89138	validation_1-auc:0.83659
[31]	validation_0-auc:0.89289	validation_1-auc:0.83654
[32]	validation_0-auc:0.89393	validation_1-auc:0.83691
[33]	validation_0-auc:0.89420	validation_1-auc:0.83728
[34]	validation_0-auc:0.89496	validation_1-auc:0.83779
[35]	validation_0-auc:0.89564	validation_1-auc:0.83753
[36]	validation_0-auc:0.89654	validation_1-auc:0.83754
[37]	validation_0-auc:0.89732	validation_1-auc:0.83709
[38]	validation_0-auc:0.89795	validation_1-auc:0.83681
[39]	validation_0-auc:0.89842	validation_1-auc:0.83721
[40]	validation_0-auc:0.89925	validation_1-auc:0.83704
[41]	validation_0-auc:0.90028	validation_1-auc:0.83737
[42]	validation_0-auc:0.90066	validation_1-auc:0.83690
[43]	validation_0-auc:0.90134	validation_1-auc:0.83762
[44]	validation_0-auc:0.90197	validation_1-auc:0.83723
[45]	validation_0-auc:0.90238	validation_1-auc:0.83710
[46]	validation_0-auc:0.90249	validation_1-auc:0.83706
[47]	validation_0-auc:0.90343	validation_1-auc:0.83683
[48]	validation_0-auc:0.90373	validation_1-auc:0.83664
[49]	validation_0-auc:0.90444	validation_1-auc:0.83679
[50]	validation_0-auc:0.90464	validation_1-auc:0.83704
[51]	validation_0-auc:0.90477	validation_1-auc:0.83690
[52]	validation_0-auc:0.90528	validation_1-auc:0.83684
[53]	validation_0-auc:0.90570	validation_1-auc:0.83668
[54]	validation_0-auc:0.90613	validation_1-auc:0.83659
[55]	validation_0-auc:0.90663	validation_1-auc:0.83650
[56]	validation_0-auc:0.90680	validation_1-auc:0.83658
[57]	validation_0-auc:0.90697	validation_1-auc:0.83663
[58]	validation_0-auc:0.90754	validation_1-auc:0.83657
[59]	validation_0-auc:0.90792	validation_1-auc:0.83662
[60]	validation_0-auc:0.90846	validation_1-auc:0.83644
[61]	validation_0-auc:0.90938	validation_1-auc:0.83657
[62]	validation_0-auc:0.90955	validation_1-auc:0.83664
[63]	validation_0-auc:0.90985	validation_1-auc:0.83655
[64]	validation_0-auc:0.91005	validation_1-auc:0.83650
  0%|          | 0/50 [00:07<?, ?trial/s, best loss=?]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82215	validation_1-auc:0.81040
[1]	validation_0-auc:0.82900	validation_1-auc:0.81319
[2]	validation_0-auc:0.83933	validation_1-auc:0.82337
[3]	validation_0-auc:0.84428	validation_1-auc:0.82877
[4]	validation_0-auc:0.84791	validation_1-auc:0.82987
[5]	validation_0-auc:0.84848	validation_1-auc:0.83035
[6]	validation_0-auc:0.84998	validation_1-auc:0.83305
[7]	validation_0-auc:0.85171	validation_1-auc:0.83363
[8]	validation_0-auc:0.85311	validation_1-auc:0.83500
[9]	validation_0-auc:0.85600	validation_1-auc:0.83399
[10]	validation_0-auc:0.85596	validation_1-auc:0.83169
[11]	validation_0-auc:0.85379	validation_1-auc:0.82797
[12]	validation_0-auc:0.85877	validation_1-auc:0.83236
[13]	validation_0-auc:0.86179	validation_1-auc:0.83484
[14]	validation_0-auc:0.86335	validation_1-auc:0.83682
[15]	validation_0-auc:0.86518	validation_1-auc:0.83862
[16]	validation_0-auc:0.86714	validation_1-auc:0.83999
[17]	validation_0-auc:0.86984	validation_1-auc:0.84237
[18]	validation_0-auc:0.87004	validation_1-auc:0.84136
[19]	validation_0-auc:0.87216	validation_1-auc:0.84145
[20]	validation_0-auc:0.87458	validation_1-auc:0.84275
[21]	validation_0-auc:0.87597	validation_1-auc:0.84274
[22]	validation_0-auc:0.87783	validation_1-auc:0.84368
[23]	validation_0-auc:0.87895	validation_1-auc:0.84347
[24]	validation_0-auc:0.88039	validation_1-auc:0.84361
[25]	validation_0-auc:0.88149	validation_1-auc:0.84384
[26]	validation_0-auc:0.88287	validation_1-auc:0.84404
[27]	validation_0-auc:0.88415	validation_1-auc:0.84366
[28]	validation_0-auc:0.88522	validation_1-auc:0.84349
[29]	validation_0-auc:0.88606	validation_1-auc:0.84361
[30]	validation_0-auc:0.88752	validation_1-auc:0.84388
[31]	validation_0-auc:0.88906	validation_1-auc:0.84446
[32]	validation_0-auc:0.88987	validation_1-auc:0.84463
[33]	validation_0-auc:0.89063	validation_1-auc:0.84445
[34]	validation_0-auc:0.89120	validation_1-auc:0.84433
[35]	validation_0-auc:0.89207	validation_1-auc:0.84424
[36]	validation_0-auc:0.89342	validation_1-auc:0.84456
[37]	validation_0-auc:0.89409	validation_1-auc:0.84462
[38]	validation_0-auc:0.89498	validation_1-auc:0.84485
[39]	validation_0-auc:0.89526	validation_1-auc:0.84482
[40]	validation_0-auc:0.89561	validation_1-auc:0.84515
[41]	validation_0-auc:0.89648	validation_1-auc:0.84498
[42]	validation_0-auc:0.89706	validation_1-auc:0.84523
[43]	validation_0-auc:0.89754	validation_1-auc:0.84520
[44]	validation_0-auc:0.89842	validation_1-auc:0.84508
[45]	validation_0-auc:0.89894	validation_1-auc:0.84490
[46]	validation_0-auc:0.89953	validation_1-auc:0.84472
[47]	validation_0-auc:0.90022	validation_1-auc:0.84448
[48]	validation_0-auc:0.90082	validation_1-auc:0.84444
[49]	validation_0-auc:0.90093	validation_1-auc:0.84451
[50]	validation_0-auc:0.90172	validation_1-auc:0.84466
[51]	validation_0-auc:0.90195	validation_1-auc:0.84446
[52]	validation_0-auc:0.90216	validation_1-auc:0.84425
[53]	validation_0-auc:0.90246	validation_1-auc:0.84421
[54]	validation_0-auc:0.90258	validation_1-auc:0.84444
[55]	validation_0-auc:0.90347	validation_1-auc:0.84421
[56]	validation_0-auc:0.90366	validation_1-auc:0.84410
[57]	validation_0-auc:0.90371	validation_1-auc:0.84413
[58]	validation_0-auc:0.90452	validation_1-auc:0.84392
[59]	validation_0-auc:0.90466	validation_1-auc:0.84389
[60]	validation_0-auc:0.90529	validation_1-auc:0.84377
[61]	validation_0-auc:0.90597	validation_1-auc:0.84356
[62]	validation_0-auc:0.90615	validation_1-auc:0.84355
[63]	validation_0-auc:0.90651	validation_1-auc:0.84344
[64]	validation_0-auc:0.90715	validation_1-auc:0.84330
[65]	validation_0-auc:0.90729	validation_1-auc:0.84334
[66]	validation_0-auc:0.90764	validation_1-auc:0.84345
[67]	validation_0-auc:0.90799	validation_1-auc:0.84341
[68]	validation_0-auc:0.90811	validation_1-auc:0.84347
[69]	validation_0-auc:0.90821	validation_1-auc:0.84353
[70]	validation_0-auc:0.90864	validation_1-auc:0.84332
[71]	validation_0-auc:0.90870	validation_1-auc:0.84333
  2%|▏         | 1/50 [00:11<09:17, 11.38s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83260	validation_1-auc:0.81334
[1]	validation_0-auc:0.83932	validation_1-auc:0.81463
[2]	validation_0-auc:0.84713	validation_1-auc:0.81705
[3]	validation_0-auc:0.85070	validation_1-auc:0.81721
[4]	validation_0-auc:0.85774	validation_1-auc:0.81893
[5]	validation_0-auc:0.86350	validation_1-auc:0.82488
[6]	validation_0-auc:0.86884	validation_1-auc:0.82901
[7]	validation_0-auc:0.87030	validation_1-auc:0.82853
[8]	validation_0-auc:0.87232	validation_1-auc:0.82799
[9]	validation_0-auc:0.87377	validation_1-auc:0.82800
[10]	validation_0-auc:0.87404	validation_1-auc:0.82630
[11]	validation_0-auc:0.87738	validation_1-auc:0.82585
[12]	validation_0-auc:0.88169	validation_1-auc:0.83011
[13]	validation_0-auc:0.88657	validation_1-auc:0.83315
[14]	validation_0-auc:0.88829	validation_1-auc:0.83510
[15]	validation_0-auc:0.88901	validation_1-auc:0.83500
[16]	validation_0-auc:0.89142	validation_1-auc:0.83673
[17]	validation_0-auc:0.89504	validation_1-auc:0.83782
[18]	validation_0-auc:0.89509	validation_1-auc:0.83859
[19]	validation_0-auc:0.89798	validation_1-auc:0.83928
[20]	validation_0-auc:0.89796	validation_1-auc:0.83862
[21]	validation_0-auc:0.89832	validation_1-auc:0.83716
[22]	validation_0-auc:0.90075	validation_1-auc:0.83753
[23]	validation_0-auc:0.90454	validation_1-auc:0.83862
[24]	validation_0-auc:0.90603	validation_1-auc:0.83891
[25]	validation_0-auc:0.90708	validation_1-auc:0.83924
[26]	validation_0-auc:0.90874	validation_1-auc:0.83761
[27]	validation_0-auc:0.91121	validation_1-auc:0.83811
[28]	validation_0-auc:0.91146	validation_1-auc:0.83780
[29]	validation_0-auc:0.91325	validation_1-auc:0.83868
[30]	validation_0-auc:0.91450	validation_1-auc:0.83802
[31]	validation_0-auc:0.91666	validation_1-auc:0.83831
[32]	validation_0-auc:0.91810	validation_1-auc:0.83911
[33]	validation_0-auc:0.91922	validation_1-auc:0.83972
[34]	validation_0-auc:0.91965	validation_1-auc:0.84056
[35]	validation_0-auc:0.92112	validation_1-auc:0.84006
[36]	validation_0-auc:0.92244	validation_1-auc:0.83919
[37]	validation_0-auc:0.92328	validation_1-auc:0.83909
[38]	validation_0-auc:0.92415	validation_1-auc:0.83878
[39]	validation_0-auc:0.92502	validation_1-auc:0.83915
[40]	validation_0-auc:0.92536	validation_1-auc:0.83980
[41]	validation_0-auc:0.92601	validation_1-auc:0.83984
[42]	validation_0-auc:0.92686	validation_1-auc:0.83981
[43]	validation_0-auc:0.92680	validation_1-auc:0.84008
[44]	validation_0-auc:0.92793	validation_1-auc:0.83994
[45]	validation_0-auc:0.92810	validation_1-auc:0.84035
[46]	validation_0-auc:0.92815	validation_1-auc:0.84020
[47]	validation_0-auc:0.92870	validation_1-auc:0.83996
[48]	validation_0-auc:0.92874	validation_1-auc:0.84019
[49]	validation_0-auc:0.92918	validation_1-auc:0.84023
[50]	validation_0-auc:0.92953	validation_1-auc:0.83993
[51]	validation_0-auc:0.93002	validation_1-auc:0.83987
[52]	validation_0-auc:0.93051	validation_1-auc:0.84009
[53]	validation_0-auc:0.93097	validation_1-auc:0.84011
[54]	validation_0-auc:0.93122	validation_1-auc:0.84034
[55]	validation_0-auc:0.93182	validation_1-auc:0.84048
[56]	validation_0-auc:0.93207	validation_1-auc:0.84043
[57]	validation_0-auc:0.93221	validation_1-auc:0.84054
[58]	validation_0-auc:0.93289	validation_1-auc:0.84056
[59]	validation_0-auc:0.93355	validation_1-auc:0.84050
[60]	validation_0-auc:0.93372	validation_1-auc:0.84065
[61]	validation_0-auc:0.93435	validation_1-auc:0.84054
[62]	validation_0-auc:0.93444	validation_1-auc:0.84044
[63]	validation_0-auc:0.93470	validation_1-auc:0.84000
[64]	validation_0-auc:0.93518	validation_1-auc:0.83962
[65]	validation_0-auc:0.93571	validation_1-auc:0.83970
[66]	validation_0-auc:0.93593	validation_1-auc:0.83968
[67]	validation_0-auc:0.93625	validation_1-auc:0.83987
[68]	validation_0-auc:0.93663	validation_1-auc:0.83952
[69]	validation_0-auc:0.93700	validation_1-auc:0.83969
[70]	validation_0-auc:0.93717	validation_1-auc:0.83978
[71]	validation_0-auc:0.93736	validation_1-auc:0.83960
[72]	validation_0-auc:0.93776	validation_1-auc:0.83971
[73]	validation_0-auc:0.93800	validation_1-auc:0.83972
[74]	validation_0-auc:0.93816	validation_1-auc:0.83954
[75]	validation_0-auc:0.93893	validation_1-auc:0.83948
[76]	validation_0-auc:0.93894	validation_1-auc:0.83951
[77]	validation_0-auc:0.93921	validation_1-auc:0.83932
[78]	validation_0-auc:0.93927	validation_1-auc:0.83922
[79]	validation_0-auc:0.93972	validation_1-auc:0.83888
[80]	validation_0-auc:0.93980	validation_1-auc:0.83873
[81]	validation_0-auc:0.93997	validation_1-auc:0.83895
[82]	validation_0-auc:0.94036	validation_1-auc:0.83888
[83]	validation_0-auc:0.94054	validation_1-auc:0.83897
[84]	validation_0-auc:0.94073	validation_1-auc:0.83895
[85]	validation_0-auc:0.94097	validation_1-auc:0.83873
[86]	validation_0-auc:0.94136	validation_1-auc:0.83868
[87]	validation_0-auc:0.94145	validation_1-auc:0.83871
[88]	validation_0-auc:0.94152	validation_1-auc:0.83869
[89]	validation_0-auc:0.94173	validation_1-auc:0.83856
[90]	validation_0-auc:0.94189	validation_1-auc:0.83836
  2%|▏         | 1/50 [00:18<09:17, 11.38s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82832	validation_1-auc:0.80774
[1]	validation_0-auc:0.83457	validation_1-auc:0.81032
[2]	validation_0-auc:0.84126	validation_1-auc:0.81625
[3]	validation_0-auc:0.84800	validation_1-auc:0.82058
[4]	validation_0-auc:0.85684	validation_1-auc:0.82465
[5]	validation_0-auc:0.86056	validation_1-auc:0.82736
[6]	validation_0-auc:0.86643	validation_1-auc:0.82951
[7]	validation_0-auc:0.87097	validation_1-auc:0.83052
[8]	validation_0-auc:0.87414	validation_1-auc:0.82994
[9]	validation_0-auc:0.87748	validation_1-auc:0.82700
[10]	validation_0-auc:0.87840	validation_1-auc:0.82633
[11]	validation_0-auc:0.88080	validation_1-auc:0.82571
[12]	validation_0-auc:0.88467	validation_1-auc:0.82701
[13]	validation_0-auc:0.89049	validation_1-auc:0.82912
[14]	validation_0-auc:0.89287	validation_1-auc:0.82982
[15]	validation_0-auc:0.89393	validation_1-auc:0.82803
[16]	validation_0-auc:0.89526	validation_1-auc:0.83006
[17]	validation_0-auc:0.89727	validation_1-auc:0.83046
[18]	validation_0-auc:0.89754	validation_1-auc:0.82928
[19]	validation_0-auc:0.90124	validation_1-auc:0.83137
[20]	validation_0-auc:0.90197	validation_1-auc:0.83118
[21]	validation_0-auc:0.90165	validation_1-auc:0.82998
[22]	validation_0-auc:0.90309	validation_1-auc:0.83197
[23]	validation_0-auc:0.90653	validation_1-auc:0.83362
[24]	validation_0-auc:0.90811	validation_1-auc:0.83485
[25]	validation_0-auc:0.90952	validation_1-auc:0.83514
[26]	validation_0-auc:0.91113	validation_1-auc:0.83396
[27]	validation_0-auc:0.91315	validation_1-auc:0.83416
[28]	validation_0-auc:0.91386	validation_1-auc:0.83364
[29]	validation_0-auc:0.91537	validation_1-auc:0.83473
[30]	validation_0-auc:0.91683	validation_1-auc:0.83444
[31]	validation_0-auc:0.91815	validation_1-auc:0.83490
[32]	validation_0-auc:0.91933	validation_1-auc:0.83653
[33]	validation_0-auc:0.92001	validation_1-auc:0.83680
[34]	validation_0-auc:0.92044	validation_1-auc:0.83693
[35]	validation_0-auc:0.92121	validation_1-auc:0.83719
[36]	validation_0-auc:0.92211	validation_1-auc:0.83671
[37]	validation_0-auc:0.92308	validation_1-auc:0.83599
[38]	validation_0-auc:0.92369	validation_1-auc:0.83504
[39]	validation_0-auc:0.92375	validation_1-auc:0.83567
[40]	validation_0-auc:0.92409	validation_1-auc:0.83602
[41]	validation_0-auc:0.92498	validation_1-auc:0.83558
[42]	validation_0-auc:0.92576	validation_1-auc:0.83554
[43]	validation_0-auc:0.92586	validation_1-auc:0.83619
[44]	validation_0-auc:0.92680	validation_1-auc:0.83590
[45]	validation_0-auc:0.92716	validation_1-auc:0.83597
[46]	validation_0-auc:0.92727	validation_1-auc:0.83603
[47]	validation_0-auc:0.92787	validation_1-auc:0.83593
[48]	validation_0-auc:0.92817	validation_1-auc:0.83599
[49]	validation_0-auc:0.92881	validation_1-auc:0.83621
[50]	validation_0-auc:0.92929	validation_1-auc:0.83634
[51]	validation_0-auc:0.92965	validation_1-auc:0.83640
[52]	validation_0-auc:0.92985	validation_1-auc:0.83645
[53]	validation_0-auc:0.93029	validation_1-auc:0.83624
[54]	validation_0-auc:0.93058	validation_1-auc:0.83611
[55]	validation_0-auc:0.93122	validation_1-auc:0.83636
[56]	validation_0-auc:0.93145	validation_1-auc:0.83608
[57]	validation_0-auc:0.93158	validation_1-auc:0.83622
[58]	validation_0-auc:0.93208	validation_1-auc:0.83598
[59]	validation_0-auc:0.93266	validation_1-auc:0.83598
[60]	validation_0-auc:0.93330	validation_1-auc:0.83573
[61]	validation_0-auc:0.93360	validation_1-auc:0.83548
[62]	validation_0-auc:0.93386	validation_1-auc:0.83532
[63]	validation_0-auc:0.93398	validation_1-auc:0.83525
[64]	validation_0-auc:0.93497	validation_1-auc:0.83479
  2%|▏         | 1/50 [00:22<09:17, 11.38s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82572	validation_1-auc:0.80964
[1]	validation_0-auc:0.83349	validation_1-auc:0.81463
[2]	validation_0-auc:0.84144	validation_1-auc:0.82213
[3]	validation_0-auc:0.84553	validation_1-auc:0.82634
[4]	validation_0-auc:0.85666	validation_1-auc:0.83106
[5]	validation_0-auc:0.85905	validation_1-auc:0.82906
[6]	validation_0-auc:0.86684	validation_1-auc:0.83394
[7]	validation_0-auc:0.87042	validation_1-auc:0.83401
[8]	validation_0-auc:0.87278	validation_1-auc:0.83543
[9]	validation_0-auc:0.87423	validation_1-auc:0.83131
[10]	validation_0-auc:0.87538	validation_1-auc:0.83103
[11]	validation_0-auc:0.87693	validation_1-auc:0.82889
[12]	validation_0-auc:0.88102	validation_1-auc:0.83123
[13]	validation_0-auc:0.88493	validation_1-auc:0.83407
[14]	validation_0-auc:0.88630	validation_1-auc:0.83634
[15]	validation_0-auc:0.88692	validation_1-auc:0.83504
[16]	validation_0-auc:0.89040	validation_1-auc:0.83774
[17]	validation_0-auc:0.89362	validation_1-auc:0.83923
[18]	validation_0-auc:0.89380	validation_1-auc:0.83687
[19]	validation_0-auc:0.89688	validation_1-auc:0.83818
[20]	validation_0-auc:0.89741	validation_1-auc:0.83702
[21]	validation_0-auc:0.89830	validation_1-auc:0.83446
[22]	validation_0-auc:0.89995	validation_1-auc:0.83657
[23]	validation_0-auc:0.90273	validation_1-auc:0.83740
[24]	validation_0-auc:0.90464	validation_1-auc:0.83809
[25]	validation_0-auc:0.90566	validation_1-auc:0.83818
[26]	validation_0-auc:0.90752	validation_1-auc:0.83717
[27]	validation_0-auc:0.90982	validation_1-auc:0.83804
[28]	validation_0-auc:0.91018	validation_1-auc:0.83710
[29]	validation_0-auc:0.91202	validation_1-auc:0.83799
[30]	validation_0-auc:0.91369	validation_1-auc:0.83692
[31]	validation_0-auc:0.91518	validation_1-auc:0.83779
[32]	validation_0-auc:0.91601	validation_1-auc:0.83869
[33]	validation_0-auc:0.91679	validation_1-auc:0.83927
[34]	validation_0-auc:0.91717	validation_1-auc:0.83983
[35]	validation_0-auc:0.91793	validation_1-auc:0.84018
[36]	validation_0-auc:0.91897	validation_1-auc:0.83955
[37]	validation_0-auc:0.92027	validation_1-auc:0.83907
[38]	validation_0-auc:0.92170	validation_1-auc:0.83856
[39]	validation_0-auc:0.92189	validation_1-auc:0.83918
[40]	validation_0-auc:0.92215	validation_1-auc:0.83916
[41]	validation_0-auc:0.92323	validation_1-auc:0.83844
[42]	validation_0-auc:0.92374	validation_1-auc:0.83860
[43]	validation_0-auc:0.92424	validation_1-auc:0.83870
[44]	validation_0-auc:0.92462	validation_1-auc:0.83916
[45]	validation_0-auc:0.92478	validation_1-auc:0.83945
[46]	validation_0-auc:0.92512	validation_1-auc:0.83925
[47]	validation_0-auc:0.92565	validation_1-auc:0.83957
[48]	validation_0-auc:0.92593	validation_1-auc:0.83931
[49]	validation_0-auc:0.92628	validation_1-auc:0.83919
[50]	validation_0-auc:0.92660	validation_1-auc:0.83896
[51]	validation_0-auc:0.92682	validation_1-auc:0.83915
[52]	validation_0-auc:0.92725	validation_1-auc:0.83924
[53]	validation_0-auc:0.92799	validation_1-auc:0.83914
[54]	validation_0-auc:0.92828	validation_1-auc:0.83892
[55]	validation_0-auc:0.92896	validation_1-auc:0.83900
[56]	validation_0-auc:0.92928	validation_1-auc:0.83887
[57]	validation_0-auc:0.92943	validation_1-auc:0.83860
[58]	validation_0-auc:0.93005	validation_1-auc:0.83866
[59]	validation_0-auc:0.93043	validation_1-auc:0.83819
[60]	validation_0-auc:0.93065	validation_1-auc:0.83793
[61]	validation_0-auc:0.93100	validation_1-auc:0.83789
[62]	validation_0-auc:0.93116	validation_1-auc:0.83813
[63]	validation_0-auc:0.93143	validation_1-auc:0.83810
[64]	validation_0-auc:0.93166	validation_1-auc:0.83813
  4%|▍         | 2/50 [00:27<11:28, 14.34s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83584	validation_1-auc:0.81267
[1]	validation_0-auc:0.84261	validation_1-auc:0.81428
[2]	validation_0-auc:0.84836	validation_1-auc:0.81572
[3]	validation_0-auc:0.85524	validation_1-auc:0.81773
[4]	validation_0-auc:0.86188	validation_1-auc:0.82138
[5]	validation_0-auc:0.86520	validation_1-auc:0.82364
[6]	validation_0-auc:0.87049	validation_1-auc:0.82310
[7]	validation_0-auc:0.87749	validation_1-auc:0.82713
[8]	validation_0-auc:0.88094	validation_1-auc:0.82741
[9]	validation_0-auc:0.88744	validation_1-auc:0.82973
[10]	validation_0-auc:0.88797	validation_1-auc:0.82992
[11]	validation_0-auc:0.89257	validation_1-auc:0.82878
[12]	validation_0-auc:0.89735	validation_1-auc:0.83172
[13]	validation_0-auc:0.90132	validation_1-auc:0.83266
[14]	validation_0-auc:0.90334	validation_1-auc:0.83460
[15]	validation_0-auc:0.90771	validation_1-auc:0.83524
[16]	validation_0-auc:0.91111	validation_1-auc:0.83556
[17]	validation_0-auc:0.91380	validation_1-auc:0.83526
[18]	validation_0-auc:0.91532	validation_1-auc:0.83526
[19]	validation_0-auc:0.91780	validation_1-auc:0.83662
[20]	validation_0-auc:0.92083	validation_1-auc:0.83668
[21]	validation_0-auc:0.92268	validation_1-auc:0.83594
[22]	validation_0-auc:0.92527	validation_1-auc:0.83669
[23]	validation_0-auc:0.92714	validation_1-auc:0.83676
[24]	validation_0-auc:0.92854	validation_1-auc:0.83661
[25]	validation_0-auc:0.92966	validation_1-auc:0.83721
[26]	validation_0-auc:0.93127	validation_1-auc:0.83775
[27]	validation_0-auc:0.93401	validation_1-auc:0.83719
[28]	validation_0-auc:0.93539	validation_1-auc:0.83686
[29]	validation_0-auc:0.93666	validation_1-auc:0.83705
[30]	validation_0-auc:0.93762	validation_1-auc:0.83685
[31]	validation_0-auc:0.93879	validation_1-auc:0.83708
[32]	validation_0-auc:0.93954	validation_1-auc:0.83648
[33]	validation_0-auc:0.94009	validation_1-auc:0.83689
[34]	validation_0-auc:0.94051	validation_1-auc:0.83701
[35]	validation_0-auc:0.94087	validation_1-auc:0.83729
[36]	validation_0-auc:0.94214	validation_1-auc:0.83797
[37]	validation_0-auc:0.94234	validation_1-auc:0.83788
[38]	validation_0-auc:0.94303	validation_1-auc:0.83813
[39]	validation_0-auc:0.94379	validation_1-auc:0.83765
[40]	validation_0-auc:0.94426	validation_1-auc:0.83770
[41]	validation_0-auc:0.94434	validation_1-auc:0.83752
[42]	validation_0-auc:0.94477	validation_1-auc:0.83750
[43]	validation_0-auc:0.94498	validation_1-auc:0.83788
[44]	validation_0-auc:0.94539	validation_1-auc:0.83795
[45]	validation_0-auc:0.94552	validation_1-auc:0.83806
[46]	validation_0-auc:0.94558	validation_1-auc:0.83804
[47]	validation_0-auc:0.94620	validation_1-auc:0.83780
[48]	validation_0-auc:0.94661	validation_1-auc:0.83752
[49]	validation_0-auc:0.94672	validation_1-auc:0.83758
[50]	validation_0-auc:0.94693	validation_1-auc:0.83773
[51]	validation_0-auc:0.94719	validation_1-auc:0.83771
[52]	validation_0-auc:0.94734	validation_1-auc:0.83755
[53]	validation_0-auc:0.94781	validation_1-auc:0.83744
[54]	validation_0-auc:0.94815	validation_1-auc:0.83730
[55]	validation_0-auc:0.94828	validation_1-auc:0.83718
[56]	validation_0-auc:0.94853	validation_1-auc:0.83720
[57]	validation_0-auc:0.94860	validation_1-auc:0.83729
[58]	validation_0-auc:0.94935	validation_1-auc:0.83700
[59]	validation_0-auc:0.94947	validation_1-auc:0.83694
[60]	validation_0-auc:0.94955	validation_1-auc:0.83709
[61]	validation_0-auc:0.94970	validation_1-auc:0.83694
[62]	validation_0-auc:0.94992	validation_1-auc:0.83694
[63]	validation_0-auc:0.95002	validation_1-auc:0.83670
[64]	validation_0-auc:0.95071	validation_1-auc:0.83651
[65]	validation_0-auc:0.95084	validation_1-auc:0.83633
[66]	validation_0-auc:0.95116	validation_1-auc:0.83602
[67]	validation_0-auc:0.95138	validation_1-auc:0.83574
  4%|▍         | 2/50 [00:32<11:28, 14.34s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83121	validation_1-auc:0.80827
[1]	validation_0-auc:0.84008	validation_1-auc:0.81346
[2]	validation_0-auc:0.84701	validation_1-auc:0.81776
[3]	validation_0-auc:0.85118	validation_1-auc:0.81872
[4]	validation_0-auc:0.86122	validation_1-auc:0.82031
[5]	validation_0-auc:0.86576	validation_1-auc:0.82166
[6]	validation_0-auc:0.87260	validation_1-auc:0.82342
[7]	validation_0-auc:0.87597	validation_1-auc:0.82529
[8]	validation_0-auc:0.88201	validation_1-auc:0.82449
[9]	validation_0-auc:0.88839	validation_1-auc:0.82513
[10]	validation_0-auc:0.89125	validation_1-auc:0.82644
[11]	validation_0-auc:0.89257	validation_1-auc:0.82519
[12]	validation_0-auc:0.89842	validation_1-auc:0.82572
[13]	validation_0-auc:0.90281	validation_1-auc:0.82726
[14]	validation_0-auc:0.90655	validation_1-auc:0.82904
[15]	validation_0-auc:0.91052	validation_1-auc:0.82869
[16]	validation_0-auc:0.91419	validation_1-auc:0.82887
[17]	validation_0-auc:0.91645	validation_1-auc:0.82942
[18]	validation_0-auc:0.91852	validation_1-auc:0.82901
[19]	validation_0-auc:0.92205	validation_1-auc:0.82877
[20]	validation_0-auc:0.92471	validation_1-auc:0.82945
[21]	validation_0-auc:0.92596	validation_1-auc:0.82799
[22]	validation_0-auc:0.92819	validation_1-auc:0.82748
[23]	validation_0-auc:0.92970	validation_1-auc:0.82826
[24]	validation_0-auc:0.93108	validation_1-auc:0.82833
[25]	validation_0-auc:0.93160	validation_1-auc:0.82962
[26]	validation_0-auc:0.93335	validation_1-auc:0.82865
[27]	validation_0-auc:0.93501	validation_1-auc:0.82897
[28]	validation_0-auc:0.93579	validation_1-auc:0.82874
[29]	validation_0-auc:0.93705	validation_1-auc:0.82837
[30]	validation_0-auc:0.93859	validation_1-auc:0.82798
[31]	validation_0-auc:0.93961	validation_1-auc:0.82804
[32]	validation_0-auc:0.94079	validation_1-auc:0.82773
[33]	validation_0-auc:0.94107	validation_1-auc:0.82826
[34]	validation_0-auc:0.94140	validation_1-auc:0.82813
[35]	validation_0-auc:0.94201	validation_1-auc:0.82856
[36]	validation_0-auc:0.94260	validation_1-auc:0.82806
[37]	validation_0-auc:0.94301	validation_1-auc:0.82779
[38]	validation_0-auc:0.94339	validation_1-auc:0.82768
[39]	validation_0-auc:0.94366	validation_1-auc:0.82746
[40]	validation_0-auc:0.94382	validation_1-auc:0.82760
[41]	validation_0-auc:0.94432	validation_1-auc:0.82757
[42]	validation_0-auc:0.94446	validation_1-auc:0.82735
[43]	validation_0-auc:0.94541	validation_1-auc:0.82780
[44]	validation_0-auc:0.94626	validation_1-auc:0.82771
[45]	validation_0-auc:0.94706	validation_1-auc:0.82752
[46]	validation_0-auc:0.94725	validation_1-auc:0.82760
[47]	validation_0-auc:0.94783	validation_1-auc:0.82701
[48]	validation_0-auc:0.94820	validation_1-auc:0.82668
[49]	validation_0-auc:0.94859	validation_1-auc:0.82691
[50]	validation_0-auc:0.94856	validation_1-auc:0.82693
[51]	validation_0-auc:0.94866	validation_1-auc:0.82681
[52]	validation_0-auc:0.94931	validation_1-auc:0.82664
[53]	validation_0-auc:0.94974	validation_1-auc:0.82603
[54]	validation_0-auc:0.95007	validation_1-auc:0.82600
  4%|▍         | 2/50 [00:36<11:28, 14.34s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82884	validation_1-auc:0.80889
[1]	validation_0-auc:0.83787	validation_1-auc:0.81282
[2]	validation_0-auc:0.84641	validation_1-auc:0.82057
[3]	validation_0-auc:0.85702	validation_1-auc:0.82728
[4]	validation_0-auc:0.86422	validation_1-auc:0.82852
[5]	validation_0-auc:0.86757	validation_1-auc:0.82897
[6]	validation_0-auc:0.87176	validation_1-auc:0.83097
[7]	validation_0-auc:0.87352	validation_1-auc:0.83225
[8]	validation_0-auc:0.87544	validation_1-auc:0.83116
[9]	validation_0-auc:0.88181	validation_1-auc:0.83380
[10]	validation_0-auc:0.88502	validation_1-auc:0.83198
[11]	validation_0-auc:0.88593	validation_1-auc:0.82995
[12]	validation_0-auc:0.89501	validation_1-auc:0.83225
[13]	validation_0-auc:0.89965	validation_1-auc:0.83403
[14]	validation_0-auc:0.90237	validation_1-auc:0.83570
[15]	validation_0-auc:0.90745	validation_1-auc:0.83589
[16]	validation_0-auc:0.91059	validation_1-auc:0.83738
[17]	validation_0-auc:0.91366	validation_1-auc:0.83867
[18]	validation_0-auc:0.91534	validation_1-auc:0.83670
[19]	validation_0-auc:0.91899	validation_1-auc:0.83655
[20]	validation_0-auc:0.92107	validation_1-auc:0.83726
[21]	validation_0-auc:0.92221	validation_1-auc:0.83524
[22]	validation_0-auc:0.92446	validation_1-auc:0.83751
[23]	validation_0-auc:0.92616	validation_1-auc:0.83728
[24]	validation_0-auc:0.92784	validation_1-auc:0.83753
[25]	validation_0-auc:0.92869	validation_1-auc:0.83759
[26]	validation_0-auc:0.93117	validation_1-auc:0.83814
[27]	validation_0-auc:0.93348	validation_1-auc:0.83790
[28]	validation_0-auc:0.93470	validation_1-auc:0.83742
[29]	validation_0-auc:0.93532	validation_1-auc:0.83869
[30]	validation_0-auc:0.93614	validation_1-auc:0.83841
[31]	validation_0-auc:0.93744	validation_1-auc:0.83878
[32]	validation_0-auc:0.93813	validation_1-auc:0.83905
[33]	validation_0-auc:0.93878	validation_1-auc:0.83865
[34]	validation_0-auc:0.93950	validation_1-auc:0.83832
[35]	validation_0-auc:0.94089	validation_1-auc:0.83818
[36]	validation_0-auc:0.94156	validation_1-auc:0.83839
[37]	validation_0-auc:0.94174	validation_1-auc:0.83842
[38]	validation_0-auc:0.94278	validation_1-auc:0.83841
[39]	validation_0-auc:0.94310	validation_1-auc:0.83781
[40]	validation_0-auc:0.94349	validation_1-auc:0.83753
[41]	validation_0-auc:0.94456	validation_1-auc:0.83690
[42]	validation_0-auc:0.94505	validation_1-auc:0.83693
[43]	validation_0-auc:0.94527	validation_1-auc:0.83683
[44]	validation_0-auc:0.94569	validation_1-auc:0.83665
[45]	validation_0-auc:0.94627	validation_1-auc:0.83684
[46]	validation_0-auc:0.94630	validation_1-auc:0.83683
[47]	validation_0-auc:0.94729	validation_1-auc:0.83659
[48]	validation_0-auc:0.94757	validation_1-auc:0.83627
[49]	validation_0-auc:0.94783	validation_1-auc:0.83631
[50]	validation_0-auc:0.94804	validation_1-auc:0.83599
[51]	validation_0-auc:0.94812	validation_1-auc:0.83604
[52]	validation_0-auc:0.94830	validation_1-auc:0.83583
[53]	validation_0-auc:0.94866	validation_1-auc:0.83569
[54]	validation_0-auc:0.94873	validation_1-auc:0.83565
[55]	validation_0-auc:0.94882	validation_1-auc:0.83569
[56]	validation_0-auc:0.94898	validation_1-auc:0.83560
[57]	validation_0-auc:0.94907	validation_1-auc:0.83535
[58]	validation_0-auc:0.94989	validation_1-auc:0.83484
[59]	validation_0-auc:0.95001	validation_1-auc:0.83482
[60]	validation_0-auc:0.95070	validation_1-auc:0.83417
[61]	validation_0-auc:0.95087	validation_1-auc:0.83402
  6%|▌         | 3/50 [00:41<11:03, 14.13s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83250	validation_1-auc:0.81445
[1]	validation_0-auc:0.83941	validation_1-auc:0.81488
[2]	validation_0-auc:0.84446	validation_1-auc:0.81720
[3]	validation_0-auc:0.85066	validation_1-auc:0.81770
[4]	validation_0-auc:0.85756	validation_1-auc:0.82062
[5]	validation_0-auc:0.86497	validation_1-auc:0.82746
[6]	validation_0-auc:0.86911	validation_1-auc:0.82844
[7]	validation_0-auc:0.87272	validation_1-auc:0.82798
[8]	validation_0-auc:0.87452	validation_1-auc:0.82828
[9]	validation_0-auc:0.87562	validation_1-auc:0.82806
[10]	validation_0-auc:0.87763	validation_1-auc:0.82863
[11]	validation_0-auc:0.87982	validation_1-auc:0.82788
[12]	validation_0-auc:0.88369	validation_1-auc:0.83244
[13]	validation_0-auc:0.88809	validation_1-auc:0.83355
[14]	validation_0-auc:0.88972	validation_1-auc:0.83510
[15]	validation_0-auc:0.89258	validation_1-auc:0.83641
[16]	validation_0-auc:0.89508	validation_1-auc:0.83625
[17]	validation_0-auc:0.89874	validation_1-auc:0.83729
[18]	validation_0-auc:0.89986	validation_1-auc:0.83685
[19]	validation_0-auc:0.90244	validation_1-auc:0.83685
[20]	validation_0-auc:0.90454	validation_1-auc:0.83696
[21]	validation_0-auc:0.90546	validation_1-auc:0.83587
[22]	validation_0-auc:0.90789	validation_1-auc:0.83653
[23]	validation_0-auc:0.91042	validation_1-auc:0.83684
[24]	validation_0-auc:0.91122	validation_1-auc:0.83696
[25]	validation_0-auc:0.91251	validation_1-auc:0.83703
[26]	validation_0-auc:0.91435	validation_1-auc:0.83736
[27]	validation_0-auc:0.91648	validation_1-auc:0.83740
[28]	validation_0-auc:0.91689	validation_1-auc:0.83760
[29]	validation_0-auc:0.91851	validation_1-auc:0.83795
[30]	validation_0-auc:0.92000	validation_1-auc:0.83801
[31]	validation_0-auc:0.92140	validation_1-auc:0.83732
[32]	validation_0-auc:0.92312	validation_1-auc:0.83687
[33]	validation_0-auc:0.92385	validation_1-auc:0.83746
[34]	validation_0-auc:0.92482	validation_1-auc:0.83817
[35]	validation_0-auc:0.92567	validation_1-auc:0.83880
[36]	validation_0-auc:0.92731	validation_1-auc:0.83842
[37]	validation_0-auc:0.92836	validation_1-auc:0.83879
[38]	validation_0-auc:0.92962	validation_1-auc:0.83815
[39]	validation_0-auc:0.93004	validation_1-auc:0.83851
[40]	validation_0-auc:0.93088	validation_1-auc:0.83828
[41]	validation_0-auc:0.93174	validation_1-auc:0.83820
[42]	validation_0-auc:0.93245	validation_1-auc:0.83847
[43]	validation_0-auc:0.93292	validation_1-auc:0.83856
[44]	validation_0-auc:0.93387	validation_1-auc:0.83868
[45]	validation_0-auc:0.93433	validation_1-auc:0.83912
[46]	validation_0-auc:0.93487	validation_1-auc:0.83921
[47]	validation_0-auc:0.93539	validation_1-auc:0.83920
[48]	validation_0-auc:0.93561	validation_1-auc:0.83921
[49]	validation_0-auc:0.93631	validation_1-auc:0.83914
[50]	validation_0-auc:0.93649	validation_1-auc:0.83930
[51]	validation_0-auc:0.93694	validation_1-auc:0.83875
[52]	validation_0-auc:0.93788	validation_1-auc:0.83845
[53]	validation_0-auc:0.93847	validation_1-auc:0.83854
[54]	validation_0-auc:0.93901	validation_1-auc:0.83778
[55]	validation_0-auc:0.93946	validation_1-auc:0.83778
[56]	validation_0-auc:0.93966	validation_1-auc:0.83836
[57]	validation_0-auc:0.93990	validation_1-auc:0.83845
[58]	validation_0-auc:0.94051	validation_1-auc:0.83833
[59]	validation_0-auc:0.94064	validation_1-auc:0.83815
[60]	validation_0-auc:0.94084	validation_1-auc:0.83770
[61]	validation_0-auc:0.94108	validation_1-auc:0.83767
[62]	validation_0-auc:0.94127	validation_1-auc:0.83781
[63]	validation_0-auc:0.94170	validation_1-auc:0.83722
[64]	validation_0-auc:0.94199	validation_1-auc:0.83698
[65]	validation_0-auc:0.94281	validation_1-auc:0.83695
[66]	validation_0-auc:0.94305	validation_1-auc:0.83690
[67]	validation_0-auc:0.94322	validation_1-auc:0.83680
[68]	validation_0-auc:0.94337	validation_1-auc:0.83671
[69]	validation_0-auc:0.94366	validation_1-auc:0.83688
[70]	validation_0-auc:0.94410	validation_1-auc:0.83660
[71]	validation_0-auc:0.94454	validation_1-auc:0.83664
[72]	validation_0-auc:0.94475	validation_1-auc:0.83691
[73]	validation_0-auc:0.94490	validation_1-auc:0.83705
[74]	validation_0-auc:0.94505	validation_1-auc:0.83717
[75]	validation_0-auc:0.94562	validation_1-auc:0.83724
[76]	validation_0-auc:0.94580	validation_1-auc:0.83743
[77]	validation_0-auc:0.94593	validation_1-auc:0.83741
[78]	validation_0-auc:0.94629	validation_1-auc:0.83736
[79]	validation_0-auc:0.94655	validation_1-auc:0.83722
[80]	validation_0-auc:0.94671	validation_1-auc:0.83727
  6%|▌         | 3/50 [00:48<11:03, 14.13s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82934	validation_1-auc:0.80876
[1]	validation_0-auc:0.83460	validation_1-auc:0.81171
[2]	validation_0-auc:0.84234	validation_1-auc:0.81647
[3]	validation_0-auc:0.84702	validation_1-auc:0.81947
[4]	validation_0-auc:0.85547	validation_1-auc:0.82306
[5]	validation_0-auc:0.85941	validation_1-auc:0.82366
[6]	validation_0-auc:0.86433	validation_1-auc:0.82516
[7]	validation_0-auc:0.87035	validation_1-auc:0.82571
[8]	validation_0-auc:0.87438	validation_1-auc:0.82722
[9]	validation_0-auc:0.87937	validation_1-auc:0.82736
[10]	validation_0-auc:0.88144	validation_1-auc:0.82780
[11]	validation_0-auc:0.88406	validation_1-auc:0.82672
[12]	validation_0-auc:0.88835	validation_1-auc:0.82821
[13]	validation_0-auc:0.89420	validation_1-auc:0.82959
[14]	validation_0-auc:0.89620	validation_1-auc:0.83001
[15]	validation_0-auc:0.89869	validation_1-auc:0.83078
[16]	validation_0-auc:0.89940	validation_1-auc:0.83212
[17]	validation_0-auc:0.90217	validation_1-auc:0.83265
[18]	validation_0-auc:0.90356	validation_1-auc:0.83195
[19]	validation_0-auc:0.90629	validation_1-auc:0.83205
[20]	validation_0-auc:0.90834	validation_1-auc:0.83298
[21]	validation_0-auc:0.90980	validation_1-auc:0.83230
[22]	validation_0-auc:0.91173	validation_1-auc:0.83283
[23]	validation_0-auc:0.91356	validation_1-auc:0.83294
[24]	validation_0-auc:0.91460	validation_1-auc:0.83335
[25]	validation_0-auc:0.91529	validation_1-auc:0.83399
[26]	validation_0-auc:0.91741	validation_1-auc:0.83270
[27]	validation_0-auc:0.91915	validation_1-auc:0.83371
[28]	validation_0-auc:0.91956	validation_1-auc:0.83416
[29]	validation_0-auc:0.92096	validation_1-auc:0.83368
[30]	validation_0-auc:0.92268	validation_1-auc:0.83317
[31]	validation_0-auc:0.92384	validation_1-auc:0.83376
[32]	validation_0-auc:0.92496	validation_1-auc:0.83450
[33]	validation_0-auc:0.92565	validation_1-auc:0.83479
[34]	validation_0-auc:0.92636	validation_1-auc:0.83466
[35]	validation_0-auc:0.92742	validation_1-auc:0.83443
[36]	validation_0-auc:0.92867	validation_1-auc:0.83434
[37]	validation_0-auc:0.92974	validation_1-auc:0.83375
[38]	validation_0-auc:0.93050	validation_1-auc:0.83313
[39]	validation_0-auc:0.93080	validation_1-auc:0.83364
[40]	validation_0-auc:0.93147	validation_1-auc:0.83332
[41]	validation_0-auc:0.93247	validation_1-auc:0.83356
[42]	validation_0-auc:0.93351	validation_1-auc:0.83351
[43]	validation_0-auc:0.93405	validation_1-auc:0.83364
[44]	validation_0-auc:0.93511	validation_1-auc:0.83393
[45]	validation_0-auc:0.93542	validation_1-auc:0.83393
[46]	validation_0-auc:0.93553	validation_1-auc:0.83432
[47]	validation_0-auc:0.93592	validation_1-auc:0.83436
[48]	validation_0-auc:0.93603	validation_1-auc:0.83448
[49]	validation_0-auc:0.93638	validation_1-auc:0.83429
[50]	validation_0-auc:0.93656	validation_1-auc:0.83440
[51]	validation_0-auc:0.93702	validation_1-auc:0.83418
[52]	validation_0-auc:0.93732	validation_1-auc:0.83387
[53]	validation_0-auc:0.93764	validation_1-auc:0.83368
[54]	validation_0-auc:0.93797	validation_1-auc:0.83371
[55]	validation_0-auc:0.93860	validation_1-auc:0.83393
[56]	validation_0-auc:0.93912	validation_1-auc:0.83393
[57]	validation_0-auc:0.93983	validation_1-auc:0.83393
[58]	validation_0-auc:0.94035	validation_1-auc:0.83383
[59]	validation_0-auc:0.94065	validation_1-auc:0.83385
[60]	validation_0-auc:0.94116	validation_1-auc:0.83358
[61]	validation_0-auc:0.94155	validation_1-auc:0.83341
[62]	validation_0-auc:0.94175	validation_1-auc:0.83354
  6%|▌         | 3/50 [00:53<11:03, 14.13s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82655	validation_1-auc:0.80862
[1]	validation_0-auc:0.83472	validation_1-auc:0.81360
[2]	validation_0-auc:0.84456	validation_1-auc:0.82547
[3]	validation_0-auc:0.85059	validation_1-auc:0.82906
[4]	validation_0-auc:0.85881	validation_1-auc:0.83305
[5]	validation_0-auc:0.86143	validation_1-auc:0.83208
[6]	validation_0-auc:0.86488	validation_1-auc:0.83282
[7]	validation_0-auc:0.86875	validation_1-auc:0.83426
[8]	validation_0-auc:0.87127	validation_1-auc:0.83491
[9]	validation_0-auc:0.87304	validation_1-auc:0.83399
[10]	validation_0-auc:0.87425	validation_1-auc:0.83208
[11]	validation_0-auc:0.87629	validation_1-auc:0.83218
[12]	validation_0-auc:0.87846	validation_1-auc:0.83363
[13]	validation_0-auc:0.88403	validation_1-auc:0.83569
[14]	validation_0-auc:0.88548	validation_1-auc:0.83628
[15]	validation_0-auc:0.88941	validation_1-auc:0.83674
[16]	validation_0-auc:0.89334	validation_1-auc:0.83873
[17]	validation_0-auc:0.89600	validation_1-auc:0.83971
[18]	validation_0-auc:0.89664	validation_1-auc:0.83744
[19]	validation_0-auc:0.89992	validation_1-auc:0.83817
[20]	validation_0-auc:0.90261	validation_1-auc:0.83952
[21]	validation_0-auc:0.90389	validation_1-auc:0.83737
[22]	validation_0-auc:0.90612	validation_1-auc:0.83927
[23]	validation_0-auc:0.90820	validation_1-auc:0.83976
[24]	validation_0-auc:0.90951	validation_1-auc:0.83958
[25]	validation_0-auc:0.91035	validation_1-auc:0.83993
[26]	validation_0-auc:0.91287	validation_1-auc:0.83890
[27]	validation_0-auc:0.91453	validation_1-auc:0.83897
[28]	validation_0-auc:0.91522	validation_1-auc:0.83937
[29]	validation_0-auc:0.91692	validation_1-auc:0.83960
[30]	validation_0-auc:0.91892	validation_1-auc:0.83939
[31]	validation_0-auc:0.91997	validation_1-auc:0.83924
[32]	validation_0-auc:0.92118	validation_1-auc:0.83939
[33]	validation_0-auc:0.92117	validation_1-auc:0.83943
[34]	validation_0-auc:0.92185	validation_1-auc:0.83980
[35]	validation_0-auc:0.92247	validation_1-auc:0.84023
[36]	validation_0-auc:0.92396	validation_1-auc:0.83935
[37]	validation_0-auc:0.92537	validation_1-auc:0.83837
[38]	validation_0-auc:0.92626	validation_1-auc:0.83781
[39]	validation_0-auc:0.92659	validation_1-auc:0.83828
[40]	validation_0-auc:0.92698	validation_1-auc:0.83854
[41]	validation_0-auc:0.92780	validation_1-auc:0.83831
[42]	validation_0-auc:0.92825	validation_1-auc:0.83821
[43]	validation_0-auc:0.92887	validation_1-auc:0.83745
[44]	validation_0-auc:0.93004	validation_1-auc:0.83754
[45]	validation_0-auc:0.93061	validation_1-auc:0.83744
[46]	validation_0-auc:0.93105	validation_1-auc:0.83775
[47]	validation_0-auc:0.93142	validation_1-auc:0.83798
[48]	validation_0-auc:0.93187	validation_1-auc:0.83780
[49]	validation_0-auc:0.93255	validation_1-auc:0.83801
[50]	validation_0-auc:0.93277	validation_1-auc:0.83806
[51]	validation_0-auc:0.93329	validation_1-auc:0.83802
[52]	validation_0-auc:0.93349	validation_1-auc:0.83799
[53]	validation_0-auc:0.93415	validation_1-auc:0.83783
[54]	validation_0-auc:0.93446	validation_1-auc:0.83762
[55]	validation_0-auc:0.93494	validation_1-auc:0.83777
[56]	validation_0-auc:0.93501	validation_1-auc:0.83749
[57]	validation_0-auc:0.93594	validation_1-auc:0.83700
[58]	validation_0-auc:0.93647	validation_1-auc:0.83725
[59]	validation_0-auc:0.93671	validation_1-auc:0.83706
[60]	validation_0-auc:0.93692	validation_1-auc:0.83679
[61]	validation_0-auc:0.93766	validation_1-auc:0.83692
[62]	validation_0-auc:0.93819	validation_1-auc:0.83693
[63]	validation_0-auc:0.93848	validation_1-auc:0.83688
[64]	validation_0-auc:0.93875	validation_1-auc:0.83682
  8%|▊         | 4/50 [00:59<12:00, 15.65s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83654	validation_1-auc:0.81324
[1]	validation_0-auc:0.84321	validation_1-auc:0.81332
[2]	validation_0-auc:0.84885	validation_1-auc:0.81378
[3]	validation_0-auc:0.85794	validation_1-auc:0.81561
[4]	validation_0-auc:0.86494	validation_1-auc:0.82027
[5]	validation_0-auc:0.86747	validation_1-auc:0.82190
[6]	validation_0-auc:0.87466	validation_1-auc:0.82375
[7]	validation_0-auc:0.88244	validation_1-auc:0.82591
[8]	validation_0-auc:0.88484	validation_1-auc:0.82583
[9]	validation_0-auc:0.89245	validation_1-auc:0.82908
[10]	validation_0-auc:0.89610	validation_1-auc:0.83185
[11]	validation_0-auc:0.89925	validation_1-auc:0.82943
[12]	validation_0-auc:0.90662	validation_1-auc:0.83138
[13]	validation_0-auc:0.91157	validation_1-auc:0.83194
[14]	validation_0-auc:0.91394	validation_1-auc:0.83395
[15]	validation_0-auc:0.91884	validation_1-auc:0.83551
[16]	validation_0-auc:0.92277	validation_1-auc:0.83557
[17]	validation_0-auc:0.92502	validation_1-auc:0.83563
[18]	validation_0-auc:0.92659	validation_1-auc:0.83543
[19]	validation_0-auc:0.92963	validation_1-auc:0.83517
[20]	validation_0-auc:0.93285	validation_1-auc:0.83556
[21]	validation_0-auc:0.93455	validation_1-auc:0.83556
[22]	validation_0-auc:0.93674	validation_1-auc:0.83501
[23]	validation_0-auc:0.93849	validation_1-auc:0.83376
[24]	validation_0-auc:0.94041	validation_1-auc:0.83300
[25]	validation_0-auc:0.94146	validation_1-auc:0.83392
[26]	validation_0-auc:0.94286	validation_1-auc:0.83423
[27]	validation_0-auc:0.94424	validation_1-auc:0.83381
[28]	validation_0-auc:0.94592	validation_1-auc:0.83339
[29]	validation_0-auc:0.94673	validation_1-auc:0.83306
[30]	validation_0-auc:0.94755	validation_1-auc:0.83311
[31]	validation_0-auc:0.94834	validation_1-auc:0.83268
[32]	validation_0-auc:0.94886	validation_1-auc:0.83301
[33]	validation_0-auc:0.94916	validation_1-auc:0.83348
[34]	validation_0-auc:0.94973	validation_1-auc:0.83346
[35]	validation_0-auc:0.95024	validation_1-auc:0.83331
[36]	validation_0-auc:0.95106	validation_1-auc:0.83324
[37]	validation_0-auc:0.95142	validation_1-auc:0.83307
[38]	validation_0-auc:0.95180	validation_1-auc:0.83310
[39]	validation_0-auc:0.95199	validation_1-auc:0.83323
[40]	validation_0-auc:0.95217	validation_1-auc:0.83309
[41]	validation_0-auc:0.95305	validation_1-auc:0.83353
[42]	validation_0-auc:0.95328	validation_1-auc:0.83369
[43]	validation_0-auc:0.95365	validation_1-auc:0.83345
[44]	validation_0-auc:0.95389	validation_1-auc:0.83323
[45]	validation_0-auc:0.95421	validation_1-auc:0.83305
[46]	validation_0-auc:0.95433	validation_1-auc:0.83300
  8%|▊         | 4/50 [01:03<12:00, 15.65s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83334	validation_1-auc:0.80870
[1]	validation_0-auc:0.84269	validation_1-auc:0.81376
[2]	validation_0-auc:0.84942	validation_1-auc:0.81888
[3]	validation_0-auc:0.85551	validation_1-auc:0.81903
[4]	validation_0-auc:0.86704	validation_1-auc:0.82043
[5]	validation_0-auc:0.87365	validation_1-auc:0.82093
[6]	validation_0-auc:0.87867	validation_1-auc:0.82253
[7]	validation_0-auc:0.88304	validation_1-auc:0.82108
[8]	validation_0-auc:0.88808	validation_1-auc:0.82127
[9]	validation_0-auc:0.89657	validation_1-auc:0.82155
[10]	validation_0-auc:0.89882	validation_1-auc:0.82202
[11]	validation_0-auc:0.90220	validation_1-auc:0.82092
[12]	validation_0-auc:0.90891	validation_1-auc:0.82314
[13]	validation_0-auc:0.91433	validation_1-auc:0.82450
[14]	validation_0-auc:0.91824	validation_1-auc:0.82646
[15]	validation_0-auc:0.92316	validation_1-auc:0.82685
[16]	validation_0-auc:0.92710	validation_1-auc:0.82779
[17]	validation_0-auc:0.92922	validation_1-auc:0.82769
[18]	validation_0-auc:0.93036	validation_1-auc:0.82673
[19]	validation_0-auc:0.93305	validation_1-auc:0.82745
[20]	validation_0-auc:0.93566	validation_1-auc:0.82745
[21]	validation_0-auc:0.93711	validation_1-auc:0.82694
[22]	validation_0-auc:0.93877	validation_1-auc:0.82622
[23]	validation_0-auc:0.94045	validation_1-auc:0.82643
[24]	validation_0-auc:0.94214	validation_1-auc:0.82574
[25]	validation_0-auc:0.94268	validation_1-auc:0.82713
[26]	validation_0-auc:0.94408	validation_1-auc:0.82627
[27]	validation_0-auc:0.94493	validation_1-auc:0.82682
[28]	validation_0-auc:0.94582	validation_1-auc:0.82696
[29]	validation_0-auc:0.94651	validation_1-auc:0.82749
[30]	validation_0-auc:0.94785	validation_1-auc:0.82713
[31]	validation_0-auc:0.94848	validation_1-auc:0.82726
[32]	validation_0-auc:0.94897	validation_1-auc:0.82711
[33]	validation_0-auc:0.94931	validation_1-auc:0.82741
[34]	validation_0-auc:0.94965	validation_1-auc:0.82716
[35]	validation_0-auc:0.95054	validation_1-auc:0.82680
[36]	validation_0-auc:0.95109	validation_1-auc:0.82685
[37]	validation_0-auc:0.95137	validation_1-auc:0.82690
[38]	validation_0-auc:0.95252	validation_1-auc:0.82580
[39]	validation_0-auc:0.95256	validation_1-auc:0.82574
[40]	validation_0-auc:0.95302	validation_1-auc:0.82558
[41]	validation_0-auc:0.95337	validation_1-auc:0.82551
[42]	validation_0-auc:0.95369	validation_1-auc:0.82530
[43]	validation_0-auc:0.95391	validation_1-auc:0.82533
[44]	validation_0-auc:0.95484	validation_1-auc:0.82467
[45]	validation_0-auc:0.95520	validation_1-auc:0.82449
  8%|▊         | 4/50 [01:07<12:00, 15.65s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82967	validation_1-auc:0.80870
[1]	validation_0-auc:0.84750	validation_1-auc:0.82147
[2]	validation_0-auc:0.85552	validation_1-auc:0.82485
[3]	validation_0-auc:0.86137	validation_1-auc:0.82601
[4]	validation_0-auc:0.86741	validation_1-auc:0.82822
[5]	validation_0-auc:0.87285	validation_1-auc:0.82826
[6]	validation_0-auc:0.87722	validation_1-auc:0.82940
[7]	validation_0-auc:0.88054	validation_1-auc:0.83246
[8]	validation_0-auc:0.88349	validation_1-auc:0.83187
[9]	validation_0-auc:0.89048	validation_1-auc:0.83133
[10]	validation_0-auc:0.89397	validation_1-auc:0.82711
[11]	validation_0-auc:0.89815	validation_1-auc:0.82507
[12]	validation_0-auc:0.90615	validation_1-auc:0.82739
[13]	validation_0-auc:0.91050	validation_1-auc:0.82951
[14]	validation_0-auc:0.91442	validation_1-auc:0.83013
[15]	validation_0-auc:0.91875	validation_1-auc:0.83168
[16]	validation_0-auc:0.92318	validation_1-auc:0.83282
[17]	validation_0-auc:0.92625	validation_1-auc:0.83426
[18]	validation_0-auc:0.92745	validation_1-auc:0.83283
[19]	validation_0-auc:0.93092	validation_1-auc:0.83245
[20]	validation_0-auc:0.93284	validation_1-auc:0.83392
[21]	validation_0-auc:0.93461	validation_1-auc:0.83307
[22]	validation_0-auc:0.93617	validation_1-auc:0.83497
[23]	validation_0-auc:0.93756	validation_1-auc:0.83547
[24]	validation_0-auc:0.93953	validation_1-auc:0.83537
[25]	validation_0-auc:0.94004	validation_1-auc:0.83557
[26]	validation_0-auc:0.94183	validation_1-auc:0.83455
[27]	validation_0-auc:0.94311	validation_1-auc:0.83478
[28]	validation_0-auc:0.94450	validation_1-auc:0.83436
[29]	validation_0-auc:0.94556	validation_1-auc:0.83365
[30]	validation_0-auc:0.94692	validation_1-auc:0.83286
[31]	validation_0-auc:0.94756	validation_1-auc:0.83369
[32]	validation_0-auc:0.94802	validation_1-auc:0.83394
[33]	validation_0-auc:0.94825	validation_1-auc:0.83430
[34]	validation_0-auc:0.94897	validation_1-auc:0.83498
[35]	validation_0-auc:0.94963	validation_1-auc:0.83495
[36]	validation_0-auc:0.95043	validation_1-auc:0.83496
[37]	validation_0-auc:0.95067	validation_1-auc:0.83483
[38]	validation_0-auc:0.95124	validation_1-auc:0.83470
[39]	validation_0-auc:0.95166	validation_1-auc:0.83446
[40]	validation_0-auc:0.95187	validation_1-auc:0.83458
[41]	validation_0-auc:0.95220	validation_1-auc:0.83455
[42]	validation_0-auc:0.95247	validation_1-auc:0.83447
[43]	validation_0-auc:0.95270	validation_1-auc:0.83439
[44]	validation_0-auc:0.95286	validation_1-auc:0.83438
[45]	validation_0-auc:0.95314	validation_1-auc:0.83431
[46]	validation_0-auc:0.95320	validation_1-auc:0.83413
[47]	validation_0-auc:0.95330	validation_1-auc:0.83395
[48]	validation_0-auc:0.95381	validation_1-auc:0.83328
[49]	validation_0-auc:0.95416	validation_1-auc:0.83275
[50]	validation_0-auc:0.95453	validation_1-auc:0.83197
[51]	validation_0-auc:0.95459	validation_1-auc:0.83185
[52]	validation_0-auc:0.95584	validation_1-auc:0.83130
[53]	validation_0-auc:0.95591	validation_1-auc:0.83143
[54]	validation_0-auc:0.95633	validation_1-auc:0.83163
[55]	validation_0-auc:0.95827	validation_1-auc:0.83160
 10%|█         | 5/50 [01:12<11:06, 14.81s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82962	validation_1-auc:0.81485
[1]	validation_0-auc:0.83535	validation_1-auc:0.81510
[2]	validation_0-auc:0.84175	validation_1-auc:0.81788
[3]	validation_0-auc:0.84506	validation_1-auc:0.81845
[4]	validation_0-auc:0.84871	validation_1-auc:0.81942
[5]	validation_0-auc:0.85083	validation_1-auc:0.82163
[6]	validation_0-auc:0.85418	validation_1-auc:0.82446
[7]	validation_0-auc:0.85517	validation_1-auc:0.82416
[8]	validation_0-auc:0.85950	validation_1-auc:0.82787
[9]	validation_0-auc:0.86288	validation_1-auc:0.83250
[10]	validation_0-auc:0.86187	validation_1-auc:0.83103
[11]	validation_0-auc:0.86267	validation_1-auc:0.83192
[12]	validation_0-auc:0.86864	validation_1-auc:0.83610
[13]	validation_0-auc:0.87164	validation_1-auc:0.83745
[14]	validation_0-auc:0.87309	validation_1-auc:0.83919
[15]	validation_0-auc:0.87468	validation_1-auc:0.84090
[16]	validation_0-auc:0.87642	validation_1-auc:0.84110
[17]	validation_0-auc:0.87771	validation_1-auc:0.84072
[18]	validation_0-auc:0.87788	validation_1-auc:0.84075
[19]	validation_0-auc:0.87913	validation_1-auc:0.84121
[20]	validation_0-auc:0.88035	validation_1-auc:0.84119
[21]	validation_0-auc:0.88122	validation_1-auc:0.84082
[22]	validation_0-auc:0.88310	validation_1-auc:0.84239
[23]	validation_0-auc:0.88522	validation_1-auc:0.84273
[24]	validation_0-auc:0.88627	validation_1-auc:0.84297
[25]	validation_0-auc:0.88693	validation_1-auc:0.84314
[26]	validation_0-auc:0.88847	validation_1-auc:0.84412
[27]	validation_0-auc:0.89025	validation_1-auc:0.84443
[28]	validation_0-auc:0.89114	validation_1-auc:0.84360
[29]	validation_0-auc:0.89301	validation_1-auc:0.84369
[30]	validation_0-auc:0.89409	validation_1-auc:0.84387
[31]	validation_0-auc:0.89508	validation_1-auc:0.84430
[32]	validation_0-auc:0.89615	validation_1-auc:0.84431
[33]	validation_0-auc:0.89690	validation_1-auc:0.84461
[34]	validation_0-auc:0.89799	validation_1-auc:0.84504
[35]	validation_0-auc:0.89839	validation_1-auc:0.84550
[36]	validation_0-auc:0.89944	validation_1-auc:0.84551
[37]	validation_0-auc:0.90039	validation_1-auc:0.84598
[38]	validation_0-auc:0.90087	validation_1-auc:0.84635
[39]	validation_0-auc:0.90109	validation_1-auc:0.84645
[40]	validation_0-auc:0.90108	validation_1-auc:0.84664
[41]	validation_0-auc:0.90141	validation_1-auc:0.84664
[42]	validation_0-auc:0.90174	validation_1-auc:0.84657
[43]	validation_0-auc:0.90225	validation_1-auc:0.84648
[44]	validation_0-auc:0.90268	validation_1-auc:0.84638
[45]	validation_0-auc:0.90308	validation_1-auc:0.84651
[46]	validation_0-auc:0.90407	validation_1-auc:0.84623
[47]	validation_0-auc:0.90502	validation_1-auc:0.84561
[48]	validation_0-auc:0.90532	validation_1-auc:0.84528
[49]	validation_0-auc:0.90554	validation_1-auc:0.84531
[50]	validation_0-auc:0.90627	validation_1-auc:0.84515
[51]	validation_0-auc:0.90650	validation_1-auc:0.84516
[52]	validation_0-auc:0.90666	validation_1-auc:0.84523
[53]	validation_0-auc:0.90678	validation_1-auc:0.84516
[54]	validation_0-auc:0.90738	validation_1-auc:0.84511
[55]	validation_0-auc:0.90803	validation_1-auc:0.84544
[56]	validation_0-auc:0.90823	validation_1-auc:0.84548
[57]	validation_0-auc:0.90925	validation_1-auc:0.84532
[58]	validation_0-auc:0.90975	validation_1-auc:0.84490
[59]	validation_0-auc:0.90983	validation_1-auc:0.84488
[60]	validation_0-auc:0.91003	validation_1-auc:0.84494
[61]	validation_0-auc:0.91045	validation_1-auc:0.84511
[62]	validation_0-auc:0.91057	validation_1-auc:0.84515
[63]	validation_0-auc:0.91070	validation_1-auc:0.84510
[64]	validation_0-auc:0.91151	validation_1-auc:0.84496
[65]	validation_0-auc:0.91163	validation_1-auc:0.84503
[66]	validation_0-auc:0.91185	validation_1-auc:0.84495
[67]	validation_0-auc:0.91241	validation_1-auc:0.84509
[68]	validation_0-auc:0.91255	validation_1-auc:0.84490
[69]	validation_0-auc:0.91320	validation_1-auc:0.84503
[70]	validation_0-auc:0.91333	validation_1-auc:0.84496
 10%|█         | 5/50 [01:17<11:06, 14.81s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82616	validation_1-auc:0.80687
[1]	validation_0-auc:0.83386	validation_1-auc:0.81428
[2]	validation_0-auc:0.83769	validation_1-auc:0.81478
[3]	validation_0-auc:0.84108	validation_1-auc:0.81737
[4]	validation_0-auc:0.85015	validation_1-auc:0.82301
[5]	validation_0-auc:0.85224	validation_1-auc:0.82358
[6]	validation_0-auc:0.85696	validation_1-auc:0.82553
[7]	validation_0-auc:0.85931	validation_1-auc:0.82552
[8]	validation_0-auc:0.86069	validation_1-auc:0.82531
[9]	validation_0-auc:0.86431	validation_1-auc:0.82670
[10]	validation_0-auc:0.86541	validation_1-auc:0.82632
[11]	validation_0-auc:0.86645	validation_1-auc:0.82587
[12]	validation_0-auc:0.87213	validation_1-auc:0.82792
[13]	validation_0-auc:0.87504	validation_1-auc:0.82927
[14]	validation_0-auc:0.87582	validation_1-auc:0.82999
[15]	validation_0-auc:0.87851	validation_1-auc:0.83093
[16]	validation_0-auc:0.87957	validation_1-auc:0.83231
[17]	validation_0-auc:0.88155	validation_1-auc:0.83376
[18]	validation_0-auc:0.88229	validation_1-auc:0.83296
[19]	validation_0-auc:0.88486	validation_1-auc:0.83417
[20]	validation_0-auc:0.88637	validation_1-auc:0.83463
[21]	validation_0-auc:0.88692	validation_1-auc:0.83430
[22]	validation_0-auc:0.88822	validation_1-auc:0.83420
[23]	validation_0-auc:0.88981	validation_1-auc:0.83468
[24]	validation_0-auc:0.89034	validation_1-auc:0.83559
[25]	validation_0-auc:0.89084	validation_1-auc:0.83576
[26]	validation_0-auc:0.89208	validation_1-auc:0.83585
[27]	validation_0-auc:0.89380	validation_1-auc:0.83604
[28]	validation_0-auc:0.89497	validation_1-auc:0.83659
[29]	validation_0-auc:0.89594	validation_1-auc:0.83693
[30]	validation_0-auc:0.89693	validation_1-auc:0.83627
[31]	validation_0-auc:0.89800	validation_1-auc:0.83696
[32]	validation_0-auc:0.89862	validation_1-auc:0.83765
[33]	validation_0-auc:0.89912	validation_1-auc:0.83801
[34]	validation_0-auc:0.89958	validation_1-auc:0.83783
[35]	validation_0-auc:0.90040	validation_1-auc:0.83763
[36]	validation_0-auc:0.90171	validation_1-auc:0.83767
[37]	validation_0-auc:0.90224	validation_1-auc:0.83684
[38]	validation_0-auc:0.90290	validation_1-auc:0.83681
[39]	validation_0-auc:0.90319	validation_1-auc:0.83702
[40]	validation_0-auc:0.90336	validation_1-auc:0.83707
[41]	validation_0-auc:0.90402	validation_1-auc:0.83711
[42]	validation_0-auc:0.90442	validation_1-auc:0.83695
[43]	validation_0-auc:0.90487	validation_1-auc:0.83686
[44]	validation_0-auc:0.90535	validation_1-auc:0.83738
[45]	validation_0-auc:0.90574	validation_1-auc:0.83744
[46]	validation_0-auc:0.90589	validation_1-auc:0.83749
[47]	validation_0-auc:0.90655	validation_1-auc:0.83728
[48]	validation_0-auc:0.90732	validation_1-auc:0.83744
[49]	validation_0-auc:0.90773	validation_1-auc:0.83742
[50]	validation_0-auc:0.90857	validation_1-auc:0.83725
[51]	validation_0-auc:0.90922	validation_1-auc:0.83710
[52]	validation_0-auc:0.90953	validation_1-auc:0.83721
[53]	validation_0-auc:0.91034	validation_1-auc:0.83733
[54]	validation_0-auc:0.91048	validation_1-auc:0.83725
[55]	validation_0-auc:0.91115	validation_1-auc:0.83718
[56]	validation_0-auc:0.91127	validation_1-auc:0.83728
[57]	validation_0-auc:0.91151	validation_1-auc:0.83713
[58]	validation_0-auc:0.91234	validation_1-auc:0.83710
[59]	validation_0-auc:0.91249	validation_1-auc:0.83699
[60]	validation_0-auc:0.91262	validation_1-auc:0.83686
[61]	validation_0-auc:0.91301	validation_1-auc:0.83679
[62]	validation_0-auc:0.91350	validation_1-auc:0.83655
[63]	validation_0-auc:0.91363	validation_1-auc:0.83657
 10%|█         | 5/50 [01:20<11:06, 14.81s/trial, best loss: -0.8425210985180778]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82195	validation_1-auc:0.81093
[1]	validation_0-auc:0.82975	validation_1-auc:0.81490
[2]	validation_0-auc:0.83985	validation_1-auc:0.82568
[3]	validation_0-auc:0.84680	validation_1-auc:0.83013
[4]	validation_0-auc:0.85226	validation_1-auc:0.83434
[5]	validation_0-auc:0.85470	validation_1-auc:0.83552
[6]	validation_0-auc:0.85681	validation_1-auc:0.83580
[7]	validation_0-auc:0.85729	validation_1-auc:0.83618
[8]	validation_0-auc:0.85824	validation_1-auc:0.83606
[9]	validation_0-auc:0.86234	validation_1-auc:0.83685
[10]	validation_0-auc:0.86197	validation_1-auc:0.83502
[11]	validation_0-auc:0.86186	validation_1-auc:0.83238
[12]	validation_0-auc:0.86676	validation_1-auc:0.83494
[13]	validation_0-auc:0.87047	validation_1-auc:0.83666
[14]	validation_0-auc:0.87185	validation_1-auc:0.83963
[15]	validation_0-auc:0.87364	validation_1-auc:0.84058
[16]	validation_0-auc:0.87609	validation_1-auc:0.84177
[17]	validation_0-auc:0.87837	validation_1-auc:0.84326
[18]	validation_0-auc:0.87892	validation_1-auc:0.84168
[19]	validation_0-auc:0.88115	validation_1-auc:0.84375
[20]	validation_0-auc:0.88316	validation_1-auc:0.84431
[21]	validation_0-auc:0.88358	validation_1-auc:0.84318
[22]	validation_0-auc:0.88543	validation_1-auc:0.84411
[23]	validation_0-auc:0.88668	validation_1-auc:0.84395
[24]	validation_0-auc:0.88787	validation_1-auc:0.84440
[25]	validation_0-auc:0.88885	validation_1-auc:0.84422
[26]	validation_0-auc:0.89045	validation_1-auc:0.84366
[27]	validation_0-auc:0.89180	validation_1-auc:0.84368
[28]	validation_0-auc:0.89256	validation_1-auc:0.84360
[29]	validation_0-auc:0.89382	validation_1-auc:0.84396
[30]	validation_0-auc:0.89533	validation_1-auc:0.84346
[31]	validation_0-auc:0.89601	validation_1-auc:0.84354
[32]	validation_0-auc:0.89637	validation_1-auc:0.84377
[33]	validation_0-auc:0.89704	validation_1-auc:0.84360
[34]	validation_0-auc:0.89760	validation_1-auc:0.84376
[35]	validation_0-auc:0.89824	validation_1-auc:0.84394
[36]	validation_0-auc:0.89892	validation_1-auc:0.84401
[37]	validation_0-auc:0.89976	validation_1-auc:0.84436
[38]	validation_0-auc:0.90102	validation_1-auc:0.84445
[39]	validation_0-auc:0.90124	validation_1-auc:0.84452
[40]	validation_0-auc:0.90176	validation_1-auc:0.84408
[41]	validation_0-auc:0.90209	validation_1-auc:0.84419
[42]	validation_0-auc:0.90254	validation_1-auc:0.84396
[43]	validation_0-auc:0.90280	validation_1-auc:0.84419
[44]	validation_0-auc:0.90349	validation_1-auc:0.84388
[45]	validation_0-auc:0.90431	validation_1-auc:0.84372
[46]	validation_0-auc:0.90455	validation_1-auc:0.84374
[47]	validation_0-auc:0.90517	validation_1-auc:0.84371
[48]	validation_0-auc:0.90590	validation_1-auc:0.84349
[49]	validation_0-auc:0.90679	validation_1-auc:0.84327
[50]	validation_0-auc:0.90709	validation_1-auc:0.84306
[51]	validation_0-auc:0.90720	validation_1-auc:0.84308
[52]	validation_0-auc:0.90721	validation_1-auc:0.84308
[53]	validation_0-auc:0.90776	validation_1-auc:0.84300
[54]	validation_0-auc:0.90846	validation_1-auc:0.84275
[55]	validation_0-auc:0.90880	validation_1-auc:0.84280
[56]	validation_0-auc:0.90935	validation_1-auc:0.84291
[57]	validation_0-auc:0.90950	validation_1-auc:0.84288
[58]	validation_0-auc:0.90968	validation_1-auc:0.84260
[59]	validation_0-auc:0.90983	validation_1-auc:0.84255
[60]	validation_0-auc:0.90997	validation_1-auc:0.84241
[61]	validation_0-auc:0.91026	validation_1-auc:0.84220
[62]	validation_0-auc:0.91052	validation_1-auc:0.84229
[63]	validation_0-auc:0.91067	validation_1-auc:0.84236
[64]	validation_0-auc:0.91114	validation_1-auc:0.84238
[65]	validation_0-auc:0.91128	validation_1-auc:0.84219
[66]	validation_0-auc:0.91177	validation_1-auc:0.84193
[67]	validation_0-auc:0.91198	validation_1-auc:0.84195
[68]	validation_0-auc:0.91239	validation_1-auc:0.84218
 12%|█▏        | 6/50 [01:24<10:08, 13.84s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82972	validation_1-auc:0.81446
[1]	validation_0-auc:0.83692	validation_1-auc:0.81515
[2]	validation_0-auc:0.84284	validation_1-auc:0.81779
[3]	validation_0-auc:0.84561	validation_1-auc:0.81838
[4]	validation_0-auc:0.84930	validation_1-auc:0.81915
[5]	validation_0-auc:0.85574	validation_1-auc:0.82520
[6]	validation_0-auc:0.86139	validation_1-auc:0.82912
[7]	validation_0-auc:0.86352	validation_1-auc:0.83014
[8]	validation_0-auc:0.86481	validation_1-auc:0.83028
[9]	validation_0-auc:0.86632	validation_1-auc:0.83304
[10]	validation_0-auc:0.86579	validation_1-auc:0.83148
[11]	validation_0-auc:0.86727	validation_1-auc:0.83098
[12]	validation_0-auc:0.87085	validation_1-auc:0.83363
[13]	validation_0-auc:0.87380	validation_1-auc:0.83717
[14]	validation_0-auc:0.87606	validation_1-auc:0.83956
[15]	validation_0-auc:0.87792	validation_1-auc:0.84148
[16]	validation_0-auc:0.87835	validation_1-auc:0.84217
[17]	validation_0-auc:0.87983	validation_1-auc:0.84185
[18]	validation_0-auc:0.88020	validation_1-auc:0.84170
[19]	validation_0-auc:0.88201	validation_1-auc:0.84166
[20]	validation_0-auc:0.88333	validation_1-auc:0.84224
[21]	validation_0-auc:0.88385	validation_1-auc:0.84181
[22]	validation_0-auc:0.88666	validation_1-auc:0.84211
[23]	validation_0-auc:0.88884	validation_1-auc:0.84216
[24]	validation_0-auc:0.88973	validation_1-auc:0.84194
[25]	validation_0-auc:0.89099	validation_1-auc:0.84269
[26]	validation_0-auc:0.89216	validation_1-auc:0.84341
[27]	validation_0-auc:0.89359	validation_1-auc:0.84301
[28]	validation_0-auc:0.89407	validation_1-auc:0.84282
[29]	validation_0-auc:0.89561	validation_1-auc:0.84317
[30]	validation_0-auc:0.89651	validation_1-auc:0.84349
[31]	validation_0-auc:0.89753	validation_1-auc:0.84389
[32]	validation_0-auc:0.89839	validation_1-auc:0.84393
[33]	validation_0-auc:0.89934	validation_1-auc:0.84432
[34]	validation_0-auc:0.90002	validation_1-auc:0.84432
[35]	validation_0-auc:0.90099	validation_1-auc:0.84437
[36]	validation_0-auc:0.90190	validation_1-auc:0.84432
[37]	validation_0-auc:0.90327	validation_1-auc:0.84436
[38]	validation_0-auc:0.90380	validation_1-auc:0.84411
[39]	validation_0-auc:0.90416	validation_1-auc:0.84409
[40]	validation_0-auc:0.90496	validation_1-auc:0.84391
[41]	validation_0-auc:0.90519	validation_1-auc:0.84401
[42]	validation_0-auc:0.90585	validation_1-auc:0.84391
[43]	validation_0-auc:0.90657	validation_1-auc:0.84380
[44]	validation_0-auc:0.90722	validation_1-auc:0.84341
[45]	validation_0-auc:0.90815	validation_1-auc:0.84336
[46]	validation_0-auc:0.90906	validation_1-auc:0.84333
[47]	validation_0-auc:0.90925	validation_1-auc:0.84330
[48]	validation_0-auc:0.90968	validation_1-auc:0.84313
[49]	validation_0-auc:0.91010	validation_1-auc:0.84299
[50]	validation_0-auc:0.91087	validation_1-auc:0.84282
[51]	validation_0-auc:0.91111	validation_1-auc:0.84272
[52]	validation_0-auc:0.91132	validation_1-auc:0.84260
[53]	validation_0-auc:0.91149	validation_1-auc:0.84251
[54]	validation_0-auc:0.91183	validation_1-auc:0.84242
[55]	validation_0-auc:0.91289	validation_1-auc:0.84208
[56]	validation_0-auc:0.91304	validation_1-auc:0.84203
[57]	validation_0-auc:0.91321	validation_1-auc:0.84209
[58]	validation_0-auc:0.91337	validation_1-auc:0.84211
[59]	validation_0-auc:0.91355	validation_1-auc:0.84212
[60]	validation_0-auc:0.91386	validation_1-auc:0.84201
[61]	validation_0-auc:0.91399	validation_1-auc:0.84198
[62]	validation_0-auc:0.91412	validation_1-auc:0.84197
[63]	validation_0-auc:0.91458	validation_1-auc:0.84181
[64]	validation_0-auc:0.91498	validation_1-auc:0.84186
[65]	validation_0-auc:0.91591	validation_1-auc:0.84154
 12%|█▏        | 6/50 [01:28<10:08, 13.84s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82570	validation_1-auc:0.80666
[1]	validation_0-auc:0.83538	validation_1-auc:0.81272
[2]	validation_0-auc:0.84035	validation_1-auc:0.81563
[3]	validation_0-auc:0.84677	validation_1-auc:0.81971
[4]	validation_0-auc:0.85181	validation_1-auc:0.82199
[5]	validation_0-auc:0.85621	validation_1-auc:0.82468
[6]	validation_0-auc:0.86065	validation_1-auc:0.82744
[7]	validation_0-auc:0.86422	validation_1-auc:0.82765
[8]	validation_0-auc:0.86535	validation_1-auc:0.82841
[9]	validation_0-auc:0.86863	validation_1-auc:0.82856
[10]	validation_0-auc:0.86807	validation_1-auc:0.82570
[11]	validation_0-auc:0.86893	validation_1-auc:0.82453
[12]	validation_0-auc:0.87340	validation_1-auc:0.82724
[13]	validation_0-auc:0.87591	validation_1-auc:0.82914
[14]	validation_0-auc:0.87682	validation_1-auc:0.83100
[15]	validation_0-auc:0.88001	validation_1-auc:0.83321
[16]	validation_0-auc:0.88122	validation_1-auc:0.83436
[17]	validation_0-auc:0.88439	validation_1-auc:0.83429
[18]	validation_0-auc:0.88494	validation_1-auc:0.83308
[19]	validation_0-auc:0.88796	validation_1-auc:0.83463
[20]	validation_0-auc:0.88943	validation_1-auc:0.83570
[21]	validation_0-auc:0.89034	validation_1-auc:0.83474
[22]	validation_0-auc:0.89265	validation_1-auc:0.83487
[23]	validation_0-auc:0.89365	validation_1-auc:0.83541
[24]	validation_0-auc:0.89451	validation_1-auc:0.83623
[25]	validation_0-auc:0.89470	validation_1-auc:0.83707
[26]	validation_0-auc:0.89662	validation_1-auc:0.83734
[27]	validation_0-auc:0.89839	validation_1-auc:0.83748
[28]	validation_0-auc:0.89874	validation_1-auc:0.83818
[29]	validation_0-auc:0.90001	validation_1-auc:0.83872
[30]	validation_0-auc:0.90087	validation_1-auc:0.83841
[31]	validation_0-auc:0.90201	validation_1-auc:0.83871
[32]	validation_0-auc:0.90318	validation_1-auc:0.83815
[33]	validation_0-auc:0.90345	validation_1-auc:0.83853
[34]	validation_0-auc:0.90376	validation_1-auc:0.83829
[35]	validation_0-auc:0.90421	validation_1-auc:0.83818
[36]	validation_0-auc:0.90489	validation_1-auc:0.83771
[37]	validation_0-auc:0.90597	validation_1-auc:0.83705
[38]	validation_0-auc:0.90673	validation_1-auc:0.83689
[39]	validation_0-auc:0.90702	validation_1-auc:0.83681
[40]	validation_0-auc:0.90747	validation_1-auc:0.83692
[41]	validation_0-auc:0.90772	validation_1-auc:0.83689
[42]	validation_0-auc:0.90838	validation_1-auc:0.83690
[43]	validation_0-auc:0.90918	validation_1-auc:0.83668
[44]	validation_0-auc:0.90975	validation_1-auc:0.83659
[45]	validation_0-auc:0.91031	validation_1-auc:0.83646
[46]	validation_0-auc:0.91149	validation_1-auc:0.83596
[47]	validation_0-auc:0.91247	validation_1-auc:0.83612
[48]	validation_0-auc:0.91336	validation_1-auc:0.83597
[49]	validation_0-auc:0.91349	validation_1-auc:0.83638
[50]	validation_0-auc:0.91418	validation_1-auc:0.83658
[51]	validation_0-auc:0.91458	validation_1-auc:0.83618
[52]	validation_0-auc:0.91478	validation_1-auc:0.83613
[53]	validation_0-auc:0.91491	validation_1-auc:0.83608
[54]	validation_0-auc:0.91516	validation_1-auc:0.83590
[55]	validation_0-auc:0.91528	validation_1-auc:0.83571
[56]	validation_0-auc:0.91539	validation_1-auc:0.83589
[57]	validation_0-auc:0.91559	validation_1-auc:0.83584
[58]	validation_0-auc:0.91593	validation_1-auc:0.83576
[59]	validation_0-auc:0.91715	validation_1-auc:0.83603
 12%|█▏        | 6/50 [01:32<10:08, 13.84s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82225	validation_1-auc:0.81042
[1]	validation_0-auc:0.83618	validation_1-auc:0.82540
[2]	validation_0-auc:0.84556	validation_1-auc:0.82950
[3]	validation_0-auc:0.84756	validation_1-auc:0.82856
[4]	validation_0-auc:0.85261	validation_1-auc:0.83269
[5]	validation_0-auc:0.85418	validation_1-auc:0.83084
[6]	validation_0-auc:0.85827	validation_1-auc:0.83342
[7]	validation_0-auc:0.86067	validation_1-auc:0.83493
[8]	validation_0-auc:0.86151	validation_1-auc:0.83576
[9]	validation_0-auc:0.86284	validation_1-auc:0.83275
[10]	validation_0-auc:0.86357	validation_1-auc:0.83075
[11]	validation_0-auc:0.86418	validation_1-auc:0.82938
[12]	validation_0-auc:0.86881	validation_1-auc:0.83251
[13]	validation_0-auc:0.87221	validation_1-auc:0.83570
[14]	validation_0-auc:0.87376	validation_1-auc:0.83745
[15]	validation_0-auc:0.87681	validation_1-auc:0.83915
[16]	validation_0-auc:0.87858	validation_1-auc:0.84015
[17]	validation_0-auc:0.88137	validation_1-auc:0.84093
[18]	validation_0-auc:0.88141	validation_1-auc:0.83904
[19]	validation_0-auc:0.88304	validation_1-auc:0.83973
[20]	validation_0-auc:0.88442	validation_1-auc:0.84111
[21]	validation_0-auc:0.88622	validation_1-auc:0.84000
[22]	validation_0-auc:0.88842	validation_1-auc:0.84073
[23]	validation_0-auc:0.88990	validation_1-auc:0.84065
[24]	validation_0-auc:0.89193	validation_1-auc:0.84077
[25]	validation_0-auc:0.89276	validation_1-auc:0.84126
[26]	validation_0-auc:0.89444	validation_1-auc:0.84158
[27]	validation_0-auc:0.89603	validation_1-auc:0.84203
[28]	validation_0-auc:0.89652	validation_1-auc:0.84177
[29]	validation_0-auc:0.89751	validation_1-auc:0.84179
[30]	validation_0-auc:0.89877	validation_1-auc:0.84172
[31]	validation_0-auc:0.89953	validation_1-auc:0.84202
[32]	validation_0-auc:0.90035	validation_1-auc:0.84203
[33]	validation_0-auc:0.90062	validation_1-auc:0.84232
[34]	validation_0-auc:0.90077	validation_1-auc:0.84228
[35]	validation_0-auc:0.90158	validation_1-auc:0.84241
[36]	validation_0-auc:0.90326	validation_1-auc:0.84157
[37]	validation_0-auc:0.90384	validation_1-auc:0.84183
[38]	validation_0-auc:0.90455	validation_1-auc:0.84178
[39]	validation_0-auc:0.90469	validation_1-auc:0.84211
[40]	validation_0-auc:0.90547	validation_1-auc:0.84133
[41]	validation_0-auc:0.90620	validation_1-auc:0.84149
[42]	validation_0-auc:0.90668	validation_1-auc:0.84131
[43]	validation_0-auc:0.90690	validation_1-auc:0.84155
[44]	validation_0-auc:0.90817	validation_1-auc:0.84137
[45]	validation_0-auc:0.90872	validation_1-auc:0.84165
[46]	validation_0-auc:0.90951	validation_1-auc:0.84120
[47]	validation_0-auc:0.90970	validation_1-auc:0.84112
[48]	validation_0-auc:0.91046	validation_1-auc:0.84092
[49]	validation_0-auc:0.91073	validation_1-auc:0.84090
[50]	validation_0-auc:0.91091	validation_1-auc:0.84085
[51]	validation_0-auc:0.91137	validation_1-auc:0.84092
[52]	validation_0-auc:0.91200	validation_1-auc:0.84112
[53]	validation_0-auc:0.91219	validation_1-auc:0.84111
[54]	validation_0-auc:0.91242	validation_1-auc:0.84096
[55]	validation_0-auc:0.91301	validation_1-auc:0.84105
[56]	validation_0-auc:0.91334	validation_1-auc:0.84098
[57]	validation_0-auc:0.91355	validation_1-auc:0.84119
[58]	validation_0-auc:0.91384	validation_1-auc:0.84132
[59]	validation_0-auc:0.91395	validation_1-auc:0.84133
[60]	validation_0-auc:0.91414	validation_1-auc:0.84106
[61]	validation_0-auc:0.91449	validation_1-auc:0.84069
[62]	validation_0-auc:0.91469	validation_1-auc:0.84076
[63]	validation_0-auc:0.91479	validation_1-auc:0.84070
[64]	validation_0-auc:0.91490	validation_1-auc:0.84068
 14%|█▍        | 7/50 [01:36<09:20, 13.04s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83316	validation_1-auc:0.81344
[1]	validation_0-auc:0.84099	validation_1-auc:0.81375
[2]	validation_0-auc:0.84887	validation_1-auc:0.81438
[3]	validation_0-auc:0.85382	validation_1-auc:0.81703
[4]	validation_0-auc:0.86299	validation_1-auc:0.82090
[5]	validation_0-auc:0.86506	validation_1-auc:0.82174
[6]	validation_0-auc:0.86976	validation_1-auc:0.82253
[7]	validation_0-auc:0.87262	validation_1-auc:0.82134
[8]	validation_0-auc:0.87834	validation_1-auc:0.82388
[9]	validation_0-auc:0.88676	validation_1-auc:0.82633
[10]	validation_0-auc:0.88666	validation_1-auc:0.82676
[11]	validation_0-auc:0.89035	validation_1-auc:0.82567
[12]	validation_0-auc:0.89560	validation_1-auc:0.83068
[13]	validation_0-auc:0.89928	validation_1-auc:0.83179
[14]	validation_0-auc:0.90114	validation_1-auc:0.83327
[15]	validation_0-auc:0.90493	validation_1-auc:0.83266
[16]	validation_0-auc:0.90719	validation_1-auc:0.83419
[17]	validation_0-auc:0.91014	validation_1-auc:0.83410
[18]	validation_0-auc:0.91156	validation_1-auc:0.83424
[19]	validation_0-auc:0.91398	validation_1-auc:0.83604
[20]	validation_0-auc:0.91597	validation_1-auc:0.83595
[21]	validation_0-auc:0.91742	validation_1-auc:0.83656
[22]	validation_0-auc:0.91937	validation_1-auc:0.83655
[23]	validation_0-auc:0.92182	validation_1-auc:0.83642
[24]	validation_0-auc:0.92371	validation_1-auc:0.83603
[25]	validation_0-auc:0.92484	validation_1-auc:0.83618
[26]	validation_0-auc:0.92678	validation_1-auc:0.83647
[27]	validation_0-auc:0.92873	validation_1-auc:0.83640
[28]	validation_0-auc:0.93004	validation_1-auc:0.83608
[29]	validation_0-auc:0.93169	validation_1-auc:0.83537
[30]	validation_0-auc:0.93332	validation_1-auc:0.83608
[31]	validation_0-auc:0.93467	validation_1-auc:0.83628
[32]	validation_0-auc:0.93588	validation_1-auc:0.83642
[33]	validation_0-auc:0.93649	validation_1-auc:0.83622
[34]	validation_0-auc:0.93738	validation_1-auc:0.83611
[35]	validation_0-auc:0.93817	validation_1-auc:0.83644
[36]	validation_0-auc:0.93907	validation_1-auc:0.83650
[37]	validation_0-auc:0.93994	validation_1-auc:0.83647
[38]	validation_0-auc:0.94079	validation_1-auc:0.83614
[39]	validation_0-auc:0.94106	validation_1-auc:0.83652
[40]	validation_0-auc:0.94141	validation_1-auc:0.83719
[41]	validation_0-auc:0.94234	validation_1-auc:0.83702
[42]	validation_0-auc:0.94321	validation_1-auc:0.83721
[43]	validation_0-auc:0.94364	validation_1-auc:0.83725
[44]	validation_0-auc:0.94479	validation_1-auc:0.83684
[45]	validation_0-auc:0.94538	validation_1-auc:0.83664
[46]	validation_0-auc:0.94568	validation_1-auc:0.83689
[47]	validation_0-auc:0.94589	validation_1-auc:0.83690
[48]	validation_0-auc:0.94622	validation_1-auc:0.83681
[49]	validation_0-auc:0.94686	validation_1-auc:0.83685
[50]	validation_0-auc:0.94724	validation_1-auc:0.83682
[51]	validation_0-auc:0.94761	validation_1-auc:0.83640
[52]	validation_0-auc:0.94832	validation_1-auc:0.83616
[53]	validation_0-auc:0.94892	validation_1-auc:0.83604
[54]	validation_0-auc:0.94903	validation_1-auc:0.83591
[55]	validation_0-auc:0.94953	validation_1-auc:0.83574
[56]	validation_0-auc:0.94973	validation_1-auc:0.83584
[57]	validation_0-auc:0.94998	validation_1-auc:0.83564
[58]	validation_0-auc:0.95026	validation_1-auc:0.83560
[59]	validation_0-auc:0.95051	validation_1-auc:0.83520
[60]	validation_0-auc:0.95069	validation_1-auc:0.83526
[61]	validation_0-auc:0.95084	validation_1-auc:0.83497
[62]	validation_0-auc:0.95094	validation_1-auc:0.83493
[63]	validation_0-auc:0.95116	validation_1-auc:0.83501
[64]	validation_0-auc:0.95156	validation_1-auc:0.83509
[65]	validation_0-auc:0.95170	validation_1-auc:0.83481
[66]	validation_0-auc:0.95186	validation_1-auc:0.83478
[67]	validation_0-auc:0.95194	validation_1-auc:0.83478
[68]	validation_0-auc:0.95201	validation_1-auc:0.83474
[69]	validation_0-auc:0.95214	validation_1-auc:0.83460
[70]	validation_0-auc:0.95228	validation_1-auc:0.83468
[71]	validation_0-auc:0.95242	validation_1-auc:0.83448
[72]	validation_0-auc:0.95281	validation_1-auc:0.83427
 14%|█▍        | 7/50 [01:44<09:20, 13.04s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83107	validation_1-auc:0.80828
[1]	validation_0-auc:0.83728	validation_1-auc:0.81136
[2]	validation_0-auc:0.84394	validation_1-auc:0.81396
[3]	validation_0-auc:0.84880	validation_1-auc:0.81557
[4]	validation_0-auc:0.85983	validation_1-auc:0.82007
[5]	validation_0-auc:0.86323	validation_1-auc:0.82069
[6]	validation_0-auc:0.86958	validation_1-auc:0.81959
[7]	validation_0-auc:0.87406	validation_1-auc:0.82135
[8]	validation_0-auc:0.87849	validation_1-auc:0.82350
[9]	validation_0-auc:0.88788	validation_1-auc:0.82394
[10]	validation_0-auc:0.89071	validation_1-auc:0.82503
[11]	validation_0-auc:0.89304	validation_1-auc:0.82508
[12]	validation_0-auc:0.89918	validation_1-auc:0.82672
[13]	validation_0-auc:0.90306	validation_1-auc:0.82813
[14]	validation_0-auc:0.90556	validation_1-auc:0.82924
[15]	validation_0-auc:0.90731	validation_1-auc:0.82922
[16]	validation_0-auc:0.90934	validation_1-auc:0.82938
[17]	validation_0-auc:0.91211	validation_1-auc:0.82891
[18]	validation_0-auc:0.91321	validation_1-auc:0.82802
[19]	validation_0-auc:0.91554	validation_1-auc:0.82918
[20]	validation_0-auc:0.91708	validation_1-auc:0.83034
[21]	validation_0-auc:0.91847	validation_1-auc:0.83053
[22]	validation_0-auc:0.92046	validation_1-auc:0.83155
[23]	validation_0-auc:0.92198	validation_1-auc:0.83171
[24]	validation_0-auc:0.92416	validation_1-auc:0.83101
[25]	validation_0-auc:0.92501	validation_1-auc:0.83222
[26]	validation_0-auc:0.92737	validation_1-auc:0.83092
[27]	validation_0-auc:0.92939	validation_1-auc:0.83024
[28]	validation_0-auc:0.93066	validation_1-auc:0.82934
[29]	validation_0-auc:0.93166	validation_1-auc:0.82964
[30]	validation_0-auc:0.93320	validation_1-auc:0.82881
[31]	validation_0-auc:0.93447	validation_1-auc:0.82845
[32]	validation_0-auc:0.93550	validation_1-auc:0.82849
[33]	validation_0-auc:0.93627	validation_1-auc:0.82848
[34]	validation_0-auc:0.93756	validation_1-auc:0.82822
[35]	validation_0-auc:0.93854	validation_1-auc:0.82813
[36]	validation_0-auc:0.93970	validation_1-auc:0.82781
[37]	validation_0-auc:0.94029	validation_1-auc:0.82821
[38]	validation_0-auc:0.94090	validation_1-auc:0.82804
[39]	validation_0-auc:0.94129	validation_1-auc:0.82817
[40]	validation_0-auc:0.94177	validation_1-auc:0.82844
[41]	validation_0-auc:0.94217	validation_1-auc:0.82822
[42]	validation_0-auc:0.94251	validation_1-auc:0.82869
[43]	validation_0-auc:0.94326	validation_1-auc:0.82887
[44]	validation_0-auc:0.94359	validation_1-auc:0.82884
[45]	validation_0-auc:0.94401	validation_1-auc:0.82873
[46]	validation_0-auc:0.94416	validation_1-auc:0.82858
[47]	validation_0-auc:0.94466	validation_1-auc:0.82839
[48]	validation_0-auc:0.94532	validation_1-auc:0.82820
[49]	validation_0-auc:0.94573	validation_1-auc:0.82844
[50]	validation_0-auc:0.94659	validation_1-auc:0.82815
[51]	validation_0-auc:0.94702	validation_1-auc:0.82842
[52]	validation_0-auc:0.94773	validation_1-auc:0.82840
[53]	validation_0-auc:0.94800	validation_1-auc:0.82839
[54]	validation_0-auc:0.94848	validation_1-auc:0.82835
[55]	validation_0-auc:0.94895	validation_1-auc:0.82805
 14%|█▍        | 7/50 [01:49<09:20, 13.04s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82855	validation_1-auc:0.80806
[1]	validation_0-auc:0.84572	validation_1-auc:0.82289
[2]	validation_0-auc:0.84920	validation_1-auc:0.82370
[3]	validation_0-auc:0.85372	validation_1-auc:0.82560
[4]	validation_0-auc:0.86449	validation_1-auc:0.82749
[5]	validation_0-auc:0.86853	validation_1-auc:0.82685
[6]	validation_0-auc:0.87213	validation_1-auc:0.82769
[7]	validation_0-auc:0.87364	validation_1-auc:0.82853
[8]	validation_0-auc:0.87552	validation_1-auc:0.82870
[9]	validation_0-auc:0.88300	validation_1-auc:0.83087
[10]	validation_0-auc:0.88492	validation_1-auc:0.82873
[11]	validation_0-auc:0.88497	validation_1-auc:0.82537
[12]	validation_0-auc:0.89111	validation_1-auc:0.82776
[13]	validation_0-auc:0.89545	validation_1-auc:0.82974
[14]	validation_0-auc:0.89690	validation_1-auc:0.83127
[15]	validation_0-auc:0.90104	validation_1-auc:0.83341
[16]	validation_0-auc:0.90440	validation_1-auc:0.83604
[17]	validation_0-auc:0.90668	validation_1-auc:0.83680
[18]	validation_0-auc:0.90846	validation_1-auc:0.83439
[19]	validation_0-auc:0.91087	validation_1-auc:0.83516
[20]	validation_0-auc:0.91293	validation_1-auc:0.83473
[21]	validation_0-auc:0.91468	validation_1-auc:0.83597
[22]	validation_0-auc:0.91668	validation_1-auc:0.83780
[23]	validation_0-auc:0.91862	validation_1-auc:0.83726
[24]	validation_0-auc:0.92069	validation_1-auc:0.83718
[25]	validation_0-auc:0.92185	validation_1-auc:0.83802
[26]	validation_0-auc:0.92455	validation_1-auc:0.83675
[27]	validation_0-auc:0.92638	validation_1-auc:0.83697
[28]	validation_0-auc:0.92778	validation_1-auc:0.83685
[29]	validation_0-auc:0.92875	validation_1-auc:0.83642
[30]	validation_0-auc:0.93029	validation_1-auc:0.83599
[31]	validation_0-auc:0.93127	validation_1-auc:0.83668
[32]	validation_0-auc:0.93229	validation_1-auc:0.83711
[33]	validation_0-auc:0.93279	validation_1-auc:0.83699
[34]	validation_0-auc:0.93420	validation_1-auc:0.83687
[35]	validation_0-auc:0.93494	validation_1-auc:0.83716
[36]	validation_0-auc:0.93588	validation_1-auc:0.83706
[37]	validation_0-auc:0.93745	validation_1-auc:0.83692
[38]	validation_0-auc:0.93823	validation_1-auc:0.83718
[39]	validation_0-auc:0.93850	validation_1-auc:0.83716
[40]	validation_0-auc:0.93893	validation_1-auc:0.83685
[41]	validation_0-auc:0.93957	validation_1-auc:0.83655
[42]	validation_0-auc:0.94045	validation_1-auc:0.83634
[43]	validation_0-auc:0.94117	validation_1-auc:0.83643
[44]	validation_0-auc:0.94173	validation_1-auc:0.83668
[45]	validation_0-auc:0.94228	validation_1-auc:0.83659
[46]	validation_0-auc:0.94254	validation_1-auc:0.83677
[47]	validation_0-auc:0.94278	validation_1-auc:0.83660
[48]	validation_0-auc:0.94315	validation_1-auc:0.83652
[49]	validation_0-auc:0.94360	validation_1-auc:0.83639
[50]	validation_0-auc:0.94403	validation_1-auc:0.83646
[51]	validation_0-auc:0.94437	validation_1-auc:0.83627
[52]	validation_0-auc:0.94544	validation_1-auc:0.83580
[53]	validation_0-auc:0.94579	validation_1-auc:0.83562
[54]	validation_0-auc:0.94637	validation_1-auc:0.83524
 16%|█▌        | 8/50 [01:55<10:27, 14.94s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82681	validation_1-auc:0.81272
[1]	validation_0-auc:0.83484	validation_1-auc:0.81644
[2]	validation_0-auc:0.83993	validation_1-auc:0.81864
[3]	validation_0-auc:0.84228	validation_1-auc:0.81911
[4]	validation_0-auc:0.84610	validation_1-auc:0.82145
[5]	validation_0-auc:0.84857	validation_1-auc:0.82304
[6]	validation_0-auc:0.84993	validation_1-auc:0.82272
[7]	validation_0-auc:0.85362	validation_1-auc:0.82607
[8]	validation_0-auc:0.85446	validation_1-auc:0.82701
[9]	validation_0-auc:0.85921	validation_1-auc:0.83013
[10]	validation_0-auc:0.86022	validation_1-auc:0.83197
[11]	validation_0-auc:0.86323	validation_1-auc:0.83373
[12]	validation_0-auc:0.86668	validation_1-auc:0.83653
[13]	validation_0-auc:0.86790	validation_1-auc:0.83711
[14]	validation_0-auc:0.86856	validation_1-auc:0.83845
[15]	validation_0-auc:0.87043	validation_1-auc:0.83899
[16]	validation_0-auc:0.87178	validation_1-auc:0.83877
[17]	validation_0-auc:0.87219	validation_1-auc:0.83837
[18]	validation_0-auc:0.87327	validation_1-auc:0.83835
[19]	validation_0-auc:0.87423	validation_1-auc:0.83887
[20]	validation_0-auc:0.87580	validation_1-auc:0.83970
[21]	validation_0-auc:0.87717	validation_1-auc:0.83894
[22]	validation_0-auc:0.87845	validation_1-auc:0.83893
[23]	validation_0-auc:0.87991	validation_1-auc:0.84012
[24]	validation_0-auc:0.88093	validation_1-auc:0.84045
[25]	validation_0-auc:0.88213	validation_1-auc:0.84104
[26]	validation_0-auc:0.88341	validation_1-auc:0.84178
[27]	validation_0-auc:0.88514	validation_1-auc:0.84146
[28]	validation_0-auc:0.88578	validation_1-auc:0.84084
[29]	validation_0-auc:0.88612	validation_1-auc:0.84092
[30]	validation_0-auc:0.88658	validation_1-auc:0.84145
[31]	validation_0-auc:0.88787	validation_1-auc:0.84179
[32]	validation_0-auc:0.88862	validation_1-auc:0.84130
[33]	validation_0-auc:0.88978	validation_1-auc:0.84170
[34]	validation_0-auc:0.89095	validation_1-auc:0.84159
[35]	validation_0-auc:0.89163	validation_1-auc:0.84162
[36]	validation_0-auc:0.89216	validation_1-auc:0.84145
[37]	validation_0-auc:0.89310	validation_1-auc:0.84138
[38]	validation_0-auc:0.89365	validation_1-auc:0.84144
[39]	validation_0-auc:0.89380	validation_1-auc:0.84161
[40]	validation_0-auc:0.89402	validation_1-auc:0.84171
[41]	validation_0-auc:0.89421	validation_1-auc:0.84184
[42]	validation_0-auc:0.89484	validation_1-auc:0.84173
[43]	validation_0-auc:0.89504	validation_1-auc:0.84168
[44]	validation_0-auc:0.89551	validation_1-auc:0.84156
[45]	validation_0-auc:0.89580	validation_1-auc:0.84156
[46]	validation_0-auc:0.89785	validation_1-auc:0.84152
[47]	validation_0-auc:0.89807	validation_1-auc:0.84150
[48]	validation_0-auc:0.89834	validation_1-auc:0.84178
[49]	validation_0-auc:0.89867	validation_1-auc:0.84170
[50]	validation_0-auc:0.89889	validation_1-auc:0.84154
[51]	validation_0-auc:0.89932	validation_1-auc:0.84155
[52]	validation_0-auc:0.89966	validation_1-auc:0.84156
[53]	validation_0-auc:0.89999	validation_1-auc:0.84164
[54]	validation_0-auc:0.90064	validation_1-auc:0.84157
[55]	validation_0-auc:0.90082	validation_1-auc:0.84145
[56]	validation_0-auc:0.90188	validation_1-auc:0.84107
[57]	validation_0-auc:0.90229	validation_1-auc:0.84100
[58]	validation_0-auc:0.90302	validation_1-auc:0.84113
[59]	validation_0-auc:0.90326	validation_1-auc:0.84109
[60]	validation_0-auc:0.90383	validation_1-auc:0.84098
[61]	validation_0-auc:0.90412	validation_1-auc:0.84100
[62]	validation_0-auc:0.90431	validation_1-auc:0.84091
[63]	validation_0-auc:0.90462	validation_1-auc:0.84088
[64]	validation_0-auc:0.90552	validation_1-auc:0.84067
[65]	validation_0-auc:0.90562	validation_1-auc:0.84066
[66]	validation_0-auc:0.90598	validation_1-auc:0.84071
[67]	validation_0-auc:0.90614	validation_1-auc:0.84079
[68]	validation_0-auc:0.90635	validation_1-auc:0.84095
[69]	validation_0-auc:0.90682	validation_1-auc:0.84097
[70]	validation_0-auc:0.90692	validation_1-auc:0.84098
[71]	validation_0-auc:0.90741	validation_1-auc:0.84040
 16%|█▌        | 8/50 [01:59<10:27, 14.94s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82447	validation_1-auc:0.80644
[1]	validation_0-auc:0.83096	validation_1-auc:0.81060
[2]	validation_0-auc:0.83957	validation_1-auc:0.81880
[3]	validation_0-auc:0.84441	validation_1-auc:0.82124
[4]	validation_0-auc:0.84736	validation_1-auc:0.82264
[5]	validation_0-auc:0.85029	validation_1-auc:0.82307
[6]	validation_0-auc:0.85221	validation_1-auc:0.82412
[7]	validation_0-auc:0.85354	validation_1-auc:0.82387
[8]	validation_0-auc:0.85535	validation_1-auc:0.82640
[9]	validation_0-auc:0.85991	validation_1-auc:0.82597
[10]	validation_0-auc:0.86120	validation_1-auc:0.82719
[11]	validation_0-auc:0.86625	validation_1-auc:0.82879
[12]	validation_0-auc:0.86928	validation_1-auc:0.83057
[13]	validation_0-auc:0.87122	validation_1-auc:0.83170
[14]	validation_0-auc:0.87185	validation_1-auc:0.83188
[15]	validation_0-auc:0.87469	validation_1-auc:0.83324
[16]	validation_0-auc:0.87609	validation_1-auc:0.83382
[17]	validation_0-auc:0.87757	validation_1-auc:0.83348
[18]	validation_0-auc:0.87884	validation_1-auc:0.83315
[19]	validation_0-auc:0.88012	validation_1-auc:0.83408
[20]	validation_0-auc:0.88081	validation_1-auc:0.83431
[21]	validation_0-auc:0.88229	validation_1-auc:0.83386
[22]	validation_0-auc:0.88478	validation_1-auc:0.83461
[23]	validation_0-auc:0.88651	validation_1-auc:0.83549
[24]	validation_0-auc:0.88742	validation_1-auc:0.83537
[25]	validation_0-auc:0.88853	validation_1-auc:0.83514
[26]	validation_0-auc:0.88975	validation_1-auc:0.83479
[27]	validation_0-auc:0.89072	validation_1-auc:0.83510
[28]	validation_0-auc:0.89132	validation_1-auc:0.83507
[29]	validation_0-auc:0.89212	validation_1-auc:0.83511
[30]	validation_0-auc:0.89285	validation_1-auc:0.83527
[31]	validation_0-auc:0.89375	validation_1-auc:0.83512
[32]	validation_0-auc:0.89456	validation_1-auc:0.83536
[33]	validation_0-auc:0.89502	validation_1-auc:0.83530
[34]	validation_0-auc:0.89573	validation_1-auc:0.83508
[35]	validation_0-auc:0.89679	validation_1-auc:0.83502
[36]	validation_0-auc:0.89816	validation_1-auc:0.83468
[37]	validation_0-auc:0.89854	validation_1-auc:0.83476
[38]	validation_0-auc:0.89928	validation_1-auc:0.83487
[39]	validation_0-auc:0.90000	validation_1-auc:0.83497
[40]	validation_0-auc:0.90029	validation_1-auc:0.83532
[41]	validation_0-auc:0.90092	validation_1-auc:0.83547
[42]	validation_0-auc:0.90169	validation_1-auc:0.83561
[43]	validation_0-auc:0.90291	validation_1-auc:0.83613
[44]	validation_0-auc:0.90339	validation_1-auc:0.83613
[45]	validation_0-auc:0.90357	validation_1-auc:0.83607
[46]	validation_0-auc:0.90372	validation_1-auc:0.83594
[47]	validation_0-auc:0.90480	validation_1-auc:0.83539
[48]	validation_0-auc:0.90519	validation_1-auc:0.83538
[49]	validation_0-auc:0.90552	validation_1-auc:0.83553
[50]	validation_0-auc:0.90559	validation_1-auc:0.83558
[51]	validation_0-auc:0.90610	validation_1-auc:0.83542
[52]	validation_0-auc:0.90632	validation_1-auc:0.83521
[53]	validation_0-auc:0.90643	validation_1-auc:0.83510
[54]	validation_0-auc:0.90712	validation_1-auc:0.83456
[55]	validation_0-auc:0.90765	validation_1-auc:0.83394
[56]	validation_0-auc:0.90774	validation_1-auc:0.83398
[57]	validation_0-auc:0.90816	validation_1-auc:0.83373
[58]	validation_0-auc:0.90872	validation_1-auc:0.83400
[59]	validation_0-auc:0.90891	validation_1-auc:0.83409
[60]	validation_0-auc:0.90906	validation_1-auc:0.83406
[61]	validation_0-auc:0.90994	validation_1-auc:0.83415
[62]	validation_0-auc:0.91008	validation_1-auc:0.83389
[63]	validation_0-auc:0.91061	validation_1-auc:0.83372
[64]	validation_0-auc:0.91103	validation_1-auc:0.83337
[65]	validation_0-auc:0.91133	validation_1-auc:0.83343
[66]	validation_0-auc:0.91149	validation_1-auc:0.83332
[67]	validation_0-auc:0.91183	validation_1-auc:0.83349
[68]	validation_0-auc:0.91193	validation_1-auc:0.83344
[69]	validation_0-auc:0.91200	validation_1-auc:0.83347
[70]	validation_0-auc:0.91216	validation_1-auc:0.83339
[71]	validation_0-auc:0.91279	validation_1-auc:0.83327
[72]	validation_0-auc:0.91309	validation_1-auc:0.83326
[73]	validation_0-auc:0.91323	validation_1-auc:0.83320
 16%|█▌        | 8/50 [02:03<10:27, 14.94s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82361	validation_1-auc:0.81165
[1]	validation_0-auc:0.83160	validation_1-auc:0.81663
[2]	validation_0-auc:0.84086	validation_1-auc:0.82398
[3]	validation_0-auc:0.84586	validation_1-auc:0.82931
[4]	validation_0-auc:0.84848	validation_1-auc:0.83114
[5]	validation_0-auc:0.84966	validation_1-auc:0.83140
[6]	validation_0-auc:0.85124	validation_1-auc:0.83116
[7]	validation_0-auc:0.85258	validation_1-auc:0.83186
[8]	validation_0-auc:0.85328	validation_1-auc:0.83213
[9]	validation_0-auc:0.85723	validation_1-auc:0.83305
[10]	validation_0-auc:0.85642	validation_1-auc:0.83073
[11]	validation_0-auc:0.86119	validation_1-auc:0.83465
[12]	validation_0-auc:0.86460	validation_1-auc:0.83782
[13]	validation_0-auc:0.86605	validation_1-auc:0.83959
[14]	validation_0-auc:0.86761	validation_1-auc:0.84005
[15]	validation_0-auc:0.86949	validation_1-auc:0.84085
[16]	validation_0-auc:0.87122	validation_1-auc:0.84053
[17]	validation_0-auc:0.87264	validation_1-auc:0.84075
[18]	validation_0-auc:0.87487	validation_1-auc:0.84182
[19]	validation_0-auc:0.87631	validation_1-auc:0.84278
[20]	validation_0-auc:0.87827	validation_1-auc:0.84259
[21]	validation_0-auc:0.87967	validation_1-auc:0.84194
[22]	validation_0-auc:0.88111	validation_1-auc:0.84132
[23]	validation_0-auc:0.88245	validation_1-auc:0.84130
[24]	validation_0-auc:0.88318	validation_1-auc:0.84120
[25]	validation_0-auc:0.88407	validation_1-auc:0.84109
[26]	validation_0-auc:0.88535	validation_1-auc:0.84182
[27]	validation_0-auc:0.88633	validation_1-auc:0.84217
[28]	validation_0-auc:0.88714	validation_1-auc:0.84182
[29]	validation_0-auc:0.88819	validation_1-auc:0.84177
[30]	validation_0-auc:0.88936	validation_1-auc:0.84217
[31]	validation_0-auc:0.88995	validation_1-auc:0.84259
[32]	validation_0-auc:0.89153	validation_1-auc:0.84219
[33]	validation_0-auc:0.89286	validation_1-auc:0.84250
[34]	validation_0-auc:0.89357	validation_1-auc:0.84249
[35]	validation_0-auc:0.89395	validation_1-auc:0.84257
[36]	validation_0-auc:0.89544	validation_1-auc:0.84258
[37]	validation_0-auc:0.89605	validation_1-auc:0.84254
[38]	validation_0-auc:0.89618	validation_1-auc:0.84274
[39]	validation_0-auc:0.89620	validation_1-auc:0.84266
[40]	validation_0-auc:0.89688	validation_1-auc:0.84265
[41]	validation_0-auc:0.89706	validation_1-auc:0.84261
[42]	validation_0-auc:0.89769	validation_1-auc:0.84260
[43]	validation_0-auc:0.89835	validation_1-auc:0.84270
[44]	validation_0-auc:0.89888	validation_1-auc:0.84269
[45]	validation_0-auc:0.89927	validation_1-auc:0.84281
[46]	validation_0-auc:0.89945	validation_1-auc:0.84269
[47]	validation_0-auc:0.89957	validation_1-auc:0.84263
[48]	validation_0-auc:0.89969	validation_1-auc:0.84247
[49]	validation_0-auc:0.90006	validation_1-auc:0.84282
[50]	validation_0-auc:0.90091	validation_1-auc:0.84320
[51]	validation_0-auc:0.90200	validation_1-auc:0.84318
[52]	validation_0-auc:0.90210	validation_1-auc:0.84301
[53]	validation_0-auc:0.90225	validation_1-auc:0.84304
[54]	validation_0-auc:0.90255	validation_1-auc:0.84298
[55]	validation_0-auc:0.90346	validation_1-auc:0.84246
[56]	validation_0-auc:0.90402	validation_1-auc:0.84270
[57]	validation_0-auc:0.90469	validation_1-auc:0.84253
[58]	validation_0-auc:0.90483	validation_1-auc:0.84259
[59]	validation_0-auc:0.90500	validation_1-auc:0.84247
[60]	validation_0-auc:0.90511	validation_1-auc:0.84243
[61]	validation_0-auc:0.90542	validation_1-auc:0.84223
[62]	validation_0-auc:0.90544	validation_1-auc:0.84223
[63]	validation_0-auc:0.90572	validation_1-auc:0.84225
[64]	validation_0-auc:0.90586	validation_1-auc:0.84230
[65]	validation_0-auc:0.90608	validation_1-auc:0.84219
[66]	validation_0-auc:0.90636	validation_1-auc:0.84190
[67]	validation_0-auc:0.90654	validation_1-auc:0.84187
[68]	validation_0-auc:0.90683	validation_1-auc:0.84184
[69]	validation_0-auc:0.90776	validation_1-auc:0.84147
[70]	validation_0-auc:0.90844	validation_1-auc:0.84158
[71]	validation_0-auc:0.90881	validation_1-auc:0.84132
[72]	validation_0-auc:0.90961	validation_1-auc:0.84103
[73]	validation_0-auc:0.90976	validation_1-auc:0.84108
[74]	validation_0-auc:0.91041	validation_1-auc:0.84096
[75]	validation_0-auc:0.91128	validation_1-auc:0.84124
[76]	validation_0-auc:0.91210	validation_1-auc:0.84098
[77]	validation_0-auc:0.91231	validation_1-auc:0.84098
[78]	validation_0-auc:0.91250	validation_1-auc:0.84094
[79]	validation_0-auc:0.91261	validation_1-auc:0.84089
[80]	validation_0-auc:0.91342	validation_1-auc:0.84058
 18%|█▊        | 9/50 [02:08<09:49, 14.38s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83681	validation_1-auc:0.81212
[1]	validation_0-auc:0.84386	validation_1-auc:0.81217
[2]	validation_0-auc:0.84835	validation_1-auc:0.81389
[3]	validation_0-auc:0.85748	validation_1-auc:0.81560
[4]	validation_0-auc:0.86128	validation_1-auc:0.81565
[5]	validation_0-auc:0.86579	validation_1-auc:0.81623
[6]	validation_0-auc:0.87088	validation_1-auc:0.81875
[7]	validation_0-auc:0.87728	validation_1-auc:0.82206
[8]	validation_0-auc:0.88233	validation_1-auc:0.82346
[9]	validation_0-auc:0.89117	validation_1-auc:0.82729
[10]	validation_0-auc:0.89310	validation_1-auc:0.82750
[11]	validation_0-auc:0.89991	validation_1-auc:0.83174
[12]	validation_0-auc:0.90459	validation_1-auc:0.83327
[13]	validation_0-auc:0.90992	validation_1-auc:0.83472
[14]	validation_0-auc:0.91342	validation_1-auc:0.83595
[15]	validation_0-auc:0.91710	validation_1-auc:0.83660
[16]	validation_0-auc:0.92053	validation_1-auc:0.83591
[17]	validation_0-auc:0.92205	validation_1-auc:0.83482
[18]	validation_0-auc:0.92496	validation_1-auc:0.83399
[19]	validation_0-auc:0.92740	validation_1-auc:0.83324
[20]	validation_0-auc:0.93057	validation_1-auc:0.83292
[21]	validation_0-auc:0.93343	validation_1-auc:0.83306
[22]	validation_0-auc:0.93569	validation_1-auc:0.83242
[23]	validation_0-auc:0.93773	validation_1-auc:0.83147
[24]	validation_0-auc:0.94037	validation_1-auc:0.83158
[25]	validation_0-auc:0.94127	validation_1-auc:0.83185
[26]	validation_0-auc:0.94264	validation_1-auc:0.83278
[27]	validation_0-auc:0.94397	validation_1-auc:0.83264
[28]	validation_0-auc:0.94495	validation_1-auc:0.83271
[29]	validation_0-auc:0.94595	validation_1-auc:0.83288
[30]	validation_0-auc:0.94731	validation_1-auc:0.83266
[31]	validation_0-auc:0.94779	validation_1-auc:0.83317
[32]	validation_0-auc:0.94845	validation_1-auc:0.83311
[33]	validation_0-auc:0.94881	validation_1-auc:0.83329
[34]	validation_0-auc:0.94930	validation_1-auc:0.83351
[35]	validation_0-auc:0.94966	validation_1-auc:0.83386
[36]	validation_0-auc:0.94992	validation_1-auc:0.83363
[37]	validation_0-auc:0.95033	validation_1-auc:0.83377
[38]	validation_0-auc:0.95073	validation_1-auc:0.83392
[39]	validation_0-auc:0.95172	validation_1-auc:0.83348
[40]	validation_0-auc:0.95192	validation_1-auc:0.83338
[41]	validation_0-auc:0.95216	validation_1-auc:0.83338
[42]	validation_0-auc:0.95226	validation_1-auc:0.83352
[43]	validation_0-auc:0.95245	validation_1-auc:0.83342
[44]	validation_0-auc:0.95343	validation_1-auc:0.83303
[45]	validation_0-auc:0.95361	validation_1-auc:0.83288
 18%|█▊        | 9/50 [02:12<09:49, 14.38s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83354	validation_1-auc:0.80899
[1]	validation_0-auc:0.83993	validation_1-auc:0.81004
[2]	validation_0-auc:0.84821	validation_1-auc:0.81547
[3]	validation_0-auc:0.85589	validation_1-auc:0.81889
[4]	validation_0-auc:0.86639	validation_1-auc:0.82230
[5]	validation_0-auc:0.87241	validation_1-auc:0.82210
[6]	validation_0-auc:0.87756	validation_1-auc:0.82271
[7]	validation_0-auc:0.88357	validation_1-auc:0.82398
[8]	validation_0-auc:0.88637	validation_1-auc:0.82414
[9]	validation_0-auc:0.89461	validation_1-auc:0.82470
[10]	validation_0-auc:0.89633	validation_1-auc:0.82545
[11]	validation_0-auc:0.90284	validation_1-auc:0.82618
[12]	validation_0-auc:0.90692	validation_1-auc:0.82767
[13]	validation_0-auc:0.90981	validation_1-auc:0.82751
[14]	validation_0-auc:0.91281	validation_1-auc:0.82745
[15]	validation_0-auc:0.91743	validation_1-auc:0.82850
[16]	validation_0-auc:0.92188	validation_1-auc:0.82805
[17]	validation_0-auc:0.92403	validation_1-auc:0.82879
[18]	validation_0-auc:0.92644	validation_1-auc:0.82775
[19]	validation_0-auc:0.93010	validation_1-auc:0.82711
[20]	validation_0-auc:0.93316	validation_1-auc:0.82735
[21]	validation_0-auc:0.93552	validation_1-auc:0.82748
[22]	validation_0-auc:0.93709	validation_1-auc:0.82799
[23]	validation_0-auc:0.93831	validation_1-auc:0.82838
[24]	validation_0-auc:0.94038	validation_1-auc:0.82846
[25]	validation_0-auc:0.94125	validation_1-auc:0.82861
[26]	validation_0-auc:0.94215	validation_1-auc:0.82884
[27]	validation_0-auc:0.94338	validation_1-auc:0.82815
[28]	validation_0-auc:0.94495	validation_1-auc:0.82691
[29]	validation_0-auc:0.94593	validation_1-auc:0.82676
[30]	validation_0-auc:0.94689	validation_1-auc:0.82749
[31]	validation_0-auc:0.94783	validation_1-auc:0.82784
[32]	validation_0-auc:0.94814	validation_1-auc:0.82796
[33]	validation_0-auc:0.94894	validation_1-auc:0.82779
[34]	validation_0-auc:0.94946	validation_1-auc:0.82753
[35]	validation_0-auc:0.95033	validation_1-auc:0.82785
[36]	validation_0-auc:0.95153	validation_1-auc:0.82699
[37]	validation_0-auc:0.95189	validation_1-auc:0.82702
[38]	validation_0-auc:0.95289	validation_1-auc:0.82715
[39]	validation_0-auc:0.95342	validation_1-auc:0.82638
[40]	validation_0-auc:0.95349	validation_1-auc:0.82682
[41]	validation_0-auc:0.95393	validation_1-auc:0.82666
[42]	validation_0-auc:0.95402	validation_1-auc:0.82694
[43]	validation_0-auc:0.95415	validation_1-auc:0.82697
[44]	validation_0-auc:0.95466	validation_1-auc:0.82677
[45]	validation_0-auc:0.95475	validation_1-auc:0.82685
[46]	validation_0-auc:0.95507	validation_1-auc:0.82648
[47]	validation_0-auc:0.95514	validation_1-auc:0.82640
[48]	validation_0-auc:0.95525	validation_1-auc:0.82624
[49]	validation_0-auc:0.95575	validation_1-auc:0.82603
[50]	validation_0-auc:0.95605	validation_1-auc:0.82566
[51]	validation_0-auc:0.95611	validation_1-auc:0.82552
[52]	validation_0-auc:0.95698	validation_1-auc:0.82530
[53]	validation_0-auc:0.95786	validation_1-auc:0.82411
[54]	validation_0-auc:0.95796	validation_1-auc:0.82373
[55]	validation_0-auc:0.95903	validation_1-auc:0.82379
[56]	validation_0-auc:0.95920	validation_1-auc:0.82374
 18%|█▊        | 9/50 [02:17<09:49, 14.38s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83192	validation_1-auc:0.80984
[1]	validation_0-auc:0.84177	validation_1-auc:0.81379
[2]	validation_0-auc:0.84911	validation_1-auc:0.82123
[3]	validation_0-auc:0.86037	validation_1-auc:0.82597
[4]	validation_0-auc:0.86362	validation_1-auc:0.82701
[5]	validation_0-auc:0.86886	validation_1-auc:0.82859
[6]	validation_0-auc:0.87503	validation_1-auc:0.83006
[7]	validation_0-auc:0.87811	validation_1-auc:0.82960
[8]	validation_0-auc:0.88210	validation_1-auc:0.83032
[9]	validation_0-auc:0.89133	validation_1-auc:0.83236
[10]	validation_0-auc:0.89260	validation_1-auc:0.82887
[11]	validation_0-auc:0.89773	validation_1-auc:0.83085
[12]	validation_0-auc:0.90399	validation_1-auc:0.83495
[13]	validation_0-auc:0.90724	validation_1-auc:0.83664
[14]	validation_0-auc:0.90999	validation_1-auc:0.83740
[15]	validation_0-auc:0.91508	validation_1-auc:0.83859
[16]	validation_0-auc:0.91917	validation_1-auc:0.83775
[17]	validation_0-auc:0.92159	validation_1-auc:0.83802
[18]	validation_0-auc:0.92452	validation_1-auc:0.83648
[19]	validation_0-auc:0.92775	validation_1-auc:0.83630
[20]	validation_0-auc:0.93047	validation_1-auc:0.83673
[21]	validation_0-auc:0.93219	validation_1-auc:0.83582
[22]	validation_0-auc:0.93416	validation_1-auc:0.83603
[23]	validation_0-auc:0.93588	validation_1-auc:0.83551
[24]	validation_0-auc:0.93785	validation_1-auc:0.83575
[25]	validation_0-auc:0.93933	validation_1-auc:0.83612
[26]	validation_0-auc:0.94089	validation_1-auc:0.83558
[27]	validation_0-auc:0.94241	validation_1-auc:0.83584
[28]	validation_0-auc:0.94395	validation_1-auc:0.83548
[29]	validation_0-auc:0.94494	validation_1-auc:0.83540
[30]	validation_0-auc:0.94574	validation_1-auc:0.83576
[31]	validation_0-auc:0.94645	validation_1-auc:0.83602
[32]	validation_0-auc:0.94705	validation_1-auc:0.83596
[33]	validation_0-auc:0.94731	validation_1-auc:0.83597
[34]	validation_0-auc:0.94777	validation_1-auc:0.83600
[35]	validation_0-auc:0.94820	validation_1-auc:0.83606
[36]	validation_0-auc:0.94865	validation_1-auc:0.83573
[37]	validation_0-auc:0.94879	validation_1-auc:0.83587
[38]	validation_0-auc:0.94957	validation_1-auc:0.83545
[39]	validation_0-auc:0.94979	validation_1-auc:0.83531
[40]	validation_0-auc:0.95005	validation_1-auc:0.83513
[41]	validation_0-auc:0.95030	validation_1-auc:0.83508
[42]	validation_0-auc:0.95102	validation_1-auc:0.83456
[43]	validation_0-auc:0.95113	validation_1-auc:0.83469
[44]	validation_0-auc:0.95219	validation_1-auc:0.83461
 20%|██        | 10/50 [02:22<09:26, 14.17s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83697	validation_1-auc:0.81339
[1]	validation_0-auc:0.84461	validation_1-auc:0.81270
[2]	validation_0-auc:0.84965	validation_1-auc:0.81238
[3]	validation_0-auc:0.85518	validation_1-auc:0.81475
[4]	validation_0-auc:0.86502	validation_1-auc:0.81844
[5]	validation_0-auc:0.86688	validation_1-auc:0.82068
[6]	validation_0-auc:0.86997	validation_1-auc:0.81966
[7]	validation_0-auc:0.87528	validation_1-auc:0.82020
[8]	validation_0-auc:0.87746	validation_1-auc:0.82068
[9]	validation_0-auc:0.88741	validation_1-auc:0.82447
[10]	validation_0-auc:0.88919	validation_1-auc:0.82612
[11]	validation_0-auc:0.89314	validation_1-auc:0.82351
[12]	validation_0-auc:0.89807	validation_1-auc:0.82690
[13]	validation_0-auc:0.90200	validation_1-auc:0.82856
[14]	validation_0-auc:0.90438	validation_1-auc:0.83119
[15]	validation_0-auc:0.90800	validation_1-auc:0.83225
[16]	validation_0-auc:0.91123	validation_1-auc:0.83318
[17]	validation_0-auc:0.91459	validation_1-auc:0.83309
[18]	validation_0-auc:0.91732	validation_1-auc:0.83354
[19]	validation_0-auc:0.92009	validation_1-auc:0.83384
[20]	validation_0-auc:0.92304	validation_1-auc:0.83429
[21]	validation_0-auc:0.92475	validation_1-auc:0.83431
[22]	validation_0-auc:0.92717	validation_1-auc:0.83430
[23]	validation_0-auc:0.93007	validation_1-auc:0.83444
[24]	validation_0-auc:0.93153	validation_1-auc:0.83449
[25]	validation_0-auc:0.93251	validation_1-auc:0.83527
[26]	validation_0-auc:0.93476	validation_1-auc:0.83480
[27]	validation_0-auc:0.93723	validation_1-auc:0.83458
[28]	validation_0-auc:0.94014	validation_1-auc:0.83330
[29]	validation_0-auc:0.94179	validation_1-auc:0.83315
[30]	validation_0-auc:0.94341	validation_1-auc:0.83271
[31]	validation_0-auc:0.94560	validation_1-auc:0.83265
[32]	validation_0-auc:0.94741	validation_1-auc:0.83237
[33]	validation_0-auc:0.94854	validation_1-auc:0.83311
[34]	validation_0-auc:0.95005	validation_1-auc:0.83314
[35]	validation_0-auc:0.95157	validation_1-auc:0.83331
[36]	validation_0-auc:0.95302	validation_1-auc:0.83269
[37]	validation_0-auc:0.95412	validation_1-auc:0.83263
[38]	validation_0-auc:0.95498	validation_1-auc:0.83319
[39]	validation_0-auc:0.95565	validation_1-auc:0.83345
[40]	validation_0-auc:0.95603	validation_1-auc:0.83380
[41]	validation_0-auc:0.95686	validation_1-auc:0.83392
[42]	validation_0-auc:0.95811	validation_1-auc:0.83327
[43]	validation_0-auc:0.95891	validation_1-auc:0.83326
[44]	validation_0-auc:0.95938	validation_1-auc:0.83384
[45]	validation_0-auc:0.96010	validation_1-auc:0.83350
[46]	validation_0-auc:0.96048	validation_1-auc:0.83356
[47]	validation_0-auc:0.96114	validation_1-auc:0.83344
[48]	validation_0-auc:0.96174	validation_1-auc:0.83294
[49]	validation_0-auc:0.96225	validation_1-auc:0.83299
[50]	validation_0-auc:0.96287	validation_1-auc:0.83288
[51]	validation_0-auc:0.96318	validation_1-auc:0.83292
[52]	validation_0-auc:0.96346	validation_1-auc:0.83338
[53]	validation_0-auc:0.96399	validation_1-auc:0.83336
[54]	validation_0-auc:0.96432	validation_1-auc:0.83347
 20%|██        | 10/50 [02:27<09:26, 14.17s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83291	validation_1-auc:0.80846
[1]	validation_0-auc:0.83907	validation_1-auc:0.80927
[2]	validation_0-auc:0.84518	validation_1-auc:0.81447
[3]	validation_0-auc:0.85396	validation_1-auc:0.81802
[4]	validation_0-auc:0.86417	validation_1-auc:0.81903
[5]	validation_0-auc:0.86615	validation_1-auc:0.81912
[6]	validation_0-auc:0.87081	validation_1-auc:0.81913
[7]	validation_0-auc:0.87748	validation_1-auc:0.82084
[8]	validation_0-auc:0.88314	validation_1-auc:0.82342
[9]	validation_0-auc:0.89065	validation_1-auc:0.82352
[10]	validation_0-auc:0.89407	validation_1-auc:0.82461
[11]	validation_0-auc:0.89734	validation_1-auc:0.82415
[12]	validation_0-auc:0.90311	validation_1-auc:0.82447
[13]	validation_0-auc:0.90718	validation_1-auc:0.82551
[14]	validation_0-auc:0.90878	validation_1-auc:0.82649
[15]	validation_0-auc:0.91108	validation_1-auc:0.82638
[16]	validation_0-auc:0.91308	validation_1-auc:0.82582
[17]	validation_0-auc:0.91663	validation_1-auc:0.82759
[18]	validation_0-auc:0.91771	validation_1-auc:0.82616
[19]	validation_0-auc:0.92000	validation_1-auc:0.82662
[20]	validation_0-auc:0.92250	validation_1-auc:0.82688
[21]	validation_0-auc:0.92377	validation_1-auc:0.82825
[22]	validation_0-auc:0.92633	validation_1-auc:0.82861
[23]	validation_0-auc:0.92778	validation_1-auc:0.82813
[24]	validation_0-auc:0.92988	validation_1-auc:0.82915
[25]	validation_0-auc:0.93098	validation_1-auc:0.82958
[26]	validation_0-auc:0.93415	validation_1-auc:0.82854
[27]	validation_0-auc:0.93712	validation_1-auc:0.82886
[28]	validation_0-auc:0.93934	validation_1-auc:0.82918
[29]	validation_0-auc:0.94078	validation_1-auc:0.82937
[30]	validation_0-auc:0.94260	validation_1-auc:0.82879
[31]	validation_0-auc:0.94520	validation_1-auc:0.82856
[32]	validation_0-auc:0.94636	validation_1-auc:0.82864
[33]	validation_0-auc:0.94717	validation_1-auc:0.82831
[34]	validation_0-auc:0.94847	validation_1-auc:0.82805
[35]	validation_0-auc:0.94988	validation_1-auc:0.82861
[36]	validation_0-auc:0.95133	validation_1-auc:0.82839
[37]	validation_0-auc:0.95241	validation_1-auc:0.82796
[38]	validation_0-auc:0.95353	validation_1-auc:0.82815
[39]	validation_0-auc:0.95415	validation_1-auc:0.82846
[40]	validation_0-auc:0.95463	validation_1-auc:0.82853
[41]	validation_0-auc:0.95547	validation_1-auc:0.82861
[42]	validation_0-auc:0.95632	validation_1-auc:0.82841
[43]	validation_0-auc:0.95711	validation_1-auc:0.82864
[44]	validation_0-auc:0.95788	validation_1-auc:0.82870
[45]	validation_0-auc:0.95822	validation_1-auc:0.82885
[46]	validation_0-auc:0.95854	validation_1-auc:0.82876
[47]	validation_0-auc:0.95903	validation_1-auc:0.82888
[48]	validation_0-auc:0.95943	validation_1-auc:0.82871
[49]	validation_0-auc:0.96003	validation_1-auc:0.82842
[50]	validation_0-auc:0.96057	validation_1-auc:0.82851
[51]	validation_0-auc:0.96123	validation_1-auc:0.82807
[52]	validation_0-auc:0.96172	validation_1-auc:0.82813
[53]	validation_0-auc:0.96203	validation_1-auc:0.82795
[54]	validation_0-auc:0.96267	validation_1-auc:0.82752
 20%|██        | 10/50 [02:34<09:26, 14.17s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83155	validation_1-auc:0.80764
[1]	validation_0-auc:0.84053	validation_1-auc:0.81146
[2]	validation_0-auc:0.85201	validation_1-auc:0.82199
[3]	validation_0-auc:0.85769	validation_1-auc:0.82602
[4]	validation_0-auc:0.86465	validation_1-auc:0.82846
[5]	validation_0-auc:0.86657	validation_1-auc:0.82930
[6]	validation_0-auc:0.87214	validation_1-auc:0.82926
[7]	validation_0-auc:0.87610	validation_1-auc:0.83069
[8]	validation_0-auc:0.87772	validation_1-auc:0.83070
[9]	validation_0-auc:0.88460	validation_1-auc:0.83053
[10]	validation_0-auc:0.88823	validation_1-auc:0.82949
[11]	validation_0-auc:0.88940	validation_1-auc:0.82811
[12]	validation_0-auc:0.89351	validation_1-auc:0.82919
[13]	validation_0-auc:0.89622	validation_1-auc:0.83063
[14]	validation_0-auc:0.89940	validation_1-auc:0.83242
[15]	validation_0-auc:0.90158	validation_1-auc:0.83348
[16]	validation_0-auc:0.90474	validation_1-auc:0.83438
[17]	validation_0-auc:0.90863	validation_1-auc:0.83551
[18]	validation_0-auc:0.91007	validation_1-auc:0.83392
[19]	validation_0-auc:0.91410	validation_1-auc:0.83510
[20]	validation_0-auc:0.91732	validation_1-auc:0.83633
[21]	validation_0-auc:0.92007	validation_1-auc:0.83589
[22]	validation_0-auc:0.92293	validation_1-auc:0.83714
[23]	validation_0-auc:0.92482	validation_1-auc:0.83686
[24]	validation_0-auc:0.92641	validation_1-auc:0.83719
[25]	validation_0-auc:0.92760	validation_1-auc:0.83754
[26]	validation_0-auc:0.93080	validation_1-auc:0.83682
[27]	validation_0-auc:0.93368	validation_1-auc:0.83725
[28]	validation_0-auc:0.93559	validation_1-auc:0.83735
[29]	validation_0-auc:0.93749	validation_1-auc:0.83700
[30]	validation_0-auc:0.94026	validation_1-auc:0.83701
[31]	validation_0-auc:0.94273	validation_1-auc:0.83725
[32]	validation_0-auc:0.94394	validation_1-auc:0.83783
[33]	validation_0-auc:0.94450	validation_1-auc:0.83768
[34]	validation_0-auc:0.94585	validation_1-auc:0.83705
[35]	validation_0-auc:0.94744	validation_1-auc:0.83685
[36]	validation_0-auc:0.94860	validation_1-auc:0.83698
[37]	validation_0-auc:0.94976	validation_1-auc:0.83709
[38]	validation_0-auc:0.95055	validation_1-auc:0.83627
[39]	validation_0-auc:0.95111	validation_1-auc:0.83620
[40]	validation_0-auc:0.95161	validation_1-auc:0.83566
[41]	validation_0-auc:0.95264	validation_1-auc:0.83536
[42]	validation_0-auc:0.95372	validation_1-auc:0.83571
[43]	validation_0-auc:0.95424	validation_1-auc:0.83592
[44]	validation_0-auc:0.95509	validation_1-auc:0.83587
[45]	validation_0-auc:0.95567	validation_1-auc:0.83530
[46]	validation_0-auc:0.95597	validation_1-auc:0.83546
[47]	validation_0-auc:0.95657	validation_1-auc:0.83560
[48]	validation_0-auc:0.95732	validation_1-auc:0.83506
[49]	validation_0-auc:0.95780	validation_1-auc:0.83506
[50]	validation_0-auc:0.95807	validation_1-auc:0.83484
[51]	validation_0-auc:0.95852	validation_1-auc:0.83531
[52]	validation_0-auc:0.95894	validation_1-auc:0.83546
[53]	validation_0-auc:0.95928	validation_1-auc:0.83587
[54]	validation_0-auc:0.95973	validation_1-auc:0.83513
[55]	validation_0-auc:0.96013	validation_1-auc:0.83509
[56]	validation_0-auc:0.96035	validation_1-auc:0.83492
[57]	validation_0-auc:0.96092	validation_1-auc:0.83463
[58]	validation_0-auc:0.96121	validation_1-auc:0.83486
[59]	validation_0-auc:0.96157	validation_1-auc:0.83491
[60]	validation_0-auc:0.96191	validation_1-auc:0.83468
[61]	validation_0-auc:0.96247	validation_1-auc:0.83469
 22%|██▏       | 11/50 [02:40<09:56, 15.30s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83764	validation_1-auc:0.81157
[1]	validation_0-auc:0.84592	validation_1-auc:0.81197
[2]	validation_0-auc:0.85320	validation_1-auc:0.81493
[3]	validation_0-auc:0.86001	validation_1-auc:0.81430
[4]	validation_0-auc:0.86650	validation_1-auc:0.81398
[5]	validation_0-auc:0.87070	validation_1-auc:0.81484
[6]	validation_0-auc:0.87823	validation_1-auc:0.81755
[7]	validation_0-auc:0.88549	validation_1-auc:0.82090
[8]	validation_0-auc:0.89200	validation_1-auc:0.82184
[9]	validation_0-auc:0.90119	validation_1-auc:0.82615
[10]	validation_0-auc:0.90585	validation_1-auc:0.82448
[11]	validation_0-auc:0.91436	validation_1-auc:0.82769
[12]	validation_0-auc:0.91915	validation_1-auc:0.82794
[13]	validation_0-auc:0.92305	validation_1-auc:0.82954
[14]	validation_0-auc:0.92711	validation_1-auc:0.83102
[15]	validation_0-auc:0.93157	validation_1-auc:0.83130
[16]	validation_0-auc:0.93583	validation_1-auc:0.83060
[17]	validation_0-auc:0.93869	validation_1-auc:0.82941
[18]	validation_0-auc:0.94109	validation_1-auc:0.82958
[19]	validation_0-auc:0.94450	validation_1-auc:0.82753
[20]	validation_0-auc:0.94646	validation_1-auc:0.82683
[21]	validation_0-auc:0.94891	validation_1-auc:0.82583
[22]	validation_0-auc:0.95125	validation_1-auc:0.82619
[23]	validation_0-auc:0.95339	validation_1-auc:0.82527
[24]	validation_0-auc:0.95589	validation_1-auc:0.82545
[25]	validation_0-auc:0.95760	validation_1-auc:0.82602
[26]	validation_0-auc:0.95928	validation_1-auc:0.82498
[27]	validation_0-auc:0.96094	validation_1-auc:0.82444
[28]	validation_0-auc:0.96165	validation_1-auc:0.82448
[29]	validation_0-auc:0.96262	validation_1-auc:0.82475
[30]	validation_0-auc:0.96322	validation_1-auc:0.82537
[31]	validation_0-auc:0.96361	validation_1-auc:0.82585
[32]	validation_0-auc:0.96453	validation_1-auc:0.82557
[33]	validation_0-auc:0.96516	validation_1-auc:0.82652
[34]	validation_0-auc:0.96556	validation_1-auc:0.82626
[35]	validation_0-auc:0.96607	validation_1-auc:0.82617
[36]	validation_0-auc:0.96650	validation_1-auc:0.82617
[37]	validation_0-auc:0.96682	validation_1-auc:0.82622
[38]	validation_0-auc:0.96724	validation_1-auc:0.82621
[39]	validation_0-auc:0.96761	validation_1-auc:0.82604
[40]	validation_0-auc:0.96769	validation_1-auc:0.82617
[41]	validation_0-auc:0.96785	validation_1-auc:0.82586
[42]	validation_0-auc:0.96810	validation_1-auc:0.82575
[43]	validation_0-auc:0.96815	validation_1-auc:0.82590
[44]	validation_0-auc:0.96861	validation_1-auc:0.82586
[45]	validation_0-auc:0.96878	validation_1-auc:0.82621
 22%|██▏       | 11/50 [02:45<09:56, 15.30s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83485	validation_1-auc:0.80849
[1]	validation_0-auc:0.84109	validation_1-auc:0.81018
[2]	validation_0-auc:0.85033	validation_1-auc:0.81651
[3]	validation_0-auc:0.85906	validation_1-auc:0.81776
[4]	validation_0-auc:0.87125	validation_1-auc:0.81906
[5]	validation_0-auc:0.87802	validation_1-auc:0.81973
[6]	validation_0-auc:0.88537	validation_1-auc:0.82018
[7]	validation_0-auc:0.89276	validation_1-auc:0.82102
[8]	validation_0-auc:0.89871	validation_1-auc:0.82227
[9]	validation_0-auc:0.90910	validation_1-auc:0.81943
[10]	validation_0-auc:0.91076	validation_1-auc:0.81926
[11]	validation_0-auc:0.91649	validation_1-auc:0.82334
[12]	validation_0-auc:0.92131	validation_1-auc:0.82415
[13]	validation_0-auc:0.92469	validation_1-auc:0.82633
[14]	validation_0-auc:0.92735	validation_1-auc:0.82562
[15]	validation_0-auc:0.93034	validation_1-auc:0.82774
[16]	validation_0-auc:0.93553	validation_1-auc:0.82683
[17]	validation_0-auc:0.93827	validation_1-auc:0.82750
[18]	validation_0-auc:0.94072	validation_1-auc:0.82613
[19]	validation_0-auc:0.94491	validation_1-auc:0.82526
[20]	validation_0-auc:0.94730	validation_1-auc:0.82579
[21]	validation_0-auc:0.94968	validation_1-auc:0.82466
[22]	validation_0-auc:0.95144	validation_1-auc:0.82476
[23]	validation_0-auc:0.95306	validation_1-auc:0.82485
[24]	validation_0-auc:0.95467	validation_1-auc:0.82484
[25]	validation_0-auc:0.95595	validation_1-auc:0.82500
[26]	validation_0-auc:0.95717	validation_1-auc:0.82531
[27]	validation_0-auc:0.95817	validation_1-auc:0.82564
[28]	validation_0-auc:0.95910	validation_1-auc:0.82543
[29]	validation_0-auc:0.95989	validation_1-auc:0.82508
[30]	validation_0-auc:0.96080	validation_1-auc:0.82510
[31]	validation_0-auc:0.96156	validation_1-auc:0.82505
[32]	validation_0-auc:0.96254	validation_1-auc:0.82491
[33]	validation_0-auc:0.96281	validation_1-auc:0.82505
[34]	validation_0-auc:0.96324	validation_1-auc:0.82483
[35]	validation_0-auc:0.96357	validation_1-auc:0.82483
[36]	validation_0-auc:0.96452	validation_1-auc:0.82397
[37]	validation_0-auc:0.96534	validation_1-auc:0.82349
[38]	validation_0-auc:0.96582	validation_1-auc:0.82286
[39]	validation_0-auc:0.96667	validation_1-auc:0.82254
[40]	validation_0-auc:0.96666	validation_1-auc:0.82288
[41]	validation_0-auc:0.96681	validation_1-auc:0.82277
[42]	validation_0-auc:0.96732	validation_1-auc:0.82310
[43]	validation_0-auc:0.96769	validation_1-auc:0.82268
[44]	validation_0-auc:0.96892	validation_1-auc:0.82207
 22%|██▏       | 11/50 [02:50<09:56, 15.30s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83411	validation_1-auc:0.81005
[1]	validation_0-auc:0.84324	validation_1-auc:0.81405
[2]	validation_0-auc:0.85145	validation_1-auc:0.82012
[3]	validation_0-auc:0.86461	validation_1-auc:0.82514
[4]	validation_0-auc:0.86784	validation_1-auc:0.82629
[5]	validation_0-auc:0.87565	validation_1-auc:0.82856
[6]	validation_0-auc:0.88018	validation_1-auc:0.82860
[7]	validation_0-auc:0.88578	validation_1-auc:0.82948
[8]	validation_0-auc:0.89093	validation_1-auc:0.83120
[9]	validation_0-auc:0.90081	validation_1-auc:0.83073
[10]	validation_0-auc:0.90270	validation_1-auc:0.82887
[11]	validation_0-auc:0.90960	validation_1-auc:0.83058
[12]	validation_0-auc:0.91607	validation_1-auc:0.83233
[13]	validation_0-auc:0.91995	validation_1-auc:0.83380
[14]	validation_0-auc:0.92394	validation_1-auc:0.83396
[15]	validation_0-auc:0.92904	validation_1-auc:0.83325
[16]	validation_0-auc:0.93242	validation_1-auc:0.83437
[17]	validation_0-auc:0.93450	validation_1-auc:0.83274
[18]	validation_0-auc:0.93724	validation_1-auc:0.83308
[19]	validation_0-auc:0.93969	validation_1-auc:0.83339
[20]	validation_0-auc:0.94246	validation_1-auc:0.83378
[21]	validation_0-auc:0.94469	validation_1-auc:0.83290
[22]	validation_0-auc:0.94693	validation_1-auc:0.83243
[23]	validation_0-auc:0.94870	validation_1-auc:0.83194
[24]	validation_0-auc:0.95055	validation_1-auc:0.83167
[25]	validation_0-auc:0.95275	validation_1-auc:0.83229
[26]	validation_0-auc:0.95413	validation_1-auc:0.83182
[27]	validation_0-auc:0.95613	validation_1-auc:0.83140
[28]	validation_0-auc:0.95750	validation_1-auc:0.83046
[29]	validation_0-auc:0.95837	validation_1-auc:0.83031
[30]	validation_0-auc:0.95945	validation_1-auc:0.83105
[31]	validation_0-auc:0.96034	validation_1-auc:0.83091
[32]	validation_0-auc:0.96091	validation_1-auc:0.83118
[33]	validation_0-auc:0.96192	validation_1-auc:0.83073
[34]	validation_0-auc:0.96245	validation_1-auc:0.83033
[35]	validation_0-auc:0.96268	validation_1-auc:0.83010
[36]	validation_0-auc:0.96345	validation_1-auc:0.82998
[37]	validation_0-auc:0.96389	validation_1-auc:0.82971
[38]	validation_0-auc:0.96431	validation_1-auc:0.82978
[39]	validation_0-auc:0.96469	validation_1-auc:0.82970
[40]	validation_0-auc:0.96502	validation_1-auc:0.83007
[41]	validation_0-auc:0.96518	validation_1-auc:0.82971
[42]	validation_0-auc:0.96573	validation_1-auc:0.82917
[43]	validation_0-auc:0.96610	validation_1-auc:0.82877
[44]	validation_0-auc:0.96643	validation_1-auc:0.82866
[45]	validation_0-auc:0.96652	validation_1-auc:0.82850
 24%|██▍       | 12/50 [02:55<09:42, 15.33s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83097	validation_1-auc:0.81426
[1]	validation_0-auc:0.83709	validation_1-auc:0.81582
[2]	validation_0-auc:0.84127	validation_1-auc:0.81682
[3]	validation_0-auc:0.84751	validation_1-auc:0.81910
[4]	validation_0-auc:0.85292	validation_1-auc:0.82185
[5]	validation_0-auc:0.85451	validation_1-auc:0.82274
[6]	validation_0-auc:0.85735	validation_1-auc:0.82477
[7]	validation_0-auc:0.85943	validation_1-auc:0.82557
[8]	validation_0-auc:0.86058	validation_1-auc:0.82605
[9]	validation_0-auc:0.86720	validation_1-auc:0.82997
[10]	validation_0-auc:0.86683	validation_1-auc:0.82973
[11]	validation_0-auc:0.86737	validation_1-auc:0.82881
[12]	validation_0-auc:0.87134	validation_1-auc:0.83292
[13]	validation_0-auc:0.87396	validation_1-auc:0.83539
[14]	validation_0-auc:0.87553	validation_1-auc:0.83756
[15]	validation_0-auc:0.87819	validation_1-auc:0.83965
[16]	validation_0-auc:0.87875	validation_1-auc:0.83984
[17]	validation_0-auc:0.88086	validation_1-auc:0.83949
[18]	validation_0-auc:0.88145	validation_1-auc:0.83968
[19]	validation_0-auc:0.88328	validation_1-auc:0.84064
[20]	validation_0-auc:0.88455	validation_1-auc:0.84046
[21]	validation_0-auc:0.88451	validation_1-auc:0.84023
[22]	validation_0-auc:0.88656	validation_1-auc:0.84041
[23]	validation_0-auc:0.88799	validation_1-auc:0.84035
[24]	validation_0-auc:0.88912	validation_1-auc:0.84050
[25]	validation_0-auc:0.88960	validation_1-auc:0.84100
[26]	validation_0-auc:0.89072	validation_1-auc:0.84138
[27]	validation_0-auc:0.89262	validation_1-auc:0.84155
[28]	validation_0-auc:0.89346	validation_1-auc:0.84144
[29]	validation_0-auc:0.89452	validation_1-auc:0.84111
[30]	validation_0-auc:0.89566	validation_1-auc:0.84113
[31]	validation_0-auc:0.89699	validation_1-auc:0.84079
[32]	validation_0-auc:0.89794	validation_1-auc:0.84098
[33]	validation_0-auc:0.89854	validation_1-auc:0.84108
[34]	validation_0-auc:0.89949	validation_1-auc:0.84141
[35]	validation_0-auc:0.90084	validation_1-auc:0.84175
[36]	validation_0-auc:0.90194	validation_1-auc:0.84165
[37]	validation_0-auc:0.90269	validation_1-auc:0.84198
[38]	validation_0-auc:0.90389	validation_1-auc:0.84220
[39]	validation_0-auc:0.90503	validation_1-auc:0.84260
[40]	validation_0-auc:0.90571	validation_1-auc:0.84262
[41]	validation_0-auc:0.90653	validation_1-auc:0.84298
[42]	validation_0-auc:0.90790	validation_1-auc:0.84357
[43]	validation_0-auc:0.90846	validation_1-auc:0.84386
[44]	validation_0-auc:0.90960	validation_1-auc:0.84384
[45]	validation_0-auc:0.90965	validation_1-auc:0.84386
[46]	validation_0-auc:0.90994	validation_1-auc:0.84430
[47]	validation_0-auc:0.91019	validation_1-auc:0.84442
[48]	validation_0-auc:0.91129	validation_1-auc:0.84412
[49]	validation_0-auc:0.91156	validation_1-auc:0.84419
[50]	validation_0-auc:0.91237	validation_1-auc:0.84412
[51]	validation_0-auc:0.91341	validation_1-auc:0.84380
[52]	validation_0-auc:0.91368	validation_1-auc:0.84374
[53]	validation_0-auc:0.91408	validation_1-auc:0.84363
[54]	validation_0-auc:0.91430	validation_1-auc:0.84352
[55]	validation_0-auc:0.91555	validation_1-auc:0.84327
[56]	validation_0-auc:0.91570	validation_1-auc:0.84327
[57]	validation_0-auc:0.91582	validation_1-auc:0.84312
[58]	validation_0-auc:0.91639	validation_1-auc:0.84286
[59]	validation_0-auc:0.91682	validation_1-auc:0.84293
[60]	validation_0-auc:0.91696	validation_1-auc:0.84289
[61]	validation_0-auc:0.91715	validation_1-auc:0.84287
[62]	validation_0-auc:0.91735	validation_1-auc:0.84279
[63]	validation_0-auc:0.91745	validation_1-auc:0.84282
[64]	validation_0-auc:0.91788	validation_1-auc:0.84276
[65]	validation_0-auc:0.91804	validation_1-auc:0.84273
[66]	validation_0-auc:0.91807	validation_1-auc:0.84270
[67]	validation_0-auc:0.91831	validation_1-auc:0.84277
[68]	validation_0-auc:0.91851	validation_1-auc:0.84272
[69]	validation_0-auc:0.91876	validation_1-auc:0.84259
[70]	validation_0-auc:0.91951	validation_1-auc:0.84253
[71]	validation_0-auc:0.91978	validation_1-auc:0.84232
[72]	validation_0-auc:0.91997	validation_1-auc:0.84237
[73]	validation_0-auc:0.92014	validation_1-auc:0.84247
[74]	validation_0-auc:0.92023	validation_1-auc:0.84248
[75]	validation_0-auc:0.92042	validation_1-auc:0.84242
[76]	validation_0-auc:0.92055	validation_1-auc:0.84229
[77]	validation_0-auc:0.92066	validation_1-auc:0.84227
 24%|██▍       | 12/50 [02:59<09:42, 15.33s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82677	validation_1-auc:0.80670
[1]	validation_0-auc:0.83318	validation_1-auc:0.81156
[2]	validation_0-auc:0.84000	validation_1-auc:0.81593
[3]	validation_0-auc:0.84301	validation_1-auc:0.81984
[4]	validation_0-auc:0.85070	validation_1-auc:0.82306
[5]	validation_0-auc:0.85195	validation_1-auc:0.82336
[6]	validation_0-auc:0.85699	validation_1-auc:0.82613
[7]	validation_0-auc:0.86053	validation_1-auc:0.82706
[8]	validation_0-auc:0.86307	validation_1-auc:0.82754
[9]	validation_0-auc:0.86722	validation_1-auc:0.82929
[10]	validation_0-auc:0.87021	validation_1-auc:0.82923
[11]	validation_0-auc:0.87141	validation_1-auc:0.82983
[12]	validation_0-auc:0.87411	validation_1-auc:0.83087
[13]	validation_0-auc:0.87666	validation_1-auc:0.83184
[14]	validation_0-auc:0.87759	validation_1-auc:0.83265
[15]	validation_0-auc:0.88003	validation_1-auc:0.83205
[16]	validation_0-auc:0.88011	validation_1-auc:0.83243
[17]	validation_0-auc:0.88193	validation_1-auc:0.83294
[18]	validation_0-auc:0.88299	validation_1-auc:0.83284
[19]	validation_0-auc:0.88504	validation_1-auc:0.83288
[20]	validation_0-auc:0.88656	validation_1-auc:0.83350
[21]	validation_0-auc:0.88726	validation_1-auc:0.83336
[22]	validation_0-auc:0.88845	validation_1-auc:0.83379
[23]	validation_0-auc:0.88967	validation_1-auc:0.83439
[24]	validation_0-auc:0.89090	validation_1-auc:0.83459
[25]	validation_0-auc:0.89137	validation_1-auc:0.83564
[26]	validation_0-auc:0.89302	validation_1-auc:0.83556
[27]	validation_0-auc:0.89446	validation_1-auc:0.83566
[28]	validation_0-auc:0.89608	validation_1-auc:0.83506
[29]	validation_0-auc:0.89782	validation_1-auc:0.83526
[30]	validation_0-auc:0.89902	validation_1-auc:0.83519
[31]	validation_0-auc:0.90052	validation_1-auc:0.83554
[32]	validation_0-auc:0.90132	validation_1-auc:0.83587
[33]	validation_0-auc:0.90170	validation_1-auc:0.83665
[34]	validation_0-auc:0.90304	validation_1-auc:0.83656
[35]	validation_0-auc:0.90392	validation_1-auc:0.83753
[36]	validation_0-auc:0.90481	validation_1-auc:0.83688
[37]	validation_0-auc:0.90553	validation_1-auc:0.83637
[38]	validation_0-auc:0.90605	validation_1-auc:0.83542
[39]	validation_0-auc:0.90665	validation_1-auc:0.83575
[40]	validation_0-auc:0.90720	validation_1-auc:0.83593
[41]	validation_0-auc:0.90765	validation_1-auc:0.83565
[42]	validation_0-auc:0.90816	validation_1-auc:0.83594
[43]	validation_0-auc:0.90878	validation_1-auc:0.83636
[44]	validation_0-auc:0.91000	validation_1-auc:0.83682
[45]	validation_0-auc:0.91031	validation_1-auc:0.83687
[46]	validation_0-auc:0.91053	validation_1-auc:0.83707
[47]	validation_0-auc:0.91095	validation_1-auc:0.83719
[48]	validation_0-auc:0.91159	validation_1-auc:0.83665
[49]	validation_0-auc:0.91207	validation_1-auc:0.83643
[50]	validation_0-auc:0.91286	validation_1-auc:0.83654
[51]	validation_0-auc:0.91369	validation_1-auc:0.83621
[52]	validation_0-auc:0.91433	validation_1-auc:0.83616
[53]	validation_0-auc:0.91463	validation_1-auc:0.83647
[54]	validation_0-auc:0.91500	validation_1-auc:0.83654
[55]	validation_0-auc:0.91593	validation_1-auc:0.83592
[56]	validation_0-auc:0.91599	validation_1-auc:0.83598
[57]	validation_0-auc:0.91693	validation_1-auc:0.83585
[58]	validation_0-auc:0.91739	validation_1-auc:0.83583
[59]	validation_0-auc:0.91802	validation_1-auc:0.83575
[60]	validation_0-auc:0.91819	validation_1-auc:0.83583
[61]	validation_0-auc:0.91873	validation_1-auc:0.83577
[62]	validation_0-auc:0.91895	validation_1-auc:0.83565
[63]	validation_0-auc:0.91949	validation_1-auc:0.83549
[64]	validation_0-auc:0.91997	validation_1-auc:0.83531
[65]	validation_0-auc:0.92037	validation_1-auc:0.83499
 24%|██▍       | 12/50 [03:03<09:42, 15.33s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82311	validation_1-auc:0.81046
[1]	validation_0-auc:0.83823	validation_1-auc:0.82521
[2]	validation_0-auc:0.84273	validation_1-auc:0.82682
[3]	validation_0-auc:0.84891	validation_1-auc:0.83024
[4]	validation_0-auc:0.85455	validation_1-auc:0.83374
[5]	validation_0-auc:0.85727	validation_1-auc:0.83421
[6]	validation_0-auc:0.85938	validation_1-auc:0.83549
[7]	validation_0-auc:0.86142	validation_1-auc:0.83476
[8]	validation_0-auc:0.86194	validation_1-auc:0.83398
[9]	validation_0-auc:0.86538	validation_1-auc:0.83516
[10]	validation_0-auc:0.86502	validation_1-auc:0.83446
[11]	validation_0-auc:0.86626	validation_1-auc:0.83204
[12]	validation_0-auc:0.86950	validation_1-auc:0.83407
[13]	validation_0-auc:0.87162	validation_1-auc:0.83565
[14]	validation_0-auc:0.87291	validation_1-auc:0.83645
[15]	validation_0-auc:0.87434	validation_1-auc:0.83736
[16]	validation_0-auc:0.87690	validation_1-auc:0.83798
[17]	validation_0-auc:0.87844	validation_1-auc:0.83882
[18]	validation_0-auc:0.87917	validation_1-auc:0.83757
[19]	validation_0-auc:0.88194	validation_1-auc:0.83909
[20]	validation_0-auc:0.88301	validation_1-auc:0.84079
[21]	validation_0-auc:0.88403	validation_1-auc:0.83945
[22]	validation_0-auc:0.88613	validation_1-auc:0.84144
[23]	validation_0-auc:0.88752	validation_1-auc:0.84201
[24]	validation_0-auc:0.88850	validation_1-auc:0.84235
[25]	validation_0-auc:0.88974	validation_1-auc:0.84260
[26]	validation_0-auc:0.89100	validation_1-auc:0.84163
[27]	validation_0-auc:0.89294	validation_1-auc:0.84142
[28]	validation_0-auc:0.89417	validation_1-auc:0.84169
[29]	validation_0-auc:0.89543	validation_1-auc:0.84196
[30]	validation_0-auc:0.89723	validation_1-auc:0.84139
[31]	validation_0-auc:0.89858	validation_1-auc:0.84170
[32]	validation_0-auc:0.89932	validation_1-auc:0.84135
[33]	validation_0-auc:0.89964	validation_1-auc:0.84178
[34]	validation_0-auc:0.90045	validation_1-auc:0.84151
[35]	validation_0-auc:0.90092	validation_1-auc:0.84174
[36]	validation_0-auc:0.90210	validation_1-auc:0.84163
[37]	validation_0-auc:0.90328	validation_1-auc:0.84062
[38]	validation_0-auc:0.90464	validation_1-auc:0.84070
[39]	validation_0-auc:0.90550	validation_1-auc:0.84100
[40]	validation_0-auc:0.90621	validation_1-auc:0.84136
[41]	validation_0-auc:0.90691	validation_1-auc:0.84111
[42]	validation_0-auc:0.90754	validation_1-auc:0.84149
[43]	validation_0-auc:0.90808	validation_1-auc:0.84141
[44]	validation_0-auc:0.90860	validation_1-auc:0.84159
[45]	validation_0-auc:0.90924	validation_1-auc:0.84177
[46]	validation_0-auc:0.90944	validation_1-auc:0.84179
[47]	validation_0-auc:0.90974	validation_1-auc:0.84172
[48]	validation_0-auc:0.91016	validation_1-auc:0.84171
[49]	validation_0-auc:0.91076	validation_1-auc:0.84164
[50]	validation_0-auc:0.91138	validation_1-auc:0.84181
[51]	validation_0-auc:0.91177	validation_1-auc:0.84192
[52]	validation_0-auc:0.91210	validation_1-auc:0.84215
[53]	validation_0-auc:0.91272	validation_1-auc:0.84191
[54]	validation_0-auc:0.91322	validation_1-auc:0.84164
 26%|██▌       | 13/50 [03:06<08:43, 14.16s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83598	validation_1-auc:0.81211
[1]	validation_0-auc:0.84134	validation_1-auc:0.81289
[2]	validation_0-auc:0.84537	validation_1-auc:0.81351
[3]	validation_0-auc:0.85115	validation_1-auc:0.81462
[4]	validation_0-auc:0.85374	validation_1-auc:0.81470
[5]	validation_0-auc:0.85502	validation_1-auc:0.81646
[6]	validation_0-auc:0.86308	validation_1-auc:0.81925
[7]	validation_0-auc:0.86541	validation_1-auc:0.81921
[8]	validation_0-auc:0.86710	validation_1-auc:0.81958
[9]	validation_0-auc:0.87551	validation_1-auc:0.82290
[10]	validation_0-auc:0.87679	validation_1-auc:0.82585
[11]	validation_0-auc:0.88302	validation_1-auc:0.82936
[12]	validation_0-auc:0.88649	validation_1-auc:0.82974
[13]	validation_0-auc:0.89025	validation_1-auc:0.83120
[14]	validation_0-auc:0.89194	validation_1-auc:0.83191
[15]	validation_0-auc:0.89476	validation_1-auc:0.83246
[16]	validation_0-auc:0.89714	validation_1-auc:0.83286
[17]	validation_0-auc:0.90010	validation_1-auc:0.83389
[18]	validation_0-auc:0.90213	validation_1-auc:0.83427
[19]	validation_0-auc:0.90500	validation_1-auc:0.83437
[20]	validation_0-auc:0.90625	validation_1-auc:0.83546
[21]	validation_0-auc:0.90818	validation_1-auc:0.83553
[22]	validation_0-auc:0.91060	validation_1-auc:0.83509
[23]	validation_0-auc:0.91273	validation_1-auc:0.83509
[24]	validation_0-auc:0.91505	validation_1-auc:0.83470
[25]	validation_0-auc:0.91678	validation_1-auc:0.83587
[26]	validation_0-auc:0.91857	validation_1-auc:0.83641
[27]	validation_0-auc:0.92037	validation_1-auc:0.83609
[28]	validation_0-auc:0.92246	validation_1-auc:0.83606
[29]	validation_0-auc:0.92478	validation_1-auc:0.83631
[30]	validation_0-auc:0.92681	validation_1-auc:0.83597
[31]	validation_0-auc:0.92825	validation_1-auc:0.83669
[32]	validation_0-auc:0.92981	validation_1-auc:0.83659
[33]	validation_0-auc:0.93075	validation_1-auc:0.83662
[34]	validation_0-auc:0.93162	validation_1-auc:0.83631
[35]	validation_0-auc:0.93357	validation_1-auc:0.83590
[36]	validation_0-auc:0.93472	validation_1-auc:0.83539
[37]	validation_0-auc:0.93557	validation_1-auc:0.83605
[38]	validation_0-auc:0.93672	validation_1-auc:0.83584
[39]	validation_0-auc:0.93736	validation_1-auc:0.83603
[40]	validation_0-auc:0.93823	validation_1-auc:0.83635
[41]	validation_0-auc:0.93876	validation_1-auc:0.83691
[42]	validation_0-auc:0.93942	validation_1-auc:0.83664
[43]	validation_0-auc:0.94022	validation_1-auc:0.83617
[44]	validation_0-auc:0.94051	validation_1-auc:0.83663
[45]	validation_0-auc:0.94069	validation_1-auc:0.83685
[46]	validation_0-auc:0.94103	validation_1-auc:0.83699
[47]	validation_0-auc:0.94147	validation_1-auc:0.83698
[48]	validation_0-auc:0.94182	validation_1-auc:0.83716
[49]	validation_0-auc:0.94223	validation_1-auc:0.83740
[50]	validation_0-auc:0.94242	validation_1-auc:0.83738
[51]	validation_0-auc:0.94294	validation_1-auc:0.83718
[52]	validation_0-auc:0.94318	validation_1-auc:0.83710
[53]	validation_0-auc:0.94341	validation_1-auc:0.83709
[54]	validation_0-auc:0.94369	validation_1-auc:0.83703
[55]	validation_0-auc:0.94395	validation_1-auc:0.83698
[56]	validation_0-auc:0.94424	validation_1-auc:0.83705
[57]	validation_0-auc:0.94442	validation_1-auc:0.83723
[58]	validation_0-auc:0.94448	validation_1-auc:0.83735
[59]	validation_0-auc:0.94466	validation_1-auc:0.83757
[60]	validation_0-auc:0.94475	validation_1-auc:0.83755
[61]	validation_0-auc:0.94528	validation_1-auc:0.83745
[62]	validation_0-auc:0.94557	validation_1-auc:0.83752
[63]	validation_0-auc:0.94586	validation_1-auc:0.83734
[64]	validation_0-auc:0.94600	validation_1-auc:0.83738
[65]	validation_0-auc:0.94629	validation_1-auc:0.83725
[66]	validation_0-auc:0.94657	validation_1-auc:0.83730
[67]	validation_0-auc:0.94674	validation_1-auc:0.83723
[68]	validation_0-auc:0.94682	validation_1-auc:0.83725
[69]	validation_0-auc:0.94716	validation_1-auc:0.83718
[70]	validation_0-auc:0.94726	validation_1-auc:0.83720
[71]	validation_0-auc:0.94740	validation_1-auc:0.83725
[72]	validation_0-auc:0.94771	validation_1-auc:0.83722
[73]	validation_0-auc:0.94816	validation_1-auc:0.83708
[74]	validation_0-auc:0.94844	validation_1-auc:0.83713
[75]	validation_0-auc:0.94864	validation_1-auc:0.83719
[76]	validation_0-auc:0.94876	validation_1-auc:0.83733
[77]	validation_0-auc:0.94886	validation_1-auc:0.83721
[78]	validation_0-auc:0.94914	validation_1-auc:0.83688
[79]	validation_0-auc:0.94927	validation_1-auc:0.83685
[80]	validation_0-auc:0.94939	validation_1-auc:0.83671
[81]	validation_0-auc:0.94943	validation_1-auc:0.83677
[82]	validation_0-auc:0.95032	validation_1-auc:0.83718
[83]	validation_0-auc:0.95043	validation_1-auc:0.83698
[84]	validation_0-auc:0.95071	validation_1-auc:0.83698
[85]	validation_0-auc:0.95081	validation_1-auc:0.83690
[86]	validation_0-auc:0.95099	validation_1-auc:0.83688
[87]	validation_0-auc:0.95110	validation_1-auc:0.83679
[88]	validation_0-auc:0.95153	validation_1-auc:0.83696
[89]	validation_0-auc:0.95160	validation_1-auc:0.83707
 26%|██▌       | 13/50 [03:13<08:43, 14.16s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83262	validation_1-auc:0.80947
[1]	validation_0-auc:0.83718	validation_1-auc:0.81033
[2]	validation_0-auc:0.84083	validation_1-auc:0.81141
[3]	validation_0-auc:0.84781	validation_1-auc:0.81583
[4]	validation_0-auc:0.85423	validation_1-auc:0.81765
[5]	validation_0-auc:0.85735	validation_1-auc:0.81731
[6]	validation_0-auc:0.86505	validation_1-auc:0.82028
[7]	validation_0-auc:0.87041	validation_1-auc:0.82135
[8]	validation_0-auc:0.87369	validation_1-auc:0.82343
[9]	validation_0-auc:0.88089	validation_1-auc:0.82493
[10]	validation_0-auc:0.88372	validation_1-auc:0.82592
[11]	validation_0-auc:0.88722	validation_1-auc:0.82564
[12]	validation_0-auc:0.89059	validation_1-auc:0.82660
[13]	validation_0-auc:0.89350	validation_1-auc:0.82676
[14]	validation_0-auc:0.89477	validation_1-auc:0.82989
[15]	validation_0-auc:0.89822	validation_1-auc:0.83017
[16]	validation_0-auc:0.90121	validation_1-auc:0.83019
[17]	validation_0-auc:0.90298	validation_1-auc:0.82987
[18]	validation_0-auc:0.90616	validation_1-auc:0.82696
[19]	validation_0-auc:0.90835	validation_1-auc:0.82845
[20]	validation_0-auc:0.90983	validation_1-auc:0.82852
[21]	validation_0-auc:0.91092	validation_1-auc:0.82869
[22]	validation_0-auc:0.91405	validation_1-auc:0.82839
[23]	validation_0-auc:0.91666	validation_1-auc:0.83004
[24]	validation_0-auc:0.91925	validation_1-auc:0.83059
[25]	validation_0-auc:0.92170	validation_1-auc:0.83102
[26]	validation_0-auc:0.92355	validation_1-auc:0.83108
[27]	validation_0-auc:0.92623	validation_1-auc:0.83014
[28]	validation_0-auc:0.92798	validation_1-auc:0.82981
[29]	validation_0-auc:0.92968	validation_1-auc:0.83040
[30]	validation_0-auc:0.93110	validation_1-auc:0.82993
[31]	validation_0-auc:0.93222	validation_1-auc:0.82976
[32]	validation_0-auc:0.93356	validation_1-auc:0.83016
[33]	validation_0-auc:0.93502	validation_1-auc:0.83020
[34]	validation_0-auc:0.93578	validation_1-auc:0.83000
[35]	validation_0-auc:0.93680	validation_1-auc:0.82974
[36]	validation_0-auc:0.93797	validation_1-auc:0.82970
[37]	validation_0-auc:0.93839	validation_1-auc:0.82963
[38]	validation_0-auc:0.93917	validation_1-auc:0.82992
[39]	validation_0-auc:0.94000	validation_1-auc:0.82920
[40]	validation_0-auc:0.94046	validation_1-auc:0.82943
[41]	validation_0-auc:0.94114	validation_1-auc:0.82966
[42]	validation_0-auc:0.94183	validation_1-auc:0.83003
[43]	validation_0-auc:0.94248	validation_1-auc:0.82955
[44]	validation_0-auc:0.94284	validation_1-auc:0.82971
[45]	validation_0-auc:0.94333	validation_1-auc:0.82990
[46]	validation_0-auc:0.94368	validation_1-auc:0.82984
[47]	validation_0-auc:0.94405	validation_1-auc:0.82961
[48]	validation_0-auc:0.94481	validation_1-auc:0.82931
[49]	validation_0-auc:0.94523	validation_1-auc:0.82933
[50]	validation_0-auc:0.94576	validation_1-auc:0.82898
[51]	validation_0-auc:0.94644	validation_1-auc:0.82891
[52]	validation_0-auc:0.94669	validation_1-auc:0.82875
[53]	validation_0-auc:0.94711	validation_1-auc:0.82828
[54]	validation_0-auc:0.94742	validation_1-auc:0.82837
[55]	validation_0-auc:0.94761	validation_1-auc:0.82831
 26%|██▌       | 13/50 [03:18<08:43, 14.16s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83145	validation_1-auc:0.80971
[1]	validation_0-auc:0.83952	validation_1-auc:0.81317
[2]	validation_0-auc:0.85030	validation_1-auc:0.82280
[3]	validation_0-auc:0.85399	validation_1-auc:0.82587
[4]	validation_0-auc:0.85821	validation_1-auc:0.82631
[5]	validation_0-auc:0.86098	validation_1-auc:0.82649
[6]	validation_0-auc:0.86510	validation_1-auc:0.82821
[7]	validation_0-auc:0.86749	validation_1-auc:0.82876
[8]	validation_0-auc:0.87055	validation_1-auc:0.83053
[9]	validation_0-auc:0.87759	validation_1-auc:0.82979
[10]	validation_0-auc:0.87851	validation_1-auc:0.82759
[11]	validation_0-auc:0.88074	validation_1-auc:0.82917
[12]	validation_0-auc:0.88352	validation_1-auc:0.83020
[13]	validation_0-auc:0.88491	validation_1-auc:0.83144
[14]	validation_0-auc:0.88866	validation_1-auc:0.83361
[15]	validation_0-auc:0.89262	validation_1-auc:0.83457
[16]	validation_0-auc:0.89508	validation_1-auc:0.83601
[17]	validation_0-auc:0.89934	validation_1-auc:0.83805
[18]	validation_0-auc:0.90198	validation_1-auc:0.83700
[19]	validation_0-auc:0.90540	validation_1-auc:0.83757
[20]	validation_0-auc:0.90674	validation_1-auc:0.83847
[21]	validation_0-auc:0.90854	validation_1-auc:0.83870
[22]	validation_0-auc:0.91114	validation_1-auc:0.83943
[23]	validation_0-auc:0.91463	validation_1-auc:0.83878
[24]	validation_0-auc:0.91646	validation_1-auc:0.83874
[25]	validation_0-auc:0.91899	validation_1-auc:0.83860
[26]	validation_0-auc:0.92079	validation_1-auc:0.83826
[27]	validation_0-auc:0.92249	validation_1-auc:0.83770
[28]	validation_0-auc:0.92410	validation_1-auc:0.83718
[29]	validation_0-auc:0.92551	validation_1-auc:0.83660
[30]	validation_0-auc:0.92683	validation_1-auc:0.83655
[31]	validation_0-auc:0.92804	validation_1-auc:0.83660
[32]	validation_0-auc:0.92947	validation_1-auc:0.83669
[33]	validation_0-auc:0.93059	validation_1-auc:0.83671
[34]	validation_0-auc:0.93195	validation_1-auc:0.83579
[35]	validation_0-auc:0.93274	validation_1-auc:0.83628
[36]	validation_0-auc:0.93374	validation_1-auc:0.83626
[37]	validation_0-auc:0.93453	validation_1-auc:0.83616
[38]	validation_0-auc:0.93551	validation_1-auc:0.83638
[39]	validation_0-auc:0.93627	validation_1-auc:0.83665
[40]	validation_0-auc:0.93684	validation_1-auc:0.83691
[41]	validation_0-auc:0.93755	validation_1-auc:0.83646
[42]	validation_0-auc:0.93802	validation_1-auc:0.83683
[43]	validation_0-auc:0.93869	validation_1-auc:0.83740
[44]	validation_0-auc:0.93894	validation_1-auc:0.83746
[45]	validation_0-auc:0.93945	validation_1-auc:0.83761
[46]	validation_0-auc:0.94011	validation_1-auc:0.83770
[47]	validation_0-auc:0.94037	validation_1-auc:0.83744
[48]	validation_0-auc:0.94077	validation_1-auc:0.83776
[49]	validation_0-auc:0.94110	validation_1-auc:0.83799
[50]	validation_0-auc:0.94123	validation_1-auc:0.83793
[51]	validation_0-auc:0.94151	validation_1-auc:0.83818
 28%|██▊       | 14/50 [03:24<09:05, 15.16s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82709	validation_1-auc:0.81284
[1]	validation_0-auc:0.83192	validation_1-auc:0.81395
[2]	validation_0-auc:0.84228	validation_1-auc:0.82160
[3]	validation_0-auc:0.84535	validation_1-auc:0.82216
[4]	validation_0-auc:0.84659	validation_1-auc:0.82067
[5]	validation_0-auc:0.84716	validation_1-auc:0.82288
[6]	validation_0-auc:0.84996	validation_1-auc:0.82386
[7]	validation_0-auc:0.85090	validation_1-auc:0.82392
[8]	validation_0-auc:0.85392	validation_1-auc:0.82631
[9]	validation_0-auc:0.85771	validation_1-auc:0.83008
[10]	validation_0-auc:0.85693	validation_1-auc:0.83098
[11]	validation_0-auc:0.85705	validation_1-auc:0.83040
[12]	validation_0-auc:0.86033	validation_1-auc:0.83380
[13]	validation_0-auc:0.86236	validation_1-auc:0.83533
[14]	validation_0-auc:0.86397	validation_1-auc:0.83759
[15]	validation_0-auc:0.86597	validation_1-auc:0.83763
[16]	validation_0-auc:0.86648	validation_1-auc:0.83795
[17]	validation_0-auc:0.86765	validation_1-auc:0.83813
[18]	validation_0-auc:0.86763	validation_1-auc:0.83825
[19]	validation_0-auc:0.86894	validation_1-auc:0.83927
[20]	validation_0-auc:0.87018	validation_1-auc:0.83931
[21]	validation_0-auc:0.86999	validation_1-auc:0.83920
[22]	validation_0-auc:0.87210	validation_1-auc:0.84027
[23]	validation_0-auc:0.87357	validation_1-auc:0.84096
[24]	validation_0-auc:0.87401	validation_1-auc:0.84093
[25]	validation_0-auc:0.87453	validation_1-auc:0.84061
[26]	validation_0-auc:0.87587	validation_1-auc:0.84148
[27]	validation_0-auc:0.87730	validation_1-auc:0.84192
[28]	validation_0-auc:0.87807	validation_1-auc:0.84189
[29]	validation_0-auc:0.87879	validation_1-auc:0.84144
[30]	validation_0-auc:0.87954	validation_1-auc:0.84208
[31]	validation_0-auc:0.88089	validation_1-auc:0.84281
[32]	validation_0-auc:0.88217	validation_1-auc:0.84309
[33]	validation_0-auc:0.88247	validation_1-auc:0.84364
[34]	validation_0-auc:0.88333	validation_1-auc:0.84400
[35]	validation_0-auc:0.88366	validation_1-auc:0.84414
[36]	validation_0-auc:0.88455	validation_1-auc:0.84427
[37]	validation_0-auc:0.88534	validation_1-auc:0.84470
[38]	validation_0-auc:0.88565	validation_1-auc:0.84485
[39]	validation_0-auc:0.88583	validation_1-auc:0.84503
[40]	validation_0-auc:0.88611	validation_1-auc:0.84519
[41]	validation_0-auc:0.88722	validation_1-auc:0.84519
[42]	validation_0-auc:0.88760	validation_1-auc:0.84517
[43]	validation_0-auc:0.88792	validation_1-auc:0.84513
[44]	validation_0-auc:0.88862	validation_1-auc:0.84533
[45]	validation_0-auc:0.88898	validation_1-auc:0.84561
[46]	validation_0-auc:0.88948	validation_1-auc:0.84576
[47]	validation_0-auc:0.89034	validation_1-auc:0.84549
[48]	validation_0-auc:0.89052	validation_1-auc:0.84530
[49]	validation_0-auc:0.89075	validation_1-auc:0.84547
[50]	validation_0-auc:0.89178	validation_1-auc:0.84584
[51]	validation_0-auc:0.89239	validation_1-auc:0.84541
[52]	validation_0-auc:0.89304	validation_1-auc:0.84541
[53]	validation_0-auc:0.89330	validation_1-auc:0.84546
[54]	validation_0-auc:0.89359	validation_1-auc:0.84537
[55]	validation_0-auc:0.89397	validation_1-auc:0.84532
[56]	validation_0-auc:0.89408	validation_1-auc:0.84519
[57]	validation_0-auc:0.89476	validation_1-auc:0.84513
[58]	validation_0-auc:0.89513	validation_1-auc:0.84522
[59]	validation_0-auc:0.89553	validation_1-auc:0.84517
[60]	validation_0-auc:0.89563	validation_1-auc:0.84517
[61]	validation_0-auc:0.89654	validation_1-auc:0.84497
[62]	validation_0-auc:0.89716	validation_1-auc:0.84508
[63]	validation_0-auc:0.89728	validation_1-auc:0.84519
[64]	validation_0-auc:0.89734	validation_1-auc:0.84511
[65]	validation_0-auc:0.89796	validation_1-auc:0.84524
[66]	validation_0-auc:0.89806	validation_1-auc:0.84531
[67]	validation_0-auc:0.89832	validation_1-auc:0.84520
[68]	validation_0-auc:0.89875	validation_1-auc:0.84513
[69]	validation_0-auc:0.89924	validation_1-auc:0.84508
[70]	validation_0-auc:0.89956	validation_1-auc:0.84499
[71]	validation_0-auc:0.89964	validation_1-auc:0.84492
[72]	validation_0-auc:0.89981	validation_1-auc:0.84504
[73]	validation_0-auc:0.89986	validation_1-auc:0.84505
[74]	validation_0-auc:0.89989	validation_1-auc:0.84503
[75]	validation_0-auc:0.90015	validation_1-auc:0.84521
[76]	validation_0-auc:0.90036	validation_1-auc:0.84497
[77]	validation_0-auc:0.90047	validation_1-auc:0.84496
[78]	validation_0-auc:0.90054	validation_1-auc:0.84499
[79]	validation_0-auc:0.90093	validation_1-auc:0.84484
[80]	validation_0-auc:0.90119	validation_1-auc:0.84470
 28%|██▊       | 14/50 [03:28<09:05, 15.16s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82368	validation_1-auc:0.80750
[1]	validation_0-auc:0.82902	validation_1-auc:0.81046
[2]	validation_0-auc:0.83458	validation_1-auc:0.81625
[3]	validation_0-auc:0.83953	validation_1-auc:0.82130
[4]	validation_0-auc:0.84510	validation_1-auc:0.82447
[5]	validation_0-auc:0.84506	validation_1-auc:0.82418
[6]	validation_0-auc:0.84910	validation_1-auc:0.82434
[7]	validation_0-auc:0.85082	validation_1-auc:0.82572
[8]	validation_0-auc:0.85242	validation_1-auc:0.82616
[9]	validation_0-auc:0.85565	validation_1-auc:0.82733
[10]	validation_0-auc:0.85676	validation_1-auc:0.82649
[11]	validation_0-auc:0.85775	validation_1-auc:0.82575
[12]	validation_0-auc:0.86252	validation_1-auc:0.82769
[13]	validation_0-auc:0.86552	validation_1-auc:0.83084
[14]	validation_0-auc:0.86636	validation_1-auc:0.83108
[15]	validation_0-auc:0.86851	validation_1-auc:0.83161
[16]	validation_0-auc:0.86997	validation_1-auc:0.83318
[17]	validation_0-auc:0.87051	validation_1-auc:0.83350
[18]	validation_0-auc:0.87112	validation_1-auc:0.83329
[19]	validation_0-auc:0.87291	validation_1-auc:0.83458
[20]	validation_0-auc:0.87415	validation_1-auc:0.83501
[21]	validation_0-auc:0.87442	validation_1-auc:0.83509
[22]	validation_0-auc:0.87591	validation_1-auc:0.83603
[23]	validation_0-auc:0.87764	validation_1-auc:0.83718
[24]	validation_0-auc:0.87836	validation_1-auc:0.83730
[25]	validation_0-auc:0.87876	validation_1-auc:0.83803
[26]	validation_0-auc:0.88052	validation_1-auc:0.83781
[27]	validation_0-auc:0.88156	validation_1-auc:0.83804
[28]	validation_0-auc:0.88239	validation_1-auc:0.83833
[29]	validation_0-auc:0.88360	validation_1-auc:0.83865
[30]	validation_0-auc:0.88423	validation_1-auc:0.83833
[31]	validation_0-auc:0.88518	validation_1-auc:0.83863
[32]	validation_0-auc:0.88576	validation_1-auc:0.83866
[33]	validation_0-auc:0.88636	validation_1-auc:0.83901
[34]	validation_0-auc:0.88684	validation_1-auc:0.83871
[35]	validation_0-auc:0.88721	validation_1-auc:0.83896
[36]	validation_0-auc:0.88818	validation_1-auc:0.83873
[37]	validation_0-auc:0.88893	validation_1-auc:0.83880
[38]	validation_0-auc:0.88970	validation_1-auc:0.83927
[39]	validation_0-auc:0.88994	validation_1-auc:0.83954
[40]	validation_0-auc:0.89019	validation_1-auc:0.83966
[41]	validation_0-auc:0.89094	validation_1-auc:0.83949
[42]	validation_0-auc:0.89127	validation_1-auc:0.83946
[43]	validation_0-auc:0.89167	validation_1-auc:0.83955
[44]	validation_0-auc:0.89220	validation_1-auc:0.83962
[45]	validation_0-auc:0.89246	validation_1-auc:0.83973
[46]	validation_0-auc:0.89286	validation_1-auc:0.83962
[47]	validation_0-auc:0.89344	validation_1-auc:0.83946
[48]	validation_0-auc:0.89384	validation_1-auc:0.83928
[49]	validation_0-auc:0.89421	validation_1-auc:0.83949
[50]	validation_0-auc:0.89516	validation_1-auc:0.83963
[51]	validation_0-auc:0.89545	validation_1-auc:0.83977
[52]	validation_0-auc:0.89553	validation_1-auc:0.83975
[53]	validation_0-auc:0.89577	validation_1-auc:0.83965
[54]	validation_0-auc:0.89598	validation_1-auc:0.83943
[55]	validation_0-auc:0.89624	validation_1-auc:0.83944
[56]	validation_0-auc:0.89676	validation_1-auc:0.83932
[57]	validation_0-auc:0.89755	validation_1-auc:0.83884
[58]	validation_0-auc:0.89788	validation_1-auc:0.83889
[59]	validation_0-auc:0.89833	validation_1-auc:0.83885
[60]	validation_0-auc:0.89847	validation_1-auc:0.83906
[61]	validation_0-auc:0.89863	validation_1-auc:0.83906
[62]	validation_0-auc:0.89876	validation_1-auc:0.83910
[63]	validation_0-auc:0.89889	validation_1-auc:0.83894
[64]	validation_0-auc:0.89967	validation_1-auc:0.83899
[65]	validation_0-auc:0.89991	validation_1-auc:0.83877
[66]	validation_0-auc:0.90010	validation_1-auc:0.83869
[67]	validation_0-auc:0.90061	validation_1-auc:0.83872
[68]	validation_0-auc:0.90076	validation_1-auc:0.83897
[69]	validation_0-auc:0.90114	validation_1-auc:0.83869
[70]	validation_0-auc:0.90132	validation_1-auc:0.83871
[71]	validation_0-auc:0.90152	validation_1-auc:0.83867
[72]	validation_0-auc:0.90158	validation_1-auc:0.83869
[73]	validation_0-auc:0.90175	validation_1-auc:0.83853
[74]	validation_0-auc:0.90227	validation_1-auc:0.83844
[75]	validation_0-auc:0.90259	validation_1-auc:0.83827
[76]	validation_0-auc:0.90323	validation_1-auc:0.83824
[77]	validation_0-auc:0.90334	validation_1-auc:0.83823
[78]	validation_0-auc:0.90342	validation_1-auc:0.83811
[79]	validation_0-auc:0.90386	validation_1-auc:0.83826
[80]	validation_0-auc:0.90397	validation_1-auc:0.83820
[81]	validation_0-auc:0.90482	validation_1-auc:0.83811
 28%|██▊       | 14/50 [03:32<09:05, 15.16s/trial, best loss: -0.8430557881612776]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82057	validation_1-auc:0.81074
[1]	validation_0-auc:0.82822	validation_1-auc:0.81499
[2]	validation_0-auc:0.83393	validation_1-auc:0.82071
[3]	validation_0-auc:0.84218	validation_1-auc:0.82902
[4]	validation_0-auc:0.84563	validation_1-auc:0.83105
[5]	validation_0-auc:0.84778	validation_1-auc:0.83160
[6]	validation_0-auc:0.84953	validation_1-auc:0.83246
[7]	validation_0-auc:0.85061	validation_1-auc:0.83309
[8]	validation_0-auc:0.85126	validation_1-auc:0.83401
[9]	validation_0-auc:0.85516	validation_1-auc:0.83448
[10]	validation_0-auc:0.85462	validation_1-auc:0.83141
[11]	validation_0-auc:0.85446	validation_1-auc:0.83074
[12]	validation_0-auc:0.85791	validation_1-auc:0.83260
[13]	validation_0-auc:0.86114	validation_1-auc:0.83625
[14]	validation_0-auc:0.86213	validation_1-auc:0.83752
[15]	validation_0-auc:0.86379	validation_1-auc:0.83875
[16]	validation_0-auc:0.86556	validation_1-auc:0.84033
[17]	validation_0-auc:0.86792	validation_1-auc:0.84178
[18]	validation_0-auc:0.86798	validation_1-auc:0.84039
[19]	validation_0-auc:0.86893	validation_1-auc:0.84090
[20]	validation_0-auc:0.86991	validation_1-auc:0.84155
[21]	validation_0-auc:0.87027	validation_1-auc:0.84072
[22]	validation_0-auc:0.87075	validation_1-auc:0.84144
[23]	validation_0-auc:0.87168	validation_1-auc:0.84204
[24]	validation_0-auc:0.87352	validation_1-auc:0.84259
[25]	validation_0-auc:0.87506	validation_1-auc:0.84297
[26]	validation_0-auc:0.87667	validation_1-auc:0.84255
[27]	validation_0-auc:0.87807	validation_1-auc:0.84272
[28]	validation_0-auc:0.87880	validation_1-auc:0.84240
[29]	validation_0-auc:0.87937	validation_1-auc:0.84264
[30]	validation_0-auc:0.88044	validation_1-auc:0.84272
[31]	validation_0-auc:0.88164	validation_1-auc:0.84303
[32]	validation_0-auc:0.88221	validation_1-auc:0.84309
[33]	validation_0-auc:0.88256	validation_1-auc:0.84313
[34]	validation_0-auc:0.88309	validation_1-auc:0.84331
[35]	validation_0-auc:0.88338	validation_1-auc:0.84336
[36]	validation_0-auc:0.88359	validation_1-auc:0.84375
[37]	validation_0-auc:0.88443	validation_1-auc:0.84348
[38]	validation_0-auc:0.88547	validation_1-auc:0.84376
[39]	validation_0-auc:0.88568	validation_1-auc:0.84399
[40]	validation_0-auc:0.88592	validation_1-auc:0.84410
[41]	validation_0-auc:0.88699	validation_1-auc:0.84441
[42]	validation_0-auc:0.88775	validation_1-auc:0.84461
[43]	validation_0-auc:0.88833	validation_1-auc:0.84458
[44]	validation_0-auc:0.88859	validation_1-auc:0.84485
[45]	validation_0-auc:0.88914	validation_1-auc:0.84484
[46]	validation_0-auc:0.88932	validation_1-auc:0.84462
[47]	validation_0-auc:0.88986	validation_1-auc:0.84459
[48]	validation_0-auc:0.89024	validation_1-auc:0.84464
[49]	validation_0-auc:0.89093	validation_1-auc:0.84483
[50]	validation_0-auc:0.89106	validation_1-auc:0.84489
[51]	validation_0-auc:0.89125	validation_1-auc:0.84492
[52]	validation_0-auc:0.89185	validation_1-auc:0.84505
[53]	validation_0-auc:0.89196	validation_1-auc:0.84487
[54]	validation_0-auc:0.89207	validation_1-auc:0.84479
[55]	validation_0-auc:0.89269	validation_1-auc:0.84470
[56]	validation_0-auc:0.89275	validation_1-auc:0.84478
[57]	validation_0-auc:0.89288	validation_1-auc:0.84473
[58]	validation_0-auc:0.89374	validation_1-auc:0.84443
[59]	validation_0-auc:0.89472	validation_1-auc:0.84433
[60]	validation_0-auc:0.89560	validation_1-auc:0.84393
[61]	validation_0-auc:0.89613	validation_1-auc:0.84397
[62]	validation_0-auc:0.89679	validation_1-auc:0.84396
[63]	validation_0-auc:0.89695	validation_1-auc:0.84411
[64]	validation_0-auc:0.89738	validation_1-auc:0.84396
[65]	validation_0-auc:0.89776	validation_1-auc:0.84374
[66]	validation_0-auc:0.89846	validation_1-auc:0.84381
[67]	validation_0-auc:0.89855	validation_1-auc:0.84381
[68]	validation_0-auc:0.89866	validation_1-auc:0.84368
[69]	validation_0-auc:0.89885	validation_1-auc:0.84368
[70]	validation_0-auc:0.89903	validation_1-auc:0.84347
[71]	validation_0-auc:0.89935	validation_1-auc:0.84367
[72]	validation_0-auc:0.89985	validation_1-auc:0.84358
[73]	validation_0-auc:0.90027	validation_1-auc:0.84332
[74]	validation_0-auc:0.90047	validation_1-auc:0.84333
[75]	validation_0-auc:0.90060	validation_1-auc:0.84334
[76]	validation_0-auc:0.90072	validation_1-auc:0.84327
[77]	validation_0-auc:0.90109	validation_1-auc:0.84305
[78]	validation_0-auc:0.90168	validation_1-auc:0.84293
[79]	validation_0-auc:0.90182	validation_1-auc:0.84286
[80]	validation_0-auc:0.90229	validation_1-auc:0.84267
[81]	validation_0-auc:0.90271	validation_1-auc:0.84245
[82]	validation_0-auc:0.90338	validation_1-auc:0.84221
 30%|███       | 15/50 [03:37<08:28, 14.54s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83431	validation_1-auc:0.81357
[1]	validation_0-auc:0.84402	validation_1-auc:0.81329
[2]	validation_0-auc:0.85228	validation_1-auc:0.81634
[3]	validation_0-auc:0.85641	validation_1-auc:0.81602
[4]	validation_0-auc:0.86637	validation_1-auc:0.81848
[5]	validation_0-auc:0.87347	validation_1-auc:0.82153
[6]	validation_0-auc:0.88262	validation_1-auc:0.82601
[7]	validation_0-auc:0.88777	validation_1-auc:0.82634
[8]	validation_0-auc:0.89274	validation_1-auc:0.82762
[9]	validation_0-auc:0.89622	validation_1-auc:0.82717
[10]	validation_0-auc:0.89944	validation_1-auc:0.82698
[11]	validation_0-auc:0.90304	validation_1-auc:0.82652
[12]	validation_0-auc:0.90792	validation_1-auc:0.82908
[13]	validation_0-auc:0.91334	validation_1-auc:0.83014
[14]	validation_0-auc:0.91453	validation_1-auc:0.83302
[15]	validation_0-auc:0.91720	validation_1-auc:0.83279
[16]	validation_0-auc:0.92055	validation_1-auc:0.83359
[17]	validation_0-auc:0.92383	validation_1-auc:0.83517
[18]	validation_0-auc:0.92515	validation_1-auc:0.83445
[19]	validation_0-auc:0.92990	validation_1-auc:0.83481
[20]	validation_0-auc:0.93101	validation_1-auc:0.83369
[21]	validation_0-auc:0.93231	validation_1-auc:0.83235
[22]	validation_0-auc:0.93494	validation_1-auc:0.83296
[23]	validation_0-auc:0.93858	validation_1-auc:0.83137
[24]	validation_0-auc:0.94041	validation_1-auc:0.83138
[25]	validation_0-auc:0.94143	validation_1-auc:0.83100
[26]	validation_0-auc:0.94300	validation_1-auc:0.83044
[27]	validation_0-auc:0.94521	validation_1-auc:0.83138
[28]	validation_0-auc:0.94603	validation_1-auc:0.83099
[29]	validation_0-auc:0.94776	validation_1-auc:0.83136
[30]	validation_0-auc:0.94933	validation_1-auc:0.83091
[31]	validation_0-auc:0.95098	validation_1-auc:0.83079
[32]	validation_0-auc:0.95168	validation_1-auc:0.83120
[33]	validation_0-auc:0.95205	validation_1-auc:0.83183
[34]	validation_0-auc:0.95265	validation_1-auc:0.83157
[35]	validation_0-auc:0.95314	validation_1-auc:0.83202
[36]	validation_0-auc:0.95385	validation_1-auc:0.83210
[37]	validation_0-auc:0.95409	validation_1-auc:0.83218
[38]	validation_0-auc:0.95433	validation_1-auc:0.83214
[39]	validation_0-auc:0.95450	validation_1-auc:0.83241
[40]	validation_0-auc:0.95480	validation_1-auc:0.83175
[41]	validation_0-auc:0.95521	validation_1-auc:0.83085
[42]	validation_0-auc:0.95594	validation_1-auc:0.83159
[43]	validation_0-auc:0.95605	validation_1-auc:0.83195
[44]	validation_0-auc:0.95614	validation_1-auc:0.83223
[45]	validation_0-auc:0.95628	validation_1-auc:0.83231
[46]	validation_0-auc:0.95696	validation_1-auc:0.83208
[47]	validation_0-auc:0.95781	validation_1-auc:0.83169
 30%|███       | 15/50 [03:42<08:28, 14.54s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83108	validation_1-auc:0.80712
[1]	validation_0-auc:0.84215	validation_1-auc:0.81318
[2]	validation_0-auc:0.84974	validation_1-auc:0.81765
[3]	validation_0-auc:0.86154	validation_1-auc:0.81952
[4]	validation_0-auc:0.87048	validation_1-auc:0.82185
[5]	validation_0-auc:0.87967	validation_1-auc:0.82426
[6]	validation_0-auc:0.88479	validation_1-auc:0.82501
[7]	validation_0-auc:0.89114	validation_1-auc:0.82319
[8]	validation_0-auc:0.89474	validation_1-auc:0.82421
[9]	validation_0-auc:0.89958	validation_1-auc:0.82366
[10]	validation_0-auc:0.90309	validation_1-auc:0.82282
[11]	validation_0-auc:0.90664	validation_1-auc:0.82179
[12]	validation_0-auc:0.91014	validation_1-auc:0.82486
[13]	validation_0-auc:0.91603	validation_1-auc:0.82458
[14]	validation_0-auc:0.91810	validation_1-auc:0.82739
[15]	validation_0-auc:0.92246	validation_1-auc:0.82294
[16]	validation_0-auc:0.92455	validation_1-auc:0.82475
[17]	validation_0-auc:0.92796	validation_1-auc:0.82657
[18]	validation_0-auc:0.92927	validation_1-auc:0.82565
[19]	validation_0-auc:0.93277	validation_1-auc:0.82726
[20]	validation_0-auc:0.93372	validation_1-auc:0.82734
[21]	validation_0-auc:0.93476	validation_1-auc:0.82737
[22]	validation_0-auc:0.93625	validation_1-auc:0.82867
[23]	validation_0-auc:0.93887	validation_1-auc:0.82930
[24]	validation_0-auc:0.94019	validation_1-auc:0.82888
[25]	validation_0-auc:0.94125	validation_1-auc:0.82899
[26]	validation_0-auc:0.94309	validation_1-auc:0.82731
[27]	validation_0-auc:0.94497	validation_1-auc:0.82779
[28]	validation_0-auc:0.94556	validation_1-auc:0.82705
[29]	validation_0-auc:0.94639	validation_1-auc:0.82694
[30]	validation_0-auc:0.94838	validation_1-auc:0.82602
[31]	validation_0-auc:0.94935	validation_1-auc:0.82674
[32]	validation_0-auc:0.95028	validation_1-auc:0.82786
[33]	validation_0-auc:0.95085	validation_1-auc:0.82794
[34]	validation_0-auc:0.95118	validation_1-auc:0.82810
[35]	validation_0-auc:0.95149	validation_1-auc:0.82795
[36]	validation_0-auc:0.95318	validation_1-auc:0.82621
[37]	validation_0-auc:0.95425	validation_1-auc:0.82542
[38]	validation_0-auc:0.95544	validation_1-auc:0.82479
[39]	validation_0-auc:0.95565	validation_1-auc:0.82512
[40]	validation_0-auc:0.95602	validation_1-auc:0.82520
[41]	validation_0-auc:0.95614	validation_1-auc:0.82526
[42]	validation_0-auc:0.95665	validation_1-auc:0.82520
[43]	validation_0-auc:0.95673	validation_1-auc:0.82523
[44]	validation_0-auc:0.95727	validation_1-auc:0.82541
[45]	validation_0-auc:0.95737	validation_1-auc:0.82559
[46]	validation_0-auc:0.95763	validation_1-auc:0.82551
[47]	validation_0-auc:0.95843	validation_1-auc:0.82601
[48]	validation_0-auc:0.95880	validation_1-auc:0.82601
[49]	validation_0-auc:0.95966	validation_1-auc:0.82538
[50]	validation_0-auc:0.96006	validation_1-auc:0.82544
[51]	validation_0-auc:0.96031	validation_1-auc:0.82553
[52]	validation_0-auc:0.96051	validation_1-auc:0.82538
 30%|███       | 15/50 [03:46<08:28, 14.54s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82931	validation_1-auc:0.80740
[1]	validation_0-auc:0.84851	validation_1-auc:0.82095
[2]	validation_0-auc:0.85517	validation_1-auc:0.82413
[3]	validation_0-auc:0.86185	validation_1-auc:0.82527
[4]	validation_0-auc:0.87101	validation_1-auc:0.83013
[5]	validation_0-auc:0.87286	validation_1-auc:0.82784
[6]	validation_0-auc:0.88226	validation_1-auc:0.83280
[7]	validation_0-auc:0.88542	validation_1-auc:0.83344
[8]	validation_0-auc:0.88769	validation_1-auc:0.83428
[9]	validation_0-auc:0.89197	validation_1-auc:0.83108
[10]	validation_0-auc:0.89487	validation_1-auc:0.82983
[11]	validation_0-auc:0.89915	validation_1-auc:0.82737
[12]	validation_0-auc:0.90497	validation_1-auc:0.82840
[13]	validation_0-auc:0.91224	validation_1-auc:0.83107
[14]	validation_0-auc:0.91393	validation_1-auc:0.83273
[15]	validation_0-auc:0.91646	validation_1-auc:0.82988
[16]	validation_0-auc:0.91927	validation_1-auc:0.83245
[17]	validation_0-auc:0.92394	validation_1-auc:0.83239
[18]	validation_0-auc:0.92478	validation_1-auc:0.83094
[19]	validation_0-auc:0.92767	validation_1-auc:0.83216
[20]	validation_0-auc:0.92836	validation_1-auc:0.83198
[21]	validation_0-auc:0.92968	validation_1-auc:0.82975
[22]	validation_0-auc:0.93145	validation_1-auc:0.83200
[23]	validation_0-auc:0.93405	validation_1-auc:0.83319
[24]	validation_0-auc:0.93558	validation_1-auc:0.83352
[25]	validation_0-auc:0.93656	validation_1-auc:0.83355
[26]	validation_0-auc:0.93880	validation_1-auc:0.83419
[27]	validation_0-auc:0.94114	validation_1-auc:0.83451
[28]	validation_0-auc:0.94184	validation_1-auc:0.83391
[29]	validation_0-auc:0.94322	validation_1-auc:0.83460
[30]	validation_0-auc:0.94515	validation_1-auc:0.83342
[31]	validation_0-auc:0.94633	validation_1-auc:0.83397
[32]	validation_0-auc:0.94720	validation_1-auc:0.83436
[33]	validation_0-auc:0.94741	validation_1-auc:0.83449
[34]	validation_0-auc:0.94792	validation_1-auc:0.83505
[35]	validation_0-auc:0.94869	validation_1-auc:0.83531
[36]	validation_0-auc:0.94972	validation_1-auc:0.83417
[37]	validation_0-auc:0.95112	validation_1-auc:0.83351
[38]	validation_0-auc:0.95249	validation_1-auc:0.83369
[39]	validation_0-auc:0.95277	validation_1-auc:0.83363
[40]	validation_0-auc:0.95290	validation_1-auc:0.83353
[41]	validation_0-auc:0.95343	validation_1-auc:0.83323
[42]	validation_0-auc:0.95409	validation_1-auc:0.83312
[43]	validation_0-auc:0.95447	validation_1-auc:0.83293
[44]	validation_0-auc:0.95544	validation_1-auc:0.83296
[45]	validation_0-auc:0.95561	validation_1-auc:0.83295
[46]	validation_0-auc:0.95621	validation_1-auc:0.83315
[47]	validation_0-auc:0.95670	validation_1-auc:0.83297
[48]	validation_0-auc:0.95697	validation_1-auc:0.83253
[49]	validation_0-auc:0.95731	validation_1-auc:0.83219
[50]	validation_0-auc:0.95786	validation_1-auc:0.83199
[51]	validation_0-auc:0.95853	validation_1-auc:0.83122
[52]	validation_0-auc:0.95873	validation_1-auc:0.83124
[53]	validation_0-auc:0.95897	validation_1-auc:0.83121
[54]	validation_0-auc:0.95948	validation_1-auc:0.83056
[55]	validation_0-auc:0.95971	validation_1-auc:0.83065
[56]	validation_0-auc:0.95978	validation_1-auc:0.83036
[57]	validation_0-auc:0.95990	validation_1-auc:0.82998
[58]	validation_0-auc:0.96011	validation_1-auc:0.83007
[59]	validation_0-auc:0.96027	validation_1-auc:0.82990
[60]	validation_0-auc:0.96043	validation_1-auc:0.82974
[61]	validation_0-auc:0.96054	validation_1-auc:0.82960
[62]	validation_0-auc:0.96080	validation_1-auc:0.82926
[63]	validation_0-auc:0.96091	validation_1-auc:0.82895
[64]	validation_0-auc:0.96110	validation_1-auc:0.82867
[65]	validation_0-auc:0.96123	validation_1-auc:0.82856
 32%|███▏      | 16/50 [03:52<08:20, 14.73s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82973	validation_1-auc:0.81426
[1]	validation_0-auc:0.83472	validation_1-auc:0.81463
[2]	validation_0-auc:0.84147	validation_1-auc:0.81654
[3]	validation_0-auc:0.84556	validation_1-auc:0.81849
[4]	validation_0-auc:0.84886	validation_1-auc:0.82180
[5]	validation_0-auc:0.85207	validation_1-auc:0.82343
[6]	validation_0-auc:0.85363	validation_1-auc:0.82341
[7]	validation_0-auc:0.85377	validation_1-auc:0.82329
[8]	validation_0-auc:0.85729	validation_1-auc:0.82583
[9]	validation_0-auc:0.86291	validation_1-auc:0.82979
[10]	validation_0-auc:0.86217	validation_1-auc:0.83072
[11]	validation_0-auc:0.86253	validation_1-auc:0.82924
[12]	validation_0-auc:0.86682	validation_1-auc:0.83282
[13]	validation_0-auc:0.86929	validation_1-auc:0.83496
[14]	validation_0-auc:0.87103	validation_1-auc:0.83646
[15]	validation_0-auc:0.87369	validation_1-auc:0.83817
[16]	validation_0-auc:0.87532	validation_1-auc:0.83892
[17]	validation_0-auc:0.87664	validation_1-auc:0.83884
[18]	validation_0-auc:0.87677	validation_1-auc:0.83873
[19]	validation_0-auc:0.87814	validation_1-auc:0.83926
[20]	validation_0-auc:0.87954	validation_1-auc:0.83886
[21]	validation_0-auc:0.88007	validation_1-auc:0.83946
[22]	validation_0-auc:0.88219	validation_1-auc:0.84002
[23]	validation_0-auc:0.88284	validation_1-auc:0.83919
[24]	validation_0-auc:0.88414	validation_1-auc:0.83963
[25]	validation_0-auc:0.88480	validation_1-auc:0.84020
[26]	validation_0-auc:0.88690	validation_1-auc:0.84050
[27]	validation_0-auc:0.88870	validation_1-auc:0.84114
[28]	validation_0-auc:0.89057	validation_1-auc:0.84185
[29]	validation_0-auc:0.89265	validation_1-auc:0.84141
[30]	validation_0-auc:0.89403	validation_1-auc:0.84187
[31]	validation_0-auc:0.89551	validation_1-auc:0.84216
[32]	validation_0-auc:0.89678	validation_1-auc:0.84215
[33]	validation_0-auc:0.89790	validation_1-auc:0.84246
[34]	validation_0-auc:0.89927	validation_1-auc:0.84324
[35]	validation_0-auc:0.89956	validation_1-auc:0.84356
[36]	validation_0-auc:0.90044	validation_1-auc:0.84375
[37]	validation_0-auc:0.90088	validation_1-auc:0.84397
[38]	validation_0-auc:0.90189	validation_1-auc:0.84372
[39]	validation_0-auc:0.90211	validation_1-auc:0.84400
[40]	validation_0-auc:0.90241	validation_1-auc:0.84419
[41]	validation_0-auc:0.90288	validation_1-auc:0.84448
[42]	validation_0-auc:0.90362	validation_1-auc:0.84460
[43]	validation_0-auc:0.90420	validation_1-auc:0.84472
[44]	validation_0-auc:0.90509	validation_1-auc:0.84463
[45]	validation_0-auc:0.90538	validation_1-auc:0.84456
[46]	validation_0-auc:0.90564	validation_1-auc:0.84453
[47]	validation_0-auc:0.90634	validation_1-auc:0.84489
[48]	validation_0-auc:0.90667	validation_1-auc:0.84490
[49]	validation_0-auc:0.90692	validation_1-auc:0.84490
[50]	validation_0-auc:0.90773	validation_1-auc:0.84521
[51]	validation_0-auc:0.90779	validation_1-auc:0.84514
[52]	validation_0-auc:0.90800	validation_1-auc:0.84518
[53]	validation_0-auc:0.90844	validation_1-auc:0.84519
[54]	validation_0-auc:0.90859	validation_1-auc:0.84518
[55]	validation_0-auc:0.90918	validation_1-auc:0.84534
[56]	validation_0-auc:0.90946	validation_1-auc:0.84517
[57]	validation_0-auc:0.90959	validation_1-auc:0.84521
[58]	validation_0-auc:0.90976	validation_1-auc:0.84518
[59]	validation_0-auc:0.90997	validation_1-auc:0.84507
[60]	validation_0-auc:0.91053	validation_1-auc:0.84491
[61]	validation_0-auc:0.91081	validation_1-auc:0.84480
[62]	validation_0-auc:0.91103	validation_1-auc:0.84485
[63]	validation_0-auc:0.91145	validation_1-auc:0.84478
[64]	validation_0-auc:0.91164	validation_1-auc:0.84483
[65]	validation_0-auc:0.91202	validation_1-auc:0.84472
[66]	validation_0-auc:0.91231	validation_1-auc:0.84449
[67]	validation_0-auc:0.91242	validation_1-auc:0.84448
[68]	validation_0-auc:0.91321	validation_1-auc:0.84433
[69]	validation_0-auc:0.91330	validation_1-auc:0.84427
[70]	validation_0-auc:0.91340	validation_1-auc:0.84434
[71]	validation_0-auc:0.91356	validation_1-auc:0.84419
[72]	validation_0-auc:0.91396	validation_1-auc:0.84431
[73]	validation_0-auc:0.91409	validation_1-auc:0.84419
[74]	validation_0-auc:0.91512	validation_1-auc:0.84405
[75]	validation_0-auc:0.91594	validation_1-auc:0.84453
[76]	validation_0-auc:0.91607	validation_1-auc:0.84460
[77]	validation_0-auc:0.91668	validation_1-auc:0.84451
[78]	validation_0-auc:0.91690	validation_1-auc:0.84439
[79]	validation_0-auc:0.91704	validation_1-auc:0.84448
[80]	validation_0-auc:0.91726	validation_1-auc:0.84449
[81]	validation_0-auc:0.91741	validation_1-auc:0.84437
[82]	validation_0-auc:0.91758	validation_1-auc:0.84424
[83]	validation_0-auc:0.91799	validation_1-auc:0.84415
[84]	validation_0-auc:0.91827	validation_1-auc:0.84391
 32%|███▏      | 16/50 [03:57<08:20, 14.73s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82562	validation_1-auc:0.80647
[1]	validation_0-auc:0.83329	validation_1-auc:0.81132
[2]	validation_0-auc:0.83825	validation_1-auc:0.81561
[3]	validation_0-auc:0.84233	validation_1-auc:0.81823
[4]	validation_0-auc:0.84917	validation_1-auc:0.82256
[5]	validation_0-auc:0.84945	validation_1-auc:0.82206
[6]	validation_0-auc:0.85295	validation_1-auc:0.82247
[7]	validation_0-auc:0.85471	validation_1-auc:0.82312
[8]	validation_0-auc:0.85795	validation_1-auc:0.82585
[9]	validation_0-auc:0.86311	validation_1-auc:0.82607
[10]	validation_0-auc:0.86396	validation_1-auc:0.82640
[11]	validation_0-auc:0.86557	validation_1-auc:0.82566
[12]	validation_0-auc:0.86943	validation_1-auc:0.82746
[13]	validation_0-auc:0.87374	validation_1-auc:0.82946
[14]	validation_0-auc:0.87430	validation_1-auc:0.83002
[15]	validation_0-auc:0.87694	validation_1-auc:0.83070
[16]	validation_0-auc:0.87915	validation_1-auc:0.83162
[17]	validation_0-auc:0.88023	validation_1-auc:0.83238
[18]	validation_0-auc:0.88096	validation_1-auc:0.83198
[19]	validation_0-auc:0.88255	validation_1-auc:0.83282
[20]	validation_0-auc:0.88363	validation_1-auc:0.83348
[21]	validation_0-auc:0.88507	validation_1-auc:0.83420
[22]	validation_0-auc:0.88784	validation_1-auc:0.83456
[23]	validation_0-auc:0.88969	validation_1-auc:0.83524
[24]	validation_0-auc:0.89081	validation_1-auc:0.83487
[25]	validation_0-auc:0.89132	validation_1-auc:0.83557
[26]	validation_0-auc:0.89281	validation_1-auc:0.83620
[27]	validation_0-auc:0.89369	validation_1-auc:0.83574
[28]	validation_0-auc:0.89460	validation_1-auc:0.83613
[29]	validation_0-auc:0.89586	validation_1-auc:0.83612
[30]	validation_0-auc:0.89708	validation_1-auc:0.83634
[31]	validation_0-auc:0.89826	validation_1-auc:0.83643
[32]	validation_0-auc:0.89913	validation_1-auc:0.83697
[33]	validation_0-auc:0.90038	validation_1-auc:0.83676
[34]	validation_0-auc:0.90071	validation_1-auc:0.83680
[35]	validation_0-auc:0.90135	validation_1-auc:0.83669
[36]	validation_0-auc:0.90176	validation_1-auc:0.83715
[37]	validation_0-auc:0.90203	validation_1-auc:0.83722
[38]	validation_0-auc:0.90250	validation_1-auc:0.83686
[39]	validation_0-auc:0.90309	validation_1-auc:0.83709
[40]	validation_0-auc:0.90351	validation_1-auc:0.83708
[41]	validation_0-auc:0.90415	validation_1-auc:0.83699
[42]	validation_0-auc:0.90482	validation_1-auc:0.83721
[43]	validation_0-auc:0.90523	validation_1-auc:0.83703
[44]	validation_0-auc:0.90551	validation_1-auc:0.83687
[45]	validation_0-auc:0.90623	validation_1-auc:0.83681
[46]	validation_0-auc:0.90689	validation_1-auc:0.83666
[47]	validation_0-auc:0.90724	validation_1-auc:0.83645
[48]	validation_0-auc:0.90734	validation_1-auc:0.83646
[49]	validation_0-auc:0.90750	validation_1-auc:0.83637
[50]	validation_0-auc:0.90781	validation_1-auc:0.83620
[51]	validation_0-auc:0.90857	validation_1-auc:0.83604
[52]	validation_0-auc:0.90881	validation_1-auc:0.83592
[53]	validation_0-auc:0.90925	validation_1-auc:0.83595
[54]	validation_0-auc:0.91087	validation_1-auc:0.83555
[55]	validation_0-auc:0.91134	validation_1-auc:0.83572
[56]	validation_0-auc:0.91143	validation_1-auc:0.83583
[57]	validation_0-auc:0.91194	validation_1-auc:0.83616
[58]	validation_0-auc:0.91236	validation_1-auc:0.83618
[59]	validation_0-auc:0.91254	validation_1-auc:0.83617
[60]	validation_0-auc:0.91264	validation_1-auc:0.83607
[61]	validation_0-auc:0.91327	validation_1-auc:0.83600
[62]	validation_0-auc:0.91358	validation_1-auc:0.83582
[63]	validation_0-auc:0.91371	validation_1-auc:0.83583
[64]	validation_0-auc:0.91445	validation_1-auc:0.83565
[65]	validation_0-auc:0.91498	validation_1-auc:0.83526
[66]	validation_0-auc:0.91521	validation_1-auc:0.83525
[67]	validation_0-auc:0.91534	validation_1-auc:0.83521
 32%|███▏      | 16/50 [04:01<08:20, 14.73s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82429	validation_1-auc:0.81221
[1]	validation_0-auc:0.83265	validation_1-auc:0.81663
[2]	validation_0-auc:0.84173	validation_1-auc:0.82502
[3]	validation_0-auc:0.84676	validation_1-auc:0.82924
[4]	validation_0-auc:0.85072	validation_1-auc:0.82919
[5]	validation_0-auc:0.85327	validation_1-auc:0.83086
[6]	validation_0-auc:0.85638	validation_1-auc:0.83171
[7]	validation_0-auc:0.85749	validation_1-auc:0.83241
[8]	validation_0-auc:0.85829	validation_1-auc:0.83335
[9]	validation_0-auc:0.86219	validation_1-auc:0.83306
[10]	validation_0-auc:0.86089	validation_1-auc:0.83095
[11]	validation_0-auc:0.86006	validation_1-auc:0.82790
[12]	validation_0-auc:0.86405	validation_1-auc:0.83138
[13]	validation_0-auc:0.86781	validation_1-auc:0.83485
[14]	validation_0-auc:0.87045	validation_1-auc:0.83670
[15]	validation_0-auc:0.87258	validation_1-auc:0.83830
[16]	validation_0-auc:0.87497	validation_1-auc:0.83952
[17]	validation_0-auc:0.87720	validation_1-auc:0.84110
[18]	validation_0-auc:0.87776	validation_1-auc:0.83938
[19]	validation_0-auc:0.87941	validation_1-auc:0.84061
[20]	validation_0-auc:0.88058	validation_1-auc:0.84068
[21]	validation_0-auc:0.88176	validation_1-auc:0.84079
[22]	validation_0-auc:0.88367	validation_1-auc:0.84234
[23]	validation_0-auc:0.88482	validation_1-auc:0.84232
[24]	validation_0-auc:0.88682	validation_1-auc:0.84240
[25]	validation_0-auc:0.88817	validation_1-auc:0.84241
[26]	validation_0-auc:0.88937	validation_1-auc:0.84263
[27]	validation_0-auc:0.89083	validation_1-auc:0.84200
[28]	validation_0-auc:0.89192	validation_1-auc:0.84186
[29]	validation_0-auc:0.89291	validation_1-auc:0.84154
[30]	validation_0-auc:0.89458	validation_1-auc:0.84104
[31]	validation_0-auc:0.89571	validation_1-auc:0.84123
[32]	validation_0-auc:0.89610	validation_1-auc:0.84123
[33]	validation_0-auc:0.89664	validation_1-auc:0.84151
[34]	validation_0-auc:0.89756	validation_1-auc:0.84114
[35]	validation_0-auc:0.89801	validation_1-auc:0.84168
[36]	validation_0-auc:0.89855	validation_1-auc:0.84218
[37]	validation_0-auc:0.89930	validation_1-auc:0.84216
[38]	validation_0-auc:0.90024	validation_1-auc:0.84205
[39]	validation_0-auc:0.90035	validation_1-auc:0.84212
[40]	validation_0-auc:0.90089	validation_1-auc:0.84206
[41]	validation_0-auc:0.90165	validation_1-auc:0.84194
[42]	validation_0-auc:0.90192	validation_1-auc:0.84222
[43]	validation_0-auc:0.90296	validation_1-auc:0.84222
[44]	validation_0-auc:0.90371	validation_1-auc:0.84232
[45]	validation_0-auc:0.90418	validation_1-auc:0.84226
[46]	validation_0-auc:0.90503	validation_1-auc:0.84213
[47]	validation_0-auc:0.90549	validation_1-auc:0.84253
[48]	validation_0-auc:0.90617	validation_1-auc:0.84246
[49]	validation_0-auc:0.90653	validation_1-auc:0.84251
[50]	validation_0-auc:0.90696	validation_1-auc:0.84236
[51]	validation_0-auc:0.90752	validation_1-auc:0.84230
[52]	validation_0-auc:0.90797	validation_1-auc:0.84243
[53]	validation_0-auc:0.90816	validation_1-auc:0.84238
[54]	validation_0-auc:0.90893	validation_1-auc:0.84222
[55]	validation_0-auc:0.90907	validation_1-auc:0.84228
 34%|███▍      | 17/50 [04:05<07:46, 14.15s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.84004	validation_1-auc:0.81277
[1]	validation_0-auc:0.84627	validation_1-auc:0.81286
[2]	validation_0-auc:0.85191	validation_1-auc:0.81359
[3]	validation_0-auc:0.85580	validation_1-auc:0.81311
[4]	validation_0-auc:0.86619	validation_1-auc:0.81875
[5]	validation_0-auc:0.87051	validation_1-auc:0.82093
[6]	validation_0-auc:0.87502	validation_1-auc:0.82118
[7]	validation_0-auc:0.87937	validation_1-auc:0.82138
[8]	validation_0-auc:0.88499	validation_1-auc:0.82382
[9]	validation_0-auc:0.89515	validation_1-auc:0.82525
[10]	validation_0-auc:0.89579	validation_1-auc:0.82492
[11]	validation_0-auc:0.90237	validation_1-auc:0.82803
[12]	validation_0-auc:0.90852	validation_1-auc:0.83117
[13]	validation_0-auc:0.91292	validation_1-auc:0.83207
[14]	validation_0-auc:0.91548	validation_1-auc:0.83238
[15]	validation_0-auc:0.92124	validation_1-auc:0.83341
[16]	validation_0-auc:0.92565	validation_1-auc:0.83303
[17]	validation_0-auc:0.92876	validation_1-auc:0.83275
[18]	validation_0-auc:0.93059	validation_1-auc:0.83264
[19]	validation_0-auc:0.93343	validation_1-auc:0.83341
[20]	validation_0-auc:0.93685	validation_1-auc:0.83305
[21]	validation_0-auc:0.93916	validation_1-auc:0.83229
[22]	validation_0-auc:0.94301	validation_1-auc:0.83142
[23]	validation_0-auc:0.94596	validation_1-auc:0.83124
[24]	validation_0-auc:0.94844	validation_1-auc:0.83123
[25]	validation_0-auc:0.95106	validation_1-auc:0.83027
[26]	validation_0-auc:0.95332	validation_1-auc:0.82922
[27]	validation_0-auc:0.95528	validation_1-auc:0.82879
[28]	validation_0-auc:0.95684	validation_1-auc:0.82813
[29]	validation_0-auc:0.95827	validation_1-auc:0.82847
[30]	validation_0-auc:0.96022	validation_1-auc:0.82824
[31]	validation_0-auc:0.96132	validation_1-auc:0.82790
[32]	validation_0-auc:0.96230	validation_1-auc:0.82832
[33]	validation_0-auc:0.96319	validation_1-auc:0.82815
[34]	validation_0-auc:0.96397	validation_1-auc:0.82821
[35]	validation_0-auc:0.96445	validation_1-auc:0.82901
[36]	validation_0-auc:0.96509	validation_1-auc:0.82873
[37]	validation_0-auc:0.96556	validation_1-auc:0.82905
[38]	validation_0-auc:0.96593	validation_1-auc:0.82950
[39]	validation_0-auc:0.96635	validation_1-auc:0.82942
[40]	validation_0-auc:0.96714	validation_1-auc:0.82938
[41]	validation_0-auc:0.96805	validation_1-auc:0.82933
[42]	validation_0-auc:0.96832	validation_1-auc:0.82917
[43]	validation_0-auc:0.96885	validation_1-auc:0.82949
[44]	validation_0-auc:0.96932	validation_1-auc:0.82951
 34%|███▍      | 17/50 [04:09<07:46, 14.15s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83474	validation_1-auc:0.80815
[1]	validation_0-auc:0.84362	validation_1-auc:0.81039
[2]	validation_0-auc:0.85153	validation_1-auc:0.81546
[3]	validation_0-auc:0.85875	validation_1-auc:0.81536
[4]	validation_0-auc:0.86868	validation_1-auc:0.81750
[5]	validation_0-auc:0.87375	validation_1-auc:0.81910
[6]	validation_0-auc:0.88064	validation_1-auc:0.81975
[7]	validation_0-auc:0.88611	validation_1-auc:0.82023
[8]	validation_0-auc:0.89032	validation_1-auc:0.82136
[9]	validation_0-auc:0.89870	validation_1-auc:0.82013
[10]	validation_0-auc:0.90218	validation_1-auc:0.82145
[11]	validation_0-auc:0.91014	validation_1-auc:0.82105
[12]	validation_0-auc:0.91602	validation_1-auc:0.82047
[13]	validation_0-auc:0.92060	validation_1-auc:0.82170
[14]	validation_0-auc:0.92176	validation_1-auc:0.82336
[15]	validation_0-auc:0.92530	validation_1-auc:0.82398
[16]	validation_0-auc:0.92697	validation_1-auc:0.82447
[17]	validation_0-auc:0.92897	validation_1-auc:0.82373
[18]	validation_0-auc:0.93132	validation_1-auc:0.82264
[19]	validation_0-auc:0.93409	validation_1-auc:0.82438
[20]	validation_0-auc:0.93723	validation_1-auc:0.82504
[21]	validation_0-auc:0.94003	validation_1-auc:0.82549
[22]	validation_0-auc:0.94352	validation_1-auc:0.82583
[23]	validation_0-auc:0.94573	validation_1-auc:0.82517
[24]	validation_0-auc:0.94870	validation_1-auc:0.82381
[25]	validation_0-auc:0.95098	validation_1-auc:0.82338
[26]	validation_0-auc:0.95274	validation_1-auc:0.82296
[27]	validation_0-auc:0.95455	validation_1-auc:0.82331
[28]	validation_0-auc:0.95605	validation_1-auc:0.82280
[29]	validation_0-auc:0.95760	validation_1-auc:0.82301
[30]	validation_0-auc:0.95912	validation_1-auc:0.82264
[31]	validation_0-auc:0.96025	validation_1-auc:0.82291
[32]	validation_0-auc:0.96115	validation_1-auc:0.82336
[33]	validation_0-auc:0.96222	validation_1-auc:0.82306
[34]	validation_0-auc:0.96281	validation_1-auc:0.82332
[35]	validation_0-auc:0.96351	validation_1-auc:0.82311
[36]	validation_0-auc:0.96397	validation_1-auc:0.82329
[37]	validation_0-auc:0.96421	validation_1-auc:0.82351
[38]	validation_0-auc:0.96467	validation_1-auc:0.82386
[39]	validation_0-auc:0.96495	validation_1-auc:0.82351
[40]	validation_0-auc:0.96558	validation_1-auc:0.82335
[41]	validation_0-auc:0.96651	validation_1-auc:0.82324
[42]	validation_0-auc:0.96687	validation_1-auc:0.82306
[43]	validation_0-auc:0.96768	validation_1-auc:0.82301
[44]	validation_0-auc:0.96805	validation_1-auc:0.82321
[45]	validation_0-auc:0.96841	validation_1-auc:0.82299
[46]	validation_0-auc:0.96905	validation_1-auc:0.82280
[47]	validation_0-auc:0.96920	validation_1-auc:0.82298
[48]	validation_0-auc:0.96942	validation_1-auc:0.82265
[49]	validation_0-auc:0.96985	validation_1-auc:0.82250
[50]	validation_0-auc:0.97001	validation_1-auc:0.82218
[51]	validation_0-auc:0.97019	validation_1-auc:0.82215
[52]	validation_0-auc:0.97015	validation_1-auc:0.82219
 34%|███▍      | 17/50 [04:14<07:46, 14.15s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83782	validation_1-auc:0.80956
[1]	validation_0-auc:0.84604	validation_1-auc:0.81262
[2]	validation_0-auc:0.85327	validation_1-auc:0.81956
[3]	validation_0-auc:0.86165	validation_1-auc:0.82438
[4]	validation_0-auc:0.87025	validation_1-auc:0.82745
[5]	validation_0-auc:0.87353	validation_1-auc:0.82820
[6]	validation_0-auc:0.87767	validation_1-auc:0.82876
[7]	validation_0-auc:0.88079	validation_1-auc:0.82947
[8]	validation_0-auc:0.88364	validation_1-auc:0.82900
[9]	validation_0-auc:0.89315	validation_1-auc:0.82935
[10]	validation_0-auc:0.89650	validation_1-auc:0.82599
[11]	validation_0-auc:0.90130	validation_1-auc:0.82799
[12]	validation_0-auc:0.90885	validation_1-auc:0.82969
[13]	validation_0-auc:0.91396	validation_1-auc:0.83063
[14]	validation_0-auc:0.91501	validation_1-auc:0.83214
[15]	validation_0-auc:0.91849	validation_1-auc:0.83249
[16]	validation_0-auc:0.92252	validation_1-auc:0.83378
[17]	validation_0-auc:0.92794	validation_1-auc:0.83587
[18]	validation_0-auc:0.93042	validation_1-auc:0.83324
[19]	validation_0-auc:0.93503	validation_1-auc:0.83354
[20]	validation_0-auc:0.93810	validation_1-auc:0.83381
[21]	validation_0-auc:0.94053	validation_1-auc:0.83302
[22]	validation_0-auc:0.94335	validation_1-auc:0.83416
[23]	validation_0-auc:0.94586	validation_1-auc:0.83299
[24]	validation_0-auc:0.94842	validation_1-auc:0.83265
[25]	validation_0-auc:0.94982	validation_1-auc:0.83335
[26]	validation_0-auc:0.95190	validation_1-auc:0.83410
[27]	validation_0-auc:0.95351	validation_1-auc:0.83417
[28]	validation_0-auc:0.95498	validation_1-auc:0.83301
[29]	validation_0-auc:0.95645	validation_1-auc:0.83288
[30]	validation_0-auc:0.95725	validation_1-auc:0.83319
[31]	validation_0-auc:0.95854	validation_1-auc:0.83290
[32]	validation_0-auc:0.95911	validation_1-auc:0.83281
[33]	validation_0-auc:0.96012	validation_1-auc:0.83324
[34]	validation_0-auc:0.96082	validation_1-auc:0.83339
[35]	validation_0-auc:0.96140	validation_1-auc:0.83291
[36]	validation_0-auc:0.96232	validation_1-auc:0.83242
[37]	validation_0-auc:0.96252	validation_1-auc:0.83260
[38]	validation_0-auc:0.96341	validation_1-auc:0.83218
[39]	validation_0-auc:0.96378	validation_1-auc:0.83213
[40]	validation_0-auc:0.96398	validation_1-auc:0.83214
[41]	validation_0-auc:0.96438	validation_1-auc:0.83197
[42]	validation_0-auc:0.96509	validation_1-auc:0.83212
[43]	validation_0-auc:0.96549	validation_1-auc:0.83186
[44]	validation_0-auc:0.96570	validation_1-auc:0.83206
[45]	validation_0-auc:0.96579	validation_1-auc:0.83197
[46]	validation_0-auc:0.96598	validation_1-auc:0.83152
 36%|███▌      | 18/50 [04:19<07:34, 14.20s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83598	validation_1-auc:0.81211
[1]	validation_0-auc:0.84139	validation_1-auc:0.81284
[2]	validation_0-auc:0.84525	validation_1-auc:0.81352
[3]	validation_0-auc:0.85191	validation_1-auc:0.81493
[4]	validation_0-auc:0.85417	validation_1-auc:0.81488
[5]	validation_0-auc:0.85774	validation_1-auc:0.81651
[6]	validation_0-auc:0.86429	validation_1-auc:0.81821
[7]	validation_0-auc:0.86620	validation_1-auc:0.81916
[8]	validation_0-auc:0.86785	validation_1-auc:0.81985
[9]	validation_0-auc:0.87467	validation_1-auc:0.82682
[10]	validation_0-auc:0.87784	validation_1-auc:0.82756
[11]	validation_0-auc:0.88461	validation_1-auc:0.83199
[12]	validation_0-auc:0.88834	validation_1-auc:0.83212
[13]	validation_0-auc:0.89232	validation_1-auc:0.83464
[14]	validation_0-auc:0.89618	validation_1-auc:0.83587
[15]	validation_0-auc:0.89891	validation_1-auc:0.83631
[16]	validation_0-auc:0.90180	validation_1-auc:0.83571
[17]	validation_0-auc:0.90415	validation_1-auc:0.83653
[18]	validation_0-auc:0.90612	validation_1-auc:0.83609
[19]	validation_0-auc:0.90924	validation_1-auc:0.83618
[20]	validation_0-auc:0.91152	validation_1-auc:0.83641
[21]	validation_0-auc:0.91273	validation_1-auc:0.83608
[22]	validation_0-auc:0.91505	validation_1-auc:0.83581
[23]	validation_0-auc:0.91784	validation_1-auc:0.83489
[24]	validation_0-auc:0.91994	validation_1-auc:0.83411
[25]	validation_0-auc:0.92157	validation_1-auc:0.83438
[26]	validation_0-auc:0.92338	validation_1-auc:0.83394
[27]	validation_0-auc:0.92577	validation_1-auc:0.83321
[28]	validation_0-auc:0.92766	validation_1-auc:0.83378
[29]	validation_0-auc:0.92923	validation_1-auc:0.83380
[30]	validation_0-auc:0.93077	validation_1-auc:0.83381
[31]	validation_0-auc:0.93233	validation_1-auc:0.83391
[32]	validation_0-auc:0.93413	validation_1-auc:0.83402
[33]	validation_0-auc:0.93575	validation_1-auc:0.83397
[34]	validation_0-auc:0.93730	validation_1-auc:0.83378
[35]	validation_0-auc:0.93814	validation_1-auc:0.83384
[36]	validation_0-auc:0.93888	validation_1-auc:0.83400
[37]	validation_0-auc:0.94010	validation_1-auc:0.83424
[38]	validation_0-auc:0.94058	validation_1-auc:0.83395
[39]	validation_0-auc:0.94102	validation_1-auc:0.83384
[40]	validation_0-auc:0.94133	validation_1-auc:0.83409
[41]	validation_0-auc:0.94200	validation_1-auc:0.83417
[42]	validation_0-auc:0.94270	validation_1-auc:0.83432
[43]	validation_0-auc:0.94304	validation_1-auc:0.83445
[44]	validation_0-auc:0.94334	validation_1-auc:0.83458
[45]	validation_0-auc:0.94355	validation_1-auc:0.83467
[46]	validation_0-auc:0.94395	validation_1-auc:0.83498
[47]	validation_0-auc:0.94435	validation_1-auc:0.83497
 36%|███▌      | 18/50 [04:23<07:34, 14.20s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83262	validation_1-auc:0.80947
[1]	validation_0-auc:0.83718	validation_1-auc:0.81033
[2]	validation_0-auc:0.84077	validation_1-auc:0.81144
[3]	validation_0-auc:0.84835	validation_1-auc:0.81410
[4]	validation_0-auc:0.85452	validation_1-auc:0.81828
[5]	validation_0-auc:0.85994	validation_1-auc:0.82032
[6]	validation_0-auc:0.86633	validation_1-auc:0.82239
[7]	validation_0-auc:0.87190	validation_1-auc:0.82344
[8]	validation_0-auc:0.87455	validation_1-auc:0.82421
[9]	validation_0-auc:0.88175	validation_1-auc:0.82495
[10]	validation_0-auc:0.88374	validation_1-auc:0.82488
[11]	validation_0-auc:0.89034	validation_1-auc:0.82554
[12]	validation_0-auc:0.89296	validation_1-auc:0.82616
[13]	validation_0-auc:0.89684	validation_1-auc:0.82855
[14]	validation_0-auc:0.90043	validation_1-auc:0.82959
[15]	validation_0-auc:0.90249	validation_1-auc:0.82929
[16]	validation_0-auc:0.90471	validation_1-auc:0.82988
[17]	validation_0-auc:0.90616	validation_1-auc:0.82939
[18]	validation_0-auc:0.90938	validation_1-auc:0.83059
[19]	validation_0-auc:0.91158	validation_1-auc:0.83107
[20]	validation_0-auc:0.91341	validation_1-auc:0.83184
[21]	validation_0-auc:0.91613	validation_1-auc:0.83283
[22]	validation_0-auc:0.91776	validation_1-auc:0.83178
[23]	validation_0-auc:0.92009	validation_1-auc:0.83164
[24]	validation_0-auc:0.92255	validation_1-auc:0.83140
[25]	validation_0-auc:0.92399	validation_1-auc:0.83138
[26]	validation_0-auc:0.92589	validation_1-auc:0.83059
[27]	validation_0-auc:0.92775	validation_1-auc:0.82970
[28]	validation_0-auc:0.92898	validation_1-auc:0.82943
[29]	validation_0-auc:0.93071	validation_1-auc:0.83004
[30]	validation_0-auc:0.93198	validation_1-auc:0.83023
[31]	validation_0-auc:0.93347	validation_1-auc:0.83021
[32]	validation_0-auc:0.93461	validation_1-auc:0.82982
[33]	validation_0-auc:0.93628	validation_1-auc:0.82988
[34]	validation_0-auc:0.93717	validation_1-auc:0.82957
[35]	validation_0-auc:0.93799	validation_1-auc:0.82898
[36]	validation_0-auc:0.93871	validation_1-auc:0.82907
[37]	validation_0-auc:0.93898	validation_1-auc:0.82932
[38]	validation_0-auc:0.93982	validation_1-auc:0.82955
[39]	validation_0-auc:0.94052	validation_1-auc:0.82946
[40]	validation_0-auc:0.94098	validation_1-auc:0.82980
[41]	validation_0-auc:0.94216	validation_1-auc:0.82979
[42]	validation_0-auc:0.94286	validation_1-auc:0.82964
[43]	validation_0-auc:0.94345	validation_1-auc:0.82936
[44]	validation_0-auc:0.94387	validation_1-auc:0.82915
[45]	validation_0-auc:0.94448	validation_1-auc:0.82851
[46]	validation_0-auc:0.94477	validation_1-auc:0.82872
[47]	validation_0-auc:0.94516	validation_1-auc:0.82856
[48]	validation_0-auc:0.94604	validation_1-auc:0.82791
[49]	validation_0-auc:0.94753	validation_1-auc:0.82782
[50]	validation_0-auc:0.94798	validation_1-auc:0.82735
 36%|███▌      | 18/50 [04:28<07:34, 14.20s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83145	validation_1-auc:0.80971
[1]	validation_0-auc:0.84004	validation_1-auc:0.81301
[2]	validation_0-auc:0.85031	validation_1-auc:0.82270
[3]	validation_0-auc:0.85536	validation_1-auc:0.82559
[4]	validation_0-auc:0.85981	validation_1-auc:0.82637
[5]	validation_0-auc:0.86338	validation_1-auc:0.82570
[6]	validation_0-auc:0.86604	validation_1-auc:0.82690
[7]	validation_0-auc:0.86953	validation_1-auc:0.82792
[8]	validation_0-auc:0.87157	validation_1-auc:0.82880
[9]	validation_0-auc:0.87938	validation_1-auc:0.83143
[10]	validation_0-auc:0.88048	validation_1-auc:0.82855
[11]	validation_0-auc:0.88288	validation_1-auc:0.82937
[12]	validation_0-auc:0.88654	validation_1-auc:0.83155
[13]	validation_0-auc:0.89046	validation_1-auc:0.83332
[14]	validation_0-auc:0.89253	validation_1-auc:0.83354
[15]	validation_0-auc:0.89612	validation_1-auc:0.83578
[16]	validation_0-auc:0.89973	validation_1-auc:0.83704
[17]	validation_0-auc:0.90182	validation_1-auc:0.83795
[18]	validation_0-auc:0.90365	validation_1-auc:0.83830
[19]	validation_0-auc:0.90690	validation_1-auc:0.83806
[20]	validation_0-auc:0.90994	validation_1-auc:0.83795
[21]	validation_0-auc:0.91259	validation_1-auc:0.83790
[22]	validation_0-auc:0.91489	validation_1-auc:0.83757
[23]	validation_0-auc:0.91771	validation_1-auc:0.83761
[24]	validation_0-auc:0.91973	validation_1-auc:0.83760
[25]	validation_0-auc:0.92150	validation_1-auc:0.83815
[26]	validation_0-auc:0.92364	validation_1-auc:0.83820
[27]	validation_0-auc:0.92530	validation_1-auc:0.83808
[28]	validation_0-auc:0.92703	validation_1-auc:0.83853
[29]	validation_0-auc:0.92810	validation_1-auc:0.83794
[30]	validation_0-auc:0.92943	validation_1-auc:0.83757
[31]	validation_0-auc:0.93082	validation_1-auc:0.83768
[32]	validation_0-auc:0.93192	validation_1-auc:0.83734
[33]	validation_0-auc:0.93270	validation_1-auc:0.83687
[34]	validation_0-auc:0.93362	validation_1-auc:0.83684
[35]	validation_0-auc:0.93454	validation_1-auc:0.83729
[36]	validation_0-auc:0.93535	validation_1-auc:0.83755
[37]	validation_0-auc:0.93644	validation_1-auc:0.83743
[38]	validation_0-auc:0.93748	validation_1-auc:0.83758
[39]	validation_0-auc:0.93812	validation_1-auc:0.83739
[40]	validation_0-auc:0.93833	validation_1-auc:0.83781
[41]	validation_0-auc:0.93913	validation_1-auc:0.83731
[42]	validation_0-auc:0.93937	validation_1-auc:0.83751
[43]	validation_0-auc:0.93953	validation_1-auc:0.83772
[44]	validation_0-auc:0.93984	validation_1-auc:0.83758
[45]	validation_0-auc:0.94030	validation_1-auc:0.83754
[46]	validation_0-auc:0.94070	validation_1-auc:0.83700
[47]	validation_0-auc:0.94129	validation_1-auc:0.83700
[48]	validation_0-auc:0.94162	validation_1-auc:0.83683
[49]	validation_0-auc:0.94247	validation_1-auc:0.83701
[50]	validation_0-auc:0.94291	validation_1-auc:0.83700
[51]	validation_0-auc:0.94319	validation_1-auc:0.83710
[52]	validation_0-auc:0.94334	validation_1-auc:0.83710
[53]	validation_0-auc:0.94377	validation_1-auc:0.83709
[54]	validation_0-auc:0.94419	validation_1-auc:0.83683
[55]	validation_0-auc:0.94442	validation_1-auc:0.83702
[56]	validation_0-auc:0.94505	validation_1-auc:0.83694
[57]	validation_0-auc:0.94540	validation_1-auc:0.83659
[58]	validation_0-auc:0.94608	validation_1-auc:0.83659
 38%|███▊      | 19/50 [04:33<07:17, 14.11s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82911	validation_1-auc:0.81392
[1]	validation_0-auc:0.83559	validation_1-auc:0.81493
[2]	validation_0-auc:0.84452	validation_1-auc:0.81955
[3]	validation_0-auc:0.84682	validation_1-auc:0.82012
[4]	validation_0-auc:0.84910	validation_1-auc:0.81861
[5]	validation_0-auc:0.85194	validation_1-auc:0.82183
[6]	validation_0-auc:0.85364	validation_1-auc:0.82170
[7]	validation_0-auc:0.85465	validation_1-auc:0.82217
[8]	validation_0-auc:0.85842	validation_1-auc:0.82522
[9]	validation_0-auc:0.86349	validation_1-auc:0.82972
[10]	validation_0-auc:0.86379	validation_1-auc:0.83019
[11]	validation_0-auc:0.86434	validation_1-auc:0.82941
[12]	validation_0-auc:0.86851	validation_1-auc:0.83285
[13]	validation_0-auc:0.87132	validation_1-auc:0.83453
[14]	validation_0-auc:0.87306	validation_1-auc:0.83636
[15]	validation_0-auc:0.87485	validation_1-auc:0.83709
[16]	validation_0-auc:0.87588	validation_1-auc:0.83723
[17]	validation_0-auc:0.87686	validation_1-auc:0.83771
[18]	validation_0-auc:0.87732	validation_1-auc:0.83784
[19]	validation_0-auc:0.87847	validation_1-auc:0.83862
[20]	validation_0-auc:0.87944	validation_1-auc:0.83907
[21]	validation_0-auc:0.88057	validation_1-auc:0.83913
[22]	validation_0-auc:0.88223	validation_1-auc:0.83946
[23]	validation_0-auc:0.88296	validation_1-auc:0.84002
[24]	validation_0-auc:0.88392	validation_1-auc:0.84024
[25]	validation_0-auc:0.88482	validation_1-auc:0.84022
[26]	validation_0-auc:0.88589	validation_1-auc:0.84133
[27]	validation_0-auc:0.88780	validation_1-auc:0.84150
[28]	validation_0-auc:0.88902	validation_1-auc:0.84215
[29]	validation_0-auc:0.89021	validation_1-auc:0.84152
[30]	validation_0-auc:0.89109	validation_1-auc:0.84207
[31]	validation_0-auc:0.89247	validation_1-auc:0.84243
[32]	validation_0-auc:0.89340	validation_1-auc:0.84284
[33]	validation_0-auc:0.89432	validation_1-auc:0.84322
[34]	validation_0-auc:0.89508	validation_1-auc:0.84297
[35]	validation_0-auc:0.89536	validation_1-auc:0.84292
[36]	validation_0-auc:0.89574	validation_1-auc:0.84313
[37]	validation_0-auc:0.89608	validation_1-auc:0.84325
[38]	validation_0-auc:0.89656	validation_1-auc:0.84323
[39]	validation_0-auc:0.89746	validation_1-auc:0.84320
[40]	validation_0-auc:0.89769	validation_1-auc:0.84337
[41]	validation_0-auc:0.89852	validation_1-auc:0.84338
[42]	validation_0-auc:0.89908	validation_1-auc:0.84385
[43]	validation_0-auc:0.89927	validation_1-auc:0.84358
[44]	validation_0-auc:0.90004	validation_1-auc:0.84370
[45]	validation_0-auc:0.90026	validation_1-auc:0.84348
[46]	validation_0-auc:0.90056	validation_1-auc:0.84365
[47]	validation_0-auc:0.90155	validation_1-auc:0.84355
[48]	validation_0-auc:0.90198	validation_1-auc:0.84363
[49]	validation_0-auc:0.90233	validation_1-auc:0.84365
[50]	validation_0-auc:0.90276	validation_1-auc:0.84398
[51]	validation_0-auc:0.90297	validation_1-auc:0.84400
[52]	validation_0-auc:0.90340	validation_1-auc:0.84389
[53]	validation_0-auc:0.90355	validation_1-auc:0.84389
[54]	validation_0-auc:0.90430	validation_1-auc:0.84355
[55]	validation_0-auc:0.90463	validation_1-auc:0.84355
[56]	validation_0-auc:0.90519	validation_1-auc:0.84346
[57]	validation_0-auc:0.90531	validation_1-auc:0.84356
[58]	validation_0-auc:0.90550	validation_1-auc:0.84363
[59]	validation_0-auc:0.90608	validation_1-auc:0.84338
[60]	validation_0-auc:0.90627	validation_1-auc:0.84348
[61]	validation_0-auc:0.90674	validation_1-auc:0.84308
[62]	validation_0-auc:0.90691	validation_1-auc:0.84278
[63]	validation_0-auc:0.90774	validation_1-auc:0.84322
[64]	validation_0-auc:0.90819	validation_1-auc:0.84318
[65]	validation_0-auc:0.90833	validation_1-auc:0.84301
[66]	validation_0-auc:0.90849	validation_1-auc:0.84294
[67]	validation_0-auc:0.90870	validation_1-auc:0.84292
[68]	validation_0-auc:0.90878	validation_1-auc:0.84299
[69]	validation_0-auc:0.90900	validation_1-auc:0.84294
[70]	validation_0-auc:0.91001	validation_1-auc:0.84272
[71]	validation_0-auc:0.91015	validation_1-auc:0.84266
[72]	validation_0-auc:0.91098	validation_1-auc:0.84263
[73]	validation_0-auc:0.91115	validation_1-auc:0.84269
[74]	validation_0-auc:0.91123	validation_1-auc:0.84272
[75]	validation_0-auc:0.91173	validation_1-auc:0.84240
[76]	validation_0-auc:0.91239	validation_1-auc:0.84289
[77]	validation_0-auc:0.91254	validation_1-auc:0.84291
[78]	validation_0-auc:0.91267	validation_1-auc:0.84295
[79]	validation_0-auc:0.91283	validation_1-auc:0.84282
[80]	validation_0-auc:0.91294	validation_1-auc:0.84277
[81]	validation_0-auc:0.91358	validation_1-auc:0.84299
 38%|███▊      | 19/50 [04:38<07:17, 14.11s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82565	validation_1-auc:0.80783
[1]	validation_0-auc:0.83248	validation_1-auc:0.81471
[2]	validation_0-auc:0.83869	validation_1-auc:0.81776
[3]	validation_0-auc:0.84145	validation_1-auc:0.82035
[4]	validation_0-auc:0.84909	validation_1-auc:0.82293
[5]	validation_0-auc:0.84966	validation_1-auc:0.82327
[6]	validation_0-auc:0.85274	validation_1-auc:0.82461
[7]	validation_0-auc:0.85586	validation_1-auc:0.82599
[8]	validation_0-auc:0.85841	validation_1-auc:0.82751
[9]	validation_0-auc:0.86262	validation_1-auc:0.82908
[10]	validation_0-auc:0.86464	validation_1-auc:0.82921
[11]	validation_0-auc:0.86594	validation_1-auc:0.82902
[12]	validation_0-auc:0.87008	validation_1-auc:0.83039
[13]	validation_0-auc:0.87375	validation_1-auc:0.83189
[14]	validation_0-auc:0.87456	validation_1-auc:0.83241
[15]	validation_0-auc:0.87718	validation_1-auc:0.83254
[16]	validation_0-auc:0.87898	validation_1-auc:0.83351
[17]	validation_0-auc:0.87970	validation_1-auc:0.83335
[18]	validation_0-auc:0.88113	validation_1-auc:0.83297
[19]	validation_0-auc:0.88292	validation_1-auc:0.83421
[20]	validation_0-auc:0.88421	validation_1-auc:0.83406
[21]	validation_0-auc:0.88540	validation_1-auc:0.83467
[22]	validation_0-auc:0.88653	validation_1-auc:0.83454
[23]	validation_0-auc:0.88781	validation_1-auc:0.83591
[24]	validation_0-auc:0.88943	validation_1-auc:0.83557
[25]	validation_0-auc:0.89023	validation_1-auc:0.83596
[26]	validation_0-auc:0.89105	validation_1-auc:0.83599
[27]	validation_0-auc:0.89219	validation_1-auc:0.83665
[28]	validation_0-auc:0.89304	validation_1-auc:0.83673
[29]	validation_0-auc:0.89423	validation_1-auc:0.83659
[30]	validation_0-auc:0.89506	validation_1-auc:0.83595
[31]	validation_0-auc:0.89587	validation_1-auc:0.83630
[32]	validation_0-auc:0.89704	validation_1-auc:0.83677
[33]	validation_0-auc:0.89765	validation_1-auc:0.83711
[34]	validation_0-auc:0.89792	validation_1-auc:0.83727
[35]	validation_0-auc:0.89860	validation_1-auc:0.83704
[36]	validation_0-auc:0.89918	validation_1-auc:0.83757
[37]	validation_0-auc:0.89940	validation_1-auc:0.83796
[38]	validation_0-auc:0.89969	validation_1-auc:0.83865
[39]	validation_0-auc:0.89982	validation_1-auc:0.83848
[40]	validation_0-auc:0.90007	validation_1-auc:0.83835
[41]	validation_0-auc:0.90045	validation_1-auc:0.83866
[42]	validation_0-auc:0.90078	validation_1-auc:0.83838
[43]	validation_0-auc:0.90187	validation_1-auc:0.83805
[44]	validation_0-auc:0.90270	validation_1-auc:0.83779
[45]	validation_0-auc:0.90302	validation_1-auc:0.83793
[46]	validation_0-auc:0.90379	validation_1-auc:0.83791
[47]	validation_0-auc:0.90487	validation_1-auc:0.83774
[48]	validation_0-auc:0.90515	validation_1-auc:0.83737
[49]	validation_0-auc:0.90589	validation_1-auc:0.83715
[50]	validation_0-auc:0.90661	validation_1-auc:0.83698
[51]	validation_0-auc:0.90729	validation_1-auc:0.83705
[52]	validation_0-auc:0.90763	validation_1-auc:0.83644
[53]	validation_0-auc:0.90783	validation_1-auc:0.83629
[54]	validation_0-auc:0.90800	validation_1-auc:0.83614
[55]	validation_0-auc:0.90824	validation_1-auc:0.83603
[56]	validation_0-auc:0.90827	validation_1-auc:0.83601
[57]	validation_0-auc:0.90880	validation_1-auc:0.83559
[58]	validation_0-auc:0.90920	validation_1-auc:0.83539
[59]	validation_0-auc:0.91063	validation_1-auc:0.83587
[60]	validation_0-auc:0.91104	validation_1-auc:0.83601
[61]	validation_0-auc:0.91139	validation_1-auc:0.83607
[62]	validation_0-auc:0.91198	validation_1-auc:0.83606
[63]	validation_0-auc:0.91227	validation_1-auc:0.83597
[64]	validation_0-auc:0.91264	validation_1-auc:0.83599
[65]	validation_0-auc:0.91290	validation_1-auc:0.83595
[66]	validation_0-auc:0.91300	validation_1-auc:0.83598
[67]	validation_0-auc:0.91325	validation_1-auc:0.83587
[68]	validation_0-auc:0.91336	validation_1-auc:0.83598
[69]	validation_0-auc:0.91350	validation_1-auc:0.83609
[70]	validation_0-auc:0.91371	validation_1-auc:0.83551
[71]	validation_0-auc:0.91387	validation_1-auc:0.83541
 38%|███▊      | 19/50 [04:42<07:17, 14.11s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82259	validation_1-auc:0.81021
[1]	validation_0-auc:0.83806	validation_1-auc:0.82499
[2]	validation_0-auc:0.84435	validation_1-auc:0.82971
[3]	validation_0-auc:0.84654	validation_1-auc:0.82948
[4]	validation_0-auc:0.85052	validation_1-auc:0.83251
[5]	validation_0-auc:0.85173	validation_1-auc:0.83282
[6]	validation_0-auc:0.85398	validation_1-auc:0.83317
[7]	validation_0-auc:0.85485	validation_1-auc:0.83376
[8]	validation_0-auc:0.85576	validation_1-auc:0.83431
[9]	validation_0-auc:0.85922	validation_1-auc:0.83648
[10]	validation_0-auc:0.85918	validation_1-auc:0.83358
[11]	validation_0-auc:0.85940	validation_1-auc:0.83177
[12]	validation_0-auc:0.86530	validation_1-auc:0.83459
[13]	validation_0-auc:0.86830	validation_1-auc:0.83609
[14]	validation_0-auc:0.87048	validation_1-auc:0.83915
[15]	validation_0-auc:0.87234	validation_1-auc:0.84051
[16]	validation_0-auc:0.87383	validation_1-auc:0.84090
[17]	validation_0-auc:0.87647	validation_1-auc:0.84252
[18]	validation_0-auc:0.87715	validation_1-auc:0.84127
[19]	validation_0-auc:0.87886	validation_1-auc:0.84270
[20]	validation_0-auc:0.88021	validation_1-auc:0.84289
[21]	validation_0-auc:0.88161	validation_1-auc:0.84319
[22]	validation_0-auc:0.88296	validation_1-auc:0.84366
[23]	validation_0-auc:0.88411	validation_1-auc:0.84323
[24]	validation_0-auc:0.88585	validation_1-auc:0.84363
[25]	validation_0-auc:0.88711	validation_1-auc:0.84387
[26]	validation_0-auc:0.88880	validation_1-auc:0.84392
[27]	validation_0-auc:0.88983	validation_1-auc:0.84391
[28]	validation_0-auc:0.89056	validation_1-auc:0.84381
[29]	validation_0-auc:0.89204	validation_1-auc:0.84364
[30]	validation_0-auc:0.89324	validation_1-auc:0.84343
[31]	validation_0-auc:0.89414	validation_1-auc:0.84344
[32]	validation_0-auc:0.89454	validation_1-auc:0.84389
[33]	validation_0-auc:0.89493	validation_1-auc:0.84410
[34]	validation_0-auc:0.89543	validation_1-auc:0.84454
[35]	validation_0-auc:0.89596	validation_1-auc:0.84503
[36]	validation_0-auc:0.89637	validation_1-auc:0.84531
[37]	validation_0-auc:0.89683	validation_1-auc:0.84529
[38]	validation_0-auc:0.89773	validation_1-auc:0.84482
[39]	validation_0-auc:0.89786	validation_1-auc:0.84504
[40]	validation_0-auc:0.89818	validation_1-auc:0.84523
[41]	validation_0-auc:0.89930	validation_1-auc:0.84507
[42]	validation_0-auc:0.90017	validation_1-auc:0.84527
[43]	validation_0-auc:0.90057	validation_1-auc:0.84528
[44]	validation_0-auc:0.90141	validation_1-auc:0.84509
[45]	validation_0-auc:0.90169	validation_1-auc:0.84521
[46]	validation_0-auc:0.90220	validation_1-auc:0.84532
[47]	validation_0-auc:0.90236	validation_1-auc:0.84522
[48]	validation_0-auc:0.90295	validation_1-auc:0.84529
[49]	validation_0-auc:0.90362	validation_1-auc:0.84488
[50]	validation_0-auc:0.90376	validation_1-auc:0.84472
[51]	validation_0-auc:0.90416	validation_1-auc:0.84464
[52]	validation_0-auc:0.90448	validation_1-auc:0.84476
[53]	validation_0-auc:0.90491	validation_1-auc:0.84486
[54]	validation_0-auc:0.90505	validation_1-auc:0.84480
[55]	validation_0-auc:0.90555	validation_1-auc:0.84473
[56]	validation_0-auc:0.90587	validation_1-auc:0.84461
[57]	validation_0-auc:0.90624	validation_1-auc:0.84477
[58]	validation_0-auc:0.90682	validation_1-auc:0.84438
[59]	validation_0-auc:0.90711	validation_1-auc:0.84422
[60]	validation_0-auc:0.90727	validation_1-auc:0.84401
[61]	validation_0-auc:0.90742	validation_1-auc:0.84416
[62]	validation_0-auc:0.90747	validation_1-auc:0.84409
[63]	validation_0-auc:0.90768	validation_1-auc:0.84435
[64]	validation_0-auc:0.90833	validation_1-auc:0.84457
[65]	validation_0-auc:0.90869	validation_1-auc:0.84428
[66]	validation_0-auc:0.90879	validation_1-auc:0.84405
[67]	validation_0-auc:0.90924	validation_1-auc:0.84406
[68]	validation_0-auc:0.90935	validation_1-auc:0.84386
[69]	validation_0-auc:0.90960	validation_1-auc:0.84371
[70]	validation_0-auc:0.90999	validation_1-auc:0.84362
[71]	validation_0-auc:0.91003	validation_1-auc:0.84353
[72]	validation_0-auc:0.91019	validation_1-auc:0.84321
[73]	validation_0-auc:0.91105	validation_1-auc:0.84337
[74]	validation_0-auc:0.91172	validation_1-auc:0.84325
[75]	validation_0-auc:0.91190	validation_1-auc:0.84310
 40%|████      | 20/50 [04:47<06:56, 13.89s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83026	validation_1-auc:0.81356
[1]	validation_0-auc:0.83578	validation_1-auc:0.81591
[2]	validation_0-auc:0.83997	validation_1-auc:0.81772
[3]	validation_0-auc:0.84435	validation_1-auc:0.81843
[4]	validation_0-auc:0.84942	validation_1-auc:0.82032
[5]	validation_0-auc:0.85249	validation_1-auc:0.82200
[6]	validation_0-auc:0.85500	validation_1-auc:0.82434
[7]	validation_0-auc:0.85597	validation_1-auc:0.82450
[8]	validation_0-auc:0.85681	validation_1-auc:0.82424
[9]	validation_0-auc:0.86193	validation_1-auc:0.82881
[10]	validation_0-auc:0.86314	validation_1-auc:0.82935
[11]	validation_0-auc:0.86359	validation_1-auc:0.82747
[12]	validation_0-auc:0.86806	validation_1-auc:0.83264
[13]	validation_0-auc:0.87037	validation_1-auc:0.83391
[14]	validation_0-auc:0.87198	validation_1-auc:0.83593
[15]	validation_0-auc:0.87447	validation_1-auc:0.83700
[16]	validation_0-auc:0.87480	validation_1-auc:0.83756
[17]	validation_0-auc:0.87670	validation_1-auc:0.83796
[18]	validation_0-auc:0.87654	validation_1-auc:0.83816
[19]	validation_0-auc:0.87782	validation_1-auc:0.83904
[20]	validation_0-auc:0.87894	validation_1-auc:0.83899
[21]	validation_0-auc:0.87881	validation_1-auc:0.83894
[22]	validation_0-auc:0.88032	validation_1-auc:0.83988
[23]	validation_0-auc:0.88147	validation_1-auc:0.84025
[24]	validation_0-auc:0.88225	validation_1-auc:0.84037
[25]	validation_0-auc:0.88254	validation_1-auc:0.84114
[26]	validation_0-auc:0.88257	validation_1-auc:0.84127
[27]	validation_0-auc:0.88426	validation_1-auc:0.84117
[28]	validation_0-auc:0.88519	validation_1-auc:0.84114
[29]	validation_0-auc:0.88678	validation_1-auc:0.84174
[30]	validation_0-auc:0.88738	validation_1-auc:0.84156
[31]	validation_0-auc:0.88844	validation_1-auc:0.84159
[32]	validation_0-auc:0.88918	validation_1-auc:0.84181
[33]	validation_0-auc:0.88984	validation_1-auc:0.84201
[34]	validation_0-auc:0.89050	validation_1-auc:0.84216
[35]	validation_0-auc:0.89137	validation_1-auc:0.84286
[36]	validation_0-auc:0.89271	validation_1-auc:0.84325
[37]	validation_0-auc:0.89359	validation_1-auc:0.84335
[38]	validation_0-auc:0.89431	validation_1-auc:0.84342
[39]	validation_0-auc:0.89513	validation_1-auc:0.84377
[40]	validation_0-auc:0.89590	validation_1-auc:0.84393
[41]	validation_0-auc:0.89662	validation_1-auc:0.84435
[42]	validation_0-auc:0.89757	validation_1-auc:0.84450
[43]	validation_0-auc:0.89803	validation_1-auc:0.84439
[44]	validation_0-auc:0.89871	validation_1-auc:0.84460
[45]	validation_0-auc:0.89923	validation_1-auc:0.84463
[46]	validation_0-auc:0.89948	validation_1-auc:0.84489
[47]	validation_0-auc:0.89989	validation_1-auc:0.84516
[48]	validation_0-auc:0.90047	validation_1-auc:0.84507
[49]	validation_0-auc:0.90139	validation_1-auc:0.84499
[50]	validation_0-auc:0.90187	validation_1-auc:0.84516
[51]	validation_0-auc:0.90233	validation_1-auc:0.84480
[52]	validation_0-auc:0.90248	validation_1-auc:0.84504
[53]	validation_0-auc:0.90282	validation_1-auc:0.84528
[54]	validation_0-auc:0.90337	validation_1-auc:0.84541
[55]	validation_0-auc:0.90424	validation_1-auc:0.84542
[56]	validation_0-auc:0.90435	validation_1-auc:0.84543
[57]	validation_0-auc:0.90529	validation_1-auc:0.84537
[58]	validation_0-auc:0.90559	validation_1-auc:0.84566
[59]	validation_0-auc:0.90581	validation_1-auc:0.84563
[60]	validation_0-auc:0.90633	validation_1-auc:0.84573
[61]	validation_0-auc:0.90663	validation_1-auc:0.84586
[62]	validation_0-auc:0.90708	validation_1-auc:0.84582
[63]	validation_0-auc:0.90728	validation_1-auc:0.84579
[64]	validation_0-auc:0.90761	validation_1-auc:0.84586
[65]	validation_0-auc:0.90797	validation_1-auc:0.84591
[66]	validation_0-auc:0.90815	validation_1-auc:0.84586
[67]	validation_0-auc:0.90860	validation_1-auc:0.84575
[68]	validation_0-auc:0.90898	validation_1-auc:0.84550
[69]	validation_0-auc:0.90935	validation_1-auc:0.84541
[70]	validation_0-auc:0.90956	validation_1-auc:0.84528
[71]	validation_0-auc:0.91000	validation_1-auc:0.84520
[72]	validation_0-auc:0.91005	validation_1-auc:0.84510
[73]	validation_0-auc:0.91019	validation_1-auc:0.84503
[74]	validation_0-auc:0.91033	validation_1-auc:0.84497
[75]	validation_0-auc:0.91056	validation_1-auc:0.84512
[76]	validation_0-auc:0.91069	validation_1-auc:0.84506
[77]	validation_0-auc:0.91082	validation_1-auc:0.84500
[78]	validation_0-auc:0.91118	validation_1-auc:0.84527
[79]	validation_0-auc:0.91144	validation_1-auc:0.84535
[80]	validation_0-auc:0.91159	validation_1-auc:0.84525
[81]	validation_0-auc:0.91183	validation_1-auc:0.84519
[82]	validation_0-auc:0.91203	validation_1-auc:0.84513
[83]	validation_0-auc:0.91219	validation_1-auc:0.84530
[84]	validation_0-auc:0.91240	validation_1-auc:0.84533
[85]	validation_0-auc:0.91269	validation_1-auc:0.84520
[86]	validation_0-auc:0.91286	validation_1-auc:0.84516
[87]	validation_0-auc:0.91317	validation_1-auc:0.84534
[88]	validation_0-auc:0.91346	validation_1-auc:0.84514
[89]	validation_0-auc:0.91357	validation_1-auc:0.84514
[90]	validation_0-auc:0.91394	validation_1-auc:0.84496
[91]	validation_0-auc:0.91415	validation_1-auc:0.84515
[92]	validation_0-auc:0.91442	validation_1-auc:0.84538
[93]	validation_0-auc:0.91454	validation_1-auc:0.84546
[94]	validation_0-auc:0.91495	validation_1-auc:0.84534
 40%|████      | 20/50 [04:52<06:56, 13.89s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82592	validation_1-auc:0.80753
[1]	validation_0-auc:0.83230	validation_1-auc:0.81245
[2]	validation_0-auc:0.83591	validation_1-auc:0.81382
[3]	validation_0-auc:0.83756	validation_1-auc:0.81503
[4]	validation_0-auc:0.84459	validation_1-auc:0.81841
[5]	validation_0-auc:0.84825	validation_1-auc:0.82094
[6]	validation_0-auc:0.85381	validation_1-auc:0.82506
[7]	validation_0-auc:0.85641	validation_1-auc:0.82534
[8]	validation_0-auc:0.85824	validation_1-auc:0.82583
[9]	validation_0-auc:0.86284	validation_1-auc:0.82928
[10]	validation_0-auc:0.86477	validation_1-auc:0.82977
[11]	validation_0-auc:0.86640	validation_1-auc:0.82876
[12]	validation_0-auc:0.86959	validation_1-auc:0.83046
[13]	validation_0-auc:0.87197	validation_1-auc:0.83116
[14]	validation_0-auc:0.87380	validation_1-auc:0.83237
[15]	validation_0-auc:0.87538	validation_1-auc:0.83260
[16]	validation_0-auc:0.87583	validation_1-auc:0.83303
[17]	validation_0-auc:0.87742	validation_1-auc:0.83341
[18]	validation_0-auc:0.87791	validation_1-auc:0.83301
[19]	validation_0-auc:0.88036	validation_1-auc:0.83321
[20]	validation_0-auc:0.88129	validation_1-auc:0.83316
[21]	validation_0-auc:0.88158	validation_1-auc:0.83217
[22]	validation_0-auc:0.88303	validation_1-auc:0.83308
[23]	validation_0-auc:0.88473	validation_1-auc:0.83313
[24]	validation_0-auc:0.88563	validation_1-auc:0.83379
[25]	validation_0-auc:0.88641	validation_1-auc:0.83550
[26]	validation_0-auc:0.88803	validation_1-auc:0.83580
[27]	validation_0-auc:0.88923	validation_1-auc:0.83648
[28]	validation_0-auc:0.89029	validation_1-auc:0.83650
[29]	validation_0-auc:0.89138	validation_1-auc:0.83677
[30]	validation_0-auc:0.89291	validation_1-auc:0.83608
[31]	validation_0-auc:0.89364	validation_1-auc:0.83657
[32]	validation_0-auc:0.89457	validation_1-auc:0.83706
[33]	validation_0-auc:0.89491	validation_1-auc:0.83728
[34]	validation_0-auc:0.89575	validation_1-auc:0.83766
[35]	validation_0-auc:0.89654	validation_1-auc:0.83786
[36]	validation_0-auc:0.89715	validation_1-auc:0.83810
[37]	validation_0-auc:0.89783	validation_1-auc:0.83751
[38]	validation_0-auc:0.89841	validation_1-auc:0.83711
[39]	validation_0-auc:0.89919	validation_1-auc:0.83749
[40]	validation_0-auc:0.89965	validation_1-auc:0.83773
[41]	validation_0-auc:0.90016	validation_1-auc:0.83767
[42]	validation_0-auc:0.90131	validation_1-auc:0.83752
[43]	validation_0-auc:0.90177	validation_1-auc:0.83780
[44]	validation_0-auc:0.90225	validation_1-auc:0.83759
[45]	validation_0-auc:0.90266	validation_1-auc:0.83805
[46]	validation_0-auc:0.90275	validation_1-auc:0.83797
[47]	validation_0-auc:0.90309	validation_1-auc:0.83796
[48]	validation_0-auc:0.90348	validation_1-auc:0.83802
[49]	validation_0-auc:0.90384	validation_1-auc:0.83821
[50]	validation_0-auc:0.90404	validation_1-auc:0.83807
[51]	validation_0-auc:0.90456	validation_1-auc:0.83817
[52]	validation_0-auc:0.90477	validation_1-auc:0.83781
[53]	validation_0-auc:0.90534	validation_1-auc:0.83746
[54]	validation_0-auc:0.90560	validation_1-auc:0.83761
[55]	validation_0-auc:0.90625	validation_1-auc:0.83761
[56]	validation_0-auc:0.90657	validation_1-auc:0.83792
[57]	validation_0-auc:0.90698	validation_1-auc:0.83775
[58]	validation_0-auc:0.90738	validation_1-auc:0.83793
[59]	validation_0-auc:0.90798	validation_1-auc:0.83768
[60]	validation_0-auc:0.90809	validation_1-auc:0.83761
[61]	validation_0-auc:0.90859	validation_1-auc:0.83748
[62]	validation_0-auc:0.90884	validation_1-auc:0.83755
[63]	validation_0-auc:0.90943	validation_1-auc:0.83740
[64]	validation_0-auc:0.90976	validation_1-auc:0.83727
[65]	validation_0-auc:0.91000	validation_1-auc:0.83699
[66]	validation_0-auc:0.91044	validation_1-auc:0.83715
[67]	validation_0-auc:0.91064	validation_1-auc:0.83691
[68]	validation_0-auc:0.91106	validation_1-auc:0.83673
[69]	validation_0-auc:0.91122	validation_1-auc:0.83669
[70]	validation_0-auc:0.91152	validation_1-auc:0.83657
[71]	validation_0-auc:0.91211	validation_1-auc:0.83653
[72]	validation_0-auc:0.91240	validation_1-auc:0.83640
[73]	validation_0-auc:0.91254	validation_1-auc:0.83628
[74]	validation_0-auc:0.91294	validation_1-auc:0.83626
[75]	validation_0-auc:0.91339	validation_1-auc:0.83578
[76]	validation_0-auc:0.91375	validation_1-auc:0.83597
[77]	validation_0-auc:0.91384	validation_1-auc:0.83589
[78]	validation_0-auc:0.91450	validation_1-auc:0.83593
[79]	validation_0-auc:0.91484	validation_1-auc:0.83587
 40%|████      | 20/50 [04:57<06:56, 13.89s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82348	validation_1-auc:0.81033
[1]	validation_0-auc:0.83793	validation_1-auc:0.82474
[2]	validation_0-auc:0.84183	validation_1-auc:0.82712
[3]	validation_0-auc:0.84579	validation_1-auc:0.82985
[4]	validation_0-auc:0.85068	validation_1-auc:0.83273
[5]	validation_0-auc:0.85210	validation_1-auc:0.83221
[6]	validation_0-auc:0.85386	validation_1-auc:0.83340
[7]	validation_0-auc:0.85646	validation_1-auc:0.83450
[8]	validation_0-auc:0.85724	validation_1-auc:0.83504
[9]	validation_0-auc:0.86074	validation_1-auc:0.83682
[10]	validation_0-auc:0.86218	validation_1-auc:0.83676
[11]	validation_0-auc:0.86235	validation_1-auc:0.83432
[12]	validation_0-auc:0.86552	validation_1-auc:0.83612
[13]	validation_0-auc:0.86681	validation_1-auc:0.83780
[14]	validation_0-auc:0.86768	validation_1-auc:0.83881
[15]	validation_0-auc:0.86878	validation_1-auc:0.83905
[16]	validation_0-auc:0.86974	validation_1-auc:0.83944
[17]	validation_0-auc:0.87099	validation_1-auc:0.84062
[18]	validation_0-auc:0.87130	validation_1-auc:0.84037
[19]	validation_0-auc:0.87352	validation_1-auc:0.84168
[20]	validation_0-auc:0.87481	validation_1-auc:0.84214
[21]	validation_0-auc:0.87543	validation_1-auc:0.84120
[22]	validation_0-auc:0.87734	validation_1-auc:0.84254
[23]	validation_0-auc:0.87895	validation_1-auc:0.84359
[24]	validation_0-auc:0.88037	validation_1-auc:0.84421
[25]	validation_0-auc:0.88135	validation_1-auc:0.84465
[26]	validation_0-auc:0.88332	validation_1-auc:0.84426
[27]	validation_0-auc:0.88558	validation_1-auc:0.84406
[28]	validation_0-auc:0.88690	validation_1-auc:0.84397
[29]	validation_0-auc:0.88769	validation_1-auc:0.84421
[30]	validation_0-auc:0.88921	validation_1-auc:0.84337
[31]	validation_0-auc:0.89021	validation_1-auc:0.84409
[32]	validation_0-auc:0.89049	validation_1-auc:0.84460
[33]	validation_0-auc:0.89138	validation_1-auc:0.84470
[34]	validation_0-auc:0.89225	validation_1-auc:0.84447
[35]	validation_0-auc:0.89290	validation_1-auc:0.84433
[36]	validation_0-auc:0.89331	validation_1-auc:0.84457
[37]	validation_0-auc:0.89439	validation_1-auc:0.84450
[38]	validation_0-auc:0.89573	validation_1-auc:0.84379
[39]	validation_0-auc:0.89621	validation_1-auc:0.84381
[40]	validation_0-auc:0.89672	validation_1-auc:0.84369
[41]	validation_0-auc:0.89738	validation_1-auc:0.84295
[42]	validation_0-auc:0.89811	validation_1-auc:0.84296
[43]	validation_0-auc:0.89855	validation_1-auc:0.84346
[44]	validation_0-auc:0.89919	validation_1-auc:0.84383
[45]	validation_0-auc:0.89961	validation_1-auc:0.84383
[46]	validation_0-auc:0.89981	validation_1-auc:0.84387
[47]	validation_0-auc:0.90013	validation_1-auc:0.84373
[48]	validation_0-auc:0.90091	validation_1-auc:0.84376
[49]	validation_0-auc:0.90143	validation_1-auc:0.84348
[50]	validation_0-auc:0.90201	validation_1-auc:0.84376
[51]	validation_0-auc:0.90262	validation_1-auc:0.84383
[52]	validation_0-auc:0.90301	validation_1-auc:0.84389
[53]	validation_0-auc:0.90326	validation_1-auc:0.84376
[54]	validation_0-auc:0.90368	validation_1-auc:0.84350
[55]	validation_0-auc:0.90399	validation_1-auc:0.84372
[56]	validation_0-auc:0.90445	validation_1-auc:0.84351
[57]	validation_0-auc:0.90511	validation_1-auc:0.84334
[58]	validation_0-auc:0.90529	validation_1-auc:0.84315
[59]	validation_0-auc:0.90542	validation_1-auc:0.84313
[60]	validation_0-auc:0.90584	validation_1-auc:0.84316
[61]	validation_0-auc:0.90589	validation_1-auc:0.84318
[62]	validation_0-auc:0.90606	validation_1-auc:0.84295
 42%|████▏     | 21/50 [05:01<06:43, 13.92s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82381	validation_1-auc:0.81162
[1]	validation_0-auc:0.82915	validation_1-auc:0.81314
[2]	validation_0-auc:0.83747	validation_1-auc:0.82025
[3]	validation_0-auc:0.83949	validation_1-auc:0.82094
[4]	validation_0-auc:0.84165	validation_1-auc:0.81979
[5]	validation_0-auc:0.84576	validation_1-auc:0.82427
[6]	validation_0-auc:0.85015	validation_1-auc:0.83040
[7]	validation_0-auc:0.85032	validation_1-auc:0.82980
[8]	validation_0-auc:0.85149	validation_1-auc:0.83033
[9]	validation_0-auc:0.85333	validation_1-auc:0.83380
[10]	validation_0-auc:0.85185	validation_1-auc:0.83043
[11]	validation_0-auc:0.85015	validation_1-auc:0.83024
[12]	validation_0-auc:0.85334	validation_1-auc:0.83381
[13]	validation_0-auc:0.85527	validation_1-auc:0.83421
[14]	validation_0-auc:0.85734	validation_1-auc:0.83725
[15]	validation_0-auc:0.85785	validation_1-auc:0.83832
[16]	validation_0-auc:0.85823	validation_1-auc:0.83861
[17]	validation_0-auc:0.85925	validation_1-auc:0.83863
[18]	validation_0-auc:0.85986	validation_1-auc:0.83935
[19]	validation_0-auc:0.86109	validation_1-auc:0.83962
[20]	validation_0-auc:0.86103	validation_1-auc:0.83945
[21]	validation_0-auc:0.86140	validation_1-auc:0.83952
[22]	validation_0-auc:0.86446	validation_1-auc:0.84104
[23]	validation_0-auc:0.86559	validation_1-auc:0.84114
[24]	validation_0-auc:0.86654	validation_1-auc:0.84127
[25]	validation_0-auc:0.86687	validation_1-auc:0.84137
[26]	validation_0-auc:0.86812	validation_1-auc:0.84172
[27]	validation_0-auc:0.86871	validation_1-auc:0.84196
[28]	validation_0-auc:0.86936	validation_1-auc:0.84183
[29]	validation_0-auc:0.87028	validation_1-auc:0.84132
[30]	validation_0-auc:0.87074	validation_1-auc:0.84109
[31]	validation_0-auc:0.87100	validation_1-auc:0.84177
[32]	validation_0-auc:0.87162	validation_1-auc:0.84188
[33]	validation_0-auc:0.87213	validation_1-auc:0.84207
[34]	validation_0-auc:0.87253	validation_1-auc:0.84245
[35]	validation_0-auc:0.87377	validation_1-auc:0.84306
[36]	validation_0-auc:0.87451	validation_1-auc:0.84337
[37]	validation_0-auc:0.87481	validation_1-auc:0.84365
[38]	validation_0-auc:0.87517	validation_1-auc:0.84387
[39]	validation_0-auc:0.87535	validation_1-auc:0.84388
[40]	validation_0-auc:0.87612	validation_1-auc:0.84442
[41]	validation_0-auc:0.87688	validation_1-auc:0.84433
[42]	validation_0-auc:0.87739	validation_1-auc:0.84451
[43]	validation_0-auc:0.87764	validation_1-auc:0.84457
[44]	validation_0-auc:0.87813	validation_1-auc:0.84441
[45]	validation_0-auc:0.87857	validation_1-auc:0.84437
[46]	validation_0-auc:0.87892	validation_1-auc:0.84469
[47]	validation_0-auc:0.87940	validation_1-auc:0.84459
[48]	validation_0-auc:0.87975	validation_1-auc:0.84482
[49]	validation_0-auc:0.88000	validation_1-auc:0.84503
[50]	validation_0-auc:0.88021	validation_1-auc:0.84503
[51]	validation_0-auc:0.88033	validation_1-auc:0.84499
[52]	validation_0-auc:0.88038	validation_1-auc:0.84490
[53]	validation_0-auc:0.88062	validation_1-auc:0.84469
[54]	validation_0-auc:0.88073	validation_1-auc:0.84452
[55]	validation_0-auc:0.88114	validation_1-auc:0.84484
[56]	validation_0-auc:0.88136	validation_1-auc:0.84503
[57]	validation_0-auc:0.88182	validation_1-auc:0.84513
[58]	validation_0-auc:0.88204	validation_1-auc:0.84508
[59]	validation_0-auc:0.88230	validation_1-auc:0.84492
[60]	validation_0-auc:0.88242	validation_1-auc:0.84497
[61]	validation_0-auc:0.88262	validation_1-auc:0.84492
[62]	validation_0-auc:0.88279	validation_1-auc:0.84494
[63]	validation_0-auc:0.88307	validation_1-auc:0.84482
[64]	validation_0-auc:0.88360	validation_1-auc:0.84470
[65]	validation_0-auc:0.88389	validation_1-auc:0.84461
[66]	validation_0-auc:0.88410	validation_1-auc:0.84471
[67]	validation_0-auc:0.88424	validation_1-auc:0.84466
[68]	validation_0-auc:0.88499	validation_1-auc:0.84472
[69]	validation_0-auc:0.88539	validation_1-auc:0.84489
[70]	validation_0-auc:0.88593	validation_1-auc:0.84506
[71]	validation_0-auc:0.88611	validation_1-auc:0.84488
[72]	validation_0-auc:0.88621	validation_1-auc:0.84475
[73]	validation_0-auc:0.88635	validation_1-auc:0.84470
[74]	validation_0-auc:0.88658	validation_1-auc:0.84469
[75]	validation_0-auc:0.88714	validation_1-auc:0.84453
[76]	validation_0-auc:0.88746	validation_1-auc:0.84430
[77]	validation_0-auc:0.88818	validation_1-auc:0.84438
[78]	validation_0-auc:0.88826	validation_1-auc:0.84445
[79]	validation_0-auc:0.88910	validation_1-auc:0.84424
[80]	validation_0-auc:0.88940	validation_1-auc:0.84426
[81]	validation_0-auc:0.88997	validation_1-auc:0.84396
[82]	validation_0-auc:0.89005	validation_1-auc:0.84405
[83]	validation_0-auc:0.89034	validation_1-auc:0.84414
[84]	validation_0-auc:0.89036	validation_1-auc:0.84406
[85]	validation_0-auc:0.89044	validation_1-auc:0.84410
[86]	validation_0-auc:0.89067	validation_1-auc:0.84423
 42%|████▏     | 21/50 [05:04<06:43, 13.92s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82164	validation_1-auc:0.80574
[1]	validation_0-auc:0.82495	validation_1-auc:0.80943
[2]	validation_0-auc:0.83154	validation_1-auc:0.81516
[3]	validation_0-auc:0.83460	validation_1-auc:0.81856
[4]	validation_0-auc:0.84137	validation_1-auc:0.82553
[5]	validation_0-auc:0.84530	validation_1-auc:0.82678
[6]	validation_0-auc:0.84765	validation_1-auc:0.82921
[7]	validation_0-auc:0.84889	validation_1-auc:0.82920
[8]	validation_0-auc:0.85023	validation_1-auc:0.82936
[9]	validation_0-auc:0.85237	validation_1-auc:0.83042
[10]	validation_0-auc:0.85131	validation_1-auc:0.82742
[11]	validation_0-auc:0.85097	validation_1-auc:0.82681
[12]	validation_0-auc:0.85487	validation_1-auc:0.82967
[13]	validation_0-auc:0.85684	validation_1-auc:0.83119
[14]	validation_0-auc:0.85738	validation_1-auc:0.83279
[15]	validation_0-auc:0.85885	validation_1-auc:0.83482
[16]	validation_0-auc:0.86013	validation_1-auc:0.83576
[17]	validation_0-auc:0.86173	validation_1-auc:0.83695
[18]	validation_0-auc:0.86161	validation_1-auc:0.83676
[19]	validation_0-auc:0.86319	validation_1-auc:0.83634
[20]	validation_0-auc:0.86349	validation_1-auc:0.83585
[21]	validation_0-auc:0.86315	validation_1-auc:0.83485
[22]	validation_0-auc:0.86543	validation_1-auc:0.83556
[23]	validation_0-auc:0.86726	validation_1-auc:0.83696
[24]	validation_0-auc:0.86898	validation_1-auc:0.83806
[25]	validation_0-auc:0.86969	validation_1-auc:0.83816
[26]	validation_0-auc:0.87134	validation_1-auc:0.83746
[27]	validation_0-auc:0.87229	validation_1-auc:0.83839
[28]	validation_0-auc:0.87280	validation_1-auc:0.83822
[29]	validation_0-auc:0.87395	validation_1-auc:0.83830
[30]	validation_0-auc:0.87447	validation_1-auc:0.83748
[31]	validation_0-auc:0.87528	validation_1-auc:0.83801
[32]	validation_0-auc:0.87573	validation_1-auc:0.83907
[33]	validation_0-auc:0.87611	validation_1-auc:0.83937
[34]	validation_0-auc:0.87627	validation_1-auc:0.83963
[35]	validation_0-auc:0.87676	validation_1-auc:0.83950
[36]	validation_0-auc:0.87758	validation_1-auc:0.83980
[37]	validation_0-auc:0.87835	validation_1-auc:0.83945
[38]	validation_0-auc:0.87924	validation_1-auc:0.83929
[39]	validation_0-auc:0.87963	validation_1-auc:0.83929
[40]	validation_0-auc:0.87985	validation_1-auc:0.83962
[41]	validation_0-auc:0.88006	validation_1-auc:0.83953
[42]	validation_0-auc:0.88069	validation_1-auc:0.83941
[43]	validation_0-auc:0.88119	validation_1-auc:0.83930
[44]	validation_0-auc:0.88157	validation_1-auc:0.83879
[45]	validation_0-auc:0.88159	validation_1-auc:0.83898
[46]	validation_0-auc:0.88218	validation_1-auc:0.83881
[47]	validation_0-auc:0.88308	validation_1-auc:0.83911
[48]	validation_0-auc:0.88353	validation_1-auc:0.83943
[49]	validation_0-auc:0.88404	validation_1-auc:0.83982
[50]	validation_0-auc:0.88452	validation_1-auc:0.83997
[51]	validation_0-auc:0.88576	validation_1-auc:0.83963
[52]	validation_0-auc:0.88598	validation_1-auc:0.83951
[53]	validation_0-auc:0.88616	validation_1-auc:0.83951
[54]	validation_0-auc:0.88631	validation_1-auc:0.83936
[55]	validation_0-auc:0.88644	validation_1-auc:0.83930
[56]	validation_0-auc:0.88656	validation_1-auc:0.83932
[57]	validation_0-auc:0.88678	validation_1-auc:0.83927
[58]	validation_0-auc:0.88713	validation_1-auc:0.83935
[59]	validation_0-auc:0.88745	validation_1-auc:0.83916
[60]	validation_0-auc:0.88757	validation_1-auc:0.83925
[61]	validation_0-auc:0.88781	validation_1-auc:0.83915
[62]	validation_0-auc:0.88861	validation_1-auc:0.83880
[63]	validation_0-auc:0.88901	validation_1-auc:0.83874
[64]	validation_0-auc:0.89015	validation_1-auc:0.83876
[65]	validation_0-auc:0.89081	validation_1-auc:0.83870
[66]	validation_0-auc:0.89126	validation_1-auc:0.83885
[67]	validation_0-auc:0.89167	validation_1-auc:0.83883
[68]	validation_0-auc:0.89203	validation_1-auc:0.83900
[69]	validation_0-auc:0.89219	validation_1-auc:0.83877
[70]	validation_0-auc:0.89268	validation_1-auc:0.83851
[71]	validation_0-auc:0.89317	validation_1-auc:0.83845
[72]	validation_0-auc:0.89366	validation_1-auc:0.83834
[73]	validation_0-auc:0.89379	validation_1-auc:0.83835
[74]	validation_0-auc:0.89392	validation_1-auc:0.83816
[75]	validation_0-auc:0.89420	validation_1-auc:0.83812
[76]	validation_0-auc:0.89473	validation_1-auc:0.83817
[77]	validation_0-auc:0.89487	validation_1-auc:0.83819
[78]	validation_0-auc:0.89515	validation_1-auc:0.83779
[79]	validation_0-auc:0.89524	validation_1-auc:0.83780
 42%|████▏     | 21/50 [05:07<06:43, 13.92s/trial, best loss: -0.8435547933927318]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81911	validation_1-auc:0.81065
[1]	validation_0-auc:0.82483	validation_1-auc:0.81410
[2]	validation_0-auc:0.83669	validation_1-auc:0.82830
[3]	validation_0-auc:0.83812	validation_1-auc:0.82793
[4]	validation_0-auc:0.83999	validation_1-auc:0.83082
[5]	validation_0-auc:0.84247	validation_1-auc:0.82889
[6]	validation_0-auc:0.84494	validation_1-auc:0.83099
[7]	validation_0-auc:0.84596	validation_1-auc:0.83271
[8]	validation_0-auc:0.84677	validation_1-auc:0.83410
[9]	validation_0-auc:0.84762	validation_1-auc:0.83543
[10]	validation_0-auc:0.84631	validation_1-auc:0.83193
[11]	validation_0-auc:0.84641	validation_1-auc:0.83075
[12]	validation_0-auc:0.85057	validation_1-auc:0.83375
[13]	validation_0-auc:0.85317	validation_1-auc:0.83605
[14]	validation_0-auc:0.85468	validation_1-auc:0.83774
[15]	validation_0-auc:0.85623	validation_1-auc:0.83846
[16]	validation_0-auc:0.85750	validation_1-auc:0.83969
[17]	validation_0-auc:0.85802	validation_1-auc:0.84013
[18]	validation_0-auc:0.85760	validation_1-auc:0.83875
[19]	validation_0-auc:0.86006	validation_1-auc:0.84075
[20]	validation_0-auc:0.86044	validation_1-auc:0.84103
[21]	validation_0-auc:0.86164	validation_1-auc:0.84020
[22]	validation_0-auc:0.86384	validation_1-auc:0.84092
[23]	validation_0-auc:0.86512	validation_1-auc:0.84137
[24]	validation_0-auc:0.86631	validation_1-auc:0.84210
[25]	validation_0-auc:0.86708	validation_1-auc:0.84255
[26]	validation_0-auc:0.86795	validation_1-auc:0.84294
[27]	validation_0-auc:0.86895	validation_1-auc:0.84258
[28]	validation_0-auc:0.86905	validation_1-auc:0.84268
[29]	validation_0-auc:0.86982	validation_1-auc:0.84310
[30]	validation_0-auc:0.87053	validation_1-auc:0.84279
[31]	validation_0-auc:0.87124	validation_1-auc:0.84321
[32]	validation_0-auc:0.87158	validation_1-auc:0.84374
[33]	validation_0-auc:0.87198	validation_1-auc:0.84382
[34]	validation_0-auc:0.87255	validation_1-auc:0.84369
[35]	validation_0-auc:0.87291	validation_1-auc:0.84344
[36]	validation_0-auc:0.87335	validation_1-auc:0.84338
[37]	validation_0-auc:0.87383	validation_1-auc:0.84340
[38]	validation_0-auc:0.87448	validation_1-auc:0.84383
[39]	validation_0-auc:0.87479	validation_1-auc:0.84406
[40]	validation_0-auc:0.87500	validation_1-auc:0.84439
[41]	validation_0-auc:0.87623	validation_1-auc:0.84453
[42]	validation_0-auc:0.87643	validation_1-auc:0.84472
[43]	validation_0-auc:0.87697	validation_1-auc:0.84484
[44]	validation_0-auc:0.87760	validation_1-auc:0.84502
[45]	validation_0-auc:0.87763	validation_1-auc:0.84527
[46]	validation_0-auc:0.87791	validation_1-auc:0.84515
[47]	validation_0-auc:0.87829	validation_1-auc:0.84513
[48]	validation_0-auc:0.87907	validation_1-auc:0.84526
[49]	validation_0-auc:0.88006	validation_1-auc:0.84488
[50]	validation_0-auc:0.88040	validation_1-auc:0.84483
[51]	validation_0-auc:0.88128	validation_1-auc:0.84511
[52]	validation_0-auc:0.88152	validation_1-auc:0.84510
[53]	validation_0-auc:0.88221	validation_1-auc:0.84561
[54]	validation_0-auc:0.88236	validation_1-auc:0.84568
[55]	validation_0-auc:0.88272	validation_1-auc:0.84582
[56]	validation_0-auc:0.88333	validation_1-auc:0.84572
[57]	validation_0-auc:0.88343	validation_1-auc:0.84581
[58]	validation_0-auc:0.88405	validation_1-auc:0.84599
[59]	validation_0-auc:0.88415	validation_1-auc:0.84612
[60]	validation_0-auc:0.88432	validation_1-auc:0.84602
[61]	validation_0-auc:0.88451	validation_1-auc:0.84590
[62]	validation_0-auc:0.88531	validation_1-auc:0.84619
[63]	validation_0-auc:0.88567	validation_1-auc:0.84635
[64]	validation_0-auc:0.88595	validation_1-auc:0.84651
[65]	validation_0-auc:0.88610	validation_1-auc:0.84640
[66]	validation_0-auc:0.88638	validation_1-auc:0.84617
[67]	validation_0-auc:0.88675	validation_1-auc:0.84631
[68]	validation_0-auc:0.88693	validation_1-auc:0.84619
[69]	validation_0-auc:0.88714	validation_1-auc:0.84616
[70]	validation_0-auc:0.88753	validation_1-auc:0.84609
[71]	validation_0-auc:0.88770	validation_1-auc:0.84614
[72]	validation_0-auc:0.88786	validation_1-auc:0.84611
[73]	validation_0-auc:0.88852	validation_1-auc:0.84617
[74]	validation_0-auc:0.88865	validation_1-auc:0.84623
[75]	validation_0-auc:0.88874	validation_1-auc:0.84614
[76]	validation_0-auc:0.88885	validation_1-auc:0.84599
[77]	validation_0-auc:0.88910	validation_1-auc:0.84588
[78]	validation_0-auc:0.88955	validation_1-auc:0.84567
[79]	validation_0-auc:0.88996	validation_1-auc:0.84574
[80]	validation_0-auc:0.89063	validation_1-auc:0.84603
[81]	validation_0-auc:0.89085	validation_1-auc:0.84602
[82]	validation_0-auc:0.89107	validation_1-auc:0.84602
[83]	validation_0-auc:0.89128	validation_1-auc:0.84617
[84]	validation_0-auc:0.89154	validation_1-auc:0.84609
[85]	validation_0-auc:0.89201	validation_1-auc:0.84598
[86]	validation_0-auc:0.89269	validation_1-auc:0.84580
[87]	validation_0-auc:0.89342	validation_1-auc:0.84550
[88]	validation_0-auc:0.89391	validation_1-auc:0.84535
[89]	validation_0-auc:0.89448	validation_1-auc:0.84523
[90]	validation_0-auc:0.89471	validation_1-auc:0.84532
[91]	validation_0-auc:0.89481	validation_1-auc:0.84536
[92]	validation_0-auc:0.89531	validation_1-auc:0.84512
[93]	validation_0-auc:0.89584	validation_1-auc:0.84501
 44%|████▍     | 22/50 [05:11<06:02, 12.96s/trial, best loss: -0.8438690059437031]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83019	validation_1-auc:0.81318
[1]	validation_0-auc:0.83679	validation_1-auc:0.81581
[2]	validation_0-auc:0.84824	validation_1-auc:0.82115
[3]	validation_0-auc:0.85068	validation_1-auc:0.82089
[4]	validation_0-auc:0.85419	validation_1-auc:0.82193
[5]	validation_0-auc:0.85952	validation_1-auc:0.82656
[6]	validation_0-auc:0.86516	validation_1-auc:0.83286
[7]	validation_0-auc:0.86869	validation_1-auc:0.83529
[8]	validation_0-auc:0.87181	validation_1-auc:0.83567
[9]	validation_0-auc:0.87254	validation_1-auc:0.83538
[10]	validation_0-auc:0.87172	validation_1-auc:0.83263
[11]	validation_0-auc:0.87268	validation_1-auc:0.83171
[12]	validation_0-auc:0.87621	validation_1-auc:0.83514
[13]	validation_0-auc:0.87973	validation_1-auc:0.83643
[14]	validation_0-auc:0.88082	validation_1-auc:0.83861
[15]	validation_0-auc:0.88334	validation_1-auc:0.84002
[16]	validation_0-auc:0.88435	validation_1-auc:0.84007
[17]	validation_0-auc:0.88687	validation_1-auc:0.84037
[18]	validation_0-auc:0.88836	validation_1-auc:0.84062
[19]	validation_0-auc:0.89019	validation_1-auc:0.84118
[20]	validation_0-auc:0.89151	validation_1-auc:0.84079
[21]	validation_0-auc:0.89274	validation_1-auc:0.84057
[22]	validation_0-auc:0.89489	validation_1-auc:0.84119
[23]	validation_0-auc:0.89646	validation_1-auc:0.84180
[24]	validation_0-auc:0.89790	validation_1-auc:0.84189
[25]	validation_0-auc:0.89807	validation_1-auc:0.84242
[26]	validation_0-auc:0.89978	validation_1-auc:0.84215
[27]	validation_0-auc:0.90105	validation_1-auc:0.84187
[28]	validation_0-auc:0.90154	validation_1-auc:0.84160
[29]	validation_0-auc:0.90232	validation_1-auc:0.84175
[30]	validation_0-auc:0.90329	validation_1-auc:0.84162
[31]	validation_0-auc:0.90395	validation_1-auc:0.84168
[32]	validation_0-auc:0.90441	validation_1-auc:0.84207
[33]	validation_0-auc:0.90485	validation_1-auc:0.84214
[34]	validation_0-auc:0.90620	validation_1-auc:0.84194
[35]	validation_0-auc:0.90725	validation_1-auc:0.84169
[36]	validation_0-auc:0.90808	validation_1-auc:0.84186
[37]	validation_0-auc:0.90826	validation_1-auc:0.84188
[38]	validation_0-auc:0.90872	validation_1-auc:0.84168
[39]	validation_0-auc:0.90987	validation_1-auc:0.84118
[40]	validation_0-auc:0.91060	validation_1-auc:0.84088
[41]	validation_0-auc:0.91087	validation_1-auc:0.84069
[42]	validation_0-auc:0.91201	validation_1-auc:0.84102
[43]	validation_0-auc:0.91216	validation_1-auc:0.84102
[44]	validation_0-auc:0.91349	validation_1-auc:0.84089
[45]	validation_0-auc:0.91440	validation_1-auc:0.84054
[46]	validation_0-auc:0.91459	validation_1-auc:0.84048
[47]	validation_0-auc:0.91483	validation_1-auc:0.84058
[48]	validation_0-auc:0.91495	validation_1-auc:0.84064
[49]	validation_0-auc:0.91505	validation_1-auc:0.84076
[50]	validation_0-auc:0.91528	validation_1-auc:0.84072
[51]	validation_0-auc:0.91573	validation_1-auc:0.84061
[52]	validation_0-auc:0.91595	validation_1-auc:0.84058
[53]	validation_0-auc:0.91613	validation_1-auc:0.84067
[54]	validation_0-auc:0.91629	validation_1-auc:0.84075
 44%|████▍     | 22/50 [05:14<06:02, 12.96s/trial, best loss: -0.8438690059437031]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82558	validation_1-auc:0.80693
[1]	validation_0-auc:0.83559	validation_1-auc:0.81479
[2]	validation_0-auc:0.84193	validation_1-auc:0.81988
[3]	validation_0-auc:0.84728	validation_1-auc:0.82262
[4]	validation_0-auc:0.85545	validation_1-auc:0.82604
[5]	validation_0-auc:0.86130	validation_1-auc:0.82820
[6]	validation_0-auc:0.86866	validation_1-auc:0.83127
[7]	validation_0-auc:0.87084	validation_1-auc:0.83275
[8]	validation_0-auc:0.87324	validation_1-auc:0.83280
[9]	validation_0-auc:0.87483	validation_1-auc:0.83130
[10]	validation_0-auc:0.87433	validation_1-auc:0.82995
[11]	validation_0-auc:0.87494	validation_1-auc:0.82787
[12]	validation_0-auc:0.87992	validation_1-auc:0.83272
[13]	validation_0-auc:0.88464	validation_1-auc:0.83507
[14]	validation_0-auc:0.88620	validation_1-auc:0.83617
[15]	validation_0-auc:0.88891	validation_1-auc:0.83606
[16]	validation_0-auc:0.88958	validation_1-auc:0.83649
[17]	validation_0-auc:0.89212	validation_1-auc:0.83841
[18]	validation_0-auc:0.89291	validation_1-auc:0.83803
[19]	validation_0-auc:0.89513	validation_1-auc:0.83916
[20]	validation_0-auc:0.89639	validation_1-auc:0.83784
[21]	validation_0-auc:0.89752	validation_1-auc:0.83749
[22]	validation_0-auc:0.89866	validation_1-auc:0.83828
[23]	validation_0-auc:0.90047	validation_1-auc:0.83831
[24]	validation_0-auc:0.90046	validation_1-auc:0.83833
[25]	validation_0-auc:0.90065	validation_1-auc:0.83887
[26]	validation_0-auc:0.90283	validation_1-auc:0.83755
[27]	validation_0-auc:0.90388	validation_1-auc:0.83725
[28]	validation_0-auc:0.90497	validation_1-auc:0.83664
[29]	validation_0-auc:0.90586	validation_1-auc:0.83699
[30]	validation_0-auc:0.90706	validation_1-auc:0.83664
[31]	validation_0-auc:0.90767	validation_1-auc:0.83663
[32]	validation_0-auc:0.90814	validation_1-auc:0.83681
[33]	validation_0-auc:0.90917	validation_1-auc:0.83620
[34]	validation_0-auc:0.90943	validation_1-auc:0.83604
[35]	validation_0-auc:0.91017	validation_1-auc:0.83621
[36]	validation_0-auc:0.91066	validation_1-auc:0.83615
[37]	validation_0-auc:0.91113	validation_1-auc:0.83628
[38]	validation_0-auc:0.91183	validation_1-auc:0.83572
[39]	validation_0-auc:0.91227	validation_1-auc:0.83527
[40]	validation_0-auc:0.91296	validation_1-auc:0.83495
[41]	validation_0-auc:0.91347	validation_1-auc:0.83505
[42]	validation_0-auc:0.91392	validation_1-auc:0.83508
[43]	validation_0-auc:0.91437	validation_1-auc:0.83489
[44]	validation_0-auc:0.91480	validation_1-auc:0.83468
[45]	validation_0-auc:0.91512	validation_1-auc:0.83464
[46]	validation_0-auc:0.91623	validation_1-auc:0.83446
[47]	validation_0-auc:0.91651	validation_1-auc:0.83429
[48]	validation_0-auc:0.91709	validation_1-auc:0.83412
 44%|████▍     | 22/50 [05:17<06:02, 12.96s/trial, best loss: -0.8438690059437031]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82227	validation_1-auc:0.81118
[1]	validation_0-auc:0.83839	validation_1-auc:0.82491
[2]	validation_0-auc:0.84677	validation_1-auc:0.83131
[3]	validation_0-auc:0.84901	validation_1-auc:0.83084
[4]	validation_0-auc:0.85555	validation_1-auc:0.83345
[5]	validation_0-auc:0.86013	validation_1-auc:0.83350
[6]	validation_0-auc:0.86350	validation_1-auc:0.83720
[7]	validation_0-auc:0.86691	validation_1-auc:0.83660
[8]	validation_0-auc:0.86882	validation_1-auc:0.83759
[9]	validation_0-auc:0.86984	validation_1-auc:0.83479
[10]	validation_0-auc:0.87104	validation_1-auc:0.83310
[11]	validation_0-auc:0.87124	validation_1-auc:0.83073
[12]	validation_0-auc:0.87671	validation_1-auc:0.83335
[13]	validation_0-auc:0.88060	validation_1-auc:0.83548
[14]	validation_0-auc:0.88198	validation_1-auc:0.83677
[15]	validation_0-auc:0.88419	validation_1-auc:0.83786
[16]	validation_0-auc:0.88554	validation_1-auc:0.83941
[17]	validation_0-auc:0.88794	validation_1-auc:0.83916
[18]	validation_0-auc:0.88894	validation_1-auc:0.83815
[19]	validation_0-auc:0.89073	validation_1-auc:0.83891
[20]	validation_0-auc:0.89226	validation_1-auc:0.83782
[21]	validation_0-auc:0.89369	validation_1-auc:0.83668
[22]	validation_0-auc:0.89482	validation_1-auc:0.83787
[23]	validation_0-auc:0.89668	validation_1-auc:0.83938
[24]	validation_0-auc:0.89726	validation_1-auc:0.83919
[25]	validation_0-auc:0.89779	validation_1-auc:0.83970
[26]	validation_0-auc:0.89981	validation_1-auc:0.83982
[27]	validation_0-auc:0.90075	validation_1-auc:0.84025
[28]	validation_0-auc:0.90126	validation_1-auc:0.83975
[29]	validation_0-auc:0.90219	validation_1-auc:0.83994
[30]	validation_0-auc:0.90347	validation_1-auc:0.84000
[31]	validation_0-auc:0.90378	validation_1-auc:0.84099
[32]	validation_0-auc:0.90420	validation_1-auc:0.84116
[33]	validation_0-auc:0.90446	validation_1-auc:0.84133
[34]	validation_0-auc:0.90520	validation_1-auc:0.84189
[35]	validation_0-auc:0.90603	validation_1-auc:0.84218
[36]	validation_0-auc:0.90653	validation_1-auc:0.84199
[37]	validation_0-auc:0.90732	validation_1-auc:0.84222
[38]	validation_0-auc:0.90797	validation_1-auc:0.84224
[39]	validation_0-auc:0.90836	validation_1-auc:0.84239
[40]	validation_0-auc:0.90847	validation_1-auc:0.84223
[41]	validation_0-auc:0.90981	validation_1-auc:0.84187
[42]	validation_0-auc:0.91141	validation_1-auc:0.84194
[43]	validation_0-auc:0.91164	validation_1-auc:0.84212
[44]	validation_0-auc:0.91174	validation_1-auc:0.84243
[45]	validation_0-auc:0.91205	validation_1-auc:0.84229
[46]	validation_0-auc:0.91234	validation_1-auc:0.84212
[47]	validation_0-auc:0.91266	validation_1-auc:0.84164
[48]	validation_0-auc:0.91326	validation_1-auc:0.84136
[49]	validation_0-auc:0.91397	validation_1-auc:0.84133
[50]	validation_0-auc:0.91493	validation_1-auc:0.84123
[51]	validation_0-auc:0.91539	validation_1-auc:0.84115
[52]	validation_0-auc:0.91614	validation_1-auc:0.84053
[53]	validation_0-auc:0.91629	validation_1-auc:0.84043
[54]	validation_0-auc:0.91664	validation_1-auc:0.83983
[55]	validation_0-auc:0.91683	validation_1-auc:0.83974
[56]	validation_0-auc:0.91744	validation_1-auc:0.83973
[57]	validation_0-auc:0.91764	validation_1-auc:0.83979
[58]	validation_0-auc:0.91791	validation_1-auc:0.83961
[59]	validation_0-auc:0.91824	validation_1-auc:0.83930
[60]	validation_0-auc:0.91903	validation_1-auc:0.83945
[61]	validation_0-auc:0.91920	validation_1-auc:0.83941
[62]	validation_0-auc:0.91946	validation_1-auc:0.83945
[63]	validation_0-auc:0.91968	validation_1-auc:0.83937
[64]	validation_0-auc:0.92070	validation_1-auc:0.83925
[65]	validation_0-auc:0.92115	validation_1-auc:0.83856
[66]	validation_0-auc:0.92168	validation_1-auc:0.83858
[67]	validation_0-auc:0.92190	validation_1-auc:0.83820
[68]	validation_0-auc:0.92206	validation_1-auc:0.83825
[69]	validation_0-auc:0.92232	validation_1-auc:0.83778
[70]	validation_0-auc:0.92279	validation_1-auc:0.83735
[71]	validation_0-auc:0.92306	validation_1-auc:0.83685
[72]	validation_0-auc:0.92315	validation_1-auc:0.83671
[73]	validation_0-auc:0.92322	validation_1-auc:0.83668
 46%|████▌     | 23/50 [05:21<05:26, 12.08s/trial, best loss: -0.8438690059437031]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82381	validation_1-auc:0.81162
[1]	validation_0-auc:0.82915	validation_1-auc:0.81314
[2]	validation_0-auc:0.83747	validation_1-auc:0.82025
[3]	validation_0-auc:0.83949	validation_1-auc:0.82095
[4]	validation_0-auc:0.84169	validation_1-auc:0.81988
[5]	validation_0-auc:0.84575	validation_1-auc:0.82427
[6]	validation_0-auc:0.85016	validation_1-auc:0.83042
[7]	validation_0-auc:0.85089	validation_1-auc:0.82995
[8]	validation_0-auc:0.85201	validation_1-auc:0.83050
[9]	validation_0-auc:0.85375	validation_1-auc:0.83386
[10]	validation_0-auc:0.85216	validation_1-auc:0.83058
[11]	validation_0-auc:0.85058	validation_1-auc:0.83020
[12]	validation_0-auc:0.85393	validation_1-auc:0.83373
[13]	validation_0-auc:0.85605	validation_1-auc:0.83442
[14]	validation_0-auc:0.85791	validation_1-auc:0.83698
[15]	validation_0-auc:0.85851	validation_1-auc:0.83853
[16]	validation_0-auc:0.85892	validation_1-auc:0.83818
[17]	validation_0-auc:0.85980	validation_1-auc:0.83823
[18]	validation_0-auc:0.85980	validation_1-auc:0.83874
[19]	validation_0-auc:0.86094	validation_1-auc:0.83956
[20]	validation_0-auc:0.86153	validation_1-auc:0.83934
[21]	validation_0-auc:0.86249	validation_1-auc:0.83947
[22]	validation_0-auc:0.86439	validation_1-auc:0.84075
[23]	validation_0-auc:0.86560	validation_1-auc:0.84092
[24]	validation_0-auc:0.86585	validation_1-auc:0.84115
[25]	validation_0-auc:0.86641	validation_1-auc:0.84169
[26]	validation_0-auc:0.86746	validation_1-auc:0.84203
[27]	validation_0-auc:0.86832	validation_1-auc:0.84222
[28]	validation_0-auc:0.86886	validation_1-auc:0.84255
[29]	validation_0-auc:0.86961	validation_1-auc:0.84233
[30]	validation_0-auc:0.87038	validation_1-auc:0.84269
[31]	validation_0-auc:0.87130	validation_1-auc:0.84299
[32]	validation_0-auc:0.87229	validation_1-auc:0.84315
[33]	validation_0-auc:0.87286	validation_1-auc:0.84303
[34]	validation_0-auc:0.87329	validation_1-auc:0.84362
[35]	validation_0-auc:0.87377	validation_1-auc:0.84367
[36]	validation_0-auc:0.87433	validation_1-auc:0.84423
[37]	validation_0-auc:0.87458	validation_1-auc:0.84462
[38]	validation_0-auc:0.87496	validation_1-auc:0.84481
[39]	validation_0-auc:0.87520	validation_1-auc:0.84496
[40]	validation_0-auc:0.87534	validation_1-auc:0.84516
[41]	validation_0-auc:0.87622	validation_1-auc:0.84518
[42]	validation_0-auc:0.87663	validation_1-auc:0.84552
[43]	validation_0-auc:0.87679	validation_1-auc:0.84567
[44]	validation_0-auc:0.87696	validation_1-auc:0.84555
[45]	validation_0-auc:0.87748	validation_1-auc:0.84551
[46]	validation_0-auc:0.87778	validation_1-auc:0.84545
[47]	validation_0-auc:0.87816	validation_1-auc:0.84548
[48]	validation_0-auc:0.87850	validation_1-auc:0.84540
[49]	validation_0-auc:0.87894	validation_1-auc:0.84548
[50]	validation_0-auc:0.87911	validation_1-auc:0.84552
[51]	validation_0-auc:0.87929	validation_1-auc:0.84551
[52]	validation_0-auc:0.87990	validation_1-auc:0.84543
[53]	validation_0-auc:0.88030	validation_1-auc:0.84550
[54]	validation_0-auc:0.88046	validation_1-auc:0.84552
[55]	validation_0-auc:0.88063	validation_1-auc:0.84545
[56]	validation_0-auc:0.88133	validation_1-auc:0.84541
[57]	validation_0-auc:0.88151	validation_1-auc:0.84538
[58]	validation_0-auc:0.88173	validation_1-auc:0.84525
[59]	validation_0-auc:0.88190	validation_1-auc:0.84507
[60]	validation_0-auc:0.88231	validation_1-auc:0.84503
[61]	validation_0-auc:0.88278	validation_1-auc:0.84519
[62]	validation_0-auc:0.88290	validation_1-auc:0.84512
[63]	validation_0-auc:0.88305	validation_1-auc:0.84499
[64]	validation_0-auc:0.88368	validation_1-auc:0.84492
[65]	validation_0-auc:0.88408	validation_1-auc:0.84492
[66]	validation_0-auc:0.88427	validation_1-auc:0.84494
[67]	validation_0-auc:0.88445	validation_1-auc:0.84485
[68]	validation_0-auc:0.88553	validation_1-auc:0.84527
[69]	validation_0-auc:0.88563	validation_1-auc:0.84519
[70]	validation_0-auc:0.88570	validation_1-auc:0.84515
[71]	validation_0-auc:0.88615	validation_1-auc:0.84518
[72]	validation_0-auc:0.88628	validation_1-auc:0.84512
[73]	validation_0-auc:0.88634	validation_1-auc:0.84508
 46%|████▌     | 23/50 [05:24<05:26, 12.08s/trial, best loss: -0.8438690059437031]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82164	validation_1-auc:0.80574
[1]	validation_0-auc:0.82688	validation_1-auc:0.81287
[2]	validation_0-auc:0.83267	validation_1-auc:0.81704
[3]	validation_0-auc:0.83534	validation_1-auc:0.82012
[4]	validation_0-auc:0.84147	validation_1-auc:0.82562
[5]	validation_0-auc:0.84547	validation_1-auc:0.82716
[6]	validation_0-auc:0.84780	validation_1-auc:0.82962
[7]	validation_0-auc:0.84900	validation_1-auc:0.82977
[8]	validation_0-auc:0.84999	validation_1-auc:0.82946
[9]	validation_0-auc:0.85219	validation_1-auc:0.83059
[10]	validation_0-auc:0.85117	validation_1-auc:0.82744
[11]	validation_0-auc:0.85077	validation_1-auc:0.82670
[12]	validation_0-auc:0.85419	validation_1-auc:0.82901
[13]	validation_0-auc:0.85650	validation_1-auc:0.83118
[14]	validation_0-auc:0.85742	validation_1-auc:0.83309
[15]	validation_0-auc:0.85875	validation_1-auc:0.83494
[16]	validation_0-auc:0.86013	validation_1-auc:0.83590
[17]	validation_0-auc:0.86182	validation_1-auc:0.83712
[18]	validation_0-auc:0.86154	validation_1-auc:0.83686
[19]	validation_0-auc:0.86303	validation_1-auc:0.83661
[20]	validation_0-auc:0.86355	validation_1-auc:0.83607
[21]	validation_0-auc:0.86358	validation_1-auc:0.83536
[22]	validation_0-auc:0.86550	validation_1-auc:0.83694
[23]	validation_0-auc:0.86717	validation_1-auc:0.83759
[24]	validation_0-auc:0.86836	validation_1-auc:0.83788
[25]	validation_0-auc:0.86879	validation_1-auc:0.83842
[26]	validation_0-auc:0.87059	validation_1-auc:0.83787
[27]	validation_0-auc:0.87231	validation_1-auc:0.83788
[28]	validation_0-auc:0.87265	validation_1-auc:0.83849
[29]	validation_0-auc:0.87358	validation_1-auc:0.83889
[30]	validation_0-auc:0.87457	validation_1-auc:0.83835
[31]	validation_0-auc:0.87521	validation_1-auc:0.83886
[32]	validation_0-auc:0.87612	validation_1-auc:0.83905
[33]	validation_0-auc:0.87638	validation_1-auc:0.83919
[34]	validation_0-auc:0.87665	validation_1-auc:0.83954
[35]	validation_0-auc:0.87720	validation_1-auc:0.83948
[36]	validation_0-auc:0.87763	validation_1-auc:0.83947
[37]	validation_0-auc:0.87798	validation_1-auc:0.83929
[38]	validation_0-auc:0.87854	validation_1-auc:0.83905
[39]	validation_0-auc:0.87899	validation_1-auc:0.83895
[40]	validation_0-auc:0.87916	validation_1-auc:0.83890
[41]	validation_0-auc:0.87936	validation_1-auc:0.83908
[42]	validation_0-auc:0.87974	validation_1-auc:0.83887
[43]	validation_0-auc:0.88001	validation_1-auc:0.83894
[44]	validation_0-auc:0.88061	validation_1-auc:0.83929
[45]	validation_0-auc:0.88080	validation_1-auc:0.83917
[46]	validation_0-auc:0.88109	validation_1-auc:0.83901
[47]	validation_0-auc:0.88133	validation_1-auc:0.83907
[48]	validation_0-auc:0.88178	validation_1-auc:0.83930
[49]	validation_0-auc:0.88247	validation_1-auc:0.83934
[50]	validation_0-auc:0.88318	validation_1-auc:0.83939
[51]	validation_0-auc:0.88363	validation_1-auc:0.83915
[52]	validation_0-auc:0.88407	validation_1-auc:0.83909
[53]	validation_0-auc:0.88421	validation_1-auc:0.83912
[54]	validation_0-auc:0.88437	validation_1-auc:0.83921
[55]	validation_0-auc:0.88466	validation_1-auc:0.83908
[56]	validation_0-auc:0.88522	validation_1-auc:0.83917
[57]	validation_0-auc:0.88560	validation_1-auc:0.83915
[58]	validation_0-auc:0.88629	validation_1-auc:0.83946
[59]	validation_0-auc:0.88642	validation_1-auc:0.83954
[60]	validation_0-auc:0.88651	validation_1-auc:0.83964
[61]	validation_0-auc:0.88679	validation_1-auc:0.83969
[62]	validation_0-auc:0.88712	validation_1-auc:0.83968
[63]	validation_0-auc:0.88726	validation_1-auc:0.83975
[64]	validation_0-auc:0.88762	validation_1-auc:0.83970
[65]	validation_0-auc:0.88804	validation_1-auc:0.83959
[66]	validation_0-auc:0.88911	validation_1-auc:0.83955
[67]	validation_0-auc:0.88913	validation_1-auc:0.83949
[68]	validation_0-auc:0.88956	validation_1-auc:0.83903
[69]	validation_0-auc:0.88987	validation_1-auc:0.83884
[70]	validation_0-auc:0.88995	validation_1-auc:0.83890
[71]	validation_0-auc:0.89025	validation_1-auc:0.83893
[72]	validation_0-auc:0.89035	validation_1-auc:0.83898
[73]	validation_0-auc:0.89048	validation_1-auc:0.83880
[74]	validation_0-auc:0.89098	validation_1-auc:0.83884
[75]	validation_0-auc:0.89119	validation_1-auc:0.83853
[76]	validation_0-auc:0.89147	validation_1-auc:0.83848
[77]	validation_0-auc:0.89163	validation_1-auc:0.83845
[78]	validation_0-auc:0.89190	validation_1-auc:0.83811
[79]	validation_0-auc:0.89208	validation_1-auc:0.83817
[80]	validation_0-auc:0.89218	validation_1-auc:0.83802
[81]	validation_0-auc:0.89272	validation_1-auc:0.83785
[82]	validation_0-auc:0.89297	validation_1-auc:0.83779
[83]	validation_0-auc:0.89333	validation_1-auc:0.83764
[84]	validation_0-auc:0.89371	validation_1-auc:0.83764
[85]	validation_0-auc:0.89402	validation_1-auc:0.83752
[86]	validation_0-auc:0.89430	validation_1-auc:0.83777
[87]	validation_0-auc:0.89463	validation_1-auc:0.83788
[88]	validation_0-auc:0.89488	validation_1-auc:0.83798
[89]	validation_0-auc:0.89527	validation_1-auc:0.83805
[90]	validation_0-auc:0.89568	validation_1-auc:0.83797
[91]	validation_0-auc:0.89572	validation_1-auc:0.83795
[92]	validation_0-auc:0.89638	validation_1-auc:0.83761
[93]	validation_0-auc:0.89674	validation_1-auc:0.83762
 46%|████▌     | 23/50 [05:28<05:26, 12.08s/trial, best loss: -0.8438690059437031]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81911	validation_1-auc:0.81065
[1]	validation_0-auc:0.82483	validation_1-auc:0.81410
[2]	validation_0-auc:0.83670	validation_1-auc:0.82831
[3]	validation_0-auc:0.83812	validation_1-auc:0.82794
[4]	validation_0-auc:0.84005	validation_1-auc:0.83059
[5]	validation_0-auc:0.84227	validation_1-auc:0.82858
[6]	validation_0-auc:0.84480	validation_1-auc:0.83077
[7]	validation_0-auc:0.84648	validation_1-auc:0.83275
[8]	validation_0-auc:0.84738	validation_1-auc:0.83368
[9]	validation_0-auc:0.84701	validation_1-auc:0.83400
[10]	validation_0-auc:0.84726	validation_1-auc:0.83058
[11]	validation_0-auc:0.84744	validation_1-auc:0.83040
[12]	validation_0-auc:0.85084	validation_1-auc:0.83203
[13]	validation_0-auc:0.85425	validation_1-auc:0.83644
[14]	validation_0-auc:0.85543	validation_1-auc:0.83726
[15]	validation_0-auc:0.85705	validation_1-auc:0.83789
[16]	validation_0-auc:0.85841	validation_1-auc:0.83917
[17]	validation_0-auc:0.85871	validation_1-auc:0.83989
[18]	validation_0-auc:0.85802	validation_1-auc:0.83879
[19]	validation_0-auc:0.85957	validation_1-auc:0.83941
[20]	validation_0-auc:0.85999	validation_1-auc:0.83944
[21]	validation_0-auc:0.86089	validation_1-auc:0.83860
[22]	validation_0-auc:0.86298	validation_1-auc:0.83947
[23]	validation_0-auc:0.86398	validation_1-auc:0.84014
[24]	validation_0-auc:0.86497	validation_1-auc:0.84042
[25]	validation_0-auc:0.86576	validation_1-auc:0.84090
[26]	validation_0-auc:0.86656	validation_1-auc:0.84153
[27]	validation_0-auc:0.86774	validation_1-auc:0.84184
[28]	validation_0-auc:0.86804	validation_1-auc:0.84173
[29]	validation_0-auc:0.86862	validation_1-auc:0.84253
[30]	validation_0-auc:0.86930	validation_1-auc:0.84329
[31]	validation_0-auc:0.86979	validation_1-auc:0.84354
[32]	validation_0-auc:0.87035	validation_1-auc:0.84414
[33]	validation_0-auc:0.87052	validation_1-auc:0.84424
[34]	validation_0-auc:0.87077	validation_1-auc:0.84456
[35]	validation_0-auc:0.87166	validation_1-auc:0.84490
[36]	validation_0-auc:0.87213	validation_1-auc:0.84478
[37]	validation_0-auc:0.87258	validation_1-auc:0.84470
[38]	validation_0-auc:0.87363	validation_1-auc:0.84517
[39]	validation_0-auc:0.87393	validation_1-auc:0.84508
[40]	validation_0-auc:0.87446	validation_1-auc:0.84517
[41]	validation_0-auc:0.87536	validation_1-auc:0.84550
[42]	validation_0-auc:0.87599	validation_1-auc:0.84582
[43]	validation_0-auc:0.87616	validation_1-auc:0.84562
[44]	validation_0-auc:0.87685	validation_1-auc:0.84599
[45]	validation_0-auc:0.87717	validation_1-auc:0.84604
[46]	validation_0-auc:0.87737	validation_1-auc:0.84602
[47]	validation_0-auc:0.87807	validation_1-auc:0.84612
[48]	validation_0-auc:0.87853	validation_1-auc:0.84617
[49]	validation_0-auc:0.87909	validation_1-auc:0.84635
[50]	validation_0-auc:0.87985	validation_1-auc:0.84615
[51]	validation_0-auc:0.88010	validation_1-auc:0.84594
[52]	validation_0-auc:0.88075	validation_1-auc:0.84620
[53]	validation_0-auc:0.88097	validation_1-auc:0.84593
[54]	validation_0-auc:0.88106	validation_1-auc:0.84599
[55]	validation_0-auc:0.88174	validation_1-auc:0.84589
[56]	validation_0-auc:0.88190	validation_1-auc:0.84587
[57]	validation_0-auc:0.88226	validation_1-auc:0.84581
[58]	validation_0-auc:0.88315	validation_1-auc:0.84578
[59]	validation_0-auc:0.88334	validation_1-auc:0.84568
[60]	validation_0-auc:0.88365	validation_1-auc:0.84579
[61]	validation_0-auc:0.88404	validation_1-auc:0.84586
[62]	validation_0-auc:0.88462	validation_1-auc:0.84547
[63]	validation_0-auc:0.88482	validation_1-auc:0.84533
[64]	validation_0-auc:0.88505	validation_1-auc:0.84524
[65]	validation_0-auc:0.88534	validation_1-auc:0.84530
[66]	validation_0-auc:0.88542	validation_1-auc:0.84522
[67]	validation_0-auc:0.88568	validation_1-auc:0.84519
[68]	validation_0-auc:0.88577	validation_1-auc:0.84502
[69]	validation_0-auc:0.88645	validation_1-auc:0.84518
[70]	validation_0-auc:0.88695	validation_1-auc:0.84519
[71]	validation_0-auc:0.88726	validation_1-auc:0.84509
[72]	validation_0-auc:0.88780	validation_1-auc:0.84514
[73]	validation_0-auc:0.88857	validation_1-auc:0.84513
[74]	validation_0-auc:0.88871	validation_1-auc:0.84513
[75]	validation_0-auc:0.88924	validation_1-auc:0.84500
[76]	validation_0-auc:0.88936	validation_1-auc:0.84487
[77]	validation_0-auc:0.88964	validation_1-auc:0.84465
[78]	validation_0-auc:0.88976	validation_1-auc:0.84466
[79]	validation_0-auc:0.89002	validation_1-auc:0.84455
 48%|████▊     | 24/50 [05:31<04:58, 11.49s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82370	validation_1-auc:0.81150
[1]	validation_0-auc:0.83005	validation_1-auc:0.81362
[2]	validation_0-auc:0.83885	validation_1-auc:0.82025
[3]	validation_0-auc:0.83990	validation_1-auc:0.82191
[4]	validation_0-auc:0.84193	validation_1-auc:0.82110
[5]	validation_0-auc:0.84592	validation_1-auc:0.82535
[6]	validation_0-auc:0.85044	validation_1-auc:0.83164
[7]	validation_0-auc:0.85191	validation_1-auc:0.83102
[8]	validation_0-auc:0.85255	validation_1-auc:0.83149
[9]	validation_0-auc:0.85313	validation_1-auc:0.83270
[10]	validation_0-auc:0.85201	validation_1-auc:0.83152
[11]	validation_0-auc:0.85135	validation_1-auc:0.83049
[12]	validation_0-auc:0.85477	validation_1-auc:0.83475
[13]	validation_0-auc:0.85806	validation_1-auc:0.83636
[14]	validation_0-auc:0.85917	validation_1-auc:0.83806
[15]	validation_0-auc:0.86020	validation_1-auc:0.83918
[16]	validation_0-auc:0.86105	validation_1-auc:0.83954
[17]	validation_0-auc:0.86263	validation_1-auc:0.84038
[18]	validation_0-auc:0.86322	validation_1-auc:0.84034
[19]	validation_0-auc:0.86517	validation_1-auc:0.84122
[20]	validation_0-auc:0.86480	validation_1-auc:0.84031
[21]	validation_0-auc:0.86531	validation_1-auc:0.83992
[22]	validation_0-auc:0.86664	validation_1-auc:0.84119
[23]	validation_0-auc:0.86853	validation_1-auc:0.84193
[24]	validation_0-auc:0.86946	validation_1-auc:0.84242
[25]	validation_0-auc:0.86959	validation_1-auc:0.84288
[26]	validation_0-auc:0.87138	validation_1-auc:0.84342
[27]	validation_0-auc:0.87232	validation_1-auc:0.84393
[28]	validation_0-auc:0.87288	validation_1-auc:0.84389
[29]	validation_0-auc:0.87305	validation_1-auc:0.84433
[30]	validation_0-auc:0.87409	validation_1-auc:0.84443
[31]	validation_0-auc:0.87525	validation_1-auc:0.84503
[32]	validation_0-auc:0.87601	validation_1-auc:0.84518
[33]	validation_0-auc:0.87653	validation_1-auc:0.84519
[34]	validation_0-auc:0.87686	validation_1-auc:0.84537
[35]	validation_0-auc:0.87753	validation_1-auc:0.84511
[36]	validation_0-auc:0.87830	validation_1-auc:0.84488
[37]	validation_0-auc:0.87871	validation_1-auc:0.84480
[38]	validation_0-auc:0.87983	validation_1-auc:0.84490
[39]	validation_0-auc:0.88028	validation_1-auc:0.84515
[40]	validation_0-auc:0.88069	validation_1-auc:0.84489
[41]	validation_0-auc:0.88093	validation_1-auc:0.84478
[42]	validation_0-auc:0.88109	validation_1-auc:0.84488
[43]	validation_0-auc:0.88134	validation_1-auc:0.84480
[44]	validation_0-auc:0.88225	validation_1-auc:0.84486
[45]	validation_0-auc:0.88229	validation_1-auc:0.84486
[46]	validation_0-auc:0.88246	validation_1-auc:0.84491
[47]	validation_0-auc:0.88280	validation_1-auc:0.84497
[48]	validation_0-auc:0.88383	validation_1-auc:0.84480
[49]	validation_0-auc:0.88441	validation_1-auc:0.84503
[50]	validation_0-auc:0.88456	validation_1-auc:0.84505
[51]	validation_0-auc:0.88494	validation_1-auc:0.84472
[52]	validation_0-auc:0.88513	validation_1-auc:0.84474
[53]	validation_0-auc:0.88563	validation_1-auc:0.84425
[54]	validation_0-auc:0.88573	validation_1-auc:0.84399
[55]	validation_0-auc:0.88581	validation_1-auc:0.84406
[56]	validation_0-auc:0.88601	validation_1-auc:0.84383
[57]	validation_0-auc:0.88608	validation_1-auc:0.84384
[58]	validation_0-auc:0.88641	validation_1-auc:0.84393
[59]	validation_0-auc:0.88666	validation_1-auc:0.84390
[60]	validation_0-auc:0.88695	validation_1-auc:0.84382
[61]	validation_0-auc:0.88741	validation_1-auc:0.84367
[62]	validation_0-auc:0.88785	validation_1-auc:0.84369
[63]	validation_0-auc:0.88870	validation_1-auc:0.84367
 48%|████▊     | 24/50 [05:34<04:58, 11.49s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82127	validation_1-auc:0.80522
[1]	validation_0-auc:0.82756	validation_1-auc:0.81189
[2]	validation_0-auc:0.83309	validation_1-auc:0.81654
[3]	validation_0-auc:0.83482	validation_1-auc:0.81915
[4]	validation_0-auc:0.83925	validation_1-auc:0.82192
[5]	validation_0-auc:0.84419	validation_1-auc:0.82537
[6]	validation_0-auc:0.84788	validation_1-auc:0.82843
[7]	validation_0-auc:0.84963	validation_1-auc:0.82847
[8]	validation_0-auc:0.85354	validation_1-auc:0.82852
[9]	validation_0-auc:0.85362	validation_1-auc:0.82720
[10]	validation_0-auc:0.85269	validation_1-auc:0.82471
[11]	validation_0-auc:0.85217	validation_1-auc:0.82395
[12]	validation_0-auc:0.85565	validation_1-auc:0.82705
[13]	validation_0-auc:0.85827	validation_1-auc:0.82940
[14]	validation_0-auc:0.85970	validation_1-auc:0.83116
[15]	validation_0-auc:0.86023	validation_1-auc:0.83086
[16]	validation_0-auc:0.86202	validation_1-auc:0.83264
[17]	validation_0-auc:0.86481	validation_1-auc:0.83478
[18]	validation_0-auc:0.86508	validation_1-auc:0.83459
[19]	validation_0-auc:0.86697	validation_1-auc:0.83640
[20]	validation_0-auc:0.86714	validation_1-auc:0.83597
[21]	validation_0-auc:0.86687	validation_1-auc:0.83524
[22]	validation_0-auc:0.86870	validation_1-auc:0.83626
[23]	validation_0-auc:0.87028	validation_1-auc:0.83715
[24]	validation_0-auc:0.87094	validation_1-auc:0.83704
[25]	validation_0-auc:0.87166	validation_1-auc:0.83773
[26]	validation_0-auc:0.87323	validation_1-auc:0.83731
[27]	validation_0-auc:0.87415	validation_1-auc:0.83771
[28]	validation_0-auc:0.87456	validation_1-auc:0.83730
[29]	validation_0-auc:0.87559	validation_1-auc:0.83760
[30]	validation_0-auc:0.87655	validation_1-auc:0.83778
[31]	validation_0-auc:0.87695	validation_1-auc:0.83799
[32]	validation_0-auc:0.87751	validation_1-auc:0.83766
[33]	validation_0-auc:0.87776	validation_1-auc:0.83785
[34]	validation_0-auc:0.87824	validation_1-auc:0.83784
[35]	validation_0-auc:0.87877	validation_1-auc:0.83781
[36]	validation_0-auc:0.87971	validation_1-auc:0.83767
[37]	validation_0-auc:0.87996	validation_1-auc:0.83763
[38]	validation_0-auc:0.88119	validation_1-auc:0.83718
[39]	validation_0-auc:0.88150	validation_1-auc:0.83720
[40]	validation_0-auc:0.88186	validation_1-auc:0.83737
[41]	validation_0-auc:0.88216	validation_1-auc:0.83737
[42]	validation_0-auc:0.88300	validation_1-auc:0.83695
[43]	validation_0-auc:0.88358	validation_1-auc:0.83640
[44]	validation_0-auc:0.88439	validation_1-auc:0.83606
[45]	validation_0-auc:0.88456	validation_1-auc:0.83596
[46]	validation_0-auc:0.88518	validation_1-auc:0.83595
[47]	validation_0-auc:0.88603	validation_1-auc:0.83563
[48]	validation_0-auc:0.88625	validation_1-auc:0.83564
[49]	validation_0-auc:0.88714	validation_1-auc:0.83558
[50]	validation_0-auc:0.88753	validation_1-auc:0.83552
[51]	validation_0-auc:0.88814	validation_1-auc:0.83530
[52]	validation_0-auc:0.88830	validation_1-auc:0.83535
[53]	validation_0-auc:0.88876	validation_1-auc:0.83499
[54]	validation_0-auc:0.88889	validation_1-auc:0.83484
[55]	validation_0-auc:0.88921	validation_1-auc:0.83473
[56]	validation_0-auc:0.88930	validation_1-auc:0.83465
[57]	validation_0-auc:0.88951	validation_1-auc:0.83449
[58]	validation_0-auc:0.88982	validation_1-auc:0.83448
[59]	validation_0-auc:0.88998	validation_1-auc:0.83432
[60]	validation_0-auc:0.89035	validation_1-auc:0.83422
 48%|████▊     | 24/50 [05:37<04:58, 11.49s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81911	validation_1-auc:0.81065
[1]	validation_0-auc:0.83089	validation_1-auc:0.82480
[2]	validation_0-auc:0.83673	validation_1-auc:0.82702
[3]	validation_0-auc:0.83743	validation_1-auc:0.82872
[4]	validation_0-auc:0.84086	validation_1-auc:0.82990
[5]	validation_0-auc:0.84174	validation_1-auc:0.82687
[6]	validation_0-auc:0.84451	validation_1-auc:0.82892
[7]	validation_0-auc:0.84744	validation_1-auc:0.83193
[8]	validation_0-auc:0.84831	validation_1-auc:0.83341
[9]	validation_0-auc:0.84883	validation_1-auc:0.83402
[10]	validation_0-auc:0.84800	validation_1-auc:0.83109
[11]	validation_0-auc:0.84761	validation_1-auc:0.83005
[12]	validation_0-auc:0.85259	validation_1-auc:0.83396
[13]	validation_0-auc:0.85625	validation_1-auc:0.83751
[14]	validation_0-auc:0.85726	validation_1-auc:0.83876
[15]	validation_0-auc:0.85812	validation_1-auc:0.83672
[16]	validation_0-auc:0.86073	validation_1-auc:0.83986
[17]	validation_0-auc:0.86238	validation_1-auc:0.84057
[18]	validation_0-auc:0.86162	validation_1-auc:0.83889
[19]	validation_0-auc:0.86326	validation_1-auc:0.84026
[20]	validation_0-auc:0.86304	validation_1-auc:0.83907
[21]	validation_0-auc:0.86324	validation_1-auc:0.83802
[22]	validation_0-auc:0.86527	validation_1-auc:0.83930
[23]	validation_0-auc:0.86762	validation_1-auc:0.84013
[24]	validation_0-auc:0.86852	validation_1-auc:0.84185
[25]	validation_0-auc:0.86942	validation_1-auc:0.84233
[26]	validation_0-auc:0.87035	validation_1-auc:0.84231
[27]	validation_0-auc:0.87100	validation_1-auc:0.84294
[28]	validation_0-auc:0.87141	validation_1-auc:0.84282
[29]	validation_0-auc:0.87205	validation_1-auc:0.84359
[30]	validation_0-auc:0.87313	validation_1-auc:0.84336
[31]	validation_0-auc:0.87369	validation_1-auc:0.84397
[32]	validation_0-auc:0.87448	validation_1-auc:0.84442
[33]	validation_0-auc:0.87463	validation_1-auc:0.84474
[34]	validation_0-auc:0.87485	validation_1-auc:0.84515
[35]	validation_0-auc:0.87591	validation_1-auc:0.84569
[36]	validation_0-auc:0.87725	validation_1-auc:0.84566
[37]	validation_0-auc:0.87823	validation_1-auc:0.84582
[38]	validation_0-auc:0.87892	validation_1-auc:0.84578
[39]	validation_0-auc:0.87932	validation_1-auc:0.84590
[40]	validation_0-auc:0.87938	validation_1-auc:0.84601
[41]	validation_0-auc:0.88039	validation_1-auc:0.84588
[42]	validation_0-auc:0.88061	validation_1-auc:0.84563
[43]	validation_0-auc:0.88126	validation_1-auc:0.84570
[44]	validation_0-auc:0.88194	validation_1-auc:0.84591
[45]	validation_0-auc:0.88198	validation_1-auc:0.84622
[46]	validation_0-auc:0.88295	validation_1-auc:0.84563
[47]	validation_0-auc:0.88345	validation_1-auc:0.84542
[48]	validation_0-auc:0.88356	validation_1-auc:0.84533
[49]	validation_0-auc:0.88409	validation_1-auc:0.84500
[50]	validation_0-auc:0.88414	validation_1-auc:0.84503
[51]	validation_0-auc:0.88487	validation_1-auc:0.84501
[52]	validation_0-auc:0.88569	validation_1-auc:0.84501
[53]	validation_0-auc:0.88582	validation_1-auc:0.84500
[54]	validation_0-auc:0.88633	validation_1-auc:0.84459
[55]	validation_0-auc:0.88690	validation_1-auc:0.84470
[56]	validation_0-auc:0.88707	validation_1-auc:0.84458
[57]	validation_0-auc:0.88737	validation_1-auc:0.84478
[58]	validation_0-auc:0.88762	validation_1-auc:0.84489
[59]	validation_0-auc:0.88795	validation_1-auc:0.84464
[60]	validation_0-auc:0.88798	validation_1-auc:0.84459
[61]	validation_0-auc:0.88815	validation_1-auc:0.84450
[62]	validation_0-auc:0.88824	validation_1-auc:0.84438
[63]	validation_0-auc:0.88862	validation_1-auc:0.84402
[64]	validation_0-auc:0.88938	validation_1-auc:0.84423
[65]	validation_0-auc:0.88961	validation_1-auc:0.84420
[66]	validation_0-auc:0.88986	validation_1-auc:0.84408
[67]	validation_0-auc:0.89031	validation_1-auc:0.84407
[68]	validation_0-auc:0.89070	validation_1-auc:0.84379
[69]	validation_0-auc:0.89099	validation_1-auc:0.84365
[70]	validation_0-auc:0.89172	validation_1-auc:0.84283
[71]	validation_0-auc:0.89192	validation_1-auc:0.84285
[72]	validation_0-auc:0.89248	validation_1-auc:0.84270
[73]	validation_0-auc:0.89261	validation_1-auc:0.84277
[74]	validation_0-auc:0.89297	validation_1-auc:0.84291
 50%|█████     | 25/50 [05:40<04:23, 10.54s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82381	validation_1-auc:0.81162
[1]	validation_0-auc:0.82933	validation_1-auc:0.81326
[2]	validation_0-auc:0.83767	validation_1-auc:0.82047
[3]	validation_0-auc:0.83986	validation_1-auc:0.82147
[4]	validation_0-auc:0.84178	validation_1-auc:0.82004
[5]	validation_0-auc:0.84593	validation_1-auc:0.82458
[6]	validation_0-auc:0.85020	validation_1-auc:0.83076
[7]	validation_0-auc:0.85069	validation_1-auc:0.83016
[8]	validation_0-auc:0.85144	validation_1-auc:0.83034
[9]	validation_0-auc:0.85274	validation_1-auc:0.83391
[10]	validation_0-auc:0.85174	validation_1-auc:0.83023
[11]	validation_0-auc:0.85040	validation_1-auc:0.83012
[12]	validation_0-auc:0.85396	validation_1-auc:0.83376
[13]	validation_0-auc:0.85577	validation_1-auc:0.83455
[14]	validation_0-auc:0.85794	validation_1-auc:0.83730
[15]	validation_0-auc:0.85857	validation_1-auc:0.83885
[16]	validation_0-auc:0.85900	validation_1-auc:0.83853
[17]	validation_0-auc:0.86012	validation_1-auc:0.83891
[18]	validation_0-auc:0.86025	validation_1-auc:0.83949
[19]	validation_0-auc:0.86161	validation_1-auc:0.84019
[20]	validation_0-auc:0.86187	validation_1-auc:0.83998
[21]	validation_0-auc:0.86278	validation_1-auc:0.83982
[22]	validation_0-auc:0.86437	validation_1-auc:0.84128
[23]	validation_0-auc:0.86551	validation_1-auc:0.84134
[24]	validation_0-auc:0.86610	validation_1-auc:0.84112
[25]	validation_0-auc:0.86653	validation_1-auc:0.84140
[26]	validation_0-auc:0.86765	validation_1-auc:0.84141
[27]	validation_0-auc:0.86841	validation_1-auc:0.84193
[28]	validation_0-auc:0.86891	validation_1-auc:0.84161
[29]	validation_0-auc:0.86990	validation_1-auc:0.84181
[30]	validation_0-auc:0.87038	validation_1-auc:0.84197
[31]	validation_0-auc:0.87126	validation_1-auc:0.84213
[32]	validation_0-auc:0.87209	validation_1-auc:0.84186
[33]	validation_0-auc:0.87290	validation_1-auc:0.84248
[34]	validation_0-auc:0.87320	validation_1-auc:0.84241
[35]	validation_0-auc:0.87417	validation_1-auc:0.84291
[36]	validation_0-auc:0.87479	validation_1-auc:0.84307
[37]	validation_0-auc:0.87574	validation_1-auc:0.84301
[38]	validation_0-auc:0.87596	validation_1-auc:0.84334
[39]	validation_0-auc:0.87637	validation_1-auc:0.84353
[40]	validation_0-auc:0.87681	validation_1-auc:0.84378
[41]	validation_0-auc:0.87743	validation_1-auc:0.84366
[42]	validation_0-auc:0.87810	validation_1-auc:0.84402
[43]	validation_0-auc:0.87864	validation_1-auc:0.84430
[44]	validation_0-auc:0.87921	validation_1-auc:0.84443
[45]	validation_0-auc:0.87940	validation_1-auc:0.84441
[46]	validation_0-auc:0.87995	validation_1-auc:0.84430
[47]	validation_0-auc:0.88047	validation_1-auc:0.84428
[48]	validation_0-auc:0.88095	validation_1-auc:0.84418
[49]	validation_0-auc:0.88161	validation_1-auc:0.84421
[50]	validation_0-auc:0.88192	validation_1-auc:0.84419
[51]	validation_0-auc:0.88217	validation_1-auc:0.84434
[52]	validation_0-auc:0.88247	validation_1-auc:0.84443
[53]	validation_0-auc:0.88258	validation_1-auc:0.84450
[54]	validation_0-auc:0.88263	validation_1-auc:0.84447
[55]	validation_0-auc:0.88280	validation_1-auc:0.84450
[56]	validation_0-auc:0.88290	validation_1-auc:0.84442
[57]	validation_0-auc:0.88327	validation_1-auc:0.84437
[58]	validation_0-auc:0.88360	validation_1-auc:0.84459
[59]	validation_0-auc:0.88373	validation_1-auc:0.84446
[60]	validation_0-auc:0.88408	validation_1-auc:0.84455
[61]	validation_0-auc:0.88437	validation_1-auc:0.84469
[62]	validation_0-auc:0.88492	validation_1-auc:0.84479
[63]	validation_0-auc:0.88512	validation_1-auc:0.84473
[64]	validation_0-auc:0.88586	validation_1-auc:0.84405
[65]	validation_0-auc:0.88626	validation_1-auc:0.84407
[66]	validation_0-auc:0.88639	validation_1-auc:0.84413
[67]	validation_0-auc:0.88650	validation_1-auc:0.84400
[68]	validation_0-auc:0.88736	validation_1-auc:0.84442
[69]	validation_0-auc:0.88758	validation_1-auc:0.84449
[70]	validation_0-auc:0.88767	validation_1-auc:0.84432
[71]	validation_0-auc:0.88784	validation_1-auc:0.84434
[72]	validation_0-auc:0.88803	validation_1-auc:0.84435
[73]	validation_0-auc:0.88814	validation_1-auc:0.84441
[74]	validation_0-auc:0.88838	validation_1-auc:0.84429
[75]	validation_0-auc:0.88853	validation_1-auc:0.84422
[76]	validation_0-auc:0.88895	validation_1-auc:0.84431
[77]	validation_0-auc:0.88910	validation_1-auc:0.84441
[78]	validation_0-auc:0.88922	validation_1-auc:0.84411
[79]	validation_0-auc:0.88989	validation_1-auc:0.84434
[80]	validation_0-auc:0.89024	validation_1-auc:0.84448
[81]	validation_0-auc:0.89034	validation_1-auc:0.84440
[82]	validation_0-auc:0.89067	validation_1-auc:0.84444
[83]	validation_0-auc:0.89122	validation_1-auc:0.84448
[84]	validation_0-auc:0.89141	validation_1-auc:0.84441
[85]	validation_0-auc:0.89153	validation_1-auc:0.84453
[86]	validation_0-auc:0.89214	validation_1-auc:0.84453
[87]	validation_0-auc:0.89227	validation_1-auc:0.84437
[88]	validation_0-auc:0.89259	validation_1-auc:0.84436
[89]	validation_0-auc:0.89262	validation_1-auc:0.84434
[90]	validation_0-auc:0.89293	validation_1-auc:0.84384
[91]	validation_0-auc:0.89360	validation_1-auc:0.84369
 50%|█████     | 25/50 [05:43<04:23, 10.54s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82164	validation_1-auc:0.80574
[1]	validation_0-auc:0.82495	validation_1-auc:0.80943
[2]	validation_0-auc:0.83154	validation_1-auc:0.81516
[3]	validation_0-auc:0.83460	validation_1-auc:0.81856
[4]	validation_0-auc:0.84143	validation_1-auc:0.82548
[5]	validation_0-auc:0.84541	validation_1-auc:0.82685
[6]	validation_0-auc:0.84764	validation_1-auc:0.82923
[7]	validation_0-auc:0.84892	validation_1-auc:0.82926
[8]	validation_0-auc:0.85031	validation_1-auc:0.82940
[9]	validation_0-auc:0.85244	validation_1-auc:0.83050
[10]	validation_0-auc:0.85137	validation_1-auc:0.82751
[11]	validation_0-auc:0.85123	validation_1-auc:0.82672
[12]	validation_0-auc:0.85450	validation_1-auc:0.82936
[13]	validation_0-auc:0.85662	validation_1-auc:0.83153
[14]	validation_0-auc:0.85754	validation_1-auc:0.83297
[15]	validation_0-auc:0.85955	validation_1-auc:0.83424
[16]	validation_0-auc:0.86069	validation_1-auc:0.83538
[17]	validation_0-auc:0.86300	validation_1-auc:0.83649
[18]	validation_0-auc:0.86277	validation_1-auc:0.83669
[19]	validation_0-auc:0.86447	validation_1-auc:0.83747
[20]	validation_0-auc:0.86514	validation_1-auc:0.83698
[21]	validation_0-auc:0.86525	validation_1-auc:0.83648
[22]	validation_0-auc:0.86655	validation_1-auc:0.83767
[23]	validation_0-auc:0.86834	validation_1-auc:0.83836
[24]	validation_0-auc:0.86967	validation_1-auc:0.83919
[25]	validation_0-auc:0.87021	validation_1-auc:0.83923
[26]	validation_0-auc:0.87192	validation_1-auc:0.83906
[27]	validation_0-auc:0.87329	validation_1-auc:0.83892
[28]	validation_0-auc:0.87384	validation_1-auc:0.83900
[29]	validation_0-auc:0.87489	validation_1-auc:0.83945
[30]	validation_0-auc:0.87591	validation_1-auc:0.83965
[31]	validation_0-auc:0.87687	validation_1-auc:0.83985
[32]	validation_0-auc:0.87737	validation_1-auc:0.84038
[33]	validation_0-auc:0.87756	validation_1-auc:0.84050
[34]	validation_0-auc:0.87766	validation_1-auc:0.84072
[35]	validation_0-auc:0.87864	validation_1-auc:0.84070
[36]	validation_0-auc:0.87968	validation_1-auc:0.84100
[37]	validation_0-auc:0.88017	validation_1-auc:0.84062
[38]	validation_0-auc:0.88080	validation_1-auc:0.84007
[39]	validation_0-auc:0.88104	validation_1-auc:0.84007
[40]	validation_0-auc:0.88122	validation_1-auc:0.84009
[41]	validation_0-auc:0.88142	validation_1-auc:0.84023
[42]	validation_0-auc:0.88242	validation_1-auc:0.83954
[43]	validation_0-auc:0.88274	validation_1-auc:0.83935
[44]	validation_0-auc:0.88328	validation_1-auc:0.83955
[45]	validation_0-auc:0.88337	validation_1-auc:0.83959
[46]	validation_0-auc:0.88397	validation_1-auc:0.83915
[47]	validation_0-auc:0.88482	validation_1-auc:0.83881
[48]	validation_0-auc:0.88530	validation_1-auc:0.83906
[49]	validation_0-auc:0.88559	validation_1-auc:0.83929
[50]	validation_0-auc:0.88578	validation_1-auc:0.83936
[51]	validation_0-auc:0.88641	validation_1-auc:0.83957
[52]	validation_0-auc:0.88707	validation_1-auc:0.83973
[53]	validation_0-auc:0.88772	validation_1-auc:0.83958
[54]	validation_0-auc:0.88790	validation_1-auc:0.83930
[55]	validation_0-auc:0.88857	validation_1-auc:0.83919
[56]	validation_0-auc:0.88873	validation_1-auc:0.83931
[57]	validation_0-auc:0.88886	validation_1-auc:0.83935
[58]	validation_0-auc:0.88929	validation_1-auc:0.83903
[59]	validation_0-auc:0.88940	validation_1-auc:0.83908
[60]	validation_0-auc:0.88957	validation_1-auc:0.83919
[61]	validation_0-auc:0.89038	validation_1-auc:0.83978
[62]	validation_0-auc:0.89086	validation_1-auc:0.83956
[63]	validation_0-auc:0.89104	validation_1-auc:0.83956
[64]	validation_0-auc:0.89156	validation_1-auc:0.83940
[65]	validation_0-auc:0.89196	validation_1-auc:0.83919
 50%|█████     | 25/50 [05:46<04:23, 10.54s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81911	validation_1-auc:0.81065
[1]	validation_0-auc:0.82490	validation_1-auc:0.81372
[2]	validation_0-auc:0.83670	validation_1-auc:0.82831
[3]	validation_0-auc:0.83812	validation_1-auc:0.82794
[4]	validation_0-auc:0.84125	validation_1-auc:0.83108
[5]	validation_0-auc:0.84311	validation_1-auc:0.82961
[6]	validation_0-auc:0.84512	validation_1-auc:0.83137
[7]	validation_0-auc:0.84673	validation_1-auc:0.83340
[8]	validation_0-auc:0.84774	validation_1-auc:0.83443
[9]	validation_0-auc:0.84767	validation_1-auc:0.83426
[10]	validation_0-auc:0.84757	validation_1-auc:0.83101
[11]	validation_0-auc:0.84782	validation_1-auc:0.83001
[12]	validation_0-auc:0.85142	validation_1-auc:0.83290
[13]	validation_0-auc:0.85437	validation_1-auc:0.83654
[14]	validation_0-auc:0.85602	validation_1-auc:0.83772
[15]	validation_0-auc:0.85772	validation_1-auc:0.83828
[16]	validation_0-auc:0.85884	validation_1-auc:0.83963
[17]	validation_0-auc:0.85975	validation_1-auc:0.84021
[18]	validation_0-auc:0.85920	validation_1-auc:0.83886
[19]	validation_0-auc:0.86081	validation_1-auc:0.83930
[20]	validation_0-auc:0.86116	validation_1-auc:0.83897
[21]	validation_0-auc:0.86177	validation_1-auc:0.83856
[22]	validation_0-auc:0.86359	validation_1-auc:0.83893
[23]	validation_0-auc:0.86514	validation_1-auc:0.83969
[24]	validation_0-auc:0.86650	validation_1-auc:0.84060
[25]	validation_0-auc:0.86717	validation_1-auc:0.84086
[26]	validation_0-auc:0.86812	validation_1-auc:0.84131
[27]	validation_0-auc:0.86915	validation_1-auc:0.84129
[28]	validation_0-auc:0.86963	validation_1-auc:0.84192
[29]	validation_0-auc:0.87067	validation_1-auc:0.84220
[30]	validation_0-auc:0.87145	validation_1-auc:0.84210
[31]	validation_0-auc:0.87198	validation_1-auc:0.84258
[32]	validation_0-auc:0.87233	validation_1-auc:0.84280
[33]	validation_0-auc:0.87269	validation_1-auc:0.84284
[34]	validation_0-auc:0.87285	validation_1-auc:0.84309
[35]	validation_0-auc:0.87333	validation_1-auc:0.84371
[36]	validation_0-auc:0.87388	validation_1-auc:0.84379
[37]	validation_0-auc:0.87468	validation_1-auc:0.84365
[38]	validation_0-auc:0.87575	validation_1-auc:0.84367
[39]	validation_0-auc:0.87613	validation_1-auc:0.84389
[40]	validation_0-auc:0.87624	validation_1-auc:0.84398
[41]	validation_0-auc:0.87667	validation_1-auc:0.84404
[42]	validation_0-auc:0.87704	validation_1-auc:0.84428
[43]	validation_0-auc:0.87745	validation_1-auc:0.84427
[44]	validation_0-auc:0.87824	validation_1-auc:0.84422
[45]	validation_0-auc:0.87829	validation_1-auc:0.84457
[46]	validation_0-auc:0.87889	validation_1-auc:0.84457
[47]	validation_0-auc:0.87941	validation_1-auc:0.84456
[48]	validation_0-auc:0.87960	validation_1-auc:0.84450
[49]	validation_0-auc:0.88023	validation_1-auc:0.84447
[50]	validation_0-auc:0.88071	validation_1-auc:0.84472
[51]	validation_0-auc:0.88116	validation_1-auc:0.84429
[52]	validation_0-auc:0.88165	validation_1-auc:0.84452
[53]	validation_0-auc:0.88183	validation_1-auc:0.84466
[54]	validation_0-auc:0.88204	validation_1-auc:0.84458
[55]	validation_0-auc:0.88253	validation_1-auc:0.84479
[56]	validation_0-auc:0.88277	validation_1-auc:0.84475
[57]	validation_0-auc:0.88314	validation_1-auc:0.84470
[58]	validation_0-auc:0.88383	validation_1-auc:0.84467
[59]	validation_0-auc:0.88398	validation_1-auc:0.84476
[60]	validation_0-auc:0.88413	validation_1-auc:0.84467
[61]	validation_0-auc:0.88433	validation_1-auc:0.84478
[62]	validation_0-auc:0.88483	validation_1-auc:0.84476
[63]	validation_0-auc:0.88504	validation_1-auc:0.84493
[64]	validation_0-auc:0.88531	validation_1-auc:0.84496
[65]	validation_0-auc:0.88558	validation_1-auc:0.84493
[66]	validation_0-auc:0.88585	validation_1-auc:0.84486
[67]	validation_0-auc:0.88594	validation_1-auc:0.84465
[68]	validation_0-auc:0.88652	validation_1-auc:0.84470
[69]	validation_0-auc:0.88672	validation_1-auc:0.84467
[70]	validation_0-auc:0.88718	validation_1-auc:0.84467
[71]	validation_0-auc:0.88754	validation_1-auc:0.84420
[72]	validation_0-auc:0.88829	validation_1-auc:0.84436
[73]	validation_0-auc:0.88847	validation_1-auc:0.84445
[74]	validation_0-auc:0.88862	validation_1-auc:0.84442
[75]	validation_0-auc:0.88944	validation_1-auc:0.84449
[76]	validation_0-auc:0.89027	validation_1-auc:0.84451
[77]	validation_0-auc:0.89038	validation_1-auc:0.84452
[78]	validation_0-auc:0.89114	validation_1-auc:0.84454
[79]	validation_0-auc:0.89119	validation_1-auc:0.84447
[80]	validation_0-auc:0.89135	validation_1-auc:0.84425
[81]	validation_0-auc:0.89182	validation_1-auc:0.84404
[82]	validation_0-auc:0.89190	validation_1-auc:0.84392
[83]	validation_0-auc:0.89230	validation_1-auc:0.84391
[84]	validation_0-auc:0.89258	validation_1-auc:0.84418
[85]	validation_0-auc:0.89301	validation_1-auc:0.84420
[86]	validation_0-auc:0.89378	validation_1-auc:0.84436
[87]	validation_0-auc:0.89426	validation_1-auc:0.84414
[88]	validation_0-auc:0.89483	validation_1-auc:0.84368
[89]	validation_0-auc:0.89553	validation_1-auc:0.84359
[90]	validation_0-auc:0.89592	validation_1-auc:0.84328
[91]	validation_0-auc:0.89621	validation_1-auc:0.84301
[92]	validation_0-auc:0.89644	validation_1-auc:0.84290
[93]	validation_0-auc:0.89692	validation_1-auc:0.84258
 52%|█████▏    | 26/50 [05:50<04:11, 10.48s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82381	validation_1-auc:0.81162
[1]	validation_0-auc:0.83041	validation_1-auc:0.81360
[2]	validation_0-auc:0.83915	validation_1-auc:0.82063
[3]	validation_0-auc:0.83991	validation_1-auc:0.82057
[4]	validation_0-auc:0.84228	validation_1-auc:0.82016
[5]	validation_0-auc:0.84636	validation_1-auc:0.82496
[6]	validation_0-auc:0.85101	validation_1-auc:0.83129
[7]	validation_0-auc:0.85189	validation_1-auc:0.83126
[8]	validation_0-auc:0.85323	validation_1-auc:0.83190
[9]	validation_0-auc:0.85419	validation_1-auc:0.83256
[10]	validation_0-auc:0.85294	validation_1-auc:0.82867
[11]	validation_0-auc:0.85260	validation_1-auc:0.83028
[12]	validation_0-auc:0.85697	validation_1-auc:0.83469
[13]	validation_0-auc:0.86024	validation_1-auc:0.83629
[14]	validation_0-auc:0.86172	validation_1-auc:0.83759
[15]	validation_0-auc:0.86315	validation_1-auc:0.83895
[16]	validation_0-auc:0.86398	validation_1-auc:0.83910
[17]	validation_0-auc:0.86517	validation_1-auc:0.84008
[18]	validation_0-auc:0.86628	validation_1-auc:0.84102
[19]	validation_0-auc:0.86742	validation_1-auc:0.84125
[20]	validation_0-auc:0.86779	validation_1-auc:0.84093
[21]	validation_0-auc:0.86868	validation_1-auc:0.84158
[22]	validation_0-auc:0.87005	validation_1-auc:0.84240
[23]	validation_0-auc:0.87113	validation_1-auc:0.84285
[24]	validation_0-auc:0.87212	validation_1-auc:0.84398
[25]	validation_0-auc:0.87254	validation_1-auc:0.84441
[26]	validation_0-auc:0.87425	validation_1-auc:0.84472
[27]	validation_0-auc:0.87531	validation_1-auc:0.84512
[28]	validation_0-auc:0.87576	validation_1-auc:0.84539
[29]	validation_0-auc:0.87639	validation_1-auc:0.84517
[30]	validation_0-auc:0.87761	validation_1-auc:0.84535
[31]	validation_0-auc:0.87821	validation_1-auc:0.84545
[32]	validation_0-auc:0.87908	validation_1-auc:0.84579
[33]	validation_0-auc:0.87933	validation_1-auc:0.84562
[34]	validation_0-auc:0.87948	validation_1-auc:0.84578
[35]	validation_0-auc:0.87986	validation_1-auc:0.84597
[36]	validation_0-auc:0.88031	validation_1-auc:0.84595
[37]	validation_0-auc:0.88050	validation_1-auc:0.84590
[38]	validation_0-auc:0.88078	validation_1-auc:0.84598
[39]	validation_0-auc:0.88115	validation_1-auc:0.84594
[40]	validation_0-auc:0.88149	validation_1-auc:0.84590
[41]	validation_0-auc:0.88234	validation_1-auc:0.84573
[42]	validation_0-auc:0.88294	validation_1-auc:0.84576
[43]	validation_0-auc:0.88330	validation_1-auc:0.84556
[44]	validation_0-auc:0.88366	validation_1-auc:0.84544
[45]	validation_0-auc:0.88415	validation_1-auc:0.84550
[46]	validation_0-auc:0.88481	validation_1-auc:0.84518
[47]	validation_0-auc:0.88507	validation_1-auc:0.84524
[48]	validation_0-auc:0.88517	validation_1-auc:0.84515
[49]	validation_0-auc:0.88546	validation_1-auc:0.84515
[50]	validation_0-auc:0.88603	validation_1-auc:0.84527
[51]	validation_0-auc:0.88627	validation_1-auc:0.84539
[52]	validation_0-auc:0.88640	validation_1-auc:0.84527
[53]	validation_0-auc:0.88723	validation_1-auc:0.84494
[54]	validation_0-auc:0.88782	validation_1-auc:0.84486
[55]	validation_0-auc:0.88856	validation_1-auc:0.84473
[56]	validation_0-auc:0.88883	validation_1-auc:0.84465
[57]	validation_0-auc:0.88949	validation_1-auc:0.84445
[58]	validation_0-auc:0.89054	validation_1-auc:0.84441
[59]	validation_0-auc:0.89157	validation_1-auc:0.84445
[60]	validation_0-auc:0.89227	validation_1-auc:0.84393
[61]	validation_0-auc:0.89308	validation_1-auc:0.84441
[62]	validation_0-auc:0.89413	validation_1-auc:0.84430
[63]	validation_0-auc:0.89469	validation_1-auc:0.84446
[64]	validation_0-auc:0.89509	validation_1-auc:0.84435
[65]	validation_0-auc:0.89561	validation_1-auc:0.84457
[66]	validation_0-auc:0.89581	validation_1-auc:0.84459
[67]	validation_0-auc:0.89628	validation_1-auc:0.84464
[68]	validation_0-auc:0.89645	validation_1-auc:0.84462
 52%|█████▏    | 26/50 [05:53<04:11, 10.48s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82164	validation_1-auc:0.80574
[1]	validation_0-auc:0.82762	validation_1-auc:0.81248
[2]	validation_0-auc:0.83363	validation_1-auc:0.81822
[3]	validation_0-auc:0.83589	validation_1-auc:0.82047
[4]	validation_0-auc:0.84058	validation_1-auc:0.82424
[5]	validation_0-auc:0.84496	validation_1-auc:0.82827
[6]	validation_0-auc:0.84865	validation_1-auc:0.83031
[7]	validation_0-auc:0.85183	validation_1-auc:0.83091
[8]	validation_0-auc:0.85274	validation_1-auc:0.83028
[9]	validation_0-auc:0.85491	validation_1-auc:0.83024
[10]	validation_0-auc:0.85383	validation_1-auc:0.82875
[11]	validation_0-auc:0.85370	validation_1-auc:0.82876
[12]	validation_0-auc:0.85812	validation_1-auc:0.83233
[13]	validation_0-auc:0.86116	validation_1-auc:0.83469
[14]	validation_0-auc:0.86284	validation_1-auc:0.83611
[15]	validation_0-auc:0.86432	validation_1-auc:0.83669
[16]	validation_0-auc:0.86588	validation_1-auc:0.83681
[17]	validation_0-auc:0.86740	validation_1-auc:0.83779
[18]	validation_0-auc:0.86832	validation_1-auc:0.83753
[19]	validation_0-auc:0.86976	validation_1-auc:0.83829
[20]	validation_0-auc:0.87023	validation_1-auc:0.83771
[21]	validation_0-auc:0.87074	validation_1-auc:0.83681
[22]	validation_0-auc:0.87175	validation_1-auc:0.83758
[23]	validation_0-auc:0.87287	validation_1-auc:0.83813
[24]	validation_0-auc:0.87404	validation_1-auc:0.83826
[25]	validation_0-auc:0.87458	validation_1-auc:0.83870
[26]	validation_0-auc:0.87566	validation_1-auc:0.83846
[27]	validation_0-auc:0.87613	validation_1-auc:0.83830
[28]	validation_0-auc:0.87668	validation_1-auc:0.83818
[29]	validation_0-auc:0.87748	validation_1-auc:0.83834
[30]	validation_0-auc:0.87885	validation_1-auc:0.83794
[31]	validation_0-auc:0.88019	validation_1-auc:0.83745
[32]	validation_0-auc:0.88121	validation_1-auc:0.83730
[33]	validation_0-auc:0.88149	validation_1-auc:0.83790
[34]	validation_0-auc:0.88205	validation_1-auc:0.83752
[35]	validation_0-auc:0.88366	validation_1-auc:0.83717
[36]	validation_0-auc:0.88436	validation_1-auc:0.83723
[37]	validation_0-auc:0.88469	validation_1-auc:0.83738
[38]	validation_0-auc:0.88533	validation_1-auc:0.83708
[39]	validation_0-auc:0.88551	validation_1-auc:0.83727
[40]	validation_0-auc:0.88637	validation_1-auc:0.83754
[41]	validation_0-auc:0.88666	validation_1-auc:0.83745
[42]	validation_0-auc:0.88718	validation_1-auc:0.83736
[43]	validation_0-auc:0.88795	validation_1-auc:0.83691
[44]	validation_0-auc:0.88829	validation_1-auc:0.83682
[45]	validation_0-auc:0.88880	validation_1-auc:0.83653
[46]	validation_0-auc:0.88925	validation_1-auc:0.83657
[47]	validation_0-auc:0.88959	validation_1-auc:0.83693
[48]	validation_0-auc:0.88990	validation_1-auc:0.83685
[49]	validation_0-auc:0.89030	validation_1-auc:0.83640
[50]	validation_0-auc:0.89067	validation_1-auc:0.83624
[51]	validation_0-auc:0.89115	validation_1-auc:0.83605
[52]	validation_0-auc:0.89132	validation_1-auc:0.83595
[53]	validation_0-auc:0.89149	validation_1-auc:0.83584
[54]	validation_0-auc:0.89237	validation_1-auc:0.83595
[55]	validation_0-auc:0.89302	validation_1-auc:0.83555
 52%|█████▏    | 26/50 [05:56<04:11, 10.48s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81911	validation_1-auc:0.81065
[1]	validation_0-auc:0.83093	validation_1-auc:0.82482
[2]	validation_0-auc:0.83656	validation_1-auc:0.82733
[3]	validation_0-auc:0.83867	validation_1-auc:0.82993
[4]	validation_0-auc:0.84117	validation_1-auc:0.83188
[5]	validation_0-auc:0.84123	validation_1-auc:0.82776
[6]	validation_0-auc:0.84422	validation_1-auc:0.83157
[7]	validation_0-auc:0.84857	validation_1-auc:0.83479
[8]	validation_0-auc:0.85164	validation_1-auc:0.83756
[9]	validation_0-auc:0.85187	validation_1-auc:0.83800
[10]	validation_0-auc:0.85094	validation_1-auc:0.83454
[11]	validation_0-auc:0.85038	validation_1-auc:0.83222
[12]	validation_0-auc:0.85428	validation_1-auc:0.83639
[13]	validation_0-auc:0.85730	validation_1-auc:0.83984
[14]	validation_0-auc:0.85860	validation_1-auc:0.83950
[15]	validation_0-auc:0.86144	validation_1-auc:0.83987
[16]	validation_0-auc:0.86244	validation_1-auc:0.84085
[17]	validation_0-auc:0.86390	validation_1-auc:0.84074
[18]	validation_0-auc:0.86459	validation_1-auc:0.84081
[19]	validation_0-auc:0.86617	validation_1-auc:0.84030
[20]	validation_0-auc:0.86680	validation_1-auc:0.84084
[21]	validation_0-auc:0.86793	validation_1-auc:0.84041
[22]	validation_0-auc:0.86903	validation_1-auc:0.84182
[23]	validation_0-auc:0.87041	validation_1-auc:0.84289
[24]	validation_0-auc:0.87149	validation_1-auc:0.84383
[25]	validation_0-auc:0.87209	validation_1-auc:0.84428
[26]	validation_0-auc:0.87374	validation_1-auc:0.84356
[27]	validation_0-auc:0.87469	validation_1-auc:0.84369
[28]	validation_0-auc:0.87533	validation_1-auc:0.84353
[29]	validation_0-auc:0.87638	validation_1-auc:0.84384
[30]	validation_0-auc:0.87705	validation_1-auc:0.84345
[31]	validation_0-auc:0.87751	validation_1-auc:0.84417
[32]	validation_0-auc:0.87830	validation_1-auc:0.84397
[33]	validation_0-auc:0.87864	validation_1-auc:0.84404
[34]	validation_0-auc:0.87876	validation_1-auc:0.84409
[35]	validation_0-auc:0.88001	validation_1-auc:0.84443
[36]	validation_0-auc:0.88074	validation_1-auc:0.84476
[37]	validation_0-auc:0.88126	validation_1-auc:0.84459
[38]	validation_0-auc:0.88177	validation_1-auc:0.84481
[39]	validation_0-auc:0.88294	validation_1-auc:0.84432
[40]	validation_0-auc:0.88367	validation_1-auc:0.84452
[41]	validation_0-auc:0.88385	validation_1-auc:0.84456
[42]	validation_0-auc:0.88401	validation_1-auc:0.84448
[43]	validation_0-auc:0.88420	validation_1-auc:0.84428
[44]	validation_0-auc:0.88480	validation_1-auc:0.84388
[45]	validation_0-auc:0.88494	validation_1-auc:0.84394
[46]	validation_0-auc:0.88509	validation_1-auc:0.84410
[47]	validation_0-auc:0.88529	validation_1-auc:0.84398
[48]	validation_0-auc:0.88599	validation_1-auc:0.84408
[49]	validation_0-auc:0.88652	validation_1-auc:0.84385
[50]	validation_0-auc:0.88674	validation_1-auc:0.84377
[51]	validation_0-auc:0.88720	validation_1-auc:0.84370
[52]	validation_0-auc:0.88727	validation_1-auc:0.84367
[53]	validation_0-auc:0.88792	validation_1-auc:0.84335
[54]	validation_0-auc:0.88840	validation_1-auc:0.84309
[55]	validation_0-auc:0.88841	validation_1-auc:0.84293
[56]	validation_0-auc:0.88893	validation_1-auc:0.84311
[57]	validation_0-auc:0.88929	validation_1-auc:0.84271
[58]	validation_0-auc:0.88944	validation_1-auc:0.84281
[59]	validation_0-auc:0.89004	validation_1-auc:0.84272
[60]	validation_0-auc:0.89072	validation_1-auc:0.84236
[61]	validation_0-auc:0.89116	validation_1-auc:0.84194
[62]	validation_0-auc:0.89167	validation_1-auc:0.84162
[63]	validation_0-auc:0.89245	validation_1-auc:0.84155
[64]	validation_0-auc:0.89270	validation_1-auc:0.84184
[65]	validation_0-auc:0.89296	validation_1-auc:0.84172
[66]	validation_0-auc:0.89322	validation_1-auc:0.84175
[67]	validation_0-auc:0.89412	validation_1-auc:0.84129
 54%|█████▍    | 27/50 [05:59<03:47,  9.89s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83199	validation_1-auc:0.81350
[1]	validation_0-auc:0.83847	validation_1-auc:0.81494
[2]	validation_0-auc:0.84573	validation_1-auc:0.81755
[3]	validation_0-auc:0.85081	validation_1-auc:0.81969
[4]	validation_0-auc:0.85702	validation_1-auc:0.82233
[5]	validation_0-auc:0.86148	validation_1-auc:0.82725
[6]	validation_0-auc:0.86890	validation_1-auc:0.83353
[7]	validation_0-auc:0.87087	validation_1-auc:0.83224
[8]	validation_0-auc:0.87453	validation_1-auc:0.83368
[9]	validation_0-auc:0.87584	validation_1-auc:0.83434
[10]	validation_0-auc:0.87610	validation_1-auc:0.83359
[11]	validation_0-auc:0.87852	validation_1-auc:0.83259
[12]	validation_0-auc:0.88295	validation_1-auc:0.83456
[13]	validation_0-auc:0.88620	validation_1-auc:0.83778
[14]	validation_0-auc:0.88749	validation_1-auc:0.83992
[15]	validation_0-auc:0.88835	validation_1-auc:0.83988
[16]	validation_0-auc:0.89028	validation_1-auc:0.84171
[17]	validation_0-auc:0.89342	validation_1-auc:0.84203
[18]	validation_0-auc:0.89426	validation_1-auc:0.84078
[19]	validation_0-auc:0.89809	validation_1-auc:0.84222
[20]	validation_0-auc:0.89965	validation_1-auc:0.84119
[21]	validation_0-auc:0.90117	validation_1-auc:0.84010
[22]	validation_0-auc:0.90335	validation_1-auc:0.84072
[23]	validation_0-auc:0.90570	validation_1-auc:0.84187
[24]	validation_0-auc:0.90660	validation_1-auc:0.84162
[25]	validation_0-auc:0.90713	validation_1-auc:0.84192
[26]	validation_0-auc:0.90857	validation_1-auc:0.84192
[27]	validation_0-auc:0.91057	validation_1-auc:0.84216
[28]	validation_0-auc:0.91144	validation_1-auc:0.84223
[29]	validation_0-auc:0.91200	validation_1-auc:0.84309
[30]	validation_0-auc:0.91334	validation_1-auc:0.84303
[31]	validation_0-auc:0.91495	validation_1-auc:0.84310
[32]	validation_0-auc:0.91545	validation_1-auc:0.84346
[33]	validation_0-auc:0.91600	validation_1-auc:0.84337
[34]	validation_0-auc:0.91609	validation_1-auc:0.84355
[35]	validation_0-auc:0.91758	validation_1-auc:0.84320
[36]	validation_0-auc:0.91809	validation_1-auc:0.84304
[37]	validation_0-auc:0.91838	validation_1-auc:0.84302
[38]	validation_0-auc:0.91881	validation_1-auc:0.84317
[39]	validation_0-auc:0.91928	validation_1-auc:0.84285
[40]	validation_0-auc:0.91930	validation_1-auc:0.84280
[41]	validation_0-auc:0.91983	validation_1-auc:0.84248
[42]	validation_0-auc:0.92025	validation_1-auc:0.84266
[43]	validation_0-auc:0.92046	validation_1-auc:0.84282
[44]	validation_0-auc:0.92146	validation_1-auc:0.84242
[45]	validation_0-auc:0.92159	validation_1-auc:0.84237
[46]	validation_0-auc:0.92212	validation_1-auc:0.84220
[47]	validation_0-auc:0.92229	validation_1-auc:0.84214
[48]	validation_0-auc:0.92242	validation_1-auc:0.84208
[49]	validation_0-auc:0.92289	validation_1-auc:0.84189
[50]	validation_0-auc:0.92317	validation_1-auc:0.84206
[51]	validation_0-auc:0.92355	validation_1-auc:0.84215
[52]	validation_0-auc:0.92371	validation_1-auc:0.84209
[53]	validation_0-auc:0.92409	validation_1-auc:0.84199
[54]	validation_0-auc:0.92424	validation_1-auc:0.84212
[55]	validation_0-auc:0.92467	validation_1-auc:0.84178
[56]	validation_0-auc:0.92530	validation_1-auc:0.84176
[57]	validation_0-auc:0.92537	validation_1-auc:0.84164
[58]	validation_0-auc:0.92618	validation_1-auc:0.84128
[59]	validation_0-auc:0.92716	validation_1-auc:0.84127
[60]	validation_0-auc:0.92738	validation_1-auc:0.84089
[61]	validation_0-auc:0.92846	validation_1-auc:0.84053
[62]	validation_0-auc:0.92883	validation_1-auc:0.84011
[63]	validation_0-auc:0.92911	validation_1-auc:0.83970
 54%|█████▍    | 27/50 [06:02<03:47,  9.89s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82679	validation_1-auc:0.80735
[1]	validation_0-auc:0.83623	validation_1-auc:0.81492
[2]	validation_0-auc:0.84312	validation_1-auc:0.82091
[3]	validation_0-auc:0.84818	validation_1-auc:0.82281
[4]	validation_0-auc:0.85827	validation_1-auc:0.82634
[5]	validation_0-auc:0.86541	validation_1-auc:0.82778
[6]	validation_0-auc:0.87113	validation_1-auc:0.83070
[7]	validation_0-auc:0.87460	validation_1-auc:0.83296
[8]	validation_0-auc:0.87668	validation_1-auc:0.83245
[9]	validation_0-auc:0.87882	validation_1-auc:0.83074
[10]	validation_0-auc:0.87965	validation_1-auc:0.83021
[11]	validation_0-auc:0.88142	validation_1-auc:0.82999
[12]	validation_0-auc:0.88625	validation_1-auc:0.83369
[13]	validation_0-auc:0.89155	validation_1-auc:0.83512
[14]	validation_0-auc:0.89272	validation_1-auc:0.83662
[15]	validation_0-auc:0.89459	validation_1-auc:0.83394
[16]	validation_0-auc:0.89598	validation_1-auc:0.83574
[17]	validation_0-auc:0.89865	validation_1-auc:0.83669
[18]	validation_0-auc:0.89909	validation_1-auc:0.83565
[19]	validation_0-auc:0.90214	validation_1-auc:0.83643
[20]	validation_0-auc:0.90298	validation_1-auc:0.83538
[21]	validation_0-auc:0.90402	validation_1-auc:0.83414
[22]	validation_0-auc:0.90576	validation_1-auc:0.83371
[23]	validation_0-auc:0.90741	validation_1-auc:0.83496
[24]	validation_0-auc:0.90833	validation_1-auc:0.83490
[25]	validation_0-auc:0.90886	validation_1-auc:0.83526
[26]	validation_0-auc:0.91021	validation_1-auc:0.83506
[27]	validation_0-auc:0.91144	validation_1-auc:0.83507
[28]	validation_0-auc:0.91230	validation_1-auc:0.83483
[29]	validation_0-auc:0.91367	validation_1-auc:0.83508
[30]	validation_0-auc:0.91529	validation_1-auc:0.83338
[31]	validation_0-auc:0.91597	validation_1-auc:0.83363
[32]	validation_0-auc:0.91700	validation_1-auc:0.83444
[33]	validation_0-auc:0.91711	validation_1-auc:0.83487
[34]	validation_0-auc:0.91745	validation_1-auc:0.83485
[35]	validation_0-auc:0.91831	validation_1-auc:0.83476
[36]	validation_0-auc:0.91962	validation_1-auc:0.83460
[37]	validation_0-auc:0.92007	validation_1-auc:0.83457
[38]	validation_0-auc:0.92072	validation_1-auc:0.83406
[39]	validation_0-auc:0.92113	validation_1-auc:0.83404
[40]	validation_0-auc:0.92149	validation_1-auc:0.83367
[41]	validation_0-auc:0.92184	validation_1-auc:0.83338
[42]	validation_0-auc:0.92239	validation_1-auc:0.83265
[43]	validation_0-auc:0.92273	validation_1-auc:0.83293
[44]	validation_0-auc:0.92410	validation_1-auc:0.83231
[45]	validation_0-auc:0.92462	validation_1-auc:0.83180
[46]	validation_0-auc:0.92524	validation_1-auc:0.83160
 54%|█████▍    | 27/50 [06:05<03:47,  9.89s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82456	validation_1-auc:0.81007
[1]	validation_0-auc:0.84236	validation_1-auc:0.82497
[2]	validation_0-auc:0.85077	validation_1-auc:0.83163
[3]	validation_0-auc:0.85426	validation_1-auc:0.83283
[4]	validation_0-auc:0.85895	validation_1-auc:0.83389
[5]	validation_0-auc:0.86399	validation_1-auc:0.83311
[6]	validation_0-auc:0.86869	validation_1-auc:0.83519
[7]	validation_0-auc:0.87166	validation_1-auc:0.83457
[8]	validation_0-auc:0.87255	validation_1-auc:0.83461
[9]	validation_0-auc:0.87427	validation_1-auc:0.83145
[10]	validation_0-auc:0.87587	validation_1-auc:0.82981
[11]	validation_0-auc:0.87655	validation_1-auc:0.82884
[12]	validation_0-auc:0.88168	validation_1-auc:0.83233
[13]	validation_0-auc:0.88608	validation_1-auc:0.83620
[14]	validation_0-auc:0.88830	validation_1-auc:0.83811
[15]	validation_0-auc:0.89007	validation_1-auc:0.83584
[16]	validation_0-auc:0.89289	validation_1-auc:0.83812
[17]	validation_0-auc:0.89510	validation_1-auc:0.83885
[18]	validation_0-auc:0.89603	validation_1-auc:0.83712
[19]	validation_0-auc:0.89878	validation_1-auc:0.83805
[20]	validation_0-auc:0.90043	validation_1-auc:0.83654
[21]	validation_0-auc:0.90148	validation_1-auc:0.83510
[22]	validation_0-auc:0.90294	validation_1-auc:0.83689
[23]	validation_0-auc:0.90501	validation_1-auc:0.83829
[24]	validation_0-auc:0.90602	validation_1-auc:0.83803
[25]	validation_0-auc:0.90623	validation_1-auc:0.83906
[26]	validation_0-auc:0.90863	validation_1-auc:0.83869
[27]	validation_0-auc:0.90954	validation_1-auc:0.83944
[28]	validation_0-auc:0.91026	validation_1-auc:0.83837
[29]	validation_0-auc:0.91090	validation_1-auc:0.83913
[30]	validation_0-auc:0.91210	validation_1-auc:0.83832
[31]	validation_0-auc:0.91299	validation_1-auc:0.83940
[32]	validation_0-auc:0.91460	validation_1-auc:0.83950
[33]	validation_0-auc:0.91484	validation_1-auc:0.83954
[34]	validation_0-auc:0.91501	validation_1-auc:0.83979
[35]	validation_0-auc:0.91626	validation_1-auc:0.83995
[36]	validation_0-auc:0.91645	validation_1-auc:0.84003
[37]	validation_0-auc:0.91713	validation_1-auc:0.83953
[38]	validation_0-auc:0.91889	validation_1-auc:0.83932
[39]	validation_0-auc:0.91901	validation_1-auc:0.83927
[40]	validation_0-auc:0.91929	validation_1-auc:0.83940
[41]	validation_0-auc:0.92012	validation_1-auc:0.83883
[42]	validation_0-auc:0.92034	validation_1-auc:0.83866
[43]	validation_0-auc:0.92073	validation_1-auc:0.83866
[44]	validation_0-auc:0.92174	validation_1-auc:0.83870
[45]	validation_0-auc:0.92178	validation_1-auc:0.83867
[46]	validation_0-auc:0.92257	validation_1-auc:0.83828
[47]	validation_0-auc:0.92308	validation_1-auc:0.83807
[48]	validation_0-auc:0.92347	validation_1-auc:0.83750
[49]	validation_0-auc:0.92427	validation_1-auc:0.83758
[50]	validation_0-auc:0.92508	validation_1-auc:0.83735
[51]	validation_0-auc:0.92609	validation_1-auc:0.83725
[52]	validation_0-auc:0.92641	validation_1-auc:0.83689
[53]	validation_0-auc:0.92702	validation_1-auc:0.83683
[54]	validation_0-auc:0.92721	validation_1-auc:0.83683
[55]	validation_0-auc:0.92781	validation_1-auc:0.83704
[56]	validation_0-auc:0.92805	validation_1-auc:0.83704
[57]	validation_0-auc:0.92873	validation_1-auc:0.83672
[58]	validation_0-auc:0.92912	validation_1-auc:0.83603
[59]	validation_0-auc:0.92960	validation_1-auc:0.83572
[60]	validation_0-auc:0.92978	validation_1-auc:0.83566
[61]	validation_0-auc:0.92990	validation_1-auc:0.83560
[62]	validation_0-auc:0.93026	validation_1-auc:0.83541
[63]	validation_0-auc:0.93051	validation_1-auc:0.83514
[64]	validation_0-auc:0.93077	validation_1-auc:0.83462
[65]	validation_0-auc:0.93118	validation_1-auc:0.83445
 56%|█████▌    | 28/50 [06:09<03:42, 10.09s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82355	validation_1-auc:0.80603
[1]	validation_0-auc:0.83700	validation_1-auc:0.81635
[2]	validation_0-auc:0.83822	validation_1-auc:0.81995
[3]	validation_0-auc:0.84227	validation_1-auc:0.82086
[4]	validation_0-auc:0.84593	validation_1-auc:0.82045
[5]	validation_0-auc:0.85167	validation_1-auc:0.82669
[6]	validation_0-auc:0.85491	validation_1-auc:0.83120
[7]	validation_0-auc:0.85567	validation_1-auc:0.83075
[8]	validation_0-auc:0.85660	validation_1-auc:0.83026
[9]	validation_0-auc:0.85941	validation_1-auc:0.83385
[10]	validation_0-auc:0.85766	validation_1-auc:0.83113
[11]	validation_0-auc:0.85821	validation_1-auc:0.83135
[12]	validation_0-auc:0.86148	validation_1-auc:0.83548
[13]	validation_0-auc:0.86527	validation_1-auc:0.83804
[14]	validation_0-auc:0.86591	validation_1-auc:0.83935
[15]	validation_0-auc:0.86615	validation_1-auc:0.83911
[16]	validation_0-auc:0.86836	validation_1-auc:0.84080
[17]	validation_0-auc:0.87049	validation_1-auc:0.84111
[18]	validation_0-auc:0.86984	validation_1-auc:0.83976
[19]	validation_0-auc:0.87319	validation_1-auc:0.84117
[20]	validation_0-auc:0.87312	validation_1-auc:0.83971
[21]	validation_0-auc:0.87454	validation_1-auc:0.83898
[22]	validation_0-auc:0.87755	validation_1-auc:0.84097
[23]	validation_0-auc:0.87966	validation_1-auc:0.84168
[24]	validation_0-auc:0.88084	validation_1-auc:0.84211
[25]	validation_0-auc:0.88189	validation_1-auc:0.84316
[26]	validation_0-auc:0.88338	validation_1-auc:0.84256
[27]	validation_0-auc:0.88521	validation_1-auc:0.84330
[28]	validation_0-auc:0.88624	validation_1-auc:0.84311
[29]	validation_0-auc:0.88766	validation_1-auc:0.84304
[30]	validation_0-auc:0.88857	validation_1-auc:0.84291
[31]	validation_0-auc:0.89072	validation_1-auc:0.84373
[32]	validation_0-auc:0.89163	validation_1-auc:0.84444
[33]	validation_0-auc:0.89260	validation_1-auc:0.84442
[34]	validation_0-auc:0.89308	validation_1-auc:0.84439
[35]	validation_0-auc:0.89453	validation_1-auc:0.84520
[36]	validation_0-auc:0.89546	validation_1-auc:0.84518
[37]	validation_0-auc:0.89669	validation_1-auc:0.84508
[38]	validation_0-auc:0.89728	validation_1-auc:0.84524
[39]	validation_0-auc:0.89786	validation_1-auc:0.84552
[40]	validation_0-auc:0.89829	validation_1-auc:0.84572
[41]	validation_0-auc:0.89931	validation_1-auc:0.84588
[42]	validation_0-auc:0.89994	validation_1-auc:0.84593
[43]	validation_0-auc:0.90015	validation_1-auc:0.84631
[44]	validation_0-auc:0.90042	validation_1-auc:0.84605
[45]	validation_0-auc:0.90079	validation_1-auc:0.84594
[46]	validation_0-auc:0.90152	validation_1-auc:0.84582
[47]	validation_0-auc:0.90253	validation_1-auc:0.84606
[48]	validation_0-auc:0.90280	validation_1-auc:0.84607
[49]	validation_0-auc:0.90366	validation_1-auc:0.84588
[50]	validation_0-auc:0.90479	validation_1-auc:0.84612
[51]	validation_0-auc:0.90537	validation_1-auc:0.84650
[52]	validation_0-auc:0.90550	validation_1-auc:0.84662
[53]	validation_0-auc:0.90617	validation_1-auc:0.84688
[54]	validation_0-auc:0.90683	validation_1-auc:0.84679
[55]	validation_0-auc:0.90709	validation_1-auc:0.84687
[56]	validation_0-auc:0.90751	validation_1-auc:0.84680
[57]	validation_0-auc:0.90789	validation_1-auc:0.84674
[58]	validation_0-auc:0.90799	validation_1-auc:0.84676
[59]	validation_0-auc:0.90816	validation_1-auc:0.84671
[60]	validation_0-auc:0.90857	validation_1-auc:0.84661
[61]	validation_0-auc:0.90880	validation_1-auc:0.84664
[62]	validation_0-auc:0.90909	validation_1-auc:0.84669
[63]	validation_0-auc:0.90924	validation_1-auc:0.84671
[64]	validation_0-auc:0.91048	validation_1-auc:0.84643
[65]	validation_0-auc:0.91062	validation_1-auc:0.84636
[66]	validation_0-auc:0.91081	validation_1-auc:0.84643
[67]	validation_0-auc:0.91154	validation_1-auc:0.84623
[68]	validation_0-auc:0.91161	validation_1-auc:0.84625
[69]	validation_0-auc:0.91177	validation_1-auc:0.84626
[70]	validation_0-auc:0.91193	validation_1-auc:0.84616
[71]	validation_0-auc:0.91232	validation_1-auc:0.84603
[72]	validation_0-auc:0.91273	validation_1-auc:0.84598
[73]	validation_0-auc:0.91296	validation_1-auc:0.84593
[74]	validation_0-auc:0.91330	validation_1-auc:0.84600
[75]	validation_0-auc:0.91386	validation_1-auc:0.84573
[76]	validation_0-auc:0.91427	validation_1-auc:0.84576
[77]	validation_0-auc:0.91439	validation_1-auc:0.84563
[78]	validation_0-auc:0.91457	validation_1-auc:0.84556
[79]	validation_0-auc:0.91464	validation_1-auc:0.84554
[80]	validation_0-auc:0.91479	validation_1-auc:0.84571
[81]	validation_0-auc:0.91523	validation_1-auc:0.84563
[82]	validation_0-auc:0.91535	validation_1-auc:0.84552
[83]	validation_0-auc:0.91560	validation_1-auc:0.84525
 56%|█████▌    | 28/50 [06:13<03:42, 10.09s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81064	validation_1-auc:0.79146
[1]	validation_0-auc:0.82629	validation_1-auc:0.80362
[2]	validation_0-auc:0.83504	validation_1-auc:0.81132
[3]	validation_0-auc:0.83980	validation_1-auc:0.81704
[4]	validation_0-auc:0.84554	validation_1-auc:0.82025
[5]	validation_0-auc:0.84947	validation_1-auc:0.82257
[6]	validation_0-auc:0.85320	validation_1-auc:0.82358
[7]	validation_0-auc:0.85505	validation_1-auc:0.82484
[8]	validation_0-auc:0.85660	validation_1-auc:0.82588
[9]	validation_0-auc:0.85907	validation_1-auc:0.82654
[10]	validation_0-auc:0.85871	validation_1-auc:0.82347
[11]	validation_0-auc:0.86064	validation_1-auc:0.82407
[12]	validation_0-auc:0.86562	validation_1-auc:0.82738
[13]	validation_0-auc:0.86777	validation_1-auc:0.82869
[14]	validation_0-auc:0.86880	validation_1-auc:0.83131
[15]	validation_0-auc:0.87015	validation_1-auc:0.82996
[16]	validation_0-auc:0.87151	validation_1-auc:0.83160
[17]	validation_0-auc:0.87413	validation_1-auc:0.83306
[18]	validation_0-auc:0.87359	validation_1-auc:0.83251
[19]	validation_0-auc:0.87742	validation_1-auc:0.83358
[20]	validation_0-auc:0.87782	validation_1-auc:0.83282
[21]	validation_0-auc:0.87788	validation_1-auc:0.83224
[22]	validation_0-auc:0.88035	validation_1-auc:0.83283
[23]	validation_0-auc:0.88374	validation_1-auc:0.83406
[24]	validation_0-auc:0.88492	validation_1-auc:0.83481
[25]	validation_0-auc:0.88635	validation_1-auc:0.83567
[26]	validation_0-auc:0.88880	validation_1-auc:0.83490
[27]	validation_0-auc:0.89023	validation_1-auc:0.83523
[28]	validation_0-auc:0.89114	validation_1-auc:0.83492
[29]	validation_0-auc:0.89247	validation_1-auc:0.83532
[30]	validation_0-auc:0.89350	validation_1-auc:0.83475
[31]	validation_0-auc:0.89534	validation_1-auc:0.83558
[32]	validation_0-auc:0.89672	validation_1-auc:0.83615
[33]	validation_0-auc:0.89692	validation_1-auc:0.83633
[34]	validation_0-auc:0.89763	validation_1-auc:0.83595
[35]	validation_0-auc:0.89845	validation_1-auc:0.83669
[36]	validation_0-auc:0.89912	validation_1-auc:0.83612
[37]	validation_0-auc:0.89964	validation_1-auc:0.83591
[38]	validation_0-auc:0.90067	validation_1-auc:0.83593
[39]	validation_0-auc:0.90135	validation_1-auc:0.83601
[40]	validation_0-auc:0.90179	validation_1-auc:0.83587
[41]	validation_0-auc:0.90265	validation_1-auc:0.83585
[42]	validation_0-auc:0.90313	validation_1-auc:0.83597
[43]	validation_0-auc:0.90364	validation_1-auc:0.83618
[44]	validation_0-auc:0.90448	validation_1-auc:0.83560
[45]	validation_0-auc:0.90485	validation_1-auc:0.83581
[46]	validation_0-auc:0.90525	validation_1-auc:0.83559
[47]	validation_0-auc:0.90591	validation_1-auc:0.83545
[48]	validation_0-auc:0.90656	validation_1-auc:0.83562
[49]	validation_0-auc:0.90702	validation_1-auc:0.83537
[50]	validation_0-auc:0.90746	validation_1-auc:0.83542
[51]	validation_0-auc:0.90803	validation_1-auc:0.83534
[52]	validation_0-auc:0.90809	validation_1-auc:0.83557
[53]	validation_0-auc:0.90870	validation_1-auc:0.83555
[54]	validation_0-auc:0.90896	validation_1-auc:0.83529
[55]	validation_0-auc:0.90973	validation_1-auc:0.83535
[56]	validation_0-auc:0.90999	validation_1-auc:0.83526
[57]	validation_0-auc:0.91061	validation_1-auc:0.83470
[58]	validation_0-auc:0.91136	validation_1-auc:0.83453
[59]	validation_0-auc:0.91150	validation_1-auc:0.83456
[60]	validation_0-auc:0.91180	validation_1-auc:0.83434
[61]	validation_0-auc:0.91212	validation_1-auc:0.83404
[62]	validation_0-auc:0.91237	validation_1-auc:0.83391
[63]	validation_0-auc:0.91250	validation_1-auc:0.83386
[64]	validation_0-auc:0.91279	validation_1-auc:0.83379
 56%|█████▌    | 28/50 [06:16<03:42, 10.09s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81694	validation_1-auc:0.80736
[1]	validation_0-auc:0.82987	validation_1-auc:0.81507
[2]	validation_0-auc:0.83661	validation_1-auc:0.82241
[3]	validation_0-auc:0.83909	validation_1-auc:0.82335
[4]	validation_0-auc:0.84588	validation_1-auc:0.82740
[5]	validation_0-auc:0.84682	validation_1-auc:0.82596
[6]	validation_0-auc:0.85035	validation_1-auc:0.82921
[7]	validation_0-auc:0.85223	validation_1-auc:0.83051
[8]	validation_0-auc:0.85427	validation_1-auc:0.83274
[9]	validation_0-auc:0.85492	validation_1-auc:0.83138
[10]	validation_0-auc:0.85660	validation_1-auc:0.82918
[11]	validation_0-auc:0.85697	validation_1-auc:0.82917
[12]	validation_0-auc:0.86036	validation_1-auc:0.83149
[13]	validation_0-auc:0.86347	validation_1-auc:0.83461
[14]	validation_0-auc:0.86493	validation_1-auc:0.83615
[15]	validation_0-auc:0.86536	validation_1-auc:0.83426
[16]	validation_0-auc:0.86773	validation_1-auc:0.83576
[17]	validation_0-auc:0.87058	validation_1-auc:0.83939
[18]	validation_0-auc:0.87035	validation_1-auc:0.83800
[19]	validation_0-auc:0.87352	validation_1-auc:0.83931
[20]	validation_0-auc:0.87334	validation_1-auc:0.83915
[21]	validation_0-auc:0.87342	validation_1-auc:0.83781
[22]	validation_0-auc:0.87622	validation_1-auc:0.83882
[23]	validation_0-auc:0.87787	validation_1-auc:0.84004
[24]	validation_0-auc:0.88006	validation_1-auc:0.84023
[25]	validation_0-auc:0.88106	validation_1-auc:0.84062
[26]	validation_0-auc:0.88257	validation_1-auc:0.84064
[27]	validation_0-auc:0.88442	validation_1-auc:0.84137
[28]	validation_0-auc:0.88503	validation_1-auc:0.84119
[29]	validation_0-auc:0.88659	validation_1-auc:0.84233
[30]	validation_0-auc:0.88780	validation_1-auc:0.84211
[31]	validation_0-auc:0.88934	validation_1-auc:0.84254
[32]	validation_0-auc:0.89073	validation_1-auc:0.84292
[33]	validation_0-auc:0.89186	validation_1-auc:0.84358
[34]	validation_0-auc:0.89245	validation_1-auc:0.84429
[35]	validation_0-auc:0.89315	validation_1-auc:0.84466
[36]	validation_0-auc:0.89422	validation_1-auc:0.84459
[37]	validation_0-auc:0.89538	validation_1-auc:0.84471
[38]	validation_0-auc:0.89620	validation_1-auc:0.84481
[39]	validation_0-auc:0.89679	validation_1-auc:0.84492
[40]	validation_0-auc:0.89794	validation_1-auc:0.84461
[41]	validation_0-auc:0.89842	validation_1-auc:0.84477
[42]	validation_0-auc:0.89917	validation_1-auc:0.84485
[43]	validation_0-auc:0.89940	validation_1-auc:0.84497
[44]	validation_0-auc:0.89991	validation_1-auc:0.84484
[45]	validation_0-auc:0.90038	validation_1-auc:0.84515
[46]	validation_0-auc:0.90121	validation_1-auc:0.84523
[47]	validation_0-auc:0.90229	validation_1-auc:0.84522
[48]	validation_0-auc:0.90315	validation_1-auc:0.84508
[49]	validation_0-auc:0.90344	validation_1-auc:0.84508
[50]	validation_0-auc:0.90440	validation_1-auc:0.84473
[51]	validation_0-auc:0.90491	validation_1-auc:0.84458
[52]	validation_0-auc:0.90518	validation_1-auc:0.84466
[53]	validation_0-auc:0.90534	validation_1-auc:0.84475
[54]	validation_0-auc:0.90647	validation_1-auc:0.84456
[55]	validation_0-auc:0.90666	validation_1-auc:0.84452
[56]	validation_0-auc:0.90726	validation_1-auc:0.84454
[57]	validation_0-auc:0.90739	validation_1-auc:0.84460
[58]	validation_0-auc:0.90786	validation_1-auc:0.84456
[59]	validation_0-auc:0.90799	validation_1-auc:0.84446
[60]	validation_0-auc:0.90808	validation_1-auc:0.84453
[61]	validation_0-auc:0.90841	validation_1-auc:0.84441
[62]	validation_0-auc:0.90884	validation_1-auc:0.84427
[63]	validation_0-auc:0.90898	validation_1-auc:0.84407
[64]	validation_0-auc:0.90994	validation_1-auc:0.84424
[65]	validation_0-auc:0.91037	validation_1-auc:0.84443
[66]	validation_0-auc:0.91059	validation_1-auc:0.84429
[67]	validation_0-auc:0.91077	validation_1-auc:0.84415
[68]	validation_0-auc:0.91100	validation_1-auc:0.84406
[69]	validation_0-auc:0.91150	validation_1-auc:0.84412
[70]	validation_0-auc:0.91162	validation_1-auc:0.84410
[71]	validation_0-auc:0.91171	validation_1-auc:0.84413
[72]	validation_0-auc:0.91188	validation_1-auc:0.84435
[73]	validation_0-auc:0.91253	validation_1-auc:0.84429
[74]	validation_0-auc:0.91338	validation_1-auc:0.84424
[75]	validation_0-auc:0.91363	validation_1-auc:0.84416
[76]	validation_0-auc:0.91368	validation_1-auc:0.84428
 58%|█████▊    | 29/50 [06:19<03:30, 10.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82381	validation_1-auc:0.81162
[1]	validation_0-auc:0.82933	validation_1-auc:0.81326
[2]	validation_0-auc:0.83773	validation_1-auc:0.82041
[3]	validation_0-auc:0.83991	validation_1-auc:0.82143
[4]	validation_0-auc:0.84145	validation_1-auc:0.81923
[5]	validation_0-auc:0.84245	validation_1-auc:0.82087
[6]	validation_0-auc:0.84415	validation_1-auc:0.82374
[7]	validation_0-auc:0.84766	validation_1-auc:0.82633
[8]	validation_0-auc:0.84857	validation_1-auc:0.82717
[9]	validation_0-auc:0.85102	validation_1-auc:0.82998
[10]	validation_0-auc:0.85129	validation_1-auc:0.83182
[11]	validation_0-auc:0.84987	validation_1-auc:0.83089
[12]	validation_0-auc:0.85307	validation_1-auc:0.83515
[13]	validation_0-auc:0.85564	validation_1-auc:0.83656
[14]	validation_0-auc:0.85719	validation_1-auc:0.83769
[15]	validation_0-auc:0.85843	validation_1-auc:0.83855
[16]	validation_0-auc:0.85889	validation_1-auc:0.83896
[17]	validation_0-auc:0.85992	validation_1-auc:0.83838
[18]	validation_0-auc:0.86105	validation_1-auc:0.83934
[19]	validation_0-auc:0.86174	validation_1-auc:0.83945
[20]	validation_0-auc:0.86357	validation_1-auc:0.84008
[21]	validation_0-auc:0.86486	validation_1-auc:0.84059
[22]	validation_0-auc:0.86631	validation_1-auc:0.84116
[23]	validation_0-auc:0.86693	validation_1-auc:0.84132
[24]	validation_0-auc:0.86775	validation_1-auc:0.84136
[25]	validation_0-auc:0.86824	validation_1-auc:0.84183
[26]	validation_0-auc:0.86944	validation_1-auc:0.84225
[27]	validation_0-auc:0.87011	validation_1-auc:0.84288
[28]	validation_0-auc:0.87085	validation_1-auc:0.84316
[29]	validation_0-auc:0.87172	validation_1-auc:0.84329
[30]	validation_0-auc:0.87242	validation_1-auc:0.84347
[31]	validation_0-auc:0.87307	validation_1-auc:0.84383
[32]	validation_0-auc:0.87358	validation_1-auc:0.84355
[33]	validation_0-auc:0.87387	validation_1-auc:0.84376
[34]	validation_0-auc:0.87416	validation_1-auc:0.84393
[35]	validation_0-auc:0.87487	validation_1-auc:0.84404
[36]	validation_0-auc:0.87524	validation_1-auc:0.84415
[37]	validation_0-auc:0.87559	validation_1-auc:0.84430
[38]	validation_0-auc:0.87678	validation_1-auc:0.84473
[39]	validation_0-auc:0.87703	validation_1-auc:0.84478
[40]	validation_0-auc:0.87744	validation_1-auc:0.84477
[41]	validation_0-auc:0.87763	validation_1-auc:0.84463
[42]	validation_0-auc:0.87828	validation_1-auc:0.84505
[43]	validation_0-auc:0.87858	validation_1-auc:0.84488
[44]	validation_0-auc:0.87923	validation_1-auc:0.84500
[45]	validation_0-auc:0.87953	validation_1-auc:0.84523
[46]	validation_0-auc:0.88023	validation_1-auc:0.84526
[47]	validation_0-auc:0.88073	validation_1-auc:0.84511
[48]	validation_0-auc:0.88090	validation_1-auc:0.84495
[49]	validation_0-auc:0.88105	validation_1-auc:0.84500
[50]	validation_0-auc:0.88137	validation_1-auc:0.84501
[51]	validation_0-auc:0.88224	validation_1-auc:0.84498
[52]	validation_0-auc:0.88252	validation_1-auc:0.84528
[53]	validation_0-auc:0.88274	validation_1-auc:0.84533
[54]	validation_0-auc:0.88291	validation_1-auc:0.84531
[55]	validation_0-auc:0.88346	validation_1-auc:0.84526
[56]	validation_0-auc:0.88407	validation_1-auc:0.84522
[57]	validation_0-auc:0.88450	validation_1-auc:0.84509
[58]	validation_0-auc:0.88461	validation_1-auc:0.84488
[59]	validation_0-auc:0.88486	validation_1-auc:0.84491
[60]	validation_0-auc:0.88499	validation_1-auc:0.84497
[61]	validation_0-auc:0.88561	validation_1-auc:0.84512
[62]	validation_0-auc:0.88600	validation_1-auc:0.84482
[63]	validation_0-auc:0.88634	validation_1-auc:0.84490
[64]	validation_0-auc:0.88690	validation_1-auc:0.84458
[65]	validation_0-auc:0.88729	validation_1-auc:0.84472
[66]	validation_0-auc:0.88791	validation_1-auc:0.84496
[67]	validation_0-auc:0.88847	validation_1-auc:0.84489
[68]	validation_0-auc:0.88856	validation_1-auc:0.84480
[69]	validation_0-auc:0.88905	validation_1-auc:0.84469
[70]	validation_0-auc:0.88936	validation_1-auc:0.84464
[71]	validation_0-auc:0.88955	validation_1-auc:0.84449
[72]	validation_0-auc:0.88963	validation_1-auc:0.84438
[73]	validation_0-auc:0.88973	validation_1-auc:0.84435
[74]	validation_0-auc:0.88979	validation_1-auc:0.84428
[75]	validation_0-auc:0.88992	validation_1-auc:0.84416
[76]	validation_0-auc:0.89031	validation_1-auc:0.84408
[77]	validation_0-auc:0.89040	validation_1-auc:0.84410
[78]	validation_0-auc:0.89055	validation_1-auc:0.84406
[79]	validation_0-auc:0.89074	validation_1-auc:0.84400
[80]	validation_0-auc:0.89102	validation_1-auc:0.84411
[81]	validation_0-auc:0.89112	validation_1-auc:0.84400
[82]	validation_0-auc:0.89138	validation_1-auc:0.84408
 58%|█████▊    | 29/50 [06:22<03:30, 10.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82164	validation_1-auc:0.80574
[1]	validation_0-auc:0.82755	validation_1-auc:0.81239
[2]	validation_0-auc:0.83287	validation_1-auc:0.81690
[3]	validation_0-auc:0.83565	validation_1-auc:0.81985
[4]	validation_0-auc:0.84175	validation_1-auc:0.82484
[5]	validation_0-auc:0.84217	validation_1-auc:0.82436
[6]	validation_0-auc:0.84610	validation_1-auc:0.82749
[7]	validation_0-auc:0.84809	validation_1-auc:0.82843
[8]	validation_0-auc:0.84867	validation_1-auc:0.82873
[9]	validation_0-auc:0.85117	validation_1-auc:0.82944
[10]	validation_0-auc:0.85113	validation_1-auc:0.82840
[11]	validation_0-auc:0.85110	validation_1-auc:0.82704
[12]	validation_0-auc:0.85421	validation_1-auc:0.82830
[13]	validation_0-auc:0.85676	validation_1-auc:0.83107
[14]	validation_0-auc:0.85813	validation_1-auc:0.83374
[15]	validation_0-auc:0.86055	validation_1-auc:0.83428
[16]	validation_0-auc:0.86096	validation_1-auc:0.83539
[17]	validation_0-auc:0.86254	validation_1-auc:0.83588
[18]	validation_0-auc:0.86306	validation_1-auc:0.83554
[19]	validation_0-auc:0.86530	validation_1-auc:0.83658
[20]	validation_0-auc:0.86627	validation_1-auc:0.83733
[21]	validation_0-auc:0.86672	validation_1-auc:0.83682
[22]	validation_0-auc:0.86788	validation_1-auc:0.83745
[23]	validation_0-auc:0.86883	validation_1-auc:0.83810
[24]	validation_0-auc:0.86950	validation_1-auc:0.83872
[25]	validation_0-auc:0.87000	validation_1-auc:0.83922
[26]	validation_0-auc:0.87131	validation_1-auc:0.83853
[27]	validation_0-auc:0.87230	validation_1-auc:0.83852
[28]	validation_0-auc:0.87350	validation_1-auc:0.83870
[29]	validation_0-auc:0.87468	validation_1-auc:0.83849
[30]	validation_0-auc:0.87579	validation_1-auc:0.83812
[31]	validation_0-auc:0.87634	validation_1-auc:0.83813
[32]	validation_0-auc:0.87680	validation_1-auc:0.83792
[33]	validation_0-auc:0.87708	validation_1-auc:0.83802
[34]	validation_0-auc:0.87741	validation_1-auc:0.83827
[35]	validation_0-auc:0.87772	validation_1-auc:0.83868
[36]	validation_0-auc:0.87822	validation_1-auc:0.83857
[37]	validation_0-auc:0.87919	validation_1-auc:0.83865
[38]	validation_0-auc:0.87964	validation_1-auc:0.83854
[39]	validation_0-auc:0.87987	validation_1-auc:0.83868
[40]	validation_0-auc:0.88038	validation_1-auc:0.83842
[41]	validation_0-auc:0.88061	validation_1-auc:0.83853
[42]	validation_0-auc:0.88121	validation_1-auc:0.83826
[43]	validation_0-auc:0.88181	validation_1-auc:0.83839
[44]	validation_0-auc:0.88300	validation_1-auc:0.83844
[45]	validation_0-auc:0.88324	validation_1-auc:0.83850
[46]	validation_0-auc:0.88371	validation_1-auc:0.83856
[47]	validation_0-auc:0.88432	validation_1-auc:0.83847
[48]	validation_0-auc:0.88465	validation_1-auc:0.83847
[49]	validation_0-auc:0.88497	validation_1-auc:0.83849
[50]	validation_0-auc:0.88573	validation_1-auc:0.83879
[51]	validation_0-auc:0.88637	validation_1-auc:0.83852
[52]	validation_0-auc:0.88647	validation_1-auc:0.83858
[53]	validation_0-auc:0.88688	validation_1-auc:0.83868
[54]	validation_0-auc:0.88740	validation_1-auc:0.83843
 58%|█████▊    | 29/50 [06:25<03:30, 10.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81911	validation_1-auc:0.81065
[1]	validation_0-auc:0.82491	validation_1-auc:0.81370
[2]	validation_0-auc:0.83670	validation_1-auc:0.82831
[3]	validation_0-auc:0.83811	validation_1-auc:0.82792
[4]	validation_0-auc:0.84087	validation_1-auc:0.82974
[5]	validation_0-auc:0.84275	validation_1-auc:0.82968
[6]	validation_0-auc:0.84252	validation_1-auc:0.82808
[7]	validation_0-auc:0.84386	validation_1-auc:0.83083
[8]	validation_0-auc:0.84479	validation_1-auc:0.83124
[9]	validation_0-auc:0.84758	validation_1-auc:0.83622
[10]	validation_0-auc:0.84741	validation_1-auc:0.83435
[11]	validation_0-auc:0.84658	validation_1-auc:0.83279
[12]	validation_0-auc:0.85182	validation_1-auc:0.83591
[13]	validation_0-auc:0.85478	validation_1-auc:0.83849
[14]	validation_0-auc:0.85655	validation_1-auc:0.84022
[15]	validation_0-auc:0.85780	validation_1-auc:0.84023
[16]	validation_0-auc:0.85926	validation_1-auc:0.84122
[17]	validation_0-auc:0.85997	validation_1-auc:0.84130
[18]	validation_0-auc:0.86092	validation_1-auc:0.84118
[19]	validation_0-auc:0.86242	validation_1-auc:0.84191
[20]	validation_0-auc:0.86371	validation_1-auc:0.84285
[21]	validation_0-auc:0.86483	validation_1-auc:0.84190
[22]	validation_0-auc:0.86599	validation_1-auc:0.84202
[23]	validation_0-auc:0.86711	validation_1-auc:0.84271
[24]	validation_0-auc:0.86826	validation_1-auc:0.84346
[25]	validation_0-auc:0.86869	validation_1-auc:0.84297
[26]	validation_0-auc:0.86941	validation_1-auc:0.84356
[27]	validation_0-auc:0.87016	validation_1-auc:0.84309
[28]	validation_0-auc:0.87069	validation_1-auc:0.84344
[29]	validation_0-auc:0.87134	validation_1-auc:0.84374
[30]	validation_0-auc:0.87190	validation_1-auc:0.84406
[31]	validation_0-auc:0.87289	validation_1-auc:0.84491
[32]	validation_0-auc:0.87368	validation_1-auc:0.84529
[33]	validation_0-auc:0.87419	validation_1-auc:0.84525
[34]	validation_0-auc:0.87475	validation_1-auc:0.84555
[35]	validation_0-auc:0.87516	validation_1-auc:0.84571
[36]	validation_0-auc:0.87586	validation_1-auc:0.84571
[37]	validation_0-auc:0.87650	validation_1-auc:0.84580
[38]	validation_0-auc:0.87745	validation_1-auc:0.84604
[39]	validation_0-auc:0.87768	validation_1-auc:0.84628
[40]	validation_0-auc:0.87854	validation_1-auc:0.84597
[41]	validation_0-auc:0.87894	validation_1-auc:0.84602
[42]	validation_0-auc:0.87916	validation_1-auc:0.84631
[43]	validation_0-auc:0.87982	validation_1-auc:0.84642
[44]	validation_0-auc:0.88028	validation_1-auc:0.84657
[45]	validation_0-auc:0.88059	validation_1-auc:0.84636
[46]	validation_0-auc:0.88083	validation_1-auc:0.84622
[47]	validation_0-auc:0.88127	validation_1-auc:0.84616
[48]	validation_0-auc:0.88146	validation_1-auc:0.84611
[49]	validation_0-auc:0.88178	validation_1-auc:0.84621
[50]	validation_0-auc:0.88232	validation_1-auc:0.84628
[51]	validation_0-auc:0.88230	validation_1-auc:0.84623
[52]	validation_0-auc:0.88246	validation_1-auc:0.84606
[53]	validation_0-auc:0.88253	validation_1-auc:0.84609
[54]	validation_0-auc:0.88298	validation_1-auc:0.84611
[55]	validation_0-auc:0.88361	validation_1-auc:0.84622
[56]	validation_0-auc:0.88458	validation_1-auc:0.84622
[57]	validation_0-auc:0.88484	validation_1-auc:0.84614
[58]	validation_0-auc:0.88540	validation_1-auc:0.84654
[59]	validation_0-auc:0.88554	validation_1-auc:0.84638
[60]	validation_0-auc:0.88597	validation_1-auc:0.84629
[61]	validation_0-auc:0.88626	validation_1-auc:0.84639
[62]	validation_0-auc:0.88649	validation_1-auc:0.84616
[63]	validation_0-auc:0.88699	validation_1-auc:0.84611
[64]	validation_0-auc:0.88731	validation_1-auc:0.84597
[65]	validation_0-auc:0.88762	validation_1-auc:0.84580
[66]	validation_0-auc:0.88782	validation_1-auc:0.84565
[67]	validation_0-auc:0.88805	validation_1-auc:0.84551
[68]	validation_0-auc:0.88864	validation_1-auc:0.84552
[69]	validation_0-auc:0.88884	validation_1-auc:0.84560
[70]	validation_0-auc:0.88921	validation_1-auc:0.84566
[71]	validation_0-auc:0.88939	validation_1-auc:0.84538
[72]	validation_0-auc:0.89038	validation_1-auc:0.84526
[73]	validation_0-auc:0.89068	validation_1-auc:0.84485
[74]	validation_0-auc:0.89089	validation_1-auc:0.84488
 60%|██████    | 30/50 [06:29<03:17,  9.87s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83217	validation_1-auc:0.81347
[1]	validation_0-auc:0.84029	validation_1-auc:0.81620
[2]	validation_0-auc:0.84825	validation_1-auc:0.81894
[3]	validation_0-auc:0.85312	validation_1-auc:0.81957
[4]	validation_0-auc:0.85787	validation_1-auc:0.82228
[5]	validation_0-auc:0.86060	validation_1-auc:0.82395
[6]	validation_0-auc:0.86305	validation_1-auc:0.82488
[7]	validation_0-auc:0.86810	validation_1-auc:0.82718
[8]	validation_0-auc:0.87090	validation_1-auc:0.82819
[9]	validation_0-auc:0.87601	validation_1-auc:0.83226
[10]	validation_0-auc:0.87765	validation_1-auc:0.83425
[11]	validation_0-auc:0.87903	validation_1-auc:0.83273
[12]	validation_0-auc:0.88257	validation_1-auc:0.83543
[13]	validation_0-auc:0.88618	validation_1-auc:0.83659
[14]	validation_0-auc:0.88837	validation_1-auc:0.83839
[15]	validation_0-auc:0.89167	validation_1-auc:0.83990
[16]	validation_0-auc:0.89460	validation_1-auc:0.83997
[17]	validation_0-auc:0.89637	validation_1-auc:0.83999
[18]	validation_0-auc:0.89735	validation_1-auc:0.83957
[19]	validation_0-auc:0.89950	validation_1-auc:0.84025
[20]	validation_0-auc:0.90154	validation_1-auc:0.83975
[21]	validation_0-auc:0.90301	validation_1-auc:0.84046
[22]	validation_0-auc:0.90529	validation_1-auc:0.84055
[23]	validation_0-auc:0.90701	validation_1-auc:0.84099
[24]	validation_0-auc:0.90889	validation_1-auc:0.84068
[25]	validation_0-auc:0.91013	validation_1-auc:0.84068
[26]	validation_0-auc:0.91133	validation_1-auc:0.84093
[27]	validation_0-auc:0.91262	validation_1-auc:0.84096
[28]	validation_0-auc:0.91345	validation_1-auc:0.84114
[29]	validation_0-auc:0.91544	validation_1-auc:0.84098
[30]	validation_0-auc:0.91645	validation_1-auc:0.84078
[31]	validation_0-auc:0.91697	validation_1-auc:0.84112
[32]	validation_0-auc:0.91740	validation_1-auc:0.84149
[33]	validation_0-auc:0.91770	validation_1-auc:0.84179
[34]	validation_0-auc:0.91808	validation_1-auc:0.84186
[35]	validation_0-auc:0.91879	validation_1-auc:0.84171
[36]	validation_0-auc:0.91935	validation_1-auc:0.84193
[37]	validation_0-auc:0.91991	validation_1-auc:0.84176
[38]	validation_0-auc:0.92009	validation_1-auc:0.84157
[39]	validation_0-auc:0.92138	validation_1-auc:0.84154
[40]	validation_0-auc:0.92185	validation_1-auc:0.84197
[41]	validation_0-auc:0.92215	validation_1-auc:0.84177
[42]	validation_0-auc:0.92363	validation_1-auc:0.84134
[43]	validation_0-auc:0.92416	validation_1-auc:0.84117
[44]	validation_0-auc:0.92455	validation_1-auc:0.84144
[45]	validation_0-auc:0.92496	validation_1-auc:0.84191
[46]	validation_0-auc:0.92537	validation_1-auc:0.84182
[47]	validation_0-auc:0.92591	validation_1-auc:0.84134
[48]	validation_0-auc:0.92618	validation_1-auc:0.84132
[49]	validation_0-auc:0.92642	validation_1-auc:0.84137
[50]	validation_0-auc:0.92701	validation_1-auc:0.84141
[51]	validation_0-auc:0.92717	validation_1-auc:0.84128
[52]	validation_0-auc:0.92744	validation_1-auc:0.84124
[53]	validation_0-auc:0.92779	validation_1-auc:0.84106
[54]	validation_0-auc:0.92832	validation_1-auc:0.84064
[55]	validation_0-auc:0.92843	validation_1-auc:0.84059
[56]	validation_0-auc:0.92857	validation_1-auc:0.84039
[57]	validation_0-auc:0.92865	validation_1-auc:0.84035
[58]	validation_0-auc:0.92977	validation_1-auc:0.84062
[59]	validation_0-auc:0.93002	validation_1-auc:0.84048
[60]	validation_0-auc:0.93096	validation_1-auc:0.83984
[61]	validation_0-auc:0.93155	validation_1-auc:0.84011
[62]	validation_0-auc:0.93185	validation_1-auc:0.83970
[63]	validation_0-auc:0.93200	validation_1-auc:0.83964
[64]	validation_0-auc:0.93212	validation_1-auc:0.83965
[65]	validation_0-auc:0.93231	validation_1-auc:0.83965
[66]	validation_0-auc:0.93247	validation_1-auc:0.83957
[67]	validation_0-auc:0.93264	validation_1-auc:0.83954
[68]	validation_0-auc:0.93272	validation_1-auc:0.83945
[69]	validation_0-auc:0.93369	validation_1-auc:0.83937
 60%|██████    | 30/50 [06:33<03:17,  9.87s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82807	validation_1-auc:0.80795
[1]	validation_0-auc:0.83698	validation_1-auc:0.81516
[2]	validation_0-auc:0.84427	validation_1-auc:0.81959
[3]	validation_0-auc:0.84826	validation_1-auc:0.82109
[4]	validation_0-auc:0.85627	validation_1-auc:0.82255
[5]	validation_0-auc:0.85967	validation_1-auc:0.82388
[6]	validation_0-auc:0.86541	validation_1-auc:0.82614
[7]	validation_0-auc:0.86867	validation_1-auc:0.82704
[8]	validation_0-auc:0.87254	validation_1-auc:0.82802
[9]	validation_0-auc:0.87732	validation_1-auc:0.82785
[10]	validation_0-auc:0.88005	validation_1-auc:0.82718
[11]	validation_0-auc:0.88311	validation_1-auc:0.82641
[12]	validation_0-auc:0.88933	validation_1-auc:0.82763
[13]	validation_0-auc:0.89361	validation_1-auc:0.82887
[14]	validation_0-auc:0.89544	validation_1-auc:0.83222
[15]	validation_0-auc:0.89824	validation_1-auc:0.83170
[16]	validation_0-auc:0.90020	validation_1-auc:0.83145
[17]	validation_0-auc:0.90172	validation_1-auc:0.83279
[18]	validation_0-auc:0.90295	validation_1-auc:0.83257
[19]	validation_0-auc:0.90503	validation_1-auc:0.83293
[20]	validation_0-auc:0.90692	validation_1-auc:0.83316
[21]	validation_0-auc:0.90767	validation_1-auc:0.83328
[22]	validation_0-auc:0.90876	validation_1-auc:0.83270
[23]	validation_0-auc:0.90952	validation_1-auc:0.83320
[24]	validation_0-auc:0.91121	validation_1-auc:0.83263
[25]	validation_0-auc:0.91201	validation_1-auc:0.83230
[26]	validation_0-auc:0.91327	validation_1-auc:0.83174
[27]	validation_0-auc:0.91436	validation_1-auc:0.83148
[28]	validation_0-auc:0.91510	validation_1-auc:0.83159
[29]	validation_0-auc:0.91565	validation_1-auc:0.83230
[30]	validation_0-auc:0.91683	validation_1-auc:0.83160
[31]	validation_0-auc:0.91729	validation_1-auc:0.83142
[32]	validation_0-auc:0.91782	validation_1-auc:0.83149
[33]	validation_0-auc:0.91794	validation_1-auc:0.83197
[34]	validation_0-auc:0.91850	validation_1-auc:0.83142
[35]	validation_0-auc:0.91917	validation_1-auc:0.83161
[36]	validation_0-auc:0.91985	validation_1-auc:0.83203
[37]	validation_0-auc:0.92053	validation_1-auc:0.83180
[38]	validation_0-auc:0.92108	validation_1-auc:0.83159
[39]	validation_0-auc:0.92143	validation_1-auc:0.83146
[40]	validation_0-auc:0.92224	validation_1-auc:0.83148
[41]	validation_0-auc:0.92321	validation_1-auc:0.83126
[42]	validation_0-auc:0.92334	validation_1-auc:0.83132
[43]	validation_0-auc:0.92351	validation_1-auc:0.83137
[44]	validation_0-auc:0.92381	validation_1-auc:0.83128
[45]	validation_0-auc:0.92431	validation_1-auc:0.83159
[46]	validation_0-auc:0.92490	validation_1-auc:0.83117
[47]	validation_0-auc:0.92527	validation_1-auc:0.83121
[48]	validation_0-auc:0.92537	validation_1-auc:0.83114
[49]	validation_0-auc:0.92573	validation_1-auc:0.83118
[50]	validation_0-auc:0.92626	validation_1-auc:0.83088
[51]	validation_0-auc:0.92696	validation_1-auc:0.83054
 60%|██████    | 30/50 [06:37<03:17,  9.87s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82500	validation_1-auc:0.81009
[1]	validation_0-auc:0.84173	validation_1-auc:0.82463
[2]	validation_0-auc:0.85023	validation_1-auc:0.83058
[3]	validation_0-auc:0.85623	validation_1-auc:0.83330
[4]	validation_0-auc:0.85947	validation_1-auc:0.83192
[5]	validation_0-auc:0.86149	validation_1-auc:0.83207
[6]	validation_0-auc:0.86451	validation_1-auc:0.83329
[7]	validation_0-auc:0.86567	validation_1-auc:0.83408
[8]	validation_0-auc:0.86829	validation_1-auc:0.83397
[9]	validation_0-auc:0.87411	validation_1-auc:0.83688
[10]	validation_0-auc:0.87652	validation_1-auc:0.83436
[11]	validation_0-auc:0.87768	validation_1-auc:0.83164
[12]	validation_0-auc:0.88374	validation_1-auc:0.83571
[13]	validation_0-auc:0.88822	validation_1-auc:0.83688
[14]	validation_0-auc:0.89005	validation_1-auc:0.83875
[15]	validation_0-auc:0.89306	validation_1-auc:0.83939
[16]	validation_0-auc:0.89517	validation_1-auc:0.84007
[17]	validation_0-auc:0.89720	validation_1-auc:0.84099
[18]	validation_0-auc:0.89872	validation_1-auc:0.83824
[19]	validation_0-auc:0.90059	validation_1-auc:0.83914
[20]	validation_0-auc:0.90255	validation_1-auc:0.83951
[21]	validation_0-auc:0.90437	validation_1-auc:0.83947
[22]	validation_0-auc:0.90516	validation_1-auc:0.83995
[23]	validation_0-auc:0.90593	validation_1-auc:0.84016
[24]	validation_0-auc:0.90705	validation_1-auc:0.84067
[25]	validation_0-auc:0.90760	validation_1-auc:0.84114
[26]	validation_0-auc:0.90938	validation_1-auc:0.84035
[27]	validation_0-auc:0.91085	validation_1-auc:0.83986
[28]	validation_0-auc:0.91137	validation_1-auc:0.84043
[29]	validation_0-auc:0.91203	validation_1-auc:0.84019
[30]	validation_0-auc:0.91337	validation_1-auc:0.84052
[31]	validation_0-auc:0.91438	validation_1-auc:0.84073
[32]	validation_0-auc:0.91569	validation_1-auc:0.84089
[33]	validation_0-auc:0.91618	validation_1-auc:0.84146
[34]	validation_0-auc:0.91717	validation_1-auc:0.84133
[35]	validation_0-auc:0.91764	validation_1-auc:0.84125
[36]	validation_0-auc:0.91830	validation_1-auc:0.84115
[37]	validation_0-auc:0.91859	validation_1-auc:0.84097
[38]	validation_0-auc:0.91946	validation_1-auc:0.84126
[39]	validation_0-auc:0.92016	validation_1-auc:0.84062
[40]	validation_0-auc:0.92095	validation_1-auc:0.84007
[41]	validation_0-auc:0.92185	validation_1-auc:0.84002
[42]	validation_0-auc:0.92196	validation_1-auc:0.84010
[43]	validation_0-auc:0.92254	validation_1-auc:0.83972
[44]	validation_0-auc:0.92310	validation_1-auc:0.83948
[45]	validation_0-auc:0.92373	validation_1-auc:0.83943
[46]	validation_0-auc:0.92394	validation_1-auc:0.83930
[47]	validation_0-auc:0.92422	validation_1-auc:0.83896
[48]	validation_0-auc:0.92466	validation_1-auc:0.83876
[49]	validation_0-auc:0.92486	validation_1-auc:0.83893
[50]	validation_0-auc:0.92531	validation_1-auc:0.83886
[51]	validation_0-auc:0.92555	validation_1-auc:0.83840
[52]	validation_0-auc:0.92641	validation_1-auc:0.83808
[53]	validation_0-auc:0.92658	validation_1-auc:0.83804
[54]	validation_0-auc:0.92763	validation_1-auc:0.83835
[55]	validation_0-auc:0.92833	validation_1-auc:0.83848
[56]	validation_0-auc:0.92851	validation_1-auc:0.83837
[57]	validation_0-auc:0.92873	validation_1-auc:0.83834
[58]	validation_0-auc:0.92888	validation_1-auc:0.83850
[59]	validation_0-auc:0.92900	validation_1-auc:0.83846
[60]	validation_0-auc:0.92956	validation_1-auc:0.83822
[61]	validation_0-auc:0.92970	validation_1-auc:0.83800
[62]	validation_0-auc:0.93014	validation_1-auc:0.83795
[63]	validation_0-auc:0.93033	validation_1-auc:0.83779
 62%|██████▏   | 31/50 [06:41<03:22, 10.64s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82297	validation_1-auc:0.80555
[1]	validation_0-auc:0.83574	validation_1-auc:0.81560
[2]	validation_0-auc:0.84113	validation_1-auc:0.82103
[3]	validation_0-auc:0.84353	validation_1-auc:0.82295
[4]	validation_0-auc:0.84619	validation_1-auc:0.82301
[5]	validation_0-auc:0.85011	validation_1-auc:0.82982
[6]	validation_0-auc:0.84830	validation_1-auc:0.82943
[7]	validation_0-auc:0.85463	validation_1-auc:0.83505
[8]	validation_0-auc:0.85765	validation_1-auc:0.83765
[9]	validation_0-auc:0.85774	validation_1-auc:0.83571
[10]	validation_0-auc:0.85740	validation_1-auc:0.83303
[11]	validation_0-auc:0.85687	validation_1-auc:0.83111
[12]	validation_0-auc:0.86068	validation_1-auc:0.83619
[13]	validation_0-auc:0.86437	validation_1-auc:0.83749
[14]	validation_0-auc:0.86566	validation_1-auc:0.84002
[15]	validation_0-auc:0.86754	validation_1-auc:0.84048
[16]	validation_0-auc:0.86885	validation_1-auc:0.84166
[17]	validation_0-auc:0.87090	validation_1-auc:0.84288
[18]	validation_0-auc:0.87162	validation_1-auc:0.84245
[19]	validation_0-auc:0.87432	validation_1-auc:0.84379
[20]	validation_0-auc:0.87481	validation_1-auc:0.84316
[21]	validation_0-auc:0.87493	validation_1-auc:0.84288
[22]	validation_0-auc:0.87796	validation_1-auc:0.84494
[23]	validation_0-auc:0.88010	validation_1-auc:0.84545
[24]	validation_0-auc:0.88162	validation_1-auc:0.84540
[25]	validation_0-auc:0.88182	validation_1-auc:0.84586
[26]	validation_0-auc:0.88298	validation_1-auc:0.84592
[27]	validation_0-auc:0.88443	validation_1-auc:0.84617
[28]	validation_0-auc:0.88482	validation_1-auc:0.84613
[29]	validation_0-auc:0.88541	validation_1-auc:0.84631
[30]	validation_0-auc:0.88572	validation_1-auc:0.84622
[31]	validation_0-auc:0.88649	validation_1-auc:0.84628
[32]	validation_0-auc:0.88718	validation_1-auc:0.84644
[33]	validation_0-auc:0.88738	validation_1-auc:0.84671
[34]	validation_0-auc:0.88873	validation_1-auc:0.84687
[35]	validation_0-auc:0.88970	validation_1-auc:0.84681
[36]	validation_0-auc:0.88999	validation_1-auc:0.84698
[37]	validation_0-auc:0.89043	validation_1-auc:0.84684
[38]	validation_0-auc:0.89227	validation_1-auc:0.84704
[39]	validation_0-auc:0.89240	validation_1-auc:0.84730
[40]	validation_0-auc:0.89277	validation_1-auc:0.84730
[41]	validation_0-auc:0.89298	validation_1-auc:0.84742
[42]	validation_0-auc:0.89383	validation_1-auc:0.84739
[43]	validation_0-auc:0.89399	validation_1-auc:0.84746
[44]	validation_0-auc:0.89421	validation_1-auc:0.84741
[45]	validation_0-auc:0.89494	validation_1-auc:0.84745
[46]	validation_0-auc:0.89518	validation_1-auc:0.84734
[47]	validation_0-auc:0.89629	validation_1-auc:0.84690
[48]	validation_0-auc:0.89700	validation_1-auc:0.84677
[49]	validation_0-auc:0.89715	validation_1-auc:0.84666
[50]	validation_0-auc:0.89744	validation_1-auc:0.84657
[51]	validation_0-auc:0.89805	validation_1-auc:0.84627
[52]	validation_0-auc:0.89828	validation_1-auc:0.84604
[53]	validation_0-auc:0.89947	validation_1-auc:0.84565
[54]	validation_0-auc:0.89957	validation_1-auc:0.84560
[55]	validation_0-auc:0.89976	validation_1-auc:0.84572
[56]	validation_0-auc:0.90016	validation_1-auc:0.84594
[57]	validation_0-auc:0.90032	validation_1-auc:0.84600
[58]	validation_0-auc:0.90074	validation_1-auc:0.84627
[59]	validation_0-auc:0.90097	validation_1-auc:0.84630
[60]	validation_0-auc:0.90146	validation_1-auc:0.84640
[61]	validation_0-auc:0.90221	validation_1-auc:0.84628
[62]	validation_0-auc:0.90278	validation_1-auc:0.84636
[63]	validation_0-auc:0.90296	validation_1-auc:0.84640
[64]	validation_0-auc:0.90344	validation_1-auc:0.84657
[65]	validation_0-auc:0.90381	validation_1-auc:0.84654
[66]	validation_0-auc:0.90393	validation_1-auc:0.84662
[67]	validation_0-auc:0.90419	validation_1-auc:0.84675
[68]	validation_0-auc:0.90486	validation_1-auc:0.84626
[69]	validation_0-auc:0.90500	validation_1-auc:0.84612
[70]	validation_0-auc:0.90517	validation_1-auc:0.84599
[71]	validation_0-auc:0.90532	validation_1-auc:0.84600
[72]	validation_0-auc:0.90573	validation_1-auc:0.84603
 62%|██████▏   | 31/50 [06:44<03:22, 10.64s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82204	validation_1-auc:0.80659
[1]	validation_0-auc:0.83156	validation_1-auc:0.81561
[2]	validation_0-auc:0.83885	validation_1-auc:0.82094
[3]	validation_0-auc:0.84130	validation_1-auc:0.82369
[4]	validation_0-auc:0.84613	validation_1-auc:0.82480
[5]	validation_0-auc:0.85075	validation_1-auc:0.82828
[6]	validation_0-auc:0.85169	validation_1-auc:0.82656
[7]	validation_0-auc:0.85669	validation_1-auc:0.82918
[8]	validation_0-auc:0.86200	validation_1-auc:0.82876
[9]	validation_0-auc:0.86284	validation_1-auc:0.82898
[10]	validation_0-auc:0.86143	validation_1-auc:0.82665
[11]	validation_0-auc:0.86134	validation_1-auc:0.82454
[12]	validation_0-auc:0.86618	validation_1-auc:0.82786
[13]	validation_0-auc:0.87014	validation_1-auc:0.82997
[14]	validation_0-auc:0.87262	validation_1-auc:0.83281
[15]	validation_0-auc:0.87271	validation_1-auc:0.83202
[16]	validation_0-auc:0.87410	validation_1-auc:0.83447
[17]	validation_0-auc:0.87695	validation_1-auc:0.83712
[18]	validation_0-auc:0.87697	validation_1-auc:0.83632
[19]	validation_0-auc:0.87907	validation_1-auc:0.83770
[20]	validation_0-auc:0.87940	validation_1-auc:0.83693
[21]	validation_0-auc:0.87932	validation_1-auc:0.83629
[22]	validation_0-auc:0.88059	validation_1-auc:0.83729
[23]	validation_0-auc:0.88204	validation_1-auc:0.83821
[24]	validation_0-auc:0.88377	validation_1-auc:0.83909
[25]	validation_0-auc:0.88450	validation_1-auc:0.83979
[26]	validation_0-auc:0.88580	validation_1-auc:0.83920
[27]	validation_0-auc:0.88678	validation_1-auc:0.83909
[28]	validation_0-auc:0.88751	validation_1-auc:0.83899
[29]	validation_0-auc:0.88906	validation_1-auc:0.83949
[30]	validation_0-auc:0.88926	validation_1-auc:0.83943
[31]	validation_0-auc:0.89030	validation_1-auc:0.83901
[32]	validation_0-auc:0.89110	validation_1-auc:0.83899
[33]	validation_0-auc:0.89283	validation_1-auc:0.83845
[34]	validation_0-auc:0.89330	validation_1-auc:0.83847
[35]	validation_0-auc:0.89423	validation_1-auc:0.83827
[36]	validation_0-auc:0.89514	validation_1-auc:0.83798
[37]	validation_0-auc:0.89558	validation_1-auc:0.83787
[38]	validation_0-auc:0.89627	validation_1-auc:0.83811
[39]	validation_0-auc:0.89706	validation_1-auc:0.83825
[40]	validation_0-auc:0.89720	validation_1-auc:0.83826
[41]	validation_0-auc:0.89752	validation_1-auc:0.83820
[42]	validation_0-auc:0.89792	validation_1-auc:0.83791
[43]	validation_0-auc:0.89878	validation_1-auc:0.83788
[44]	validation_0-auc:0.89924	validation_1-auc:0.83782
[45]	validation_0-auc:0.89956	validation_1-auc:0.83790
[46]	validation_0-auc:0.90042	validation_1-auc:0.83800
[47]	validation_0-auc:0.90130	validation_1-auc:0.83870
[48]	validation_0-auc:0.90147	validation_1-auc:0.83867
[49]	validation_0-auc:0.90180	validation_1-auc:0.83859
[50]	validation_0-auc:0.90258	validation_1-auc:0.83918
[51]	validation_0-auc:0.90307	validation_1-auc:0.83897
[52]	validation_0-auc:0.90323	validation_1-auc:0.83872
[53]	validation_0-auc:0.90332	validation_1-auc:0.83875
[54]	validation_0-auc:0.90344	validation_1-auc:0.83877
 62%|██████▏   | 31/50 [06:47<03:22, 10.64s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81784	validation_1-auc:0.80762
[1]	validation_0-auc:0.83472	validation_1-auc:0.82569
[2]	validation_0-auc:0.84004	validation_1-auc:0.82843
[3]	validation_0-auc:0.84289	validation_1-auc:0.83173
[4]	validation_0-auc:0.84819	validation_1-auc:0.83311
[5]	validation_0-auc:0.84989	validation_1-auc:0.83100
[6]	validation_0-auc:0.85109	validation_1-auc:0.82841
[7]	validation_0-auc:0.85644	validation_1-auc:0.83234
[8]	validation_0-auc:0.85931	validation_1-auc:0.83492
[9]	validation_0-auc:0.85892	validation_1-auc:0.83526
[10]	validation_0-auc:0.85895	validation_1-auc:0.83191
[11]	validation_0-auc:0.85732	validation_1-auc:0.82843
[12]	validation_0-auc:0.86323	validation_1-auc:0.83356
[13]	validation_0-auc:0.86677	validation_1-auc:0.83577
[14]	validation_0-auc:0.86827	validation_1-auc:0.83909
[15]	validation_0-auc:0.86855	validation_1-auc:0.83721
[16]	validation_0-auc:0.87149	validation_1-auc:0.83978
[17]	validation_0-auc:0.87426	validation_1-auc:0.84150
[18]	validation_0-auc:0.87371	validation_1-auc:0.83969
[19]	validation_0-auc:0.87609	validation_1-auc:0.84065
[20]	validation_0-auc:0.87635	validation_1-auc:0.83931
[21]	validation_0-auc:0.87667	validation_1-auc:0.83779
[22]	validation_0-auc:0.87861	validation_1-auc:0.83951
[23]	validation_0-auc:0.88004	validation_1-auc:0.84067
[24]	validation_0-auc:0.88155	validation_1-auc:0.84054
[25]	validation_0-auc:0.88208	validation_1-auc:0.84134
[26]	validation_0-auc:0.88394	validation_1-auc:0.84086
[27]	validation_0-auc:0.88530	validation_1-auc:0.84161
[28]	validation_0-auc:0.88557	validation_1-auc:0.84190
[29]	validation_0-auc:0.88636	validation_1-auc:0.84183
[30]	validation_0-auc:0.88716	validation_1-auc:0.84096
[31]	validation_0-auc:0.88755	validation_1-auc:0.84176
[32]	validation_0-auc:0.88878	validation_1-auc:0.84197
[33]	validation_0-auc:0.88879	validation_1-auc:0.84211
[34]	validation_0-auc:0.88900	validation_1-auc:0.84253
[35]	validation_0-auc:0.89003	validation_1-auc:0.84257
[36]	validation_0-auc:0.89106	validation_1-auc:0.84260
[37]	validation_0-auc:0.89187	validation_1-auc:0.84267
[38]	validation_0-auc:0.89301	validation_1-auc:0.84282
[39]	validation_0-auc:0.89357	validation_1-auc:0.84299
[40]	validation_0-auc:0.89378	validation_1-auc:0.84318
[41]	validation_0-auc:0.89412	validation_1-auc:0.84316
[42]	validation_0-auc:0.89434	validation_1-auc:0.84298
[43]	validation_0-auc:0.89497	validation_1-auc:0.84260
[44]	validation_0-auc:0.89546	validation_1-auc:0.84285
[45]	validation_0-auc:0.89624	validation_1-auc:0.84286
[46]	validation_0-auc:0.89633	validation_1-auc:0.84271
[47]	validation_0-auc:0.89649	validation_1-auc:0.84293
[48]	validation_0-auc:0.89744	validation_1-auc:0.84302
[49]	validation_0-auc:0.89761	validation_1-auc:0.84318
[50]	validation_0-auc:0.89776	validation_1-auc:0.84327
[51]	validation_0-auc:0.89854	validation_1-auc:0.84369
[52]	validation_0-auc:0.89909	validation_1-auc:0.84364
[53]	validation_0-auc:0.89913	validation_1-auc:0.84361
[54]	validation_0-auc:0.89959	validation_1-auc:0.84306
[55]	validation_0-auc:0.90020	validation_1-auc:0.84301
[56]	validation_0-auc:0.90065	validation_1-auc:0.84290
[57]	validation_0-auc:0.90081	validation_1-auc:0.84283
[58]	validation_0-auc:0.90109	validation_1-auc:0.84268
[59]	validation_0-auc:0.90120	validation_1-auc:0.84272
[60]	validation_0-auc:0.90138	validation_1-auc:0.84269
[61]	validation_0-auc:0.90186	validation_1-auc:0.84274
[62]	validation_0-auc:0.90263	validation_1-auc:0.84214
[63]	validation_0-auc:0.90270	validation_1-auc:0.84197
[64]	validation_0-auc:0.90355	validation_1-auc:0.84197
[65]	validation_0-auc:0.90378	validation_1-auc:0.84195
[66]	validation_0-auc:0.90431	validation_1-auc:0.84197
[67]	validation_0-auc:0.90456	validation_1-auc:0.84184
[68]	validation_0-auc:0.90563	validation_1-auc:0.84158
[69]	validation_0-auc:0.90618	validation_1-auc:0.84147
[70]	validation_0-auc:0.90621	validation_1-auc:0.84126
[71]	validation_0-auc:0.90638	validation_1-auc:0.84125
[72]	validation_0-auc:0.90659	validation_1-auc:0.84120
[73]	validation_0-auc:0.90714	validation_1-auc:0.84078
[74]	validation_0-auc:0.90730	validation_1-auc:0.84063
[75]	validation_0-auc:0.90775	validation_1-auc:0.84063
[76]	validation_0-auc:0.90823	validation_1-auc:0.84031
[77]	validation_0-auc:0.90841	validation_1-auc:0.84027
[78]	validation_0-auc:0.90843	validation_1-auc:0.84025
[79]	validation_0-auc:0.90887	validation_1-auc:0.84004
[80]	validation_0-auc:0.90907	validation_1-auc:0.83975
 64%|██████▍   | 32/50 [06:50<03:04, 10.25s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83115	validation_1-auc:0.81336
[1]	validation_0-auc:0.83727	validation_1-auc:0.81479
[2]	validation_0-auc:0.84424	validation_1-auc:0.81755
[3]	validation_0-auc:0.84660	validation_1-auc:0.81708
[4]	validation_0-auc:0.85230	validation_1-auc:0.81935
[5]	validation_0-auc:0.85745	validation_1-auc:0.82460
[6]	validation_0-auc:0.86361	validation_1-auc:0.83225
[7]	validation_0-auc:0.86546	validation_1-auc:0.83224
[8]	validation_0-auc:0.86708	validation_1-auc:0.83171
[9]	validation_0-auc:0.86940	validation_1-auc:0.83264
[10]	validation_0-auc:0.86911	validation_1-auc:0.82996
[11]	validation_0-auc:0.87081	validation_1-auc:0.83034
[12]	validation_0-auc:0.87301	validation_1-auc:0.83257
[13]	validation_0-auc:0.87609	validation_1-auc:0.83409
[14]	validation_0-auc:0.87691	validation_1-auc:0.83627
[15]	validation_0-auc:0.87703	validation_1-auc:0.83525
[16]	validation_0-auc:0.87946	validation_1-auc:0.83673
[17]	validation_0-auc:0.88106	validation_1-auc:0.83808
[18]	validation_0-auc:0.88066	validation_1-auc:0.83722
[19]	validation_0-auc:0.88364	validation_1-auc:0.83848
[20]	validation_0-auc:0.88412	validation_1-auc:0.83712
[21]	validation_0-auc:0.88421	validation_1-auc:0.83519
[22]	validation_0-auc:0.88625	validation_1-auc:0.83656
[23]	validation_0-auc:0.88959	validation_1-auc:0.83820
[24]	validation_0-auc:0.89123	validation_1-auc:0.83874
[25]	validation_0-auc:0.89182	validation_1-auc:0.83890
[26]	validation_0-auc:0.89333	validation_1-auc:0.83841
[27]	validation_0-auc:0.89557	validation_1-auc:0.83925
[28]	validation_0-auc:0.89569	validation_1-auc:0.83922
[29]	validation_0-auc:0.89781	validation_1-auc:0.83983
[30]	validation_0-auc:0.89876	validation_1-auc:0.84008
[31]	validation_0-auc:0.90030	validation_1-auc:0.84033
[32]	validation_0-auc:0.90158	validation_1-auc:0.84113
[33]	validation_0-auc:0.90225	validation_1-auc:0.84196
[34]	validation_0-auc:0.90299	validation_1-auc:0.84250
[35]	validation_0-auc:0.90389	validation_1-auc:0.84294
[36]	validation_0-auc:0.90532	validation_1-auc:0.84313
[37]	validation_0-auc:0.90617	validation_1-auc:0.84277
[38]	validation_0-auc:0.90634	validation_1-auc:0.84260
[39]	validation_0-auc:0.90692	validation_1-auc:0.84294
[40]	validation_0-auc:0.90766	validation_1-auc:0.84377
[41]	validation_0-auc:0.90844	validation_1-auc:0.84374
[42]	validation_0-auc:0.90928	validation_1-auc:0.84391
[43]	validation_0-auc:0.90930	validation_1-auc:0.84401
[44]	validation_0-auc:0.91061	validation_1-auc:0.84383
[45]	validation_0-auc:0.91070	validation_1-auc:0.84370
[46]	validation_0-auc:0.91107	validation_1-auc:0.84374
[47]	validation_0-auc:0.91133	validation_1-auc:0.84402
[48]	validation_0-auc:0.91144	validation_1-auc:0.84379
[49]	validation_0-auc:0.91266	validation_1-auc:0.84346
[50]	validation_0-auc:0.91303	validation_1-auc:0.84329
[51]	validation_0-auc:0.91326	validation_1-auc:0.84328
[52]	validation_0-auc:0.91435	validation_1-auc:0.84323
[53]	validation_0-auc:0.91471	validation_1-auc:0.84321
[54]	validation_0-auc:0.91513	validation_1-auc:0.84309
[55]	validation_0-auc:0.91557	validation_1-auc:0.84289
[56]	validation_0-auc:0.91577	validation_1-auc:0.84269
[57]	validation_0-auc:0.91602	validation_1-auc:0.84248
[58]	validation_0-auc:0.91664	validation_1-auc:0.84225
[59]	validation_0-auc:0.91692	validation_1-auc:0.84244
[60]	validation_0-auc:0.91712	validation_1-auc:0.84241
[61]	validation_0-auc:0.91739	validation_1-auc:0.84247
[62]	validation_0-auc:0.91750	validation_1-auc:0.84236
[63]	validation_0-auc:0.91763	validation_1-auc:0.84239
[64]	validation_0-auc:0.91794	validation_1-auc:0.84247
[65]	validation_0-auc:0.91812	validation_1-auc:0.84264
[66]	validation_0-auc:0.91842	validation_1-auc:0.84232
[67]	validation_0-auc:0.91871	validation_1-auc:0.84232
[68]	validation_0-auc:0.91952	validation_1-auc:0.84218
[69]	validation_0-auc:0.91991	validation_1-auc:0.84239
[70]	validation_0-auc:0.92014	validation_1-auc:0.84242
[71]	validation_0-auc:0.92038	validation_1-auc:0.84238
[72]	validation_0-auc:0.92074	validation_1-auc:0.84248
[73]	validation_0-auc:0.92081	validation_1-auc:0.84258
[74]	validation_0-auc:0.92120	validation_1-auc:0.84250
[75]	validation_0-auc:0.92213	validation_1-auc:0.84207
[76]	validation_0-auc:0.92223	validation_1-auc:0.84198
 64%|██████▍   | 32/50 [06:55<03:04, 10.25s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82651	validation_1-auc:0.80782
[1]	validation_0-auc:0.83409	validation_1-auc:0.81232
[2]	validation_0-auc:0.83954	validation_1-auc:0.81752
[3]	validation_0-auc:0.84478	validation_1-auc:0.82046
[4]	validation_0-auc:0.85118	validation_1-auc:0.82153
[5]	validation_0-auc:0.85530	validation_1-auc:0.82408
[6]	validation_0-auc:0.86105	validation_1-auc:0.82563
[7]	validation_0-auc:0.86490	validation_1-auc:0.82674
[8]	validation_0-auc:0.86650	validation_1-auc:0.82753
[9]	validation_0-auc:0.86910	validation_1-auc:0.82642
[10]	validation_0-auc:0.87073	validation_1-auc:0.82684
[11]	validation_0-auc:0.87200	validation_1-auc:0.82586
[12]	validation_0-auc:0.87490	validation_1-auc:0.82786
[13]	validation_0-auc:0.88015	validation_1-auc:0.82952
[14]	validation_0-auc:0.88251	validation_1-auc:0.83043
[15]	validation_0-auc:0.88349	validation_1-auc:0.82871
[16]	validation_0-auc:0.88436	validation_1-auc:0.83106
[17]	validation_0-auc:0.88620	validation_1-auc:0.83127
[18]	validation_0-auc:0.88636	validation_1-auc:0.83055
[19]	validation_0-auc:0.88915	validation_1-auc:0.83132
[20]	validation_0-auc:0.88965	validation_1-auc:0.83166
[21]	validation_0-auc:0.88938	validation_1-auc:0.83068
[22]	validation_0-auc:0.89107	validation_1-auc:0.83269
[23]	validation_0-auc:0.89402	validation_1-auc:0.83411
[24]	validation_0-auc:0.89561	validation_1-auc:0.83456
[25]	validation_0-auc:0.89699	validation_1-auc:0.83537
[26]	validation_0-auc:0.89854	validation_1-auc:0.83419
[27]	validation_0-auc:0.90045	validation_1-auc:0.83469
[28]	validation_0-auc:0.90066	validation_1-auc:0.83405
[29]	validation_0-auc:0.90210	validation_1-auc:0.83453
[30]	validation_0-auc:0.90344	validation_1-auc:0.83419
[31]	validation_0-auc:0.90460	validation_1-auc:0.83478
[32]	validation_0-auc:0.90551	validation_1-auc:0.83573
[33]	validation_0-auc:0.90591	validation_1-auc:0.83645
[34]	validation_0-auc:0.90607	validation_1-auc:0.83675
[35]	validation_0-auc:0.90716	validation_1-auc:0.83676
[36]	validation_0-auc:0.90792	validation_1-auc:0.83687
[37]	validation_0-auc:0.90853	validation_1-auc:0.83634
[38]	validation_0-auc:0.90925	validation_1-auc:0.83640
[39]	validation_0-auc:0.90968	validation_1-auc:0.83670
[40]	validation_0-auc:0.90978	validation_1-auc:0.83698
[41]	validation_0-auc:0.91096	validation_1-auc:0.83670
[42]	validation_0-auc:0.91158	validation_1-auc:0.83615
[43]	validation_0-auc:0.91187	validation_1-auc:0.83647
[44]	validation_0-auc:0.91269	validation_1-auc:0.83649
[45]	validation_0-auc:0.91265	validation_1-auc:0.83676
[46]	validation_0-auc:0.91282	validation_1-auc:0.83689
[47]	validation_0-auc:0.91335	validation_1-auc:0.83684
[48]	validation_0-auc:0.91370	validation_1-auc:0.83680
[49]	validation_0-auc:0.91415	validation_1-auc:0.83659
[50]	validation_0-auc:0.91427	validation_1-auc:0.83651
[51]	validation_0-auc:0.91462	validation_1-auc:0.83678
[52]	validation_0-auc:0.91517	validation_1-auc:0.83657
[53]	validation_0-auc:0.91592	validation_1-auc:0.83650
[54]	validation_0-auc:0.91603	validation_1-auc:0.83652
[55]	validation_0-auc:0.91658	validation_1-auc:0.83612
[56]	validation_0-auc:0.91716	validation_1-auc:0.83611
[57]	validation_0-auc:0.91751	validation_1-auc:0.83607
[58]	validation_0-auc:0.91832	validation_1-auc:0.83608
[59]	validation_0-auc:0.91855	validation_1-auc:0.83608
[60]	validation_0-auc:0.91876	validation_1-auc:0.83585
[61]	validation_0-auc:0.91968	validation_1-auc:0.83579
[62]	validation_0-auc:0.91979	validation_1-auc:0.83580
[63]	validation_0-auc:0.91992	validation_1-auc:0.83577
[64]	validation_0-auc:0.92076	validation_1-auc:0.83553
[65]	validation_0-auc:0.92104	validation_1-auc:0.83541
[66]	validation_0-auc:0.92119	validation_1-auc:0.83526
[67]	validation_0-auc:0.92175	validation_1-auc:0.83511
[68]	validation_0-auc:0.92254	validation_1-auc:0.83472
[69]	validation_0-auc:0.92272	validation_1-auc:0.83467
 64%|██████▍   | 32/50 [06:59<03:04, 10.25s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82288	validation_1-auc:0.81120
[1]	validation_0-auc:0.83080	validation_1-auc:0.81555
[2]	validation_0-auc:0.84242	validation_1-auc:0.82655
[3]	validation_0-auc:0.84897	validation_1-auc:0.83054
[4]	validation_0-auc:0.85555	validation_1-auc:0.83369
[5]	validation_0-auc:0.85647	validation_1-auc:0.83311
[6]	validation_0-auc:0.85998	validation_1-auc:0.83443
[7]	validation_0-auc:0.86244	validation_1-auc:0.83633
[8]	validation_0-auc:0.86438	validation_1-auc:0.83651
[9]	validation_0-auc:0.86638	validation_1-auc:0.83518
[10]	validation_0-auc:0.86657	validation_1-auc:0.83310
[11]	validation_0-auc:0.86708	validation_1-auc:0.83169
[12]	validation_0-auc:0.87022	validation_1-auc:0.83357
[13]	validation_0-auc:0.87402	validation_1-auc:0.83651
[14]	validation_0-auc:0.87551	validation_1-auc:0.83877
[15]	validation_0-auc:0.87644	validation_1-auc:0.83741
[16]	validation_0-auc:0.87944	validation_1-auc:0.83952
[17]	validation_0-auc:0.88108	validation_1-auc:0.84133
[18]	validation_0-auc:0.88119	validation_1-auc:0.83844
[19]	validation_0-auc:0.88433	validation_1-auc:0.84111
[20]	validation_0-auc:0.88412	validation_1-auc:0.84077
[21]	validation_0-auc:0.88457	validation_1-auc:0.83828
[22]	validation_0-auc:0.88651	validation_1-auc:0.84062
[23]	validation_0-auc:0.88961	validation_1-auc:0.84196
[24]	validation_0-auc:0.89201	validation_1-auc:0.84180
[25]	validation_0-auc:0.89306	validation_1-auc:0.84159
[26]	validation_0-auc:0.89399	validation_1-auc:0.84100
[27]	validation_0-auc:0.89564	validation_1-auc:0.84105
[28]	validation_0-auc:0.89628	validation_1-auc:0.84026
[29]	validation_0-auc:0.89774	validation_1-auc:0.84054
[30]	validation_0-auc:0.89883	validation_1-auc:0.84019
[31]	validation_0-auc:0.90041	validation_1-auc:0.84092
[32]	validation_0-auc:0.90110	validation_1-auc:0.84140
[33]	validation_0-auc:0.90159	validation_1-auc:0.84145
[34]	validation_0-auc:0.90225	validation_1-auc:0.84164
[35]	validation_0-auc:0.90299	validation_1-auc:0.84236
[36]	validation_0-auc:0.90407	validation_1-auc:0.84183
[37]	validation_0-auc:0.90477	validation_1-auc:0.84154
[38]	validation_0-auc:0.90596	validation_1-auc:0.84099
[39]	validation_0-auc:0.90632	validation_1-auc:0.84144
[40]	validation_0-auc:0.90669	validation_1-auc:0.84170
[41]	validation_0-auc:0.90768	validation_1-auc:0.84089
[42]	validation_0-auc:0.90811	validation_1-auc:0.84162
[43]	validation_0-auc:0.90843	validation_1-auc:0.84225
[44]	validation_0-auc:0.90921	validation_1-auc:0.84223
[45]	validation_0-auc:0.90947	validation_1-auc:0.84233
[46]	validation_0-auc:0.90975	validation_1-auc:0.84249
[47]	validation_0-auc:0.91006	validation_1-auc:0.84261
[48]	validation_0-auc:0.91061	validation_1-auc:0.84234
[49]	validation_0-auc:0.91098	validation_1-auc:0.84266
[50]	validation_0-auc:0.91135	validation_1-auc:0.84272
[51]	validation_0-auc:0.91203	validation_1-auc:0.84286
[52]	validation_0-auc:0.91228	validation_1-auc:0.84286
[53]	validation_0-auc:0.91295	validation_1-auc:0.84279
[54]	validation_0-auc:0.91313	validation_1-auc:0.84229
[55]	validation_0-auc:0.91381	validation_1-auc:0.84226
[56]	validation_0-auc:0.91384	validation_1-auc:0.84232
[57]	validation_0-auc:0.91401	validation_1-auc:0.84228
[58]	validation_0-auc:0.91445	validation_1-auc:0.84254
[59]	validation_0-auc:0.91499	validation_1-auc:0.84257
[60]	validation_0-auc:0.91522	validation_1-auc:0.84252
[61]	validation_0-auc:0.91582	validation_1-auc:0.84232
[62]	validation_0-auc:0.91659	validation_1-auc:0.84211
[63]	validation_0-auc:0.91686	validation_1-auc:0.84206
[64]	validation_0-auc:0.91697	validation_1-auc:0.84220
[65]	validation_0-auc:0.91707	validation_1-auc:0.84236
[66]	validation_0-auc:0.91730	validation_1-auc:0.84245
[67]	validation_0-auc:0.91800	validation_1-auc:0.84230
[68]	validation_0-auc:0.91853	validation_1-auc:0.84208
[69]	validation_0-auc:0.91925	validation_1-auc:0.84219
[70]	validation_0-auc:0.91962	validation_1-auc:0.84218
[71]	validation_0-auc:0.91972	validation_1-auc:0.84210
[72]	validation_0-auc:0.92013	validation_1-auc:0.84210
[73]	validation_0-auc:0.92020	validation_1-auc:0.84193
[74]	validation_0-auc:0.92026	validation_1-auc:0.84186
[75]	validation_0-auc:0.92073	validation_1-auc:0.84190
[76]	validation_0-auc:0.92174	validation_1-auc:0.84133
[77]	validation_0-auc:0.92185	validation_1-auc:0.84113
[78]	validation_0-auc:0.92200	validation_1-auc:0.84114
[79]	validation_0-auc:0.92215	validation_1-auc:0.84095
[80]	validation_0-auc:0.92231	validation_1-auc:0.84096
[81]	validation_0-auc:0.92248	validation_1-auc:0.84074
[82]	validation_0-auc:0.92309	validation_1-auc:0.84081
 66%|██████▌   | 33/50 [07:03<03:09, 11.13s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82182	validation_1-auc:0.80827
[1]	validation_0-auc:0.82870	validation_1-auc:0.81350
[2]	validation_0-auc:0.83731	validation_1-auc:0.81929
[3]	validation_0-auc:0.83875	validation_1-auc:0.82045
[4]	validation_0-auc:0.84040	validation_1-auc:0.81818
[5]	validation_0-auc:0.84206	validation_1-auc:0.81928
[6]	validation_0-auc:0.84268	validation_1-auc:0.81938
[7]	validation_0-auc:0.84358	validation_1-auc:0.81980
[8]	validation_0-auc:0.84708	validation_1-auc:0.82304
[9]	validation_0-auc:0.84917	validation_1-auc:0.82599
[10]	validation_0-auc:0.84954	validation_1-auc:0.82955
[11]	validation_0-auc:0.84797	validation_1-auc:0.82941
[12]	validation_0-auc:0.85020	validation_1-auc:0.83111
[13]	validation_0-auc:0.85439	validation_1-auc:0.83438
[14]	validation_0-auc:0.85599	validation_1-auc:0.83689
[15]	validation_0-auc:0.85733	validation_1-auc:0.83809
[16]	validation_0-auc:0.85831	validation_1-auc:0.83815
[17]	validation_0-auc:0.85851	validation_1-auc:0.83786
[18]	validation_0-auc:0.85947	validation_1-auc:0.83843
[19]	validation_0-auc:0.86025	validation_1-auc:0.83882
[20]	validation_0-auc:0.86081	validation_1-auc:0.83843
[21]	validation_0-auc:0.86171	validation_1-auc:0.83947
[22]	validation_0-auc:0.86269	validation_1-auc:0.83975
[23]	validation_0-auc:0.86324	validation_1-auc:0.83950
[24]	validation_0-auc:0.86389	validation_1-auc:0.83945
[25]	validation_0-auc:0.86453	validation_1-auc:0.83961
[26]	validation_0-auc:0.86616	validation_1-auc:0.84016
[27]	validation_0-auc:0.86684	validation_1-auc:0.84020
[28]	validation_0-auc:0.86747	validation_1-auc:0.84100
[29]	validation_0-auc:0.86836	validation_1-auc:0.84088
[30]	validation_0-auc:0.86929	validation_1-auc:0.84158
[31]	validation_0-auc:0.87001	validation_1-auc:0.84233
[32]	validation_0-auc:0.87068	validation_1-auc:0.84228
[33]	validation_0-auc:0.87130	validation_1-auc:0.84278
[34]	validation_0-auc:0.87196	validation_1-auc:0.84327
[35]	validation_0-auc:0.87247	validation_1-auc:0.84349
[36]	validation_0-auc:0.87308	validation_1-auc:0.84364
[37]	validation_0-auc:0.87337	validation_1-auc:0.84363
[38]	validation_0-auc:0.87390	validation_1-auc:0.84355
[39]	validation_0-auc:0.87447	validation_1-auc:0.84352
[40]	validation_0-auc:0.87472	validation_1-auc:0.84388
[41]	validation_0-auc:0.87509	validation_1-auc:0.84388
[42]	validation_0-auc:0.87556	validation_1-auc:0.84378
[43]	validation_0-auc:0.87639	validation_1-auc:0.84386
[44]	validation_0-auc:0.87709	validation_1-auc:0.84397
[45]	validation_0-auc:0.87757	validation_1-auc:0.84397
[46]	validation_0-auc:0.87807	validation_1-auc:0.84394
[47]	validation_0-auc:0.87900	validation_1-auc:0.84399
[48]	validation_0-auc:0.87927	validation_1-auc:0.84413
[49]	validation_0-auc:0.87988	validation_1-auc:0.84420
[50]	validation_0-auc:0.88018	validation_1-auc:0.84417
[51]	validation_0-auc:0.88047	validation_1-auc:0.84437
[52]	validation_0-auc:0.88066	validation_1-auc:0.84439
[53]	validation_0-auc:0.88081	validation_1-auc:0.84465
[54]	validation_0-auc:0.88097	validation_1-auc:0.84462
[55]	validation_0-auc:0.88120	validation_1-auc:0.84473
[56]	validation_0-auc:0.88134	validation_1-auc:0.84466
[57]	validation_0-auc:0.88158	validation_1-auc:0.84485
[58]	validation_0-auc:0.88220	validation_1-auc:0.84469
[59]	validation_0-auc:0.88253	validation_1-auc:0.84469
[60]	validation_0-auc:0.88272	validation_1-auc:0.84456
[61]	validation_0-auc:0.88350	validation_1-auc:0.84481
[62]	validation_0-auc:0.88388	validation_1-auc:0.84508
[63]	validation_0-auc:0.88416	validation_1-auc:0.84515
[64]	validation_0-auc:0.88436	validation_1-auc:0.84521
[65]	validation_0-auc:0.88453	validation_1-auc:0.84518
[66]	validation_0-auc:0.88460	validation_1-auc:0.84518
[67]	validation_0-auc:0.88516	validation_1-auc:0.84517
[68]	validation_0-auc:0.88567	validation_1-auc:0.84511
[69]	validation_0-auc:0.88629	validation_1-auc:0.84548
[70]	validation_0-auc:0.88691	validation_1-auc:0.84541
[71]	validation_0-auc:0.88716	validation_1-auc:0.84552
[72]	validation_0-auc:0.88741	validation_1-auc:0.84569
[73]	validation_0-auc:0.88802	validation_1-auc:0.84552
[74]	validation_0-auc:0.88810	validation_1-auc:0.84556
[75]	validation_0-auc:0.88840	validation_1-auc:0.84532
[76]	validation_0-auc:0.88864	validation_1-auc:0.84545
[77]	validation_0-auc:0.88872	validation_1-auc:0.84543
[78]	validation_0-auc:0.88906	validation_1-auc:0.84526
[79]	validation_0-auc:0.88927	validation_1-auc:0.84545
[80]	validation_0-auc:0.88951	validation_1-auc:0.84559
[81]	validation_0-auc:0.88972	validation_1-auc:0.84583
[82]	validation_0-auc:0.89018	validation_1-auc:0.84577
[83]	validation_0-auc:0.89033	validation_1-auc:0.84574
[84]	validation_0-auc:0.89071	validation_1-auc:0.84604
[85]	validation_0-auc:0.89080	validation_1-auc:0.84602
[86]	validation_0-auc:0.89132	validation_1-auc:0.84595
[87]	validation_0-auc:0.89172	validation_1-auc:0.84591
[88]	validation_0-auc:0.89203	validation_1-auc:0.84596
[89]	validation_0-auc:0.89228	validation_1-auc:0.84592
[90]	validation_0-auc:0.89274	validation_1-auc:0.84585
[91]	validation_0-auc:0.89284	validation_1-auc:0.84581
[92]	validation_0-auc:0.89304	validation_1-auc:0.84596
[93]	validation_0-auc:0.89339	validation_1-auc:0.84587
[94]	validation_0-auc:0.89375	validation_1-auc:0.84591
[95]	validation_0-auc:0.89402	validation_1-auc:0.84599
[96]	validation_0-auc:0.89422	validation_1-auc:0.84568
[97]	validation_0-auc:0.89455	validation_1-auc:0.84562
[98]	validation_0-auc:0.89462	validation_1-auc:0.84555
[99]	validation_0-auc:0.89468	validation_1-auc:0.84547
 66%|██████▌   | 33/50 [07:08<03:09, 11.13s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82226	validation_1-auc:0.80560
[1]	validation_0-auc:0.82630	validation_1-auc:0.81169
[2]	validation_0-auc:0.83372	validation_1-auc:0.81863
[3]	validation_0-auc:0.83536	validation_1-auc:0.81946
[4]	validation_0-auc:0.84308	validation_1-auc:0.82549
[5]	validation_0-auc:0.84282	validation_1-auc:0.82507
[6]	validation_0-auc:0.84500	validation_1-auc:0.82457
[7]	validation_0-auc:0.84580	validation_1-auc:0.82475
[8]	validation_0-auc:0.84720	validation_1-auc:0.82550
[9]	validation_0-auc:0.85105	validation_1-auc:0.82645
[10]	validation_0-auc:0.85008	validation_1-auc:0.82391
[11]	validation_0-auc:0.85054	validation_1-auc:0.82376
[12]	validation_0-auc:0.85348	validation_1-auc:0.82574
[13]	validation_0-auc:0.85627	validation_1-auc:0.82779
[14]	validation_0-auc:0.85712	validation_1-auc:0.82943
[15]	validation_0-auc:0.85893	validation_1-auc:0.82953
[16]	validation_0-auc:0.86010	validation_1-auc:0.83139
[17]	validation_0-auc:0.86143	validation_1-auc:0.83212
[18]	validation_0-auc:0.86209	validation_1-auc:0.83231
[19]	validation_0-auc:0.86371	validation_1-auc:0.83344
[20]	validation_0-auc:0.86548	validation_1-auc:0.83371
[21]	validation_0-auc:0.86645	validation_1-auc:0.83405
[22]	validation_0-auc:0.86737	validation_1-auc:0.83473
[23]	validation_0-auc:0.86825	validation_1-auc:0.83551
[24]	validation_0-auc:0.86925	validation_1-auc:0.83528
[25]	validation_0-auc:0.86977	validation_1-auc:0.83611
[26]	validation_0-auc:0.87091	validation_1-auc:0.83597
[27]	validation_0-auc:0.87173	validation_1-auc:0.83643
[28]	validation_0-auc:0.87245	validation_1-auc:0.83664
[29]	validation_0-auc:0.87352	validation_1-auc:0.83738
[30]	validation_0-auc:0.87455	validation_1-auc:0.83692
[31]	validation_0-auc:0.87495	validation_1-auc:0.83709
[32]	validation_0-auc:0.87556	validation_1-auc:0.83759
[33]	validation_0-auc:0.87610	validation_1-auc:0.83777
[34]	validation_0-auc:0.87636	validation_1-auc:0.83775
[35]	validation_0-auc:0.87709	validation_1-auc:0.83790
[36]	validation_0-auc:0.87784	validation_1-auc:0.83774
[37]	validation_0-auc:0.87818	validation_1-auc:0.83817
[38]	validation_0-auc:0.87859	validation_1-auc:0.83840
[39]	validation_0-auc:0.87882	validation_1-auc:0.83858
[40]	validation_0-auc:0.87928	validation_1-auc:0.83868
[41]	validation_0-auc:0.87993	validation_1-auc:0.83881
[42]	validation_0-auc:0.88021	validation_1-auc:0.83904
[43]	validation_0-auc:0.88097	validation_1-auc:0.83885
[44]	validation_0-auc:0.88181	validation_1-auc:0.83890
[45]	validation_0-auc:0.88191	validation_1-auc:0.83882
[46]	validation_0-auc:0.88245	validation_1-auc:0.83898
[47]	validation_0-auc:0.88265	validation_1-auc:0.83876
[48]	validation_0-auc:0.88282	validation_1-auc:0.83888
[49]	validation_0-auc:0.88304	validation_1-auc:0.83886
[50]	validation_0-auc:0.88335	validation_1-auc:0.83894
[51]	validation_0-auc:0.88354	validation_1-auc:0.83886
[52]	validation_0-auc:0.88380	validation_1-auc:0.83869
[53]	validation_0-auc:0.88475	validation_1-auc:0.83873
[54]	validation_0-auc:0.88495	validation_1-auc:0.83874
[55]	validation_0-auc:0.88511	validation_1-auc:0.83872
[56]	validation_0-auc:0.88531	validation_1-auc:0.83856
[57]	validation_0-auc:0.88552	validation_1-auc:0.83857
[58]	validation_0-auc:0.88654	validation_1-auc:0.83837
[59]	validation_0-auc:0.88669	validation_1-auc:0.83827
[60]	validation_0-auc:0.88709	validation_1-auc:0.83825
[61]	validation_0-auc:0.88774	validation_1-auc:0.83819
[62]	validation_0-auc:0.88823	validation_1-auc:0.83810
[63]	validation_0-auc:0.88833	validation_1-auc:0.83818
[64]	validation_0-auc:0.88883	validation_1-auc:0.83801
[65]	validation_0-auc:0.88931	validation_1-auc:0.83807
[66]	validation_0-auc:0.88983	validation_1-auc:0.83817
[67]	validation_0-auc:0.89033	validation_1-auc:0.83818
[68]	validation_0-auc:0.89045	validation_1-auc:0.83811
[69]	validation_0-auc:0.89093	validation_1-auc:0.83837
[70]	validation_0-auc:0.89110	validation_1-auc:0.83827
[71]	validation_0-auc:0.89149	validation_1-auc:0.83811
[72]	validation_0-auc:0.89153	validation_1-auc:0.83824
 66%|██████▌   | 33/50 [07:11<03:09, 11.13s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81935	validation_1-auc:0.81076
[1]	validation_0-auc:0.83159	validation_1-auc:0.82451
[2]	validation_0-auc:0.83535	validation_1-auc:0.82315
[3]	validation_0-auc:0.83929	validation_1-auc:0.82781
[4]	validation_0-auc:0.84191	validation_1-auc:0.82917
[5]	validation_0-auc:0.84339	validation_1-auc:0.83080
[6]	validation_0-auc:0.84433	validation_1-auc:0.83117
[7]	validation_0-auc:0.84388	validation_1-auc:0.83051
[8]	validation_0-auc:0.84510	validation_1-auc:0.83246
[9]	validation_0-auc:0.84694	validation_1-auc:0.83174
[10]	validation_0-auc:0.84569	validation_1-auc:0.83008
[11]	validation_0-auc:0.84415	validation_1-auc:0.82678
[12]	validation_0-auc:0.84949	validation_1-auc:0.83092
[13]	validation_0-auc:0.85392	validation_1-auc:0.83431
[14]	validation_0-auc:0.85564	validation_1-auc:0.83660
[15]	validation_0-auc:0.85689	validation_1-auc:0.83847
[16]	validation_0-auc:0.85824	validation_1-auc:0.83957
[17]	validation_0-auc:0.85911	validation_1-auc:0.84040
[18]	validation_0-auc:0.85881	validation_1-auc:0.83872
[19]	validation_0-auc:0.86006	validation_1-auc:0.83999
[20]	validation_0-auc:0.86139	validation_1-auc:0.84131
[21]	validation_0-auc:0.86240	validation_1-auc:0.84239
[22]	validation_0-auc:0.86350	validation_1-auc:0.84266
[23]	validation_0-auc:0.86415	validation_1-auc:0.84268
[24]	validation_0-auc:0.86522	validation_1-auc:0.84231
[25]	validation_0-auc:0.86589	validation_1-auc:0.84221
[26]	validation_0-auc:0.86716	validation_1-auc:0.84215
[27]	validation_0-auc:0.86807	validation_1-auc:0.84223
[28]	validation_0-auc:0.86851	validation_1-auc:0.84202
[29]	validation_0-auc:0.86926	validation_1-auc:0.84228
[30]	validation_0-auc:0.87060	validation_1-auc:0.84228
[31]	validation_0-auc:0.87157	validation_1-auc:0.84301
[32]	validation_0-auc:0.87184	validation_1-auc:0.84349
[33]	validation_0-auc:0.87193	validation_1-auc:0.84361
[34]	validation_0-auc:0.87231	validation_1-auc:0.84355
[35]	validation_0-auc:0.87270	validation_1-auc:0.84386
[36]	validation_0-auc:0.87321	validation_1-auc:0.84393
[37]	validation_0-auc:0.87401	validation_1-auc:0.84427
[38]	validation_0-auc:0.87473	validation_1-auc:0.84442
[39]	validation_0-auc:0.87505	validation_1-auc:0.84463
[40]	validation_0-auc:0.87545	validation_1-auc:0.84484
[41]	validation_0-auc:0.87621	validation_1-auc:0.84492
[42]	validation_0-auc:0.87695	validation_1-auc:0.84483
[43]	validation_0-auc:0.87768	validation_1-auc:0.84467
[44]	validation_0-auc:0.87795	validation_1-auc:0.84480
[45]	validation_0-auc:0.87852	validation_1-auc:0.84474
[46]	validation_0-auc:0.87910	validation_1-auc:0.84480
[47]	validation_0-auc:0.87963	validation_1-auc:0.84460
[48]	validation_0-auc:0.87992	validation_1-auc:0.84466
[49]	validation_0-auc:0.88070	validation_1-auc:0.84487
[50]	validation_0-auc:0.88087	validation_1-auc:0.84505
[51]	validation_0-auc:0.88105	validation_1-auc:0.84501
[52]	validation_0-auc:0.88184	validation_1-auc:0.84496
[53]	validation_0-auc:0.88199	validation_1-auc:0.84513
[54]	validation_0-auc:0.88219	validation_1-auc:0.84514
[55]	validation_0-auc:0.88293	validation_1-auc:0.84475
[56]	validation_0-auc:0.88315	validation_1-auc:0.84443
[57]	validation_0-auc:0.88326	validation_1-auc:0.84450
[58]	validation_0-auc:0.88362	validation_1-auc:0.84444
[59]	validation_0-auc:0.88378	validation_1-auc:0.84448
[60]	validation_0-auc:0.88411	validation_1-auc:0.84432
[61]	validation_0-auc:0.88463	validation_1-auc:0.84400
[62]	validation_0-auc:0.88491	validation_1-auc:0.84418
[63]	validation_0-auc:0.88539	validation_1-auc:0.84412
[64]	validation_0-auc:0.88543	validation_1-auc:0.84413
[65]	validation_0-auc:0.88581	validation_1-auc:0.84391
[66]	validation_0-auc:0.88682	validation_1-auc:0.84384
[67]	validation_0-auc:0.88692	validation_1-auc:0.84377
[68]	validation_0-auc:0.88764	validation_1-auc:0.84391
[69]	validation_0-auc:0.88770	validation_1-auc:0.84384
[70]	validation_0-auc:0.88785	validation_1-auc:0.84389
[71]	validation_0-auc:0.88808	validation_1-auc:0.84391
[72]	validation_0-auc:0.88825	validation_1-auc:0.84388
[73]	validation_0-auc:0.88860	validation_1-auc:0.84398
[74]	validation_0-auc:0.88873	validation_1-auc:0.84396
[75]	validation_0-auc:0.88886	validation_1-auc:0.84391
[76]	validation_0-auc:0.88961	validation_1-auc:0.84402
[77]	validation_0-auc:0.88969	validation_1-auc:0.84390
[78]	validation_0-auc:0.88992	validation_1-auc:0.84387
[79]	validation_0-auc:0.88997	validation_1-auc:0.84387
[80]	validation_0-auc:0.89026	validation_1-auc:0.84386
[81]	validation_0-auc:0.89038	validation_1-auc:0.84375
[82]	validation_0-auc:0.89084	validation_1-auc:0.84359
[83]	validation_0-auc:0.89127	validation_1-auc:0.84358
 68%|██████▊   | 34/50 [07:15<03:01, 11.35s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82699	validation_1-auc:0.81353
[1]	validation_0-auc:0.83225	validation_1-auc:0.81413
[2]	validation_0-auc:0.84218	validation_1-auc:0.82110
[3]	validation_0-auc:0.84450	validation_1-auc:0.82198
[4]	validation_0-auc:0.84592	validation_1-auc:0.82013
[5]	validation_0-auc:0.84994	validation_1-auc:0.82495
[6]	validation_0-auc:0.85467	validation_1-auc:0.83175
[7]	validation_0-auc:0.85611	validation_1-auc:0.83171
[8]	validation_0-auc:0.85793	validation_1-auc:0.83192
[9]	validation_0-auc:0.85864	validation_1-auc:0.83528
[10]	validation_0-auc:0.85717	validation_1-auc:0.83188
[11]	validation_0-auc:0.85768	validation_1-auc:0.82977
[12]	validation_0-auc:0.86131	validation_1-auc:0.83378
[13]	validation_0-auc:0.86320	validation_1-auc:0.83526
[14]	validation_0-auc:0.86485	validation_1-auc:0.83749
[15]	validation_0-auc:0.86554	validation_1-auc:0.83819
[16]	validation_0-auc:0.86687	validation_1-auc:0.83892
[17]	validation_0-auc:0.86809	validation_1-auc:0.83960
[18]	validation_0-auc:0.86847	validation_1-auc:0.83971
[19]	validation_0-auc:0.86967	validation_1-auc:0.84014
[20]	validation_0-auc:0.87154	validation_1-auc:0.84165
[21]	validation_0-auc:0.87248	validation_1-auc:0.84147
[22]	validation_0-auc:0.87467	validation_1-auc:0.84211
[23]	validation_0-auc:0.87584	validation_1-auc:0.84239
[24]	validation_0-auc:0.87675	validation_1-auc:0.84302
[25]	validation_0-auc:0.87712	validation_1-auc:0.84349
[26]	validation_0-auc:0.87815	validation_1-auc:0.84388
[27]	validation_0-auc:0.88004	validation_1-auc:0.84475
[28]	validation_0-auc:0.88028	validation_1-auc:0.84505
[29]	validation_0-auc:0.88125	validation_1-auc:0.84450
[30]	validation_0-auc:0.88198	validation_1-auc:0.84476
[31]	validation_0-auc:0.88285	validation_1-auc:0.84516
[32]	validation_0-auc:0.88352	validation_1-auc:0.84519
[33]	validation_0-auc:0.88371	validation_1-auc:0.84552
[34]	validation_0-auc:0.88390	validation_1-auc:0.84577
[35]	validation_0-auc:0.88410	validation_1-auc:0.84579
[36]	validation_0-auc:0.88490	validation_1-auc:0.84584
[37]	validation_0-auc:0.88504	validation_1-auc:0.84602
[38]	validation_0-auc:0.88621	validation_1-auc:0.84629
[39]	validation_0-auc:0.88640	validation_1-auc:0.84635
[40]	validation_0-auc:0.88655	validation_1-auc:0.84637
[41]	validation_0-auc:0.88732	validation_1-auc:0.84631
[42]	validation_0-auc:0.88788	validation_1-auc:0.84634
[43]	validation_0-auc:0.88884	validation_1-auc:0.84638
[44]	validation_0-auc:0.88924	validation_1-auc:0.84627
[45]	validation_0-auc:0.88988	validation_1-auc:0.84593
[46]	validation_0-auc:0.89003	validation_1-auc:0.84581
[47]	validation_0-auc:0.89102	validation_1-auc:0.84576
[48]	validation_0-auc:0.89129	validation_1-auc:0.84582
[49]	validation_0-auc:0.89227	validation_1-auc:0.84559
[50]	validation_0-auc:0.89261	validation_1-auc:0.84558
[51]	validation_0-auc:0.89272	validation_1-auc:0.84549
[52]	validation_0-auc:0.89303	validation_1-auc:0.84547
[53]	validation_0-auc:0.89338	validation_1-auc:0.84562
[54]	validation_0-auc:0.89348	validation_1-auc:0.84537
[55]	validation_0-auc:0.89396	validation_1-auc:0.84524
[56]	validation_0-auc:0.89412	validation_1-auc:0.84525
[57]	validation_0-auc:0.89510	validation_1-auc:0.84525
[58]	validation_0-auc:0.89578	validation_1-auc:0.84555
[59]	validation_0-auc:0.89593	validation_1-auc:0.84580
[60]	validation_0-auc:0.89657	validation_1-auc:0.84547
[61]	validation_0-auc:0.89725	validation_1-auc:0.84536
[62]	validation_0-auc:0.89737	validation_1-auc:0.84534
[63]	validation_0-auc:0.89766	validation_1-auc:0.84526
[64]	validation_0-auc:0.89801	validation_1-auc:0.84492
[65]	validation_0-auc:0.89825	validation_1-auc:0.84475
[66]	validation_0-auc:0.89845	validation_1-auc:0.84466
[67]	validation_0-auc:0.89887	validation_1-auc:0.84458
[68]	validation_0-auc:0.89923	validation_1-auc:0.84454
[69]	validation_0-auc:0.89940	validation_1-auc:0.84449
[70]	validation_0-auc:0.89969	validation_1-auc:0.84461
[71]	validation_0-auc:0.89998	validation_1-auc:0.84457
[72]	validation_0-auc:0.90014	validation_1-auc:0.84461
[73]	validation_0-auc:0.90045	validation_1-auc:0.84436
 68%|██████▊   | 34/50 [07:19<03:01, 11.35s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82345	validation_1-auc:0.80667
[1]	validation_0-auc:0.83096	validation_1-auc:0.81362
[2]	validation_0-auc:0.83442	validation_1-auc:0.81699
[3]	validation_0-auc:0.83862	validation_1-auc:0.82072
[4]	validation_0-auc:0.84404	validation_1-auc:0.82241
[5]	validation_0-auc:0.84995	validation_1-auc:0.82714
[6]	validation_0-auc:0.85294	validation_1-auc:0.82968
[7]	validation_0-auc:0.85510	validation_1-auc:0.82938
[8]	validation_0-auc:0.85639	validation_1-auc:0.83019
[9]	validation_0-auc:0.85855	validation_1-auc:0.83089
[10]	validation_0-auc:0.85848	validation_1-auc:0.82918
[11]	validation_0-auc:0.85890	validation_1-auc:0.82771
[12]	validation_0-auc:0.86337	validation_1-auc:0.83056
[13]	validation_0-auc:0.86622	validation_1-auc:0.83190
[14]	validation_0-auc:0.86764	validation_1-auc:0.83355
[15]	validation_0-auc:0.86988	validation_1-auc:0.83392
[16]	validation_0-auc:0.87153	validation_1-auc:0.83502
[17]	validation_0-auc:0.87276	validation_1-auc:0.83576
[18]	validation_0-auc:0.87346	validation_1-auc:0.83528
[19]	validation_0-auc:0.87536	validation_1-auc:0.83602
[20]	validation_0-auc:0.87687	validation_1-auc:0.83738
[21]	validation_0-auc:0.87754	validation_1-auc:0.83711
[22]	validation_0-auc:0.87835	validation_1-auc:0.83698
[23]	validation_0-auc:0.88005	validation_1-auc:0.83684
[24]	validation_0-auc:0.88097	validation_1-auc:0.83709
[25]	validation_0-auc:0.88105	validation_1-auc:0.83745
[26]	validation_0-auc:0.88228	validation_1-auc:0.83673
[27]	validation_0-auc:0.88371	validation_1-auc:0.83735
[28]	validation_0-auc:0.88422	validation_1-auc:0.83782
[29]	validation_0-auc:0.88534	validation_1-auc:0.83805
[30]	validation_0-auc:0.88664	validation_1-auc:0.83749
[31]	validation_0-auc:0.88752	validation_1-auc:0.83747
[32]	validation_0-auc:0.88770	validation_1-auc:0.83794
[33]	validation_0-auc:0.88848	validation_1-auc:0.83815
[34]	validation_0-auc:0.88855	validation_1-auc:0.83847
[35]	validation_0-auc:0.88891	validation_1-auc:0.83853
[36]	validation_0-auc:0.88997	validation_1-auc:0.83826
[37]	validation_0-auc:0.89058	validation_1-auc:0.83788
[38]	validation_0-auc:0.89135	validation_1-auc:0.83797
[39]	validation_0-auc:0.89180	validation_1-auc:0.83793
[40]	validation_0-auc:0.89240	validation_1-auc:0.83799
[41]	validation_0-auc:0.89261	validation_1-auc:0.83832
[42]	validation_0-auc:0.89300	validation_1-auc:0.83829
[43]	validation_0-auc:0.89335	validation_1-auc:0.83838
[44]	validation_0-auc:0.89409	validation_1-auc:0.83819
[45]	validation_0-auc:0.89484	validation_1-auc:0.83794
[46]	validation_0-auc:0.89544	validation_1-auc:0.83791
[47]	validation_0-auc:0.89559	validation_1-auc:0.83799
[48]	validation_0-auc:0.89595	validation_1-auc:0.83780
[49]	validation_0-auc:0.89660	validation_1-auc:0.83763
[50]	validation_0-auc:0.89683	validation_1-auc:0.83774
[51]	validation_0-auc:0.89704	validation_1-auc:0.83781
[52]	validation_0-auc:0.89771	validation_1-auc:0.83802
[53]	validation_0-auc:0.89796	validation_1-auc:0.83807
[54]	validation_0-auc:0.89868	validation_1-auc:0.83772
[55]	validation_0-auc:0.89909	validation_1-auc:0.83768
[56]	validation_0-auc:0.89914	validation_1-auc:0.83757
[57]	validation_0-auc:0.90054	validation_1-auc:0.83736
[58]	validation_0-auc:0.90121	validation_1-auc:0.83753
[59]	validation_0-auc:0.90135	validation_1-auc:0.83737
[60]	validation_0-auc:0.90151	validation_1-auc:0.83743
[61]	validation_0-auc:0.90177	validation_1-auc:0.83693
[62]	validation_0-auc:0.90205	validation_1-auc:0.83690
[63]	validation_0-auc:0.90229	validation_1-auc:0.83667
[64]	validation_0-auc:0.90293	validation_1-auc:0.83682
[65]	validation_0-auc:0.90367	validation_1-auc:0.83651
 68%|██████▊   | 34/50 [07:22<03:01, 11.35s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82032	validation_1-auc:0.81077
[1]	validation_0-auc:0.82763	validation_1-auc:0.81453
[2]	validation_0-auc:0.83706	validation_1-auc:0.82252
[3]	validation_0-auc:0.84234	validation_1-auc:0.82883
[4]	validation_0-auc:0.84680	validation_1-auc:0.83236
[5]	validation_0-auc:0.84843	validation_1-auc:0.83111
[6]	validation_0-auc:0.85097	validation_1-auc:0.83290
[7]	validation_0-auc:0.85293	validation_1-auc:0.83466
[8]	validation_0-auc:0.85348	validation_1-auc:0.83546
[9]	validation_0-auc:0.85542	validation_1-auc:0.83749
[10]	validation_0-auc:0.85576	validation_1-auc:0.83551
[11]	validation_0-auc:0.85575	validation_1-auc:0.83293
[12]	validation_0-auc:0.85998	validation_1-auc:0.83585
[13]	validation_0-auc:0.86303	validation_1-auc:0.83838
[14]	validation_0-auc:0.86431	validation_1-auc:0.84017
[15]	validation_0-auc:0.86666	validation_1-auc:0.84117
[16]	validation_0-auc:0.86831	validation_1-auc:0.84189
[17]	validation_0-auc:0.86941	validation_1-auc:0.84309
[18]	validation_0-auc:0.87009	validation_1-auc:0.84152
[19]	validation_0-auc:0.87196	validation_1-auc:0.84269
[20]	validation_0-auc:0.87365	validation_1-auc:0.84414
[21]	validation_0-auc:0.87472	validation_1-auc:0.84303
[22]	validation_0-auc:0.87585	validation_1-auc:0.84354
[23]	validation_0-auc:0.87666	validation_1-auc:0.84401
[24]	validation_0-auc:0.87803	validation_1-auc:0.84430
[25]	validation_0-auc:0.87839	validation_1-auc:0.84436
[26]	validation_0-auc:0.87974	validation_1-auc:0.84472
[27]	validation_0-auc:0.88012	validation_1-auc:0.84465
[28]	validation_0-auc:0.88045	validation_1-auc:0.84505
[29]	validation_0-auc:0.88081	validation_1-auc:0.84522
[30]	validation_0-auc:0.88203	validation_1-auc:0.84480
[31]	validation_0-auc:0.88331	validation_1-auc:0.84487
[32]	validation_0-auc:0.88374	validation_1-auc:0.84539
[33]	validation_0-auc:0.88457	validation_1-auc:0.84494
[34]	validation_0-auc:0.88481	validation_1-auc:0.84516
[35]	validation_0-auc:0.88530	validation_1-auc:0.84517
[36]	validation_0-auc:0.88591	validation_1-auc:0.84525
[37]	validation_0-auc:0.88655	validation_1-auc:0.84520
[38]	validation_0-auc:0.88708	validation_1-auc:0.84515
[39]	validation_0-auc:0.88713	validation_1-auc:0.84536
[40]	validation_0-auc:0.88752	validation_1-auc:0.84543
[41]	validation_0-auc:0.88856	validation_1-auc:0.84514
[42]	validation_0-auc:0.88871	validation_1-auc:0.84511
[43]	validation_0-auc:0.88898	validation_1-auc:0.84520
[44]	validation_0-auc:0.88911	validation_1-auc:0.84556
[45]	validation_0-auc:0.88957	validation_1-auc:0.84546
[46]	validation_0-auc:0.89025	validation_1-auc:0.84557
[47]	validation_0-auc:0.89038	validation_1-auc:0.84568
[48]	validation_0-auc:0.89101	validation_1-auc:0.84548
[49]	validation_0-auc:0.89169	validation_1-auc:0.84540
[50]	validation_0-auc:0.89228	validation_1-auc:0.84507
[51]	validation_0-auc:0.89342	validation_1-auc:0.84531
[52]	validation_0-auc:0.89419	validation_1-auc:0.84518
[53]	validation_0-auc:0.89463	validation_1-auc:0.84512
[54]	validation_0-auc:0.89512	validation_1-auc:0.84481
[55]	validation_0-auc:0.89558	validation_1-auc:0.84468
[56]	validation_0-auc:0.89595	validation_1-auc:0.84439
[57]	validation_0-auc:0.89637	validation_1-auc:0.84416
[58]	validation_0-auc:0.89668	validation_1-auc:0.84393
[59]	validation_0-auc:0.89724	validation_1-auc:0.84386
[60]	validation_0-auc:0.89755	validation_1-auc:0.84390
[61]	validation_0-auc:0.89778	validation_1-auc:0.84384
[62]	validation_0-auc:0.89796	validation_1-auc:0.84356
[63]	validation_0-auc:0.89837	validation_1-auc:0.84334
[64]	validation_0-auc:0.89871	validation_1-auc:0.84353
[65]	validation_0-auc:0.89886	validation_1-auc:0.84342
[66]	validation_0-auc:0.89896	validation_1-auc:0.84341
[67]	validation_0-auc:0.89920	validation_1-auc:0.84299
[68]	validation_0-auc:0.89934	validation_1-auc:0.84285
[69]	validation_0-auc:0.90054	validation_1-auc:0.84253
[70]	validation_0-auc:0.90089	validation_1-auc:0.84240
[71]	validation_0-auc:0.90107	validation_1-auc:0.84215
[72]	validation_0-auc:0.90143	validation_1-auc:0.84228
[73]	validation_0-auc:0.90168	validation_1-auc:0.84200
[74]	validation_0-auc:0.90178	validation_1-auc:0.84185
[75]	validation_0-auc:0.90196	validation_1-auc:0.84177
[76]	validation_0-auc:0.90211	validation_1-auc:0.84188
 70%|███████   | 35/50 [07:26<02:45, 11.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82915	validation_1-auc:0.81461
[1]	validation_0-auc:0.83596	validation_1-auc:0.81556
[2]	validation_0-auc:0.84483	validation_1-auc:0.81924
[3]	validation_0-auc:0.84792	validation_1-auc:0.81955
[4]	validation_0-auc:0.85073	validation_1-auc:0.82092
[5]	validation_0-auc:0.85269	validation_1-auc:0.82429
[6]	validation_0-auc:0.85797	validation_1-auc:0.82886
[7]	validation_0-auc:0.85894	validation_1-auc:0.82882
[8]	validation_0-auc:0.86117	validation_1-auc:0.82898
[9]	validation_0-auc:0.86662	validation_1-auc:0.83337
[10]	validation_0-auc:0.86652	validation_1-auc:0.83405
[11]	validation_0-auc:0.86752	validation_1-auc:0.83259
[12]	validation_0-auc:0.87324	validation_1-auc:0.83577
[13]	validation_0-auc:0.87603	validation_1-auc:0.83681
[14]	validation_0-auc:0.87766	validation_1-auc:0.83898
[15]	validation_0-auc:0.87915	validation_1-auc:0.83995
[16]	validation_0-auc:0.88043	validation_1-auc:0.83988
[17]	validation_0-auc:0.88166	validation_1-auc:0.83942
[18]	validation_0-auc:0.88247	validation_1-auc:0.84019
[19]	validation_0-auc:0.88381	validation_1-auc:0.83992
[20]	validation_0-auc:0.88679	validation_1-auc:0.83985
[21]	validation_0-auc:0.88865	validation_1-auc:0.83972
[22]	validation_0-auc:0.89093	validation_1-auc:0.83991
[23]	validation_0-auc:0.89238	validation_1-auc:0.83989
[24]	validation_0-auc:0.89324	validation_1-auc:0.83989
[25]	validation_0-auc:0.89423	validation_1-auc:0.84117
[26]	validation_0-auc:0.89530	validation_1-auc:0.84119
[27]	validation_0-auc:0.89751	validation_1-auc:0.84192
[28]	validation_0-auc:0.89865	validation_1-auc:0.84156
[29]	validation_0-auc:0.89893	validation_1-auc:0.84194
[30]	validation_0-auc:0.90062	validation_1-auc:0.84170
[31]	validation_0-auc:0.90164	validation_1-auc:0.84185
[32]	validation_0-auc:0.90211	validation_1-auc:0.84210
[33]	validation_0-auc:0.90257	validation_1-auc:0.84238
[34]	validation_0-auc:0.90296	validation_1-auc:0.84251
[35]	validation_0-auc:0.90314	validation_1-auc:0.84240
[36]	validation_0-auc:0.90390	validation_1-auc:0.84247
[37]	validation_0-auc:0.90443	validation_1-auc:0.84259
[38]	validation_0-auc:0.90489	validation_1-auc:0.84238
[39]	validation_0-auc:0.90516	validation_1-auc:0.84207
[40]	validation_0-auc:0.90529	validation_1-auc:0.84221
[41]	validation_0-auc:0.90566	validation_1-auc:0.84213
[42]	validation_0-auc:0.90597	validation_1-auc:0.84185
[43]	validation_0-auc:0.90637	validation_1-auc:0.84186
[44]	validation_0-auc:0.90771	validation_1-auc:0.84124
[45]	validation_0-auc:0.90826	validation_1-auc:0.84151
[46]	validation_0-auc:0.90832	validation_1-auc:0.84153
[47]	validation_0-auc:0.90887	validation_1-auc:0.84137
[48]	validation_0-auc:0.90897	validation_1-auc:0.84142
[49]	validation_0-auc:0.90961	validation_1-auc:0.84129
[50]	validation_0-auc:0.90995	validation_1-auc:0.84152
[51]	validation_0-auc:0.91022	validation_1-auc:0.84159
[52]	validation_0-auc:0.91134	validation_1-auc:0.84156
[53]	validation_0-auc:0.91161	validation_1-auc:0.84163
[54]	validation_0-auc:0.91185	validation_1-auc:0.84150
[55]	validation_0-auc:0.91276	validation_1-auc:0.84190
[56]	validation_0-auc:0.91282	validation_1-auc:0.84179
[57]	validation_0-auc:0.91292	validation_1-auc:0.84181
[58]	validation_0-auc:0.91366	validation_1-auc:0.84178
[59]	validation_0-auc:0.91452	validation_1-auc:0.84166
[60]	validation_0-auc:0.91493	validation_1-auc:0.84150
[61]	validation_0-auc:0.91594	validation_1-auc:0.84152
[62]	validation_0-auc:0.91610	validation_1-auc:0.84149
[63]	validation_0-auc:0.91677	validation_1-auc:0.84124
[64]	validation_0-auc:0.91746	validation_1-auc:0.84090
[65]	validation_0-auc:0.91763	validation_1-auc:0.84086
[66]	validation_0-auc:0.91824	validation_1-auc:0.84004
 70%|███████   | 35/50 [07:29<02:45, 11.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82600	validation_1-auc:0.80649
[1]	validation_0-auc:0.83469	validation_1-auc:0.81317
[2]	validation_0-auc:0.84229	validation_1-auc:0.81788
[3]	validation_0-auc:0.84384	validation_1-auc:0.81882
[4]	validation_0-auc:0.85127	validation_1-auc:0.82253
[5]	validation_0-auc:0.85466	validation_1-auc:0.82532
[6]	validation_0-auc:0.85783	validation_1-auc:0.82650
[7]	validation_0-auc:0.86164	validation_1-auc:0.82924
[8]	validation_0-auc:0.86327	validation_1-auc:0.82893
[9]	validation_0-auc:0.86717	validation_1-auc:0.82970
[10]	validation_0-auc:0.86944	validation_1-auc:0.82888
[11]	validation_0-auc:0.87079	validation_1-auc:0.82959
[12]	validation_0-auc:0.87551	validation_1-auc:0.83134
[13]	validation_0-auc:0.87848	validation_1-auc:0.83248
[14]	validation_0-auc:0.87952	validation_1-auc:0.83312
[15]	validation_0-auc:0.88270	validation_1-auc:0.83439
[16]	validation_0-auc:0.88461	validation_1-auc:0.83522
[17]	validation_0-auc:0.88622	validation_1-auc:0.83557
[18]	validation_0-auc:0.88703	validation_1-auc:0.83539
[19]	validation_0-auc:0.88863	validation_1-auc:0.83616
[20]	validation_0-auc:0.89068	validation_1-auc:0.83638
[21]	validation_0-auc:0.89171	validation_1-auc:0.83610
[22]	validation_0-auc:0.89327	validation_1-auc:0.83598
[23]	validation_0-auc:0.89471	validation_1-auc:0.83668
[24]	validation_0-auc:0.89590	validation_1-auc:0.83654
[25]	validation_0-auc:0.89683	validation_1-auc:0.83728
[26]	validation_0-auc:0.89808	validation_1-auc:0.83671
[27]	validation_0-auc:0.89875	validation_1-auc:0.83659
[28]	validation_0-auc:0.90004	validation_1-auc:0.83677
[29]	validation_0-auc:0.90042	validation_1-auc:0.83704
[30]	validation_0-auc:0.90143	validation_1-auc:0.83659
[31]	validation_0-auc:0.90205	validation_1-auc:0.83660
[32]	validation_0-auc:0.90326	validation_1-auc:0.83670
[33]	validation_0-auc:0.90331	validation_1-auc:0.83657
[34]	validation_0-auc:0.90414	validation_1-auc:0.83666
[35]	validation_0-auc:0.90473	validation_1-auc:0.83675
[36]	validation_0-auc:0.90556	validation_1-auc:0.83642
[37]	validation_0-auc:0.90596	validation_1-auc:0.83597
[38]	validation_0-auc:0.90679	validation_1-auc:0.83567
[39]	validation_0-auc:0.90711	validation_1-auc:0.83586
[40]	validation_0-auc:0.90741	validation_1-auc:0.83601
[41]	validation_0-auc:0.90814	validation_1-auc:0.83588
[42]	validation_0-auc:0.90856	validation_1-auc:0.83568
[43]	validation_0-auc:0.90969	validation_1-auc:0.83527
[44]	validation_0-auc:0.91015	validation_1-auc:0.83497
[45]	validation_0-auc:0.91047	validation_1-auc:0.83505
[46]	validation_0-auc:0.91103	validation_1-auc:0.83483
[47]	validation_0-auc:0.91196	validation_1-auc:0.83448
[48]	validation_0-auc:0.91262	validation_1-auc:0.83439
[49]	validation_0-auc:0.91292	validation_1-auc:0.83448
[50]	validation_0-auc:0.91317	validation_1-auc:0.83439
[51]	validation_0-auc:0.91364	validation_1-auc:0.83414
[52]	validation_0-auc:0.91383	validation_1-auc:0.83419
[53]	validation_0-auc:0.91428	validation_1-auc:0.83377
[54]	validation_0-auc:0.91439	validation_1-auc:0.83375
 70%|███████   | 35/50 [07:32<02:45, 11.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82223	validation_1-auc:0.81071
[1]	validation_0-auc:0.83751	validation_1-auc:0.82594
[2]	validation_0-auc:0.84504	validation_1-auc:0.83087
[3]	validation_0-auc:0.84820	validation_1-auc:0.83271
[4]	validation_0-auc:0.85322	validation_1-auc:0.83334
[5]	validation_0-auc:0.85431	validation_1-auc:0.83280
[6]	validation_0-auc:0.85608	validation_1-auc:0.83315
[7]	validation_0-auc:0.85746	validation_1-auc:0.83288
[8]	validation_0-auc:0.85887	validation_1-auc:0.83403
[9]	validation_0-auc:0.86324	validation_1-auc:0.83423
[10]	validation_0-auc:0.86320	validation_1-auc:0.83021
[11]	validation_0-auc:0.86376	validation_1-auc:0.82850
[12]	validation_0-auc:0.86867	validation_1-auc:0.83200
[13]	validation_0-auc:0.87260	validation_1-auc:0.83427
[14]	validation_0-auc:0.87556	validation_1-auc:0.83725
[15]	validation_0-auc:0.87863	validation_1-auc:0.83829
[16]	validation_0-auc:0.88028	validation_1-auc:0.83953
[17]	validation_0-auc:0.88269	validation_1-auc:0.84032
[18]	validation_0-auc:0.88447	validation_1-auc:0.83836
[19]	validation_0-auc:0.88581	validation_1-auc:0.83935
[20]	validation_0-auc:0.88762	validation_1-auc:0.84091
[21]	validation_0-auc:0.88936	validation_1-auc:0.84011
[22]	validation_0-auc:0.89067	validation_1-auc:0.84097
[23]	validation_0-auc:0.89162	validation_1-auc:0.84153
[24]	validation_0-auc:0.89304	validation_1-auc:0.84103
[25]	validation_0-auc:0.89344	validation_1-auc:0.84131
[26]	validation_0-auc:0.89509	validation_1-auc:0.84099
[27]	validation_0-auc:0.89645	validation_1-auc:0.84098
[28]	validation_0-auc:0.89733	validation_1-auc:0.84171
[29]	validation_0-auc:0.89825	validation_1-auc:0.84208
[30]	validation_0-auc:0.89915	validation_1-auc:0.84124
[31]	validation_0-auc:0.90013	validation_1-auc:0.84143
[32]	validation_0-auc:0.90075	validation_1-auc:0.84173
[33]	validation_0-auc:0.90132	validation_1-auc:0.84199
[34]	validation_0-auc:0.90182	validation_1-auc:0.84190
[35]	validation_0-auc:0.90233	validation_1-auc:0.84237
[36]	validation_0-auc:0.90284	validation_1-auc:0.84222
[37]	validation_0-auc:0.90300	validation_1-auc:0.84221
[38]	validation_0-auc:0.90348	validation_1-auc:0.84225
[39]	validation_0-auc:0.90494	validation_1-auc:0.84238
[40]	validation_0-auc:0.90512	validation_1-auc:0.84248
[41]	validation_0-auc:0.90547	validation_1-auc:0.84255
[42]	validation_0-auc:0.90689	validation_1-auc:0.84261
[43]	validation_0-auc:0.90742	validation_1-auc:0.84250
[44]	validation_0-auc:0.90760	validation_1-auc:0.84246
[45]	validation_0-auc:0.90811	validation_1-auc:0.84221
[46]	validation_0-auc:0.90831	validation_1-auc:0.84244
[47]	validation_0-auc:0.90852	validation_1-auc:0.84241
[48]	validation_0-auc:0.90904	validation_1-auc:0.84241
[49]	validation_0-auc:0.90919	validation_1-auc:0.84216
[50]	validation_0-auc:0.90932	validation_1-auc:0.84203
[51]	validation_0-auc:0.91010	validation_1-auc:0.84203
[52]	validation_0-auc:0.91018	validation_1-auc:0.84207
[53]	validation_0-auc:0.91046	validation_1-auc:0.84193
[54]	validation_0-auc:0.91079	validation_1-auc:0.84161
[55]	validation_0-auc:0.91105	validation_1-auc:0.84138
[56]	validation_0-auc:0.91159	validation_1-auc:0.84136
[57]	validation_0-auc:0.91220	validation_1-auc:0.84121
[58]	validation_0-auc:0.91228	validation_1-auc:0.84116
[59]	validation_0-auc:0.91281	validation_1-auc:0.84106
[60]	validation_0-auc:0.91306	validation_1-auc:0.84115
[61]	validation_0-auc:0.91323	validation_1-auc:0.84112
[62]	validation_0-auc:0.91340	validation_1-auc:0.84103
[63]	validation_0-auc:0.91352	validation_1-auc:0.84103
[64]	validation_0-auc:0.91406	validation_1-auc:0.84098
[65]	validation_0-auc:0.91432	validation_1-auc:0.84073
[66]	validation_0-auc:0.91464	validation_1-auc:0.84044
[67]	validation_0-auc:0.91473	validation_1-auc:0.84035
[68]	validation_0-auc:0.91549	validation_1-auc:0.84019
[69]	validation_0-auc:0.91564	validation_1-auc:0.84022
[70]	validation_0-auc:0.91596	validation_1-auc:0.84034
[71]	validation_0-auc:0.91611	validation_1-auc:0.84020
[72]	validation_0-auc:0.91633	validation_1-auc:0.84011
 72%|███████▏  | 36/50 [07:36<02:32, 10.88s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83209	validation_1-auc:0.81440
[1]	validation_0-auc:0.83941	validation_1-auc:0.81462
[2]	validation_0-auc:0.84642	validation_1-auc:0.81841
[3]	validation_0-auc:0.85029	validation_1-auc:0.81868
[4]	validation_0-auc:0.85712	validation_1-auc:0.82098
[5]	validation_0-auc:0.86385	validation_1-auc:0.82499
[6]	validation_0-auc:0.87158	validation_1-auc:0.82955
[7]	validation_0-auc:0.87515	validation_1-auc:0.83002
[8]	validation_0-auc:0.87777	validation_1-auc:0.82937
[9]	validation_0-auc:0.87970	validation_1-auc:0.82846
[10]	validation_0-auc:0.87985	validation_1-auc:0.82844
[11]	validation_0-auc:0.88134	validation_1-auc:0.82777
[12]	validation_0-auc:0.88678	validation_1-auc:0.83180
[13]	validation_0-auc:0.89112	validation_1-auc:0.83369
[14]	validation_0-auc:0.89210	validation_1-auc:0.83519
[15]	validation_0-auc:0.89619	validation_1-auc:0.83732
[16]	validation_0-auc:0.89766	validation_1-auc:0.83624
[17]	validation_0-auc:0.90019	validation_1-auc:0.83631
[18]	validation_0-auc:0.90055	validation_1-auc:0.83551
[19]	validation_0-auc:0.90354	validation_1-auc:0.83622
[20]	validation_0-auc:0.90562	validation_1-auc:0.83643
[21]	validation_0-auc:0.90671	validation_1-auc:0.83572
[22]	validation_0-auc:0.90935	validation_1-auc:0.83515
[23]	validation_0-auc:0.91154	validation_1-auc:0.83568
[24]	validation_0-auc:0.91262	validation_1-auc:0.83629
[25]	validation_0-auc:0.91376	validation_1-auc:0.83621
[26]	validation_0-auc:0.91552	validation_1-auc:0.83625
[27]	validation_0-auc:0.91754	validation_1-auc:0.83646
[28]	validation_0-auc:0.91827	validation_1-auc:0.83692
[29]	validation_0-auc:0.91892	validation_1-auc:0.83719
[30]	validation_0-auc:0.92074	validation_1-auc:0.83811
[31]	validation_0-auc:0.92136	validation_1-auc:0.83872
[32]	validation_0-auc:0.92222	validation_1-auc:0.83934
[33]	validation_0-auc:0.92258	validation_1-auc:0.83920
[34]	validation_0-auc:0.92319	validation_1-auc:0.83998
[35]	validation_0-auc:0.92376	validation_1-auc:0.84088
[36]	validation_0-auc:0.92491	validation_1-auc:0.84044
[37]	validation_0-auc:0.92592	validation_1-auc:0.84080
[38]	validation_0-auc:0.92707	validation_1-auc:0.84076
[39]	validation_0-auc:0.92744	validation_1-auc:0.84049
[40]	validation_0-auc:0.92788	validation_1-auc:0.84062
[41]	validation_0-auc:0.92839	validation_1-auc:0.84016
[42]	validation_0-auc:0.92903	validation_1-auc:0.83989
[43]	validation_0-auc:0.92999	validation_1-auc:0.83981
[44]	validation_0-auc:0.93030	validation_1-auc:0.83970
[45]	validation_0-auc:0.93102	validation_1-auc:0.83948
[46]	validation_0-auc:0.93119	validation_1-auc:0.83957
[47]	validation_0-auc:0.93161	validation_1-auc:0.83929
[48]	validation_0-auc:0.93186	validation_1-auc:0.83916
[49]	validation_0-auc:0.93259	validation_1-auc:0.83893
[50]	validation_0-auc:0.93273	validation_1-auc:0.83897
[51]	validation_0-auc:0.93309	validation_1-auc:0.83895
[52]	validation_0-auc:0.93354	validation_1-auc:0.83906
[53]	validation_0-auc:0.93444	validation_1-auc:0.83901
[54]	validation_0-auc:0.93497	validation_1-auc:0.83907
[55]	validation_0-auc:0.93548	validation_1-auc:0.83867
[56]	validation_0-auc:0.93591	validation_1-auc:0.83883
[57]	validation_0-auc:0.93618	validation_1-auc:0.83892
[58]	validation_0-auc:0.93633	validation_1-auc:0.83894
[59]	validation_0-auc:0.93693	validation_1-auc:0.83902
[60]	validation_0-auc:0.93722	validation_1-auc:0.83929
[61]	validation_0-auc:0.93739	validation_1-auc:0.83919
[62]	validation_0-auc:0.93749	validation_1-auc:0.83915
[63]	validation_0-auc:0.93768	validation_1-auc:0.83889
[64]	validation_0-auc:0.93777	validation_1-auc:0.83880
 72%|███████▏  | 36/50 [07:41<02:32, 10.88s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82865	validation_1-auc:0.80828
[1]	validation_0-auc:0.83627	validation_1-auc:0.81502
[2]	validation_0-auc:0.83998	validation_1-auc:0.81531
[3]	validation_0-auc:0.84601	validation_1-auc:0.81951
[4]	validation_0-auc:0.85682	validation_1-auc:0.82351
[5]	validation_0-auc:0.86220	validation_1-auc:0.82803
[6]	validation_0-auc:0.86837	validation_1-auc:0.82965
[7]	validation_0-auc:0.87382	validation_1-auc:0.83026
[8]	validation_0-auc:0.87810	validation_1-auc:0.83156
[9]	validation_0-auc:0.87978	validation_1-auc:0.83081
[10]	validation_0-auc:0.88187	validation_1-auc:0.82902
[11]	validation_0-auc:0.88510	validation_1-auc:0.82819
[12]	validation_0-auc:0.89092	validation_1-auc:0.82799
[13]	validation_0-auc:0.89574	validation_1-auc:0.83069
[14]	validation_0-auc:0.89714	validation_1-auc:0.83196
[15]	validation_0-auc:0.89959	validation_1-auc:0.83151
[16]	validation_0-auc:0.90185	validation_1-auc:0.83270
[17]	validation_0-auc:0.90429	validation_1-auc:0.83429
[18]	validation_0-auc:0.90509	validation_1-auc:0.83367
[19]	validation_0-auc:0.90711	validation_1-auc:0.83428
[20]	validation_0-auc:0.90886	validation_1-auc:0.83465
[21]	validation_0-auc:0.90955	validation_1-auc:0.83395
[22]	validation_0-auc:0.91098	validation_1-auc:0.83422
[23]	validation_0-auc:0.91282	validation_1-auc:0.83455
[24]	validation_0-auc:0.91458	validation_1-auc:0.83477
[25]	validation_0-auc:0.91535	validation_1-auc:0.83578
[26]	validation_0-auc:0.91701	validation_1-auc:0.83488
[27]	validation_0-auc:0.91866	validation_1-auc:0.83483
[28]	validation_0-auc:0.91907	validation_1-auc:0.83563
[29]	validation_0-auc:0.92012	validation_1-auc:0.83636
[30]	validation_0-auc:0.92174	validation_1-auc:0.83559
[31]	validation_0-auc:0.92266	validation_1-auc:0.83602
[32]	validation_0-auc:0.92356	validation_1-auc:0.83612
[33]	validation_0-auc:0.92377	validation_1-auc:0.83646
[34]	validation_0-auc:0.92478	validation_1-auc:0.83587
[35]	validation_0-auc:0.92550	validation_1-auc:0.83606
[36]	validation_0-auc:0.92652	validation_1-auc:0.83577
[37]	validation_0-auc:0.92758	validation_1-auc:0.83504
[38]	validation_0-auc:0.92809	validation_1-auc:0.83489
[39]	validation_0-auc:0.92813	validation_1-auc:0.83525
[40]	validation_0-auc:0.92830	validation_1-auc:0.83578
[41]	validation_0-auc:0.92892	validation_1-auc:0.83565
[42]	validation_0-auc:0.92926	validation_1-auc:0.83537
[43]	validation_0-auc:0.92982	validation_1-auc:0.83541
[44]	validation_0-auc:0.93022	validation_1-auc:0.83544
[45]	validation_0-auc:0.93059	validation_1-auc:0.83581
[46]	validation_0-auc:0.93086	validation_1-auc:0.83556
[47]	validation_0-auc:0.93131	validation_1-auc:0.83533
[48]	validation_0-auc:0.93165	validation_1-auc:0.83542
[49]	validation_0-auc:0.93201	validation_1-auc:0.83499
[50]	validation_0-auc:0.93244	validation_1-auc:0.83482
[51]	validation_0-auc:0.93317	validation_1-auc:0.83454
[52]	validation_0-auc:0.93355	validation_1-auc:0.83454
[53]	validation_0-auc:0.93409	validation_1-auc:0.83448
[54]	validation_0-auc:0.93442	validation_1-auc:0.83433
[55]	validation_0-auc:0.93478	validation_1-auc:0.83404
[56]	validation_0-auc:0.93511	validation_1-auc:0.83360
[57]	validation_0-auc:0.93531	validation_1-auc:0.83361
[58]	validation_0-auc:0.93591	validation_1-auc:0.83296
[59]	validation_0-auc:0.93620	validation_1-auc:0.83266
[60]	validation_0-auc:0.93632	validation_1-auc:0.83260
[61]	validation_0-auc:0.93673	validation_1-auc:0.83237
[62]	validation_0-auc:0.93687	validation_1-auc:0.83214
[63]	validation_0-auc:0.93703	validation_1-auc:0.83192
 72%|███████▏  | 36/50 [07:45<02:32, 10.88s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82540	validation_1-auc:0.80953
[1]	validation_0-auc:0.84368	validation_1-auc:0.82410
[2]	validation_0-auc:0.84989	validation_1-auc:0.82883
[3]	validation_0-auc:0.85649	validation_1-auc:0.83179
[4]	validation_0-auc:0.86153	validation_1-auc:0.83205
[5]	validation_0-auc:0.86458	validation_1-auc:0.83179
[6]	validation_0-auc:0.86907	validation_1-auc:0.83275
[7]	validation_0-auc:0.87296	validation_1-auc:0.83272
[8]	validation_0-auc:0.87532	validation_1-auc:0.83321
[9]	validation_0-auc:0.87767	validation_1-auc:0.83298
[10]	validation_0-auc:0.87955	validation_1-auc:0.83078
[11]	validation_0-auc:0.88104	validation_1-auc:0.82933
[12]	validation_0-auc:0.88614	validation_1-auc:0.83099
[13]	validation_0-auc:0.89000	validation_1-auc:0.83419
[14]	validation_0-auc:0.89161	validation_1-auc:0.83603
[15]	validation_0-auc:0.89539	validation_1-auc:0.83741
[16]	validation_0-auc:0.89663	validation_1-auc:0.83861
[17]	validation_0-auc:0.89962	validation_1-auc:0.84033
[18]	validation_0-auc:0.90083	validation_1-auc:0.83802
[19]	validation_0-auc:0.90281	validation_1-auc:0.83920
[20]	validation_0-auc:0.90433	validation_1-auc:0.83960
[21]	validation_0-auc:0.90588	validation_1-auc:0.83916
[22]	validation_0-auc:0.90819	validation_1-auc:0.84133
[23]	validation_0-auc:0.90972	validation_1-auc:0.84184
[24]	validation_0-auc:0.91108	validation_1-auc:0.84157
[25]	validation_0-auc:0.91172	validation_1-auc:0.84193
[26]	validation_0-auc:0.91372	validation_1-auc:0.84184
[27]	validation_0-auc:0.91514	validation_1-auc:0.84197
[28]	validation_0-auc:0.91559	validation_1-auc:0.84182
[29]	validation_0-auc:0.91630	validation_1-auc:0.84190
[30]	validation_0-auc:0.91803	validation_1-auc:0.84117
[31]	validation_0-auc:0.91964	validation_1-auc:0.84128
[32]	validation_0-auc:0.92020	validation_1-auc:0.84186
[33]	validation_0-auc:0.92048	validation_1-auc:0.84170
[34]	validation_0-auc:0.92113	validation_1-auc:0.84167
[35]	validation_0-auc:0.92209	validation_1-auc:0.84209
[36]	validation_0-auc:0.92335	validation_1-auc:0.84181
[37]	validation_0-auc:0.92400	validation_1-auc:0.84172
[38]	validation_0-auc:0.92545	validation_1-auc:0.84150
[39]	validation_0-auc:0.92571	validation_1-auc:0.84189
[40]	validation_0-auc:0.92586	validation_1-auc:0.84177
[41]	validation_0-auc:0.92660	validation_1-auc:0.84219
[42]	validation_0-auc:0.92708	validation_1-auc:0.84272
[43]	validation_0-auc:0.92772	validation_1-auc:0.84204
[44]	validation_0-auc:0.92827	validation_1-auc:0.84206
[45]	validation_0-auc:0.92883	validation_1-auc:0.84184
[46]	validation_0-auc:0.92913	validation_1-auc:0.84187
[47]	validation_0-auc:0.92987	validation_1-auc:0.84201
[48]	validation_0-auc:0.93032	validation_1-auc:0.84175
[49]	validation_0-auc:0.93109	validation_1-auc:0.84137
[50]	validation_0-auc:0.93135	validation_1-auc:0.84148
[51]	validation_0-auc:0.93252	validation_1-auc:0.84120
[52]	validation_0-auc:0.93292	validation_1-auc:0.84091
[53]	validation_0-auc:0.93338	validation_1-auc:0.84079
[54]	validation_0-auc:0.93378	validation_1-auc:0.84068
[55]	validation_0-auc:0.93423	validation_1-auc:0.84051
[56]	validation_0-auc:0.93488	validation_1-auc:0.83981
[57]	validation_0-auc:0.93533	validation_1-auc:0.83968
[58]	validation_0-auc:0.93567	validation_1-auc:0.83929
[59]	validation_0-auc:0.93592	validation_1-auc:0.83926
[60]	validation_0-auc:0.93625	validation_1-auc:0.83902
[61]	validation_0-auc:0.93649	validation_1-auc:0.83892
[62]	validation_0-auc:0.93659	validation_1-auc:0.83892
[63]	validation_0-auc:0.93703	validation_1-auc:0.83833
[64]	validation_0-auc:0.93716	validation_1-auc:0.83827
[65]	validation_0-auc:0.93726	validation_1-auc:0.83813
[66]	validation_0-auc:0.93759	validation_1-auc:0.83787
[67]	validation_0-auc:0.93782	validation_1-auc:0.83788
[68]	validation_0-auc:0.93796	validation_1-auc:0.83747
[69]	validation_0-auc:0.93815	validation_1-auc:0.83739
[70]	validation_0-auc:0.93832	validation_1-auc:0.83723
[71]	validation_0-auc:0.93846	validation_1-auc:0.83707
[72]	validation_0-auc:0.93880	validation_1-auc:0.83709
 74%|███████▍  | 37/50 [07:50<02:34, 11.89s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83153	validation_1-auc:0.81369
[1]	validation_0-auc:0.83922	validation_1-auc:0.81514
[2]	validation_0-auc:0.84588	validation_1-auc:0.81786
[3]	validation_0-auc:0.84795	validation_1-auc:0.81741
[4]	validation_0-auc:0.85225	validation_1-auc:0.81840
[5]	validation_0-auc:0.85734	validation_1-auc:0.82446
[6]	validation_0-auc:0.86173	validation_1-auc:0.82938
[7]	validation_0-auc:0.86362	validation_1-auc:0.82914
[8]	validation_0-auc:0.86469	validation_1-auc:0.82872
[9]	validation_0-auc:0.86493	validation_1-auc:0.82946
[10]	validation_0-auc:0.86591	validation_1-auc:0.82834
[11]	validation_0-auc:0.86652	validation_1-auc:0.82812
[12]	validation_0-auc:0.87042	validation_1-auc:0.83283
[13]	validation_0-auc:0.87388	validation_1-auc:0.83455
[14]	validation_0-auc:0.87563	validation_1-auc:0.83700
[15]	validation_0-auc:0.87879	validation_1-auc:0.83926
[16]	validation_0-auc:0.88021	validation_1-auc:0.84041
[17]	validation_0-auc:0.88204	validation_1-auc:0.84012
[18]	validation_0-auc:0.88258	validation_1-auc:0.84024
[19]	validation_0-auc:0.88439	validation_1-auc:0.84054
[20]	validation_0-auc:0.88432	validation_1-auc:0.83982
[21]	validation_0-auc:0.88418	validation_1-auc:0.83836
[22]	validation_0-auc:0.88647	validation_1-auc:0.83941
[23]	validation_0-auc:0.88915	validation_1-auc:0.83977
[24]	validation_0-auc:0.89078	validation_1-auc:0.83995
[25]	validation_0-auc:0.89217	validation_1-auc:0.84007
[26]	validation_0-auc:0.89312	validation_1-auc:0.83987
[27]	validation_0-auc:0.89517	validation_1-auc:0.84022
[28]	validation_0-auc:0.89544	validation_1-auc:0.84016
[29]	validation_0-auc:0.89752	validation_1-auc:0.84109
[30]	validation_0-auc:0.89852	validation_1-auc:0.84090
[31]	validation_0-auc:0.90086	validation_1-auc:0.84119
[32]	validation_0-auc:0.90200	validation_1-auc:0.84185
[33]	validation_0-auc:0.90277	validation_1-auc:0.84246
[34]	validation_0-auc:0.90362	validation_1-auc:0.84284
[35]	validation_0-auc:0.90486	validation_1-auc:0.84360
[36]	validation_0-auc:0.90627	validation_1-auc:0.84350
[37]	validation_0-auc:0.90716	validation_1-auc:0.84348
[38]	validation_0-auc:0.90774	validation_1-auc:0.84363
[39]	validation_0-auc:0.90908	validation_1-auc:0.84359
[40]	validation_0-auc:0.90987	validation_1-auc:0.84426
[41]	validation_0-auc:0.91092	validation_1-auc:0.84376
[42]	validation_0-auc:0.91204	validation_1-auc:0.84360
[43]	validation_0-auc:0.91247	validation_1-auc:0.84369
[44]	validation_0-auc:0.91268	validation_1-auc:0.84381
[45]	validation_0-auc:0.91314	validation_1-auc:0.84376
[46]	validation_0-auc:0.91324	validation_1-auc:0.84367
[47]	validation_0-auc:0.91373	validation_1-auc:0.84383
[48]	validation_0-auc:0.91511	validation_1-auc:0.84390
[49]	validation_0-auc:0.91561	validation_1-auc:0.84414
[50]	validation_0-auc:0.91570	validation_1-auc:0.84421
[51]	validation_0-auc:0.91589	validation_1-auc:0.84430
[52]	validation_0-auc:0.91616	validation_1-auc:0.84406
[53]	validation_0-auc:0.91673	validation_1-auc:0.84366
[54]	validation_0-auc:0.91687	validation_1-auc:0.84373
[55]	validation_0-auc:0.91755	validation_1-auc:0.84358
[56]	validation_0-auc:0.91758	validation_1-auc:0.84348
[57]	validation_0-auc:0.91772	validation_1-auc:0.84343
[58]	validation_0-auc:0.91856	validation_1-auc:0.84311
[59]	validation_0-auc:0.91868	validation_1-auc:0.84315
[60]	validation_0-auc:0.91912	validation_1-auc:0.84292
[61]	validation_0-auc:0.91949	validation_1-auc:0.84269
[62]	validation_0-auc:0.91962	validation_1-auc:0.84270
[63]	validation_0-auc:0.91975	validation_1-auc:0.84268
[64]	validation_0-auc:0.92059	validation_1-auc:0.84283
[65]	validation_0-auc:0.92137	validation_1-auc:0.84285
[66]	validation_0-auc:0.92154	validation_1-auc:0.84279
[67]	validation_0-auc:0.92192	validation_1-auc:0.84263
[68]	validation_0-auc:0.92222	validation_1-auc:0.84252
[69]	validation_0-auc:0.92269	validation_1-auc:0.84258
[70]	validation_0-auc:0.92287	validation_1-auc:0.84253
[71]	validation_0-auc:0.92330	validation_1-auc:0.84246
[72]	validation_0-auc:0.92428	validation_1-auc:0.84221
[73]	validation_0-auc:0.92479	validation_1-auc:0.84215
[74]	validation_0-auc:0.92514	validation_1-auc:0.84192
[75]	validation_0-auc:0.92587	validation_1-auc:0.84179
[76]	validation_0-auc:0.92596	validation_1-auc:0.84180
[77]	validation_0-auc:0.92624	validation_1-auc:0.84183
[78]	validation_0-auc:0.92665	validation_1-auc:0.84161
[79]	validation_0-auc:0.92668	validation_1-auc:0.84161
[80]	validation_0-auc:0.92730	validation_1-auc:0.84203
[81]	validation_0-auc:0.92737	validation_1-auc:0.84207
 74%|███████▍  | 37/50 [07:55<02:34, 11.89s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82677	validation_1-auc:0.80655
[1]	validation_0-auc:0.83487	validation_1-auc:0.81114
[2]	validation_0-auc:0.84077	validation_1-auc:0.81582
[3]	validation_0-auc:0.84412	validation_1-auc:0.81933
[4]	validation_0-auc:0.85051	validation_1-auc:0.82250
[5]	validation_0-auc:0.85465	validation_1-auc:0.82414
[6]	validation_0-auc:0.85926	validation_1-auc:0.82615
[7]	validation_0-auc:0.86294	validation_1-auc:0.82781
[8]	validation_0-auc:0.86527	validation_1-auc:0.82895
[9]	validation_0-auc:0.86959	validation_1-auc:0.82955
[10]	validation_0-auc:0.87108	validation_1-auc:0.82770
[11]	validation_0-auc:0.87207	validation_1-auc:0.82757
[12]	validation_0-auc:0.87560	validation_1-auc:0.82924
[13]	validation_0-auc:0.87914	validation_1-auc:0.83010
[14]	validation_0-auc:0.88044	validation_1-auc:0.83152
[15]	validation_0-auc:0.88190	validation_1-auc:0.83185
[16]	validation_0-auc:0.88292	validation_1-auc:0.83411
[17]	validation_0-auc:0.88415	validation_1-auc:0.83422
[18]	validation_0-auc:0.88491	validation_1-auc:0.83385
[19]	validation_0-auc:0.88685	validation_1-auc:0.83374
[20]	validation_0-auc:0.88718	validation_1-auc:0.83416
[21]	validation_0-auc:0.88723	validation_1-auc:0.83259
[22]	validation_0-auc:0.88931	validation_1-auc:0.83470
[23]	validation_0-auc:0.89231	validation_1-auc:0.83559
[24]	validation_0-auc:0.89427	validation_1-auc:0.83622
[25]	validation_0-auc:0.89569	validation_1-auc:0.83630
[26]	validation_0-auc:0.89778	validation_1-auc:0.83617
[27]	validation_0-auc:0.89972	validation_1-auc:0.83678
[28]	validation_0-auc:0.90003	validation_1-auc:0.83627
[29]	validation_0-auc:0.90195	validation_1-auc:0.83726
[30]	validation_0-auc:0.90305	validation_1-auc:0.83646
[31]	validation_0-auc:0.90494	validation_1-auc:0.83621
[32]	validation_0-auc:0.90568	validation_1-auc:0.83672
[33]	validation_0-auc:0.90657	validation_1-auc:0.83680
[34]	validation_0-auc:0.90714	validation_1-auc:0.83706
[35]	validation_0-auc:0.90810	validation_1-auc:0.83710
[36]	validation_0-auc:0.90949	validation_1-auc:0.83666
[37]	validation_0-auc:0.91011	validation_1-auc:0.83627
[38]	validation_0-auc:0.91127	validation_1-auc:0.83538
[39]	validation_0-auc:0.91187	validation_1-auc:0.83548
[40]	validation_0-auc:0.91268	validation_1-auc:0.83530
[41]	validation_0-auc:0.91356	validation_1-auc:0.83515
[42]	validation_0-auc:0.91440	validation_1-auc:0.83541
[43]	validation_0-auc:0.91464	validation_1-auc:0.83590
[44]	validation_0-auc:0.91541	validation_1-auc:0.83646
[45]	validation_0-auc:0.91566	validation_1-auc:0.83655
[46]	validation_0-auc:0.91590	validation_1-auc:0.83683
[47]	validation_0-auc:0.91647	validation_1-auc:0.83671
[48]	validation_0-auc:0.91696	validation_1-auc:0.83644
[49]	validation_0-auc:0.91747	validation_1-auc:0.83638
[50]	validation_0-auc:0.91778	validation_1-auc:0.83625
[51]	validation_0-auc:0.91814	validation_1-auc:0.83610
[52]	validation_0-auc:0.91883	validation_1-auc:0.83555
[53]	validation_0-auc:0.91936	validation_1-auc:0.83524
[54]	validation_0-auc:0.91954	validation_1-auc:0.83508
[55]	validation_0-auc:0.92105	validation_1-auc:0.83426
[56]	validation_0-auc:0.92121	validation_1-auc:0.83418
[57]	validation_0-auc:0.92145	validation_1-auc:0.83407
[58]	validation_0-auc:0.92180	validation_1-auc:0.83387
[59]	validation_0-auc:0.92226	validation_1-auc:0.83354
 74%|███████▍  | 37/50 [07:58<02:34, 11.89s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82349	validation_1-auc:0.80982
[1]	validation_0-auc:0.83124	validation_1-auc:0.81464
[2]	validation_0-auc:0.84228	validation_1-auc:0.82398
[3]	validation_0-auc:0.84761	validation_1-auc:0.82854
[4]	validation_0-auc:0.85529	validation_1-auc:0.83310
[5]	validation_0-auc:0.85604	validation_1-auc:0.83164
[6]	validation_0-auc:0.86032	validation_1-auc:0.83290
[7]	validation_0-auc:0.86317	validation_1-auc:0.83413
[8]	validation_0-auc:0.86368	validation_1-auc:0.83366
[9]	validation_0-auc:0.86623	validation_1-auc:0.83167
[10]	validation_0-auc:0.86586	validation_1-auc:0.83012
[11]	validation_0-auc:0.86753	validation_1-auc:0.82917
[12]	validation_0-auc:0.87052	validation_1-auc:0.83168
[13]	validation_0-auc:0.87454	validation_1-auc:0.83321
[14]	validation_0-auc:0.87581	validation_1-auc:0.83581
[15]	validation_0-auc:0.87743	validation_1-auc:0.83639
[16]	validation_0-auc:0.87929	validation_1-auc:0.83724
[17]	validation_0-auc:0.88077	validation_1-auc:0.83898
[18]	validation_0-auc:0.88187	validation_1-auc:0.83867
[19]	validation_0-auc:0.88510	validation_1-auc:0.83994
[20]	validation_0-auc:0.88633	validation_1-auc:0.83977
[21]	validation_0-auc:0.88714	validation_1-auc:0.83775
[22]	validation_0-auc:0.88883	validation_1-auc:0.83887
[23]	validation_0-auc:0.89098	validation_1-auc:0.83990
[24]	validation_0-auc:0.89342	validation_1-auc:0.83950
[25]	validation_0-auc:0.89472	validation_1-auc:0.84004
[26]	validation_0-auc:0.89676	validation_1-auc:0.84002
[27]	validation_0-auc:0.89918	validation_1-auc:0.84041
[28]	validation_0-auc:0.90002	validation_1-auc:0.83978
[29]	validation_0-auc:0.90223	validation_1-auc:0.84053
[30]	validation_0-auc:0.90377	validation_1-auc:0.84044
[31]	validation_0-auc:0.90504	validation_1-auc:0.84085
[32]	validation_0-auc:0.90589	validation_1-auc:0.84171
[33]	validation_0-auc:0.90650	validation_1-auc:0.84141
[34]	validation_0-auc:0.90713	validation_1-auc:0.84201
[35]	validation_0-auc:0.90796	validation_1-auc:0.84200
[36]	validation_0-auc:0.90953	validation_1-auc:0.84223
[37]	validation_0-auc:0.91042	validation_1-auc:0.84226
[38]	validation_0-auc:0.91152	validation_1-auc:0.84203
[39]	validation_0-auc:0.91218	validation_1-auc:0.84197
[40]	validation_0-auc:0.91294	validation_1-auc:0.84199
[41]	validation_0-auc:0.91401	validation_1-auc:0.84139
[42]	validation_0-auc:0.91436	validation_1-auc:0.84171
[43]	validation_0-auc:0.91473	validation_1-auc:0.84182
[44]	validation_0-auc:0.91542	validation_1-auc:0.84239
[45]	validation_0-auc:0.91580	validation_1-auc:0.84241
[46]	validation_0-auc:0.91598	validation_1-auc:0.84232
[47]	validation_0-auc:0.91629	validation_1-auc:0.84244
[48]	validation_0-auc:0.91688	validation_1-auc:0.84245
[49]	validation_0-auc:0.91750	validation_1-auc:0.84254
[50]	validation_0-auc:0.91775	validation_1-auc:0.84257
[51]	validation_0-auc:0.91836	validation_1-auc:0.84252
[52]	validation_0-auc:0.91876	validation_1-auc:0.84246
[53]	validation_0-auc:0.91953	validation_1-auc:0.84223
[54]	validation_0-auc:0.92008	validation_1-auc:0.84209
[55]	validation_0-auc:0.92086	validation_1-auc:0.84197
[56]	validation_0-auc:0.92124	validation_1-auc:0.84191
[57]	validation_0-auc:0.92148	validation_1-auc:0.84155
[58]	validation_0-auc:0.92171	validation_1-auc:0.84160
[59]	validation_0-auc:0.92195	validation_1-auc:0.84159
[60]	validation_0-auc:0.92208	validation_1-auc:0.84171
[61]	validation_0-auc:0.92244	validation_1-auc:0.84173
[62]	validation_0-auc:0.92258	validation_1-auc:0.84161
[63]	validation_0-auc:0.92268	validation_1-auc:0.84155
[64]	validation_0-auc:0.92370	validation_1-auc:0.84135
[65]	validation_0-auc:0.92429	validation_1-auc:0.84145
[66]	validation_0-auc:0.92453	validation_1-auc:0.84135
[67]	validation_0-auc:0.92463	validation_1-auc:0.84139
[68]	validation_0-auc:0.92482	validation_1-auc:0.84130
[69]	validation_0-auc:0.92528	validation_1-auc:0.84114
[70]	validation_0-auc:0.92539	validation_1-auc:0.84110
[71]	validation_0-auc:0.92552	validation_1-auc:0.84106
[72]	validation_0-auc:0.92610	validation_1-auc:0.84108
[73]	validation_0-auc:0.92655	validation_1-auc:0.84101
[74]	validation_0-auc:0.92662	validation_1-auc:0.84086
[75]	validation_0-auc:0.92680	validation_1-auc:0.84102
[76]	validation_0-auc:0.92705	validation_1-auc:0.84070
[77]	validation_0-auc:0.92735	validation_1-auc:0.84069
[78]	validation_0-auc:0.92748	validation_1-auc:0.84061
[79]	validation_0-auc:0.92764	validation_1-auc:0.84058
 76%|███████▌  | 38/50 [08:02<02:22, 11.86s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82179	validation_1-auc:0.80832
[1]	validation_0-auc:0.82978	validation_1-auc:0.81456
[2]	validation_0-auc:0.83798	validation_1-auc:0.81967
[3]	validation_0-auc:0.83969	validation_1-auc:0.82037
[4]	validation_0-auc:0.84109	validation_1-auc:0.81753
[5]	validation_0-auc:0.84274	validation_1-auc:0.81972
[6]	validation_0-auc:0.84701	validation_1-auc:0.82387
[7]	validation_0-auc:0.84787	validation_1-auc:0.82415
[8]	validation_0-auc:0.84816	validation_1-auc:0.82451
[9]	validation_0-auc:0.85155	validation_1-auc:0.82823
[10]	validation_0-auc:0.85197	validation_1-auc:0.83092
[11]	validation_0-auc:0.85175	validation_1-auc:0.82985
[12]	validation_0-auc:0.85660	validation_1-auc:0.83527
[13]	validation_0-auc:0.85876	validation_1-auc:0.83618
[14]	validation_0-auc:0.85995	validation_1-auc:0.83729
[15]	validation_0-auc:0.86099	validation_1-auc:0.83814
[16]	validation_0-auc:0.86243	validation_1-auc:0.83837
[17]	validation_0-auc:0.86393	validation_1-auc:0.83876
[18]	validation_0-auc:0.86524	validation_1-auc:0.83990
[19]	validation_0-auc:0.86624	validation_1-auc:0.84030
[20]	validation_0-auc:0.86745	validation_1-auc:0.84057
[21]	validation_0-auc:0.86833	validation_1-auc:0.84093
[22]	validation_0-auc:0.86969	validation_1-auc:0.84245
[23]	validation_0-auc:0.87095	validation_1-auc:0.84275
[24]	validation_0-auc:0.87193	validation_1-auc:0.84347
[25]	validation_0-auc:0.87238	validation_1-auc:0.84351
[26]	validation_0-auc:0.87360	validation_1-auc:0.84367
[27]	validation_0-auc:0.87463	validation_1-auc:0.84386
[28]	validation_0-auc:0.87499	validation_1-auc:0.84434
[29]	validation_0-auc:0.87604	validation_1-auc:0.84406
[30]	validation_0-auc:0.87664	validation_1-auc:0.84408
[31]	validation_0-auc:0.87747	validation_1-auc:0.84424
[32]	validation_0-auc:0.87822	validation_1-auc:0.84427
[33]	validation_0-auc:0.87874	validation_1-auc:0.84429
[34]	validation_0-auc:0.87966	validation_1-auc:0.84481
[35]	validation_0-auc:0.88004	validation_1-auc:0.84500
[36]	validation_0-auc:0.88034	validation_1-auc:0.84516
[37]	validation_0-auc:0.88144	validation_1-auc:0.84528
[38]	validation_0-auc:0.88170	validation_1-auc:0.84538
[39]	validation_0-auc:0.88266	validation_1-auc:0.84558
[40]	validation_0-auc:0.88276	validation_1-auc:0.84570
[41]	validation_0-auc:0.88339	validation_1-auc:0.84526
[42]	validation_0-auc:0.88480	validation_1-auc:0.84549
[43]	validation_0-auc:0.88540	validation_1-auc:0.84538
[44]	validation_0-auc:0.88593	validation_1-auc:0.84545
[45]	validation_0-auc:0.88610	validation_1-auc:0.84558
[46]	validation_0-auc:0.88693	validation_1-auc:0.84559
[47]	validation_0-auc:0.88762	validation_1-auc:0.84542
[48]	validation_0-auc:0.88794	validation_1-auc:0.84531
[49]	validation_0-auc:0.88817	validation_1-auc:0.84547
[50]	validation_0-auc:0.88857	validation_1-auc:0.84535
[51]	validation_0-auc:0.88879	validation_1-auc:0.84518
[52]	validation_0-auc:0.88935	validation_1-auc:0.84495
[53]	validation_0-auc:0.88956	validation_1-auc:0.84484
[54]	validation_0-auc:0.89007	validation_1-auc:0.84456
[55]	validation_0-auc:0.89021	validation_1-auc:0.84435
[56]	validation_0-auc:0.89032	validation_1-auc:0.84440
[57]	validation_0-auc:0.89037	validation_1-auc:0.84417
[58]	validation_0-auc:0.89050	validation_1-auc:0.84429
[59]	validation_0-auc:0.89068	validation_1-auc:0.84428
[60]	validation_0-auc:0.89079	validation_1-auc:0.84423
[61]	validation_0-auc:0.89164	validation_1-auc:0.84385
[62]	validation_0-auc:0.89184	validation_1-auc:0.84380
[63]	validation_0-auc:0.89194	validation_1-auc:0.84370
[64]	validation_0-auc:0.89223	validation_1-auc:0.84384
[65]	validation_0-auc:0.89279	validation_1-auc:0.84371
[66]	validation_0-auc:0.89388	validation_1-auc:0.84357
[67]	validation_0-auc:0.89432	validation_1-auc:0.84361
[68]	validation_0-auc:0.89445	validation_1-auc:0.84359
[69]	validation_0-auc:0.89513	validation_1-auc:0.84386
 76%|███████▌  | 38/50 [08:05<02:22, 11.86s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82226	validation_1-auc:0.80560
[1]	validation_0-auc:0.82762	validation_1-auc:0.81243
[2]	validation_0-auc:0.83568	validation_1-auc:0.81951
[3]	validation_0-auc:0.83895	validation_1-auc:0.82133
[4]	validation_0-auc:0.84430	validation_1-auc:0.82474
[5]	validation_0-auc:0.84559	validation_1-auc:0.82528
[6]	validation_0-auc:0.84738	validation_1-auc:0.82621
[7]	validation_0-auc:0.84944	validation_1-auc:0.82677
[8]	validation_0-auc:0.85037	validation_1-auc:0.82662
[9]	validation_0-auc:0.85286	validation_1-auc:0.82703
[10]	validation_0-auc:0.85173	validation_1-auc:0.82471
[11]	validation_0-auc:0.85301	validation_1-auc:0.82587
[12]	validation_0-auc:0.85748	validation_1-auc:0.82832
[13]	validation_0-auc:0.85946	validation_1-auc:0.83044
[14]	validation_0-auc:0.86262	validation_1-auc:0.83393
[15]	validation_0-auc:0.86395	validation_1-auc:0.83481
[16]	validation_0-auc:0.86520	validation_1-auc:0.83486
[17]	validation_0-auc:0.86691	validation_1-auc:0.83670
[18]	validation_0-auc:0.86829	validation_1-auc:0.83676
[19]	validation_0-auc:0.86997	validation_1-auc:0.83719
[20]	validation_0-auc:0.87099	validation_1-auc:0.83750
[21]	validation_0-auc:0.87169	validation_1-auc:0.83879
[22]	validation_0-auc:0.87265	validation_1-auc:0.83857
[23]	validation_0-auc:0.87343	validation_1-auc:0.83884
[24]	validation_0-auc:0.87444	validation_1-auc:0.83866
[25]	validation_0-auc:0.87555	validation_1-auc:0.83856
[26]	validation_0-auc:0.87685	validation_1-auc:0.83875
[27]	validation_0-auc:0.87752	validation_1-auc:0.83874
[28]	validation_0-auc:0.87814	validation_1-auc:0.83914
[29]	validation_0-auc:0.87876	validation_1-auc:0.83938
[30]	validation_0-auc:0.88021	validation_1-auc:0.83938
[31]	validation_0-auc:0.88079	validation_1-auc:0.83916
[32]	validation_0-auc:0.88170	validation_1-auc:0.83860
[33]	validation_0-auc:0.88193	validation_1-auc:0.83886
[34]	validation_0-auc:0.88234	validation_1-auc:0.83860
[35]	validation_0-auc:0.88303	validation_1-auc:0.83865
[36]	validation_0-auc:0.88354	validation_1-auc:0.83870
[37]	validation_0-auc:0.88465	validation_1-auc:0.83862
[38]	validation_0-auc:0.88560	validation_1-auc:0.83844
[39]	validation_0-auc:0.88584	validation_1-auc:0.83854
[40]	validation_0-auc:0.88608	validation_1-auc:0.83867
[41]	validation_0-auc:0.88685	validation_1-auc:0.83846
[42]	validation_0-auc:0.88793	validation_1-auc:0.83810
[43]	validation_0-auc:0.88832	validation_1-auc:0.83822
[44]	validation_0-auc:0.88860	validation_1-auc:0.83832
[45]	validation_0-auc:0.88888	validation_1-auc:0.83833
[46]	validation_0-auc:0.88947	validation_1-auc:0.83801
[47]	validation_0-auc:0.89050	validation_1-auc:0.83798
[48]	validation_0-auc:0.89089	validation_1-auc:0.83780
[49]	validation_0-auc:0.89134	validation_1-auc:0.83797
[50]	validation_0-auc:0.89216	validation_1-auc:0.83795
[51]	validation_0-auc:0.89232	validation_1-auc:0.83784
[52]	validation_0-auc:0.89235	validation_1-auc:0.83793
[53]	validation_0-auc:0.89255	validation_1-auc:0.83781
[54]	validation_0-auc:0.89280	validation_1-auc:0.83769
[55]	validation_0-auc:0.89328	validation_1-auc:0.83737
[56]	validation_0-auc:0.89368	validation_1-auc:0.83709
[57]	validation_0-auc:0.89444	validation_1-auc:0.83750
[58]	validation_0-auc:0.89486	validation_1-auc:0.83736
 76%|███████▌  | 38/50 [08:08<02:22, 11.86s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.81868	validation_1-auc:0.80986
[1]	validation_0-auc:0.83153	validation_1-auc:0.82418
[2]	validation_0-auc:0.83543	validation_1-auc:0.82304
[3]	validation_0-auc:0.83903	validation_1-auc:0.82727
[4]	validation_0-auc:0.84203	validation_1-auc:0.82880
[5]	validation_0-auc:0.84418	validation_1-auc:0.83114
[6]	validation_0-auc:0.84489	validation_1-auc:0.83120
[7]	validation_0-auc:0.84609	validation_1-auc:0.83311
[8]	validation_0-auc:0.84627	validation_1-auc:0.83248
[9]	validation_0-auc:0.84849	validation_1-auc:0.83334
[10]	validation_0-auc:0.84879	validation_1-auc:0.83061
[11]	validation_0-auc:0.84842	validation_1-auc:0.82859
[12]	validation_0-auc:0.85394	validation_1-auc:0.83297
[13]	validation_0-auc:0.85795	validation_1-auc:0.83650
[14]	validation_0-auc:0.86020	validation_1-auc:0.83907
[15]	validation_0-auc:0.86203	validation_1-auc:0.84044
[16]	validation_0-auc:0.86353	validation_1-auc:0.84117
[17]	validation_0-auc:0.86526	validation_1-auc:0.84225
[18]	validation_0-auc:0.86646	validation_1-auc:0.84201
[19]	validation_0-auc:0.86754	validation_1-auc:0.84227
[20]	validation_0-auc:0.86827	validation_1-auc:0.84272
[21]	validation_0-auc:0.86883	validation_1-auc:0.84254
[22]	validation_0-auc:0.86988	validation_1-auc:0.84277
[23]	validation_0-auc:0.87048	validation_1-auc:0.84288
[24]	validation_0-auc:0.87164	validation_1-auc:0.84293
[25]	validation_0-auc:0.87243	validation_1-auc:0.84346
[26]	validation_0-auc:0.87369	validation_1-auc:0.84355
[27]	validation_0-auc:0.87424	validation_1-auc:0.84389
[28]	validation_0-auc:0.87485	validation_1-auc:0.84414
[29]	validation_0-auc:0.87537	validation_1-auc:0.84408
[30]	validation_0-auc:0.87705	validation_1-auc:0.84416
[31]	validation_0-auc:0.87781	validation_1-auc:0.84433
[32]	validation_0-auc:0.87866	validation_1-auc:0.84427
[33]	validation_0-auc:0.87951	validation_1-auc:0.84423
[34]	validation_0-auc:0.87987	validation_1-auc:0.84439
[35]	validation_0-auc:0.88047	validation_1-auc:0.84435
[36]	validation_0-auc:0.88111	validation_1-auc:0.84442
[37]	validation_0-auc:0.88231	validation_1-auc:0.84427
[38]	validation_0-auc:0.88280	validation_1-auc:0.84447
[39]	validation_0-auc:0.88325	validation_1-auc:0.84418
[40]	validation_0-auc:0.88346	validation_1-auc:0.84417
[41]	validation_0-auc:0.88385	validation_1-auc:0.84436
[42]	validation_0-auc:0.88401	validation_1-auc:0.84441
[43]	validation_0-auc:0.88512	validation_1-auc:0.84412
[44]	validation_0-auc:0.88574	validation_1-auc:0.84377
[45]	validation_0-auc:0.88584	validation_1-auc:0.84398
[46]	validation_0-auc:0.88614	validation_1-auc:0.84383
[47]	validation_0-auc:0.88664	validation_1-auc:0.84382
[48]	validation_0-auc:0.88690	validation_1-auc:0.84376
[49]	validation_0-auc:0.88781	validation_1-auc:0.84385
[50]	validation_0-auc:0.88810	validation_1-auc:0.84363
[51]	validation_0-auc:0.88916	validation_1-auc:0.84352
[52]	validation_0-auc:0.88937	validation_1-auc:0.84351
[53]	validation_0-auc:0.88950	validation_1-auc:0.84346
[54]	validation_0-auc:0.89063	validation_1-auc:0.84332
[55]	validation_0-auc:0.89138	validation_1-auc:0.84345
[56]	validation_0-auc:0.89155	validation_1-auc:0.84362
[57]	validation_0-auc:0.89173	validation_1-auc:0.84363
[58]	validation_0-auc:0.89196	validation_1-auc:0.84356
[59]	validation_0-auc:0.89254	validation_1-auc:0.84362
[60]	validation_0-auc:0.89304	validation_1-auc:0.84327
[61]	validation_0-auc:0.89357	validation_1-auc:0.84290
[62]	validation_0-auc:0.89363	validation_1-auc:0.84286
[63]	validation_0-auc:0.89391	validation_1-auc:0.84292
[64]	validation_0-auc:0.89436	validation_1-auc:0.84280
[65]	validation_0-auc:0.89498	validation_1-auc:0.84239
[66]	validation_0-auc:0.89521	validation_1-auc:0.84226
[67]	validation_0-auc:0.89570	validation_1-auc:0.84215
[68]	validation_0-auc:0.89613	validation_1-auc:0.84203
 78%|███████▊  | 39/50 [08:12<02:02, 11.13s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83186	validation_1-auc:0.81325
[1]	validation_0-auc:0.83855	validation_1-auc:0.81449
[2]	validation_0-auc:0.84613	validation_1-auc:0.81680
[3]	validation_0-auc:0.84866	validation_1-auc:0.81653
[4]	validation_0-auc:0.85721	validation_1-auc:0.81980
[5]	validation_0-auc:0.86354	validation_1-auc:0.82565
[6]	validation_0-auc:0.87105	validation_1-auc:0.83140
[7]	validation_0-auc:0.87251	validation_1-auc:0.83123
[8]	validation_0-auc:0.87684	validation_1-auc:0.83084
[9]	validation_0-auc:0.87872	validation_1-auc:0.82969
[10]	validation_0-auc:0.88055	validation_1-auc:0.82939
[11]	validation_0-auc:0.88286	validation_1-auc:0.82893
[12]	validation_0-auc:0.88695	validation_1-auc:0.83213
[13]	validation_0-auc:0.89023	validation_1-auc:0.83431
[14]	validation_0-auc:0.89173	validation_1-auc:0.83558
[15]	validation_0-auc:0.89242	validation_1-auc:0.83597
[16]	validation_0-auc:0.89496	validation_1-auc:0.83789
[17]	validation_0-auc:0.89870	validation_1-auc:0.83967
[18]	validation_0-auc:0.90000	validation_1-auc:0.83793
[19]	validation_0-auc:0.90429	validation_1-auc:0.83835
[20]	validation_0-auc:0.90545	validation_1-auc:0.83795
[21]	validation_0-auc:0.90628	validation_1-auc:0.83636
[22]	validation_0-auc:0.90759	validation_1-auc:0.83700
[23]	validation_0-auc:0.91047	validation_1-auc:0.83774
[24]	validation_0-auc:0.91168	validation_1-auc:0.83766
[25]	validation_0-auc:0.91276	validation_1-auc:0.83861
[26]	validation_0-auc:0.91430	validation_1-auc:0.83783
[27]	validation_0-auc:0.91637	validation_1-auc:0.83920
[28]	validation_0-auc:0.91690	validation_1-auc:0.83854
[29]	validation_0-auc:0.91874	validation_1-auc:0.83824
[30]	validation_0-auc:0.92046	validation_1-auc:0.83716
[31]	validation_0-auc:0.92180	validation_1-auc:0.83743
[32]	validation_0-auc:0.92279	validation_1-auc:0.83703
[33]	validation_0-auc:0.92288	validation_1-auc:0.83777
[34]	validation_0-auc:0.92366	validation_1-auc:0.83820
[35]	validation_0-auc:0.92409	validation_1-auc:0.83849
[36]	validation_0-auc:0.92479	validation_1-auc:0.83835
[37]	validation_0-auc:0.92539	validation_1-auc:0.83812
[38]	validation_0-auc:0.92651	validation_1-auc:0.83813
[39]	validation_0-auc:0.92741	validation_1-auc:0.83800
[40]	validation_0-auc:0.92771	validation_1-auc:0.83833
[41]	validation_0-auc:0.92829	validation_1-auc:0.83843
[42]	validation_0-auc:0.92892	validation_1-auc:0.83851
[43]	validation_0-auc:0.92924	validation_1-auc:0.83876
[44]	validation_0-auc:0.92956	validation_1-auc:0.83867
[45]	validation_0-auc:0.92975	validation_1-auc:0.83884
[46]	validation_0-auc:0.93036	validation_1-auc:0.83860
 78%|███████▊  | 39/50 [08:15<02:02, 11.13s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82840	validation_1-auc:0.80843
[1]	validation_0-auc:0.83539	validation_1-auc:0.81189
[2]	validation_0-auc:0.84127	validation_1-auc:0.81698
[3]	validation_0-auc:0.84932	validation_1-auc:0.82044
[4]	validation_0-auc:0.85990	validation_1-auc:0.82492
[5]	validation_0-auc:0.86369	validation_1-auc:0.82547
[6]	validation_0-auc:0.86969	validation_1-auc:0.82842
[7]	validation_0-auc:0.87510	validation_1-auc:0.82976
[8]	validation_0-auc:0.87963	validation_1-auc:0.83034
[9]	validation_0-auc:0.88318	validation_1-auc:0.82911
[10]	validation_0-auc:0.88393	validation_1-auc:0.82817
[11]	validation_0-auc:0.88585	validation_1-auc:0.82796
[12]	validation_0-auc:0.89045	validation_1-auc:0.83005
[13]	validation_0-auc:0.89508	validation_1-auc:0.83170
[14]	validation_0-auc:0.89669	validation_1-auc:0.83276
[15]	validation_0-auc:0.89863	validation_1-auc:0.83080
[16]	validation_0-auc:0.89978	validation_1-auc:0.83302
[17]	validation_0-auc:0.90284	validation_1-auc:0.83293
[18]	validation_0-auc:0.90426	validation_1-auc:0.83116
[19]	validation_0-auc:0.90765	validation_1-auc:0.83206
[20]	validation_0-auc:0.90799	validation_1-auc:0.83170
[21]	validation_0-auc:0.90876	validation_1-auc:0.83042
[22]	validation_0-auc:0.90984	validation_1-auc:0.83183
[23]	validation_0-auc:0.91230	validation_1-auc:0.83258
[24]	validation_0-auc:0.91356	validation_1-auc:0.83352
[25]	validation_0-auc:0.91426	validation_1-auc:0.83364
[26]	validation_0-auc:0.91576	validation_1-auc:0.83271
[27]	validation_0-auc:0.91720	validation_1-auc:0.83232
[28]	validation_0-auc:0.91800	validation_1-auc:0.83151
[29]	validation_0-auc:0.91932	validation_1-auc:0.83277
[30]	validation_0-auc:0.92122	validation_1-auc:0.83189
[31]	validation_0-auc:0.92251	validation_1-auc:0.83252
[32]	validation_0-auc:0.92358	validation_1-auc:0.83333
[33]	validation_0-auc:0.92410	validation_1-auc:0.83320
[34]	validation_0-auc:0.92437	validation_1-auc:0.83389
[35]	validation_0-auc:0.92497	validation_1-auc:0.83451
[36]	validation_0-auc:0.92615	validation_1-auc:0.83397
[37]	validation_0-auc:0.92681	validation_1-auc:0.83355
[38]	validation_0-auc:0.92725	validation_1-auc:0.83312
[39]	validation_0-auc:0.92730	validation_1-auc:0.83336
[40]	validation_0-auc:0.92749	validation_1-auc:0.83372
[41]	validation_0-auc:0.92779	validation_1-auc:0.83370
[42]	validation_0-auc:0.92896	validation_1-auc:0.83321
[43]	validation_0-auc:0.92928	validation_1-auc:0.83284
[44]	validation_0-auc:0.92995	validation_1-auc:0.83292
[45]	validation_0-auc:0.93007	validation_1-auc:0.83289
[46]	validation_0-auc:0.93052	validation_1-auc:0.83268
[47]	validation_0-auc:0.93125	validation_1-auc:0.83241
[48]	validation_0-auc:0.93197	validation_1-auc:0.83216
[49]	validation_0-auc:0.93248	validation_1-auc:0.83212
[50]	validation_0-auc:0.93282	validation_1-auc:0.83169
[51]	validation_0-auc:0.93409	validation_1-auc:0.83141
[52]	validation_0-auc:0.93432	validation_1-auc:0.83117
[53]	validation_0-auc:0.93455	validation_1-auc:0.83093
[54]	validation_0-auc:0.93488	validation_1-auc:0.83071
[55]	validation_0-auc:0.93568	validation_1-auc:0.83037
[56]	validation_0-auc:0.93604	validation_1-auc:0.83060
[57]	validation_0-auc:0.93627	validation_1-auc:0.83047
[58]	validation_0-auc:0.93637	validation_1-auc:0.83062
[59]	validation_0-auc:0.93655	validation_1-auc:0.83043
[60]	validation_0-auc:0.93676	validation_1-auc:0.83010
[61]	validation_0-auc:0.93716	validation_1-auc:0.82980
[62]	validation_0-auc:0.93736	validation_1-auc:0.82927
[63]	validation_0-auc:0.93759	validation_1-auc:0.82900
[64]	validation_0-auc:0.93777	validation_1-auc:0.82892
 78%|███████▊  | 39/50 [08:20<02:02, 11.13s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82447	validation_1-auc:0.81087
[1]	validation_0-auc:0.83182	validation_1-auc:0.81533
[2]	validation_0-auc:0.84752	validation_1-auc:0.82845
[3]	validation_0-auc:0.85272	validation_1-auc:0.82991
[4]	validation_0-auc:0.85857	validation_1-auc:0.83128
[5]	validation_0-auc:0.86135	validation_1-auc:0.82861
[6]	validation_0-auc:0.86756	validation_1-auc:0.83242
[7]	validation_0-auc:0.87187	validation_1-auc:0.83396
[8]	validation_0-auc:0.87402	validation_1-auc:0.83479
[9]	validation_0-auc:0.87626	validation_1-auc:0.83239
[10]	validation_0-auc:0.87707	validation_1-auc:0.83154
[11]	validation_0-auc:0.87957	validation_1-auc:0.82999
[12]	validation_0-auc:0.88476	validation_1-auc:0.83153
[13]	validation_0-auc:0.89040	validation_1-auc:0.83469
[14]	validation_0-auc:0.89151	validation_1-auc:0.83581
[15]	validation_0-auc:0.89342	validation_1-auc:0.83442
[16]	validation_0-auc:0.89557	validation_1-auc:0.83656
[17]	validation_0-auc:0.89862	validation_1-auc:0.83849
[18]	validation_0-auc:0.89945	validation_1-auc:0.83605
[19]	validation_0-auc:0.90248	validation_1-auc:0.83601
[20]	validation_0-auc:0.90313	validation_1-auc:0.83529
[21]	validation_0-auc:0.90400	validation_1-auc:0.83345
[22]	validation_0-auc:0.90561	validation_1-auc:0.83641
[23]	validation_0-auc:0.90815	validation_1-auc:0.83774
[24]	validation_0-auc:0.90920	validation_1-auc:0.83891
[25]	validation_0-auc:0.90987	validation_1-auc:0.83906
[26]	validation_0-auc:0.91200	validation_1-auc:0.83903
[27]	validation_0-auc:0.91391	validation_1-auc:0.83973
[28]	validation_0-auc:0.91465	validation_1-auc:0.83912
[29]	validation_0-auc:0.91551	validation_1-auc:0.84004
[30]	validation_0-auc:0.91688	validation_1-auc:0.83981
[31]	validation_0-auc:0.91802	validation_1-auc:0.84011
[32]	validation_0-auc:0.91898	validation_1-auc:0.84014
[33]	validation_0-auc:0.91906	validation_1-auc:0.84060
[34]	validation_0-auc:0.91938	validation_1-auc:0.84101
[35]	validation_0-auc:0.92000	validation_1-auc:0.84079
[36]	validation_0-auc:0.92100	validation_1-auc:0.84046
[37]	validation_0-auc:0.92245	validation_1-auc:0.83993
[38]	validation_0-auc:0.92336	validation_1-auc:0.83999
[39]	validation_0-auc:0.92343	validation_1-auc:0.84006
[40]	validation_0-auc:0.92363	validation_1-auc:0.83980
[41]	validation_0-auc:0.92398	validation_1-auc:0.83935
[42]	validation_0-auc:0.92422	validation_1-auc:0.83926
[43]	validation_0-auc:0.92433	validation_1-auc:0.83974
[44]	validation_0-auc:0.92513	validation_1-auc:0.84023
[45]	validation_0-auc:0.92549	validation_1-auc:0.84045
[46]	validation_0-auc:0.92576	validation_1-auc:0.84049
[47]	validation_0-auc:0.92690	validation_1-auc:0.84012
[48]	validation_0-auc:0.92760	validation_1-auc:0.84001
[49]	validation_0-auc:0.92823	validation_1-auc:0.83995
[50]	validation_0-auc:0.92882	validation_1-auc:0.83959
[51]	validation_0-auc:0.92965	validation_1-auc:0.83958
[52]	validation_0-auc:0.93035	validation_1-auc:0.83926
[53]	validation_0-auc:0.93063	validation_1-auc:0.83891
[54]	validation_0-auc:0.93101	validation_1-auc:0.83867
[55]	validation_0-auc:0.93188	validation_1-auc:0.83849
[56]	validation_0-auc:0.93227	validation_1-auc:0.83836
[57]	validation_0-auc:0.93250	validation_1-auc:0.83806
[58]	validation_0-auc:0.93316	validation_1-auc:0.83791
[59]	validation_0-auc:0.93329	validation_1-auc:0.83785
[60]	validation_0-auc:0.93356	validation_1-auc:0.83765
[61]	validation_0-auc:0.93405	validation_1-auc:0.83722
[62]	validation_0-auc:0.93422	validation_1-auc:0.83679
[63]	validation_0-auc:0.93433	validation_1-auc:0.83650
 80%|████████  | 40/50 [08:24<01:55, 11.53s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82712	validation_1-auc:0.81337
[1]	validation_0-auc:0.83204	validation_1-auc:0.81395
[2]	validation_0-auc:0.84266	validation_1-auc:0.82071
[3]	validation_0-auc:0.84504	validation_1-auc:0.82145
[4]	validation_0-auc:0.84729	validation_1-auc:0.82060
[5]	validation_0-auc:0.85179	validation_1-auc:0.82667
[6]	validation_0-auc:0.85657	validation_1-auc:0.83305
[7]	validation_0-auc:0.85717	validation_1-auc:0.83201
[8]	validation_0-auc:0.85768	validation_1-auc:0.83179
[9]	validation_0-auc:0.85751	validation_1-auc:0.83291
[10]	validation_0-auc:0.85723	validation_1-auc:0.83244
[11]	validation_0-auc:0.85673	validation_1-auc:0.83066
[12]	validation_0-auc:0.85922	validation_1-auc:0.83495
[13]	validation_0-auc:0.86178	validation_1-auc:0.83649
[14]	validation_0-auc:0.86331	validation_1-auc:0.83932
[15]	validation_0-auc:0.86459	validation_1-auc:0.84010
[16]	validation_0-auc:0.86544	validation_1-auc:0.84060
[17]	validation_0-auc:0.86679	validation_1-auc:0.84079
[18]	validation_0-auc:0.86714	validation_1-auc:0.84031
[19]	validation_0-auc:0.86814	validation_1-auc:0.84020
[20]	validation_0-auc:0.86832	validation_1-auc:0.84054
[21]	validation_0-auc:0.86747	validation_1-auc:0.83899
[22]	validation_0-auc:0.87014	validation_1-auc:0.84089
[23]	validation_0-auc:0.87240	validation_1-auc:0.84172
[24]	validation_0-auc:0.87331	validation_1-auc:0.84192
[25]	validation_0-auc:0.87385	validation_1-auc:0.84192
[26]	validation_0-auc:0.87525	validation_1-auc:0.84286
[27]	validation_0-auc:0.87681	validation_1-auc:0.84361
[28]	validation_0-auc:0.87711	validation_1-auc:0.84338
[29]	validation_0-auc:0.87825	validation_1-auc:0.84419
[30]	validation_0-auc:0.87878	validation_1-auc:0.84451
[31]	validation_0-auc:0.88030	validation_1-auc:0.84540
[32]	validation_0-auc:0.88129	validation_1-auc:0.84531
[33]	validation_0-auc:0.88152	validation_1-auc:0.84530
[34]	validation_0-auc:0.88247	validation_1-auc:0.84557
[35]	validation_0-auc:0.88321	validation_1-auc:0.84568
[36]	validation_0-auc:0.88447	validation_1-auc:0.84558
[37]	validation_0-auc:0.88469	validation_1-auc:0.84560
[38]	validation_0-auc:0.88538	validation_1-auc:0.84599
[39]	validation_0-auc:0.88622	validation_1-auc:0.84623
[40]	validation_0-auc:0.88688	validation_1-auc:0.84643
[41]	validation_0-auc:0.88718	validation_1-auc:0.84632
[42]	validation_0-auc:0.88769	validation_1-auc:0.84619
[43]	validation_0-auc:0.88781	validation_1-auc:0.84619
[44]	validation_0-auc:0.88816	validation_1-auc:0.84612
[45]	validation_0-auc:0.88828	validation_1-auc:0.84618
[46]	validation_0-auc:0.88863	validation_1-auc:0.84622
[47]	validation_0-auc:0.88959	validation_1-auc:0.84607
[48]	validation_0-auc:0.89022	validation_1-auc:0.84596
[49]	validation_0-auc:0.89081	validation_1-auc:0.84578
[50]	validation_0-auc:0.89121	validation_1-auc:0.84583
[51]	validation_0-auc:0.89134	validation_1-auc:0.84556
[52]	validation_0-auc:0.89236	validation_1-auc:0.84579
[53]	validation_0-auc:0.89270	validation_1-auc:0.84591
[54]	validation_0-auc:0.89294	validation_1-auc:0.84599
[55]	validation_0-auc:0.89336	validation_1-auc:0.84620
[56]	validation_0-auc:0.89406	validation_1-auc:0.84613
[57]	validation_0-auc:0.89418	validation_1-auc:0.84620
[58]	validation_0-auc:0.89461	validation_1-auc:0.84630
[59]	validation_0-auc:0.89514	validation_1-auc:0.84596
[60]	validation_0-auc:0.89534	validation_1-auc:0.84595
[61]	validation_0-auc:0.89566	validation_1-auc:0.84583
[62]	validation_0-auc:0.89651	validation_1-auc:0.84608
[63]	validation_0-auc:0.89655	validation_1-auc:0.84608
[64]	validation_0-auc:0.89717	validation_1-auc:0.84654
[65]	validation_0-auc:0.89728	validation_1-auc:0.84658
[66]	validation_0-auc:0.89795	validation_1-auc:0.84624
[67]	validation_0-auc:0.89827	validation_1-auc:0.84612
[68]	validation_0-auc:0.89855	validation_1-auc:0.84606
[69]	validation_0-auc:0.89888	validation_1-auc:0.84626
[70]	validation_0-auc:0.89907	validation_1-auc:0.84629
[71]	validation_0-auc:0.89965	validation_1-auc:0.84623
[72]	validation_0-auc:0.89981	validation_1-auc:0.84634
[73]	validation_0-auc:0.90036	validation_1-auc:0.84651
[74]	validation_0-auc:0.90074	validation_1-auc:0.84659
[75]	validation_0-auc:0.90089	validation_1-auc:0.84653
[76]	validation_0-auc:0.90101	validation_1-auc:0.84648
[77]	validation_0-auc:0.90113	validation_1-auc:0.84638
[78]	validation_0-auc:0.90133	validation_1-auc:0.84637
[79]	validation_0-auc:0.90186	validation_1-auc:0.84634
[80]	validation_0-auc:0.90275	validation_1-auc:0.84673
[81]	validation_0-auc:0.90295	validation_1-auc:0.84669
[82]	validation_0-auc:0.90346	validation_1-auc:0.84678
[83]	validation_0-auc:0.90365	validation_1-auc:0.84676
[84]	validation_0-auc:0.90385	validation_1-auc:0.84653
[85]	validation_0-auc:0.90412	validation_1-auc:0.84651
[86]	validation_0-auc:0.90452	validation_1-auc:0.84647
[87]	validation_0-auc:0.90460	validation_1-auc:0.84630
[88]	validation_0-auc:0.90470	validation_1-auc:0.84615
[89]	validation_0-auc:0.90491	validation_1-auc:0.84620
[90]	validation_0-auc:0.90500	validation_1-auc:0.84610
[91]	validation_0-auc:0.90586	validation_1-auc:0.84605
[92]	validation_0-auc:0.90643	validation_1-auc:0.84600
[93]	validation_0-auc:0.90709	validation_1-auc:0.84594
[94]	validation_0-auc:0.90741	validation_1-auc:0.84612
[95]	validation_0-auc:0.90762	validation_1-auc:0.84600
[96]	validation_0-auc:0.90769	validation_1-auc:0.84587
[97]	validation_0-auc:0.90813	validation_1-auc:0.84576
[98]	validation_0-auc:0.90857	validation_1-auc:0.84550
[99]	validation_0-auc:0.90873	validation_1-auc:0.84530
 80%|████████  | 40/50 [08:28<01:55, 11.53s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82370	validation_1-auc:0.80644
[1]	validation_0-auc:0.83102	validation_1-auc:0.81438
[2]	validation_0-auc:0.83372	validation_1-auc:0.81500
[3]	validation_0-auc:0.83662	validation_1-auc:0.81817
[4]	validation_0-auc:0.84494	validation_1-auc:0.82423
[5]	validation_0-auc:0.84858	validation_1-auc:0.82570
[6]	validation_0-auc:0.85153	validation_1-auc:0.82828
[7]	validation_0-auc:0.85385	validation_1-auc:0.82874
[8]	validation_0-auc:0.85534	validation_1-auc:0.82976
[9]	validation_0-auc:0.85747	validation_1-auc:0.82660
[10]	validation_0-auc:0.85626	validation_1-auc:0.82508
[11]	validation_0-auc:0.85724	validation_1-auc:0.82471
[12]	validation_0-auc:0.86175	validation_1-auc:0.82699
[13]	validation_0-auc:0.86428	validation_1-auc:0.82901
[14]	validation_0-auc:0.86458	validation_1-auc:0.82966
[15]	validation_0-auc:0.86692	validation_1-auc:0.83076
[16]	validation_0-auc:0.86802	validation_1-auc:0.83221
[17]	validation_0-auc:0.87006	validation_1-auc:0.83427
[18]	validation_0-auc:0.87067	validation_1-auc:0.83382
[19]	validation_0-auc:0.87312	validation_1-auc:0.83550
[20]	validation_0-auc:0.87362	validation_1-auc:0.83551
[21]	validation_0-auc:0.87267	validation_1-auc:0.83459
[22]	validation_0-auc:0.87555	validation_1-auc:0.83540
[23]	validation_0-auc:0.87761	validation_1-auc:0.83644
[24]	validation_0-auc:0.87841	validation_1-auc:0.83749
[25]	validation_0-auc:0.87890	validation_1-auc:0.83742
[26]	validation_0-auc:0.88022	validation_1-auc:0.83695
[27]	validation_0-auc:0.88170	validation_1-auc:0.83713
[28]	validation_0-auc:0.88189	validation_1-auc:0.83670
[29]	validation_0-auc:0.88292	validation_1-auc:0.83718
[30]	validation_0-auc:0.88357	validation_1-auc:0.83642
[31]	validation_0-auc:0.88501	validation_1-auc:0.83741
[32]	validation_0-auc:0.88511	validation_1-auc:0.83781
[33]	validation_0-auc:0.88547	validation_1-auc:0.83834
[34]	validation_0-auc:0.88557	validation_1-auc:0.83848
[35]	validation_0-auc:0.88600	validation_1-auc:0.83854
[36]	validation_0-auc:0.88733	validation_1-auc:0.83844
[37]	validation_0-auc:0.88794	validation_1-auc:0.83822
[38]	validation_0-auc:0.88938	validation_1-auc:0.83732
[39]	validation_0-auc:0.88961	validation_1-auc:0.83789
[40]	validation_0-auc:0.88968	validation_1-auc:0.83833
[41]	validation_0-auc:0.89040	validation_1-auc:0.83792
[42]	validation_0-auc:0.89099	validation_1-auc:0.83780
[43]	validation_0-auc:0.89123	validation_1-auc:0.83825
[44]	validation_0-auc:0.89244	validation_1-auc:0.83788
[45]	validation_0-auc:0.89263	validation_1-auc:0.83792
[46]	validation_0-auc:0.89286	validation_1-auc:0.83824
[47]	validation_0-auc:0.89359	validation_1-auc:0.83867
[48]	validation_0-auc:0.89402	validation_1-auc:0.83883
[49]	validation_0-auc:0.89448	validation_1-auc:0.83865
[50]	validation_0-auc:0.89459	validation_1-auc:0.83880
[51]	validation_0-auc:0.89505	validation_1-auc:0.83883
[52]	validation_0-auc:0.89550	validation_1-auc:0.83916
[53]	validation_0-auc:0.89590	validation_1-auc:0.83882
[54]	validation_0-auc:0.89615	validation_1-auc:0.83846
[55]	validation_0-auc:0.89718	validation_1-auc:0.83819
[56]	validation_0-auc:0.89730	validation_1-auc:0.83829
[57]	validation_0-auc:0.89756	validation_1-auc:0.83821
[58]	validation_0-auc:0.89761	validation_1-auc:0.83809
[59]	validation_0-auc:0.89775	validation_1-auc:0.83792
[60]	validation_0-auc:0.89787	validation_1-auc:0.83792
[61]	validation_0-auc:0.89826	validation_1-auc:0.83787
[62]	validation_0-auc:0.89844	validation_1-auc:0.83793
[63]	validation_0-auc:0.89909	validation_1-auc:0.83777
[64]	validation_0-auc:0.89974	validation_1-auc:0.83752
[65]	validation_0-auc:0.90035	validation_1-auc:0.83742
[66]	validation_0-auc:0.90075	validation_1-auc:0.83734
[67]	validation_0-auc:0.90119	validation_1-auc:0.83733
[68]	validation_0-auc:0.90146	validation_1-auc:0.83733
[69]	validation_0-auc:0.90165	validation_1-auc:0.83735
[70]	validation_0-auc:0.90186	validation_1-auc:0.83720
[71]	validation_0-auc:0.90224	validation_1-auc:0.83697
[72]	validation_0-auc:0.90232	validation_1-auc:0.83703
[73]	validation_0-auc:0.90273	validation_1-auc:0.83699
[74]	validation_0-auc:0.90297	validation_1-auc:0.83651
[75]	validation_0-auc:0.90322	validation_1-auc:0.83653
[76]	validation_0-auc:0.90329	validation_1-auc:0.83657
[77]	validation_0-auc:0.90383	validation_1-auc:0.83621
[78]	validation_0-auc:0.90392	validation_1-auc:0.83603
[79]	validation_0-auc:0.90468	validation_1-auc:0.83607
[80]	validation_0-auc:0.90498	validation_1-auc:0.83591
[81]	validation_0-auc:0.90508	validation_1-auc:0.83588
 80%|████████  | 40/50 [08:32<01:55, 11.53s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82057	validation_1-auc:0.81074
[1]	validation_0-auc:0.82816	validation_1-auc:0.81494
[2]	validation_0-auc:0.83398	validation_1-auc:0.82071
[3]	validation_0-auc:0.84157	validation_1-auc:0.82913
[4]	validation_0-auc:0.84585	validation_1-auc:0.83197
[5]	validation_0-auc:0.84572	validation_1-auc:0.82816
[6]	validation_0-auc:0.85049	validation_1-auc:0.83141
[7]	validation_0-auc:0.85171	validation_1-auc:0.83215
[8]	validation_0-auc:0.85389	validation_1-auc:0.83471
[9]	validation_0-auc:0.85526	validation_1-auc:0.83524
[10]	validation_0-auc:0.85430	validation_1-auc:0.83271
[11]	validation_0-auc:0.85419	validation_1-auc:0.83125
[12]	validation_0-auc:0.85846	validation_1-auc:0.83357
[13]	validation_0-auc:0.86143	validation_1-auc:0.83706
[14]	validation_0-auc:0.86215	validation_1-auc:0.83804
[15]	validation_0-auc:0.86406	validation_1-auc:0.84017
[16]	validation_0-auc:0.86570	validation_1-auc:0.84001
[17]	validation_0-auc:0.86766	validation_1-auc:0.84169
[18]	validation_0-auc:0.86769	validation_1-auc:0.84082
[19]	validation_0-auc:0.86943	validation_1-auc:0.84166
[20]	validation_0-auc:0.87020	validation_1-auc:0.84178
[21]	validation_0-auc:0.86964	validation_1-auc:0.84059
[22]	validation_0-auc:0.87171	validation_1-auc:0.84202
[23]	validation_0-auc:0.87369	validation_1-auc:0.84227
[24]	validation_0-auc:0.87538	validation_1-auc:0.84245
[25]	validation_0-auc:0.87594	validation_1-auc:0.84269
[26]	validation_0-auc:0.87691	validation_1-auc:0.84229
[27]	validation_0-auc:0.87822	validation_1-auc:0.84262
[28]	validation_0-auc:0.87864	validation_1-auc:0.84257
[29]	validation_0-auc:0.87986	validation_1-auc:0.84345
[30]	validation_0-auc:0.88149	validation_1-auc:0.84305
[31]	validation_0-auc:0.88241	validation_1-auc:0.84403
[32]	validation_0-auc:0.88329	validation_1-auc:0.84482
[33]	validation_0-auc:0.88365	validation_1-auc:0.84457
[34]	validation_0-auc:0.88375	validation_1-auc:0.84479
[35]	validation_0-auc:0.88411	validation_1-auc:0.84491
[36]	validation_0-auc:0.88499	validation_1-auc:0.84467
[37]	validation_0-auc:0.88544	validation_1-auc:0.84483
[38]	validation_0-auc:0.88626	validation_1-auc:0.84432
[39]	validation_0-auc:0.88653	validation_1-auc:0.84447
[40]	validation_0-auc:0.88696	validation_1-auc:0.84456
[41]	validation_0-auc:0.88856	validation_1-auc:0.84432
[42]	validation_0-auc:0.88894	validation_1-auc:0.84444
[43]	validation_0-auc:0.88903	validation_1-auc:0.84472
[44]	validation_0-auc:0.88993	validation_1-auc:0.84477
[45]	validation_0-auc:0.88983	validation_1-auc:0.84491
[46]	validation_0-auc:0.89045	validation_1-auc:0.84498
[47]	validation_0-auc:0.89083	validation_1-auc:0.84504
[48]	validation_0-auc:0.89111	validation_1-auc:0.84526
[49]	validation_0-auc:0.89164	validation_1-auc:0.84544
[50]	validation_0-auc:0.89190	validation_1-auc:0.84555
[51]	validation_0-auc:0.89286	validation_1-auc:0.84558
[52]	validation_0-auc:0.89331	validation_1-auc:0.84539
[53]	validation_0-auc:0.89335	validation_1-auc:0.84550
[54]	validation_0-auc:0.89337	validation_1-auc:0.84559
[55]	validation_0-auc:0.89396	validation_1-auc:0.84553
[56]	validation_0-auc:0.89420	validation_1-auc:0.84542
[57]	validation_0-auc:0.89452	validation_1-auc:0.84507
[58]	validation_0-auc:0.89461	validation_1-auc:0.84513
[59]	validation_0-auc:0.89501	validation_1-auc:0.84534
[60]	validation_0-auc:0.89515	validation_1-auc:0.84522
[61]	validation_0-auc:0.89564	validation_1-auc:0.84532
[62]	validation_0-auc:0.89598	validation_1-auc:0.84518
[63]	validation_0-auc:0.89611	validation_1-auc:0.84513
[64]	validation_0-auc:0.89660	validation_1-auc:0.84477
[65]	validation_0-auc:0.89681	validation_1-auc:0.84462
[66]	validation_0-auc:0.89693	validation_1-auc:0.84465
[67]	validation_0-auc:0.89711	validation_1-auc:0.84462
[68]	validation_0-auc:0.89719	validation_1-auc:0.84463
[69]	validation_0-auc:0.89743	validation_1-auc:0.84439
[70]	validation_0-auc:0.89774	validation_1-auc:0.84438
[71]	validation_0-auc:0.89786	validation_1-auc:0.84444
[72]	validation_0-auc:0.89808	validation_1-auc:0.84426
[73]	validation_0-auc:0.89827	validation_1-auc:0.84409
[74]	validation_0-auc:0.89835	validation_1-auc:0.84413
[75]	validation_0-auc:0.89897	validation_1-auc:0.84374
[76]	validation_0-auc:0.89905	validation_1-auc:0.84364
[77]	validation_0-auc:0.89948	validation_1-auc:0.84346
[78]	validation_0-auc:0.90010	validation_1-auc:0.84323
[79]	validation_0-auc:0.90082	validation_1-auc:0.84300
[80]	validation_0-auc:0.90101	validation_1-auc:0.84282
[81]	validation_0-auc:0.90129	validation_1-auc:0.84265
[82]	validation_0-auc:0.90179	validation_1-auc:0.84255
[83]	validation_0-auc:0.90238	validation_1-auc:0.84238
 82%|████████▏ | 41/50 [08:36<01:44, 11.64s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82927	validation_1-auc:0.81426
[1]	validation_0-auc:0.83529	validation_1-auc:0.81541
[2]	validation_0-auc:0.84140	validation_1-auc:0.81812
[3]	validation_0-auc:0.84402	validation_1-auc:0.81955
[4]	validation_0-auc:0.84835	validation_1-auc:0.81981
[5]	validation_0-auc:0.84955	validation_1-auc:0.82144
[6]	validation_0-auc:0.85322	validation_1-auc:0.82452
[7]	validation_0-auc:0.85726	validation_1-auc:0.82733
[8]	validation_0-auc:0.85923	validation_1-auc:0.82839
[9]	validation_0-auc:0.86392	validation_1-auc:0.83236
[10]	validation_0-auc:0.86362	validation_1-auc:0.83165
[11]	validation_0-auc:0.86367	validation_1-auc:0.83083
[12]	validation_0-auc:0.86856	validation_1-auc:0.83593
[13]	validation_0-auc:0.87095	validation_1-auc:0.83662
[14]	validation_0-auc:0.87186	validation_1-auc:0.83836
[15]	validation_0-auc:0.87413	validation_1-auc:0.83923
[16]	validation_0-auc:0.87509	validation_1-auc:0.83931
[17]	validation_0-auc:0.87640	validation_1-auc:0.83994
[18]	validation_0-auc:0.87637	validation_1-auc:0.83967
[19]	validation_0-auc:0.87831	validation_1-auc:0.84020
[20]	validation_0-auc:0.88129	validation_1-auc:0.84096
[21]	validation_0-auc:0.88186	validation_1-auc:0.84053
[22]	validation_0-auc:0.88338	validation_1-auc:0.84121
[23]	validation_0-auc:0.88426	validation_1-auc:0.84166
[24]	validation_0-auc:0.88516	validation_1-auc:0.84218
[25]	validation_0-auc:0.88572	validation_1-auc:0.84249
[26]	validation_0-auc:0.88675	validation_1-auc:0.84261
[27]	validation_0-auc:0.88887	validation_1-auc:0.84323
[28]	validation_0-auc:0.88974	validation_1-auc:0.84351
[29]	validation_0-auc:0.89069	validation_1-auc:0.84358
[30]	validation_0-auc:0.89186	validation_1-auc:0.84393
[31]	validation_0-auc:0.89276	validation_1-auc:0.84412
[32]	validation_0-auc:0.89338	validation_1-auc:0.84411
[33]	validation_0-auc:0.89364	validation_1-auc:0.84435
[34]	validation_0-auc:0.89382	validation_1-auc:0.84483
[35]	validation_0-auc:0.89417	validation_1-auc:0.84504
[36]	validation_0-auc:0.89558	validation_1-auc:0.84511
[37]	validation_0-auc:0.89572	validation_1-auc:0.84524
[38]	validation_0-auc:0.89584	validation_1-auc:0.84528
[39]	validation_0-auc:0.89607	validation_1-auc:0.84526
[40]	validation_0-auc:0.89683	validation_1-auc:0.84480
[41]	validation_0-auc:0.89711	validation_1-auc:0.84513
[42]	validation_0-auc:0.89733	validation_1-auc:0.84490
[43]	validation_0-auc:0.89769	validation_1-auc:0.84448
[44]	validation_0-auc:0.89813	validation_1-auc:0.84425
[45]	validation_0-auc:0.89877	validation_1-auc:0.84440
[46]	validation_0-auc:0.89943	validation_1-auc:0.84446
[47]	validation_0-auc:0.90020	validation_1-auc:0.84444
[48]	validation_0-auc:0.90050	validation_1-auc:0.84445
[49]	validation_0-auc:0.90101	validation_1-auc:0.84449
[50]	validation_0-auc:0.90124	validation_1-auc:0.84466
[51]	validation_0-auc:0.90167	validation_1-auc:0.84504
[52]	validation_0-auc:0.90185	validation_1-auc:0.84498
[53]	validation_0-auc:0.90203	validation_1-auc:0.84477
[54]	validation_0-auc:0.90214	validation_1-auc:0.84477
[55]	validation_0-auc:0.90324	validation_1-auc:0.84481
[56]	validation_0-auc:0.90356	validation_1-auc:0.84494
[57]	validation_0-auc:0.90450	validation_1-auc:0.84492
[58]	validation_0-auc:0.90485	validation_1-auc:0.84492
[59]	validation_0-auc:0.90508	validation_1-auc:0.84504
[60]	validation_0-auc:0.90518	validation_1-auc:0.84497
[61]	validation_0-auc:0.90550	validation_1-auc:0.84506
[62]	validation_0-auc:0.90572	validation_1-auc:0.84509
[63]	validation_0-auc:0.90629	validation_1-auc:0.84500
[64]	validation_0-auc:0.90720	validation_1-auc:0.84477
[65]	validation_0-auc:0.90750	validation_1-auc:0.84461
[66]	validation_0-auc:0.90785	validation_1-auc:0.84475
[67]	validation_0-auc:0.90816	validation_1-auc:0.84474
[68]	validation_0-auc:0.90918	validation_1-auc:0.84504
 82%|████████▏ | 41/50 [08:40<01:44, 11.64s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82541	validation_1-auc:0.80736
[1]	validation_0-auc:0.83389	validation_1-auc:0.81531
[2]	validation_0-auc:0.83838	validation_1-auc:0.81762
[3]	validation_0-auc:0.84240	validation_1-auc:0.82085
[4]	validation_0-auc:0.84984	validation_1-auc:0.82441
[5]	validation_0-auc:0.85160	validation_1-auc:0.82489
[6]	validation_0-auc:0.85614	validation_1-auc:0.82654
[7]	validation_0-auc:0.85831	validation_1-auc:0.82839
[8]	validation_0-auc:0.86105	validation_1-auc:0.82969
[9]	validation_0-auc:0.86372	validation_1-auc:0.83111
[10]	validation_0-auc:0.86522	validation_1-auc:0.83045
[11]	validation_0-auc:0.86580	validation_1-auc:0.82921
[12]	validation_0-auc:0.87203	validation_1-auc:0.83108
[13]	validation_0-auc:0.87511	validation_1-auc:0.83320
[14]	validation_0-auc:0.87678	validation_1-auc:0.83491
[15]	validation_0-auc:0.87953	validation_1-auc:0.83494
[16]	validation_0-auc:0.87997	validation_1-auc:0.83536
[17]	validation_0-auc:0.88221	validation_1-auc:0.83606
[18]	validation_0-auc:0.88264	validation_1-auc:0.83548
[19]	validation_0-auc:0.88432	validation_1-auc:0.83699
[20]	validation_0-auc:0.88569	validation_1-auc:0.83746
[21]	validation_0-auc:0.88667	validation_1-auc:0.83708
[22]	validation_0-auc:0.88798	validation_1-auc:0.83680
[23]	validation_0-auc:0.88955	validation_1-auc:0.83742
[24]	validation_0-auc:0.89013	validation_1-auc:0.83813
[25]	validation_0-auc:0.89093	validation_1-auc:0.83834
[26]	validation_0-auc:0.89217	validation_1-auc:0.83753
[27]	validation_0-auc:0.89364	validation_1-auc:0.83742
[28]	validation_0-auc:0.89403	validation_1-auc:0.83770
[29]	validation_0-auc:0.89488	validation_1-auc:0.83829
[30]	validation_0-auc:0.89564	validation_1-auc:0.83745
[31]	validation_0-auc:0.89597	validation_1-auc:0.83760
[32]	validation_0-auc:0.89692	validation_1-auc:0.83814
[33]	validation_0-auc:0.89696	validation_1-auc:0.83850
[34]	validation_0-auc:0.89741	validation_1-auc:0.83818
[35]	validation_0-auc:0.89771	validation_1-auc:0.83809
[36]	validation_0-auc:0.89872	validation_1-auc:0.83817
[37]	validation_0-auc:0.89916	validation_1-auc:0.83783
[38]	validation_0-auc:0.90054	validation_1-auc:0.83766
[39]	validation_0-auc:0.90065	validation_1-auc:0.83763
[40]	validation_0-auc:0.90092	validation_1-auc:0.83799
[41]	validation_0-auc:0.90147	validation_1-auc:0.83809
[42]	validation_0-auc:0.90228	validation_1-auc:0.83754
[43]	validation_0-auc:0.90254	validation_1-auc:0.83765
[44]	validation_0-auc:0.90297	validation_1-auc:0.83734
[45]	validation_0-auc:0.90381	validation_1-auc:0.83795
[46]	validation_0-auc:0.90424	validation_1-auc:0.83809
[47]	validation_0-auc:0.90489	validation_1-auc:0.83797
[48]	validation_0-auc:0.90516	validation_1-auc:0.83817
[49]	validation_0-auc:0.90604	validation_1-auc:0.83813
[50]	validation_0-auc:0.90647	validation_1-auc:0.83780
[51]	validation_0-auc:0.90729	validation_1-auc:0.83763
[52]	validation_0-auc:0.90745	validation_1-auc:0.83763
[53]	validation_0-auc:0.90761	validation_1-auc:0.83766
[54]	validation_0-auc:0.90784	validation_1-auc:0.83745
[55]	validation_0-auc:0.90985	validation_1-auc:0.83712
[56]	validation_0-auc:0.90999	validation_1-auc:0.83696
[57]	validation_0-auc:0.91024	validation_1-auc:0.83672
[58]	validation_0-auc:0.91047	validation_1-auc:0.83670
[59]	validation_0-auc:0.91131	validation_1-auc:0.83619
[60]	validation_0-auc:0.91200	validation_1-auc:0.83614
[61]	validation_0-auc:0.91261	validation_1-auc:0.83620
[62]	validation_0-auc:0.91270	validation_1-auc:0.83604
 82%|████████▏ | 41/50 [08:43<01:44, 11.64s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82239	validation_1-auc:0.81035
[1]	validation_0-auc:0.83811	validation_1-auc:0.82525
[2]	validation_0-auc:0.84454	validation_1-auc:0.82805
[3]	validation_0-auc:0.84793	validation_1-auc:0.83175
[4]	validation_0-auc:0.85183	validation_1-auc:0.83354
[5]	validation_0-auc:0.85286	validation_1-auc:0.83393
[6]	validation_0-auc:0.85483	validation_1-auc:0.83478
[7]	validation_0-auc:0.85747	validation_1-auc:0.83450
[8]	validation_0-auc:0.85795	validation_1-auc:0.83468
[9]	validation_0-auc:0.86214	validation_1-auc:0.83536
[10]	validation_0-auc:0.86362	validation_1-auc:0.83429
[11]	validation_0-auc:0.86226	validation_1-auc:0.83138
[12]	validation_0-auc:0.86858	validation_1-auc:0.83441
[13]	validation_0-auc:0.87117	validation_1-auc:0.83664
[14]	validation_0-auc:0.87265	validation_1-auc:0.83947
[15]	validation_0-auc:0.87483	validation_1-auc:0.83983
[16]	validation_0-auc:0.87665	validation_1-auc:0.84142
[17]	validation_0-auc:0.87819	validation_1-auc:0.84175
[18]	validation_0-auc:0.87997	validation_1-auc:0.84072
[19]	validation_0-auc:0.88212	validation_1-auc:0.84117
[20]	validation_0-auc:0.88365	validation_1-auc:0.84325
[21]	validation_0-auc:0.88510	validation_1-auc:0.84198
[22]	validation_0-auc:0.88654	validation_1-auc:0.84257
[23]	validation_0-auc:0.88761	validation_1-auc:0.84310
[24]	validation_0-auc:0.88859	validation_1-auc:0.84325
[25]	validation_0-auc:0.88891	validation_1-auc:0.84347
[26]	validation_0-auc:0.88959	validation_1-auc:0.84390
[27]	validation_0-auc:0.89107	validation_1-auc:0.84399
[28]	validation_0-auc:0.89143	validation_1-auc:0.84376
[29]	validation_0-auc:0.89199	validation_1-auc:0.84397
[30]	validation_0-auc:0.89298	validation_1-auc:0.84344
[31]	validation_0-auc:0.89397	validation_1-auc:0.84416
[32]	validation_0-auc:0.89457	validation_1-auc:0.84462
[33]	validation_0-auc:0.89516	validation_1-auc:0.84456
[34]	validation_0-auc:0.89554	validation_1-auc:0.84474
[35]	validation_0-auc:0.89613	validation_1-auc:0.84501
[36]	validation_0-auc:0.89667	validation_1-auc:0.84527
[37]	validation_0-auc:0.89749	validation_1-auc:0.84522
[38]	validation_0-auc:0.89873	validation_1-auc:0.84502
[39]	validation_0-auc:0.89884	validation_1-auc:0.84518
[40]	validation_0-auc:0.89945	validation_1-auc:0.84508
[41]	validation_0-auc:0.89993	validation_1-auc:0.84451
[42]	validation_0-auc:0.90001	validation_1-auc:0.84462
[43]	validation_0-auc:0.90058	validation_1-auc:0.84484
[44]	validation_0-auc:0.90156	validation_1-auc:0.84465
[45]	validation_0-auc:0.90186	validation_1-auc:0.84444
[46]	validation_0-auc:0.90241	validation_1-auc:0.84432
[47]	validation_0-auc:0.90259	validation_1-auc:0.84448
[48]	validation_0-auc:0.90311	validation_1-auc:0.84403
[49]	validation_0-auc:0.90345	validation_1-auc:0.84407
[50]	validation_0-auc:0.90388	validation_1-auc:0.84397
[51]	validation_0-auc:0.90441	validation_1-auc:0.84368
[52]	validation_0-auc:0.90466	validation_1-auc:0.84374
[53]	validation_0-auc:0.90505	validation_1-auc:0.84342
[54]	validation_0-auc:0.90532	validation_1-auc:0.84305
[55]	validation_0-auc:0.90592	validation_1-auc:0.84324
[56]	validation_0-auc:0.90616	validation_1-auc:0.84311
[57]	validation_0-auc:0.90623	validation_1-auc:0.84295
[58]	validation_0-auc:0.90657	validation_1-auc:0.84320
[59]	validation_0-auc:0.90678	validation_1-auc:0.84309
[60]	validation_0-auc:0.90692	validation_1-auc:0.84315
[61]	validation_0-auc:0.90756	validation_1-auc:0.84322
[62]	validation_0-auc:0.90862	validation_1-auc:0.84296
[63]	validation_0-auc:0.90906	validation_1-auc:0.84261
[64]	validation_0-auc:0.90984	validation_1-auc:0.84208
[65]	validation_0-auc:0.91052	validation_1-auc:0.84209
[66]	validation_0-auc:0.91073	validation_1-auc:0.84189
 84%|████████▍ | 42/50 [08:46<01:30, 11.30s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83234	validation_1-auc:0.81401
[1]	validation_0-auc:0.83951	validation_1-auc:0.81455
[2]	validation_0-auc:0.84460	validation_1-auc:0.81701
[3]	validation_0-auc:0.85181	validation_1-auc:0.81810
[4]	validation_0-auc:0.85863	validation_1-auc:0.82128
[5]	validation_0-auc:0.86160	validation_1-auc:0.82357
[6]	validation_0-auc:0.86588	validation_1-auc:0.82538
[7]	validation_0-auc:0.86942	validation_1-auc:0.82562
[8]	validation_0-auc:0.87122	validation_1-auc:0.82528
[9]	validation_0-auc:0.87848	validation_1-auc:0.82793
[10]	validation_0-auc:0.87971	validation_1-auc:0.82905
[11]	validation_0-auc:0.88207	validation_1-auc:0.82732
[12]	validation_0-auc:0.88758	validation_1-auc:0.83036
[13]	validation_0-auc:0.89083	validation_1-auc:0.83315
[14]	validation_0-auc:0.89239	validation_1-auc:0.83562
[15]	validation_0-auc:0.89571	validation_1-auc:0.83723
[16]	validation_0-auc:0.89844	validation_1-auc:0.83679
[17]	validation_0-auc:0.90148	validation_1-auc:0.83675
[18]	validation_0-auc:0.90219	validation_1-auc:0.83722
[19]	validation_0-auc:0.90433	validation_1-auc:0.83739
[20]	validation_0-auc:0.90605	validation_1-auc:0.83606
[21]	validation_0-auc:0.90695	validation_1-auc:0.83636
[22]	validation_0-auc:0.90922	validation_1-auc:0.83653
[23]	validation_0-auc:0.91077	validation_1-auc:0.83680
[24]	validation_0-auc:0.91185	validation_1-auc:0.83711
[25]	validation_0-auc:0.91313	validation_1-auc:0.83804
[26]	validation_0-auc:0.91458	validation_1-auc:0.83795
[27]	validation_0-auc:0.91714	validation_1-auc:0.83767
[28]	validation_0-auc:0.91924	validation_1-auc:0.83734
[29]	validation_0-auc:0.92103	validation_1-auc:0.83727
[30]	validation_0-auc:0.92216	validation_1-auc:0.83694
[31]	validation_0-auc:0.92363	validation_1-auc:0.83589
[32]	validation_0-auc:0.92458	validation_1-auc:0.83670
[33]	validation_0-auc:0.92546	validation_1-auc:0.83723
[34]	validation_0-auc:0.92661	validation_1-auc:0.83747
[35]	validation_0-auc:0.92809	validation_1-auc:0.83763
[36]	validation_0-auc:0.92883	validation_1-auc:0.83830
[37]	validation_0-auc:0.92980	validation_1-auc:0.83835
[38]	validation_0-auc:0.93095	validation_1-auc:0.83838
[39]	validation_0-auc:0.93156	validation_1-auc:0.83800
[40]	validation_0-auc:0.93231	validation_1-auc:0.83779
[41]	validation_0-auc:0.93333	validation_1-auc:0.83805
[42]	validation_0-auc:0.93406	validation_1-auc:0.83794
[43]	validation_0-auc:0.93447	validation_1-auc:0.83836
[44]	validation_0-auc:0.93517	validation_1-auc:0.83852
[45]	validation_0-auc:0.93597	validation_1-auc:0.83871
[46]	validation_0-auc:0.93642	validation_1-auc:0.83867
[47]	validation_0-auc:0.93710	validation_1-auc:0.83881
[48]	validation_0-auc:0.93731	validation_1-auc:0.83930
[49]	validation_0-auc:0.93761	validation_1-auc:0.83965
[50]	validation_0-auc:0.93788	validation_1-auc:0.83967
[51]	validation_0-auc:0.93822	validation_1-auc:0.83988
[52]	validation_0-auc:0.93903	validation_1-auc:0.83948
[53]	validation_0-auc:0.93949	validation_1-auc:0.83953
[54]	validation_0-auc:0.93979	validation_1-auc:0.83933
[55]	validation_0-auc:0.94020	validation_1-auc:0.83909
[56]	validation_0-auc:0.94046	validation_1-auc:0.83898
[57]	validation_0-auc:0.94067	validation_1-auc:0.83906
[58]	validation_0-auc:0.94143	validation_1-auc:0.83940
[59]	validation_0-auc:0.94166	validation_1-auc:0.83948
[60]	validation_0-auc:0.94190	validation_1-auc:0.83917
[61]	validation_0-auc:0.94214	validation_1-auc:0.83911
[62]	validation_0-auc:0.94241	validation_1-auc:0.83897
[63]	validation_0-auc:0.94255	validation_1-auc:0.83870
[64]	validation_0-auc:0.94278	validation_1-auc:0.83860
[65]	validation_0-auc:0.94312	validation_1-auc:0.83835
[66]	validation_0-auc:0.94326	validation_1-auc:0.83828
[67]	validation_0-auc:0.94363	validation_1-auc:0.83784
[68]	validation_0-auc:0.94383	validation_1-auc:0.83754
[69]	validation_0-auc:0.94409	validation_1-auc:0.83762
[70]	validation_0-auc:0.94434	validation_1-auc:0.83764
[71]	validation_0-auc:0.94451	validation_1-auc:0.83747
[72]	validation_0-auc:0.94481	validation_1-auc:0.83735
[73]	validation_0-auc:0.94493	validation_1-auc:0.83729
[74]	validation_0-auc:0.94502	validation_1-auc:0.83726
[75]	validation_0-auc:0.94507	validation_1-auc:0.83726
[76]	validation_0-auc:0.94532	validation_1-auc:0.83704
[77]	validation_0-auc:0.94541	validation_1-auc:0.83711
[78]	validation_0-auc:0.94563	validation_1-auc:0.83706
[79]	validation_0-auc:0.94599	validation_1-auc:0.83699
[80]	validation_0-auc:0.94655	validation_1-auc:0.83698
 84%|████████▍ | 42/50 [08:53<01:30, 11.30s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82969	validation_1-auc:0.80801
[1]	validation_0-auc:0.83648	validation_1-auc:0.81162
[2]	validation_0-auc:0.84136	validation_1-auc:0.81385
[3]	validation_0-auc:0.84663	validation_1-auc:0.81718
[4]	validation_0-auc:0.85529	validation_1-auc:0.82292
[5]	validation_0-auc:0.85969	validation_1-auc:0.82277
[6]	validation_0-auc:0.86482	validation_1-auc:0.82422
[7]	validation_0-auc:0.86956	validation_1-auc:0.82394
[8]	validation_0-auc:0.87312	validation_1-auc:0.82476
[9]	validation_0-auc:0.87885	validation_1-auc:0.82703
[10]	validation_0-auc:0.88193	validation_1-auc:0.82833
[11]	validation_0-auc:0.88463	validation_1-auc:0.82653
[12]	validation_0-auc:0.89040	validation_1-auc:0.82771
[13]	validation_0-auc:0.89383	validation_1-auc:0.82799
[14]	validation_0-auc:0.89609	validation_1-auc:0.82934
[15]	validation_0-auc:0.89799	validation_1-auc:0.82958
[16]	validation_0-auc:0.90028	validation_1-auc:0.82928
[17]	validation_0-auc:0.90262	validation_1-auc:0.82981
[18]	validation_0-auc:0.90415	validation_1-auc:0.83039
[19]	validation_0-auc:0.90585	validation_1-auc:0.83092
[20]	validation_0-auc:0.90831	validation_1-auc:0.83064
[21]	validation_0-auc:0.90927	validation_1-auc:0.83040
[22]	validation_0-auc:0.91085	validation_1-auc:0.83180
[23]	validation_0-auc:0.91301	validation_1-auc:0.83269
[24]	validation_0-auc:0.91447	validation_1-auc:0.83386
[25]	validation_0-auc:0.91511	validation_1-auc:0.83397
[26]	validation_0-auc:0.91701	validation_1-auc:0.83320
[27]	validation_0-auc:0.91875	validation_1-auc:0.83288
[28]	validation_0-auc:0.92038	validation_1-auc:0.83311
[29]	validation_0-auc:0.92155	validation_1-auc:0.83314
[30]	validation_0-auc:0.92303	validation_1-auc:0.83201
[31]	validation_0-auc:0.92476	validation_1-auc:0.83242
[32]	validation_0-auc:0.92582	validation_1-auc:0.83204
[33]	validation_0-auc:0.92670	validation_1-auc:0.83246
[34]	validation_0-auc:0.92788	validation_1-auc:0.83303
[35]	validation_0-auc:0.92873	validation_1-auc:0.83390
[36]	validation_0-auc:0.92969	validation_1-auc:0.83401
[37]	validation_0-auc:0.93075	validation_1-auc:0.83342
[38]	validation_0-auc:0.93143	validation_1-auc:0.83313
[39]	validation_0-auc:0.93200	validation_1-auc:0.83295
[40]	validation_0-auc:0.93224	validation_1-auc:0.83292
[41]	validation_0-auc:0.93313	validation_1-auc:0.83298
[42]	validation_0-auc:0.93377	validation_1-auc:0.83279
[43]	validation_0-auc:0.93429	validation_1-auc:0.83325
[44]	validation_0-auc:0.93488	validation_1-auc:0.83373
[45]	validation_0-auc:0.93526	validation_1-auc:0.83369
[46]	validation_0-auc:0.93550	validation_1-auc:0.83362
[47]	validation_0-auc:0.93600	validation_1-auc:0.83363
[48]	validation_0-auc:0.93667	validation_1-auc:0.83326
[49]	validation_0-auc:0.93700	validation_1-auc:0.83341
[50]	validation_0-auc:0.93741	validation_1-auc:0.83350
[51]	validation_0-auc:0.93835	validation_1-auc:0.83301
[52]	validation_0-auc:0.93884	validation_1-auc:0.83306
[53]	validation_0-auc:0.93925	validation_1-auc:0.83328
[54]	validation_0-auc:0.93960	validation_1-auc:0.83328
[55]	validation_0-auc:0.94050	validation_1-auc:0.83316
[56]	validation_0-auc:0.94083	validation_1-auc:0.83342
[57]	validation_0-auc:0.94120	validation_1-auc:0.83302
[58]	validation_0-auc:0.94163	validation_1-auc:0.83271
[59]	validation_0-auc:0.94215	validation_1-auc:0.83240
[60]	validation_0-auc:0.94284	validation_1-auc:0.83226
[61]	validation_0-auc:0.94318	validation_1-auc:0.83217
[62]	validation_0-auc:0.94329	validation_1-auc:0.83205
[63]	validation_0-auc:0.94372	validation_1-auc:0.83217
[64]	validation_0-auc:0.94434	validation_1-auc:0.83166
[65]	validation_0-auc:0.94453	validation_1-auc:0.83152
[66]	validation_0-auc:0.94490	validation_1-auc:0.83125
 84%|████████▍ | 42/50 [08:58<01:30, 11.30s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82759	validation_1-auc:0.80915
[1]	validation_0-auc:0.83504	validation_1-auc:0.81383
[2]	validation_0-auc:0.84593	validation_1-auc:0.82521
[3]	validation_0-auc:0.85167	validation_1-auc:0.82819
[4]	validation_0-auc:0.85926	validation_1-auc:0.83225
[5]	validation_0-auc:0.86391	validation_1-auc:0.83272
[6]	validation_0-auc:0.86656	validation_1-auc:0.83417
[7]	validation_0-auc:0.86846	validation_1-auc:0.83484
[8]	validation_0-auc:0.87121	validation_1-auc:0.83465
[9]	validation_0-auc:0.87711	validation_1-auc:0.83552
[10]	validation_0-auc:0.88036	validation_1-auc:0.83563
[11]	validation_0-auc:0.88109	validation_1-auc:0.83358
[12]	validation_0-auc:0.88703	validation_1-auc:0.83477
[13]	validation_0-auc:0.89050	validation_1-auc:0.83624
[14]	validation_0-auc:0.89203	validation_1-auc:0.83815
[15]	validation_0-auc:0.89474	validation_1-auc:0.83817
[16]	validation_0-auc:0.89776	validation_1-auc:0.83902
[17]	validation_0-auc:0.89955	validation_1-auc:0.83935
[18]	validation_0-auc:0.90082	validation_1-auc:0.83725
[19]	validation_0-auc:0.90378	validation_1-auc:0.83864
[20]	validation_0-auc:0.90584	validation_1-auc:0.83983
[21]	validation_0-auc:0.90701	validation_1-auc:0.83813
[22]	validation_0-auc:0.90907	validation_1-auc:0.83951
[23]	validation_0-auc:0.91045	validation_1-auc:0.83942
[24]	validation_0-auc:0.91193	validation_1-auc:0.83937
[25]	validation_0-auc:0.91258	validation_1-auc:0.83963
[26]	validation_0-auc:0.91518	validation_1-auc:0.84007
[27]	validation_0-auc:0.91731	validation_1-auc:0.84063
[28]	validation_0-auc:0.91904	validation_1-auc:0.84003
[29]	validation_0-auc:0.92027	validation_1-auc:0.84031
[30]	validation_0-auc:0.92191	validation_1-auc:0.83951
[31]	validation_0-auc:0.92308	validation_1-auc:0.83989
[32]	validation_0-auc:0.92395	validation_1-auc:0.84055
[33]	validation_0-auc:0.92468	validation_1-auc:0.84079
[34]	validation_0-auc:0.92517	validation_1-auc:0.84060
[35]	validation_0-auc:0.92612	validation_1-auc:0.84074
[36]	validation_0-auc:0.92668	validation_1-auc:0.84077
[37]	validation_0-auc:0.92822	validation_1-auc:0.83968
[38]	validation_0-auc:0.92891	validation_1-auc:0.83918
[39]	validation_0-auc:0.92942	validation_1-auc:0.83904
[40]	validation_0-auc:0.92996	validation_1-auc:0.83864
[41]	validation_0-auc:0.93062	validation_1-auc:0.83828
[42]	validation_0-auc:0.93094	validation_1-auc:0.83871
[43]	validation_0-auc:0.93139	validation_1-auc:0.83905
[44]	validation_0-auc:0.93224	validation_1-auc:0.83887
[45]	validation_0-auc:0.93275	validation_1-auc:0.83901
[46]	validation_0-auc:0.93314	validation_1-auc:0.83898
[47]	validation_0-auc:0.93369	validation_1-auc:0.83970
[48]	validation_0-auc:0.93407	validation_1-auc:0.83977
[49]	validation_0-auc:0.93489	validation_1-auc:0.84011
[50]	validation_0-auc:0.93515	validation_1-auc:0.84008
[51]	validation_0-auc:0.93590	validation_1-auc:0.84021
[52]	validation_0-auc:0.93659	validation_1-auc:0.84039
[53]	validation_0-auc:0.93711	validation_1-auc:0.84061
[54]	validation_0-auc:0.93756	validation_1-auc:0.84038
[55]	validation_0-auc:0.93780	validation_1-auc:0.84051
[56]	validation_0-auc:0.93821	validation_1-auc:0.84040
[57]	validation_0-auc:0.93867	validation_1-auc:0.84029
[58]	validation_0-auc:0.93897	validation_1-auc:0.84038
[59]	validation_0-auc:0.93924	validation_1-auc:0.84012
[60]	validation_0-auc:0.93933	validation_1-auc:0.84022
[61]	validation_0-auc:0.94004	validation_1-auc:0.83993
[62]	validation_0-auc:0.94032	validation_1-auc:0.83978
 86%|████████▌ | 43/50 [09:03<01:29, 12.85s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83266	validation_1-auc:0.81446
[1]	validation_0-auc:0.84021	validation_1-auc:0.81437
[2]	validation_0-auc:0.84334	validation_1-auc:0.81581
[3]	validation_0-auc:0.84882	validation_1-auc:0.81676
[4]	validation_0-auc:0.85374	validation_1-auc:0.81852
[5]	validation_0-auc:0.86058	validation_1-auc:0.82630
[6]	validation_0-auc:0.86305	validation_1-auc:0.82791
[7]	validation_0-auc:0.86544	validation_1-auc:0.82810
[8]	validation_0-auc:0.86729	validation_1-auc:0.82748
[9]	validation_0-auc:0.86997	validation_1-auc:0.82841
[10]	validation_0-auc:0.86901	validation_1-auc:0.82693
[11]	validation_0-auc:0.86994	validation_1-auc:0.82692
[12]	validation_0-auc:0.87330	validation_1-auc:0.83065
[13]	validation_0-auc:0.87691	validation_1-auc:0.83306
[14]	validation_0-auc:0.87819	validation_1-auc:0.83502
[15]	validation_0-auc:0.88118	validation_1-auc:0.83848
[16]	validation_0-auc:0.88238	validation_1-auc:0.83966
[17]	validation_0-auc:0.88476	validation_1-auc:0.83894
[18]	validation_0-auc:0.88560	validation_1-auc:0.83812
[19]	validation_0-auc:0.88691	validation_1-auc:0.83969
[20]	validation_0-auc:0.88925	validation_1-auc:0.83958
[21]	validation_0-auc:0.88927	validation_1-auc:0.83848
[22]	validation_0-auc:0.89066	validation_1-auc:0.83949
[23]	validation_0-auc:0.89283	validation_1-auc:0.83982
[24]	validation_0-auc:0.89385	validation_1-auc:0.83962
[25]	validation_0-auc:0.89454	validation_1-auc:0.83991
[26]	validation_0-auc:0.89494	validation_1-auc:0.83940
[27]	validation_0-auc:0.89770	validation_1-auc:0.83994
[28]	validation_0-auc:0.89858	validation_1-auc:0.84018
[29]	validation_0-auc:0.89970	validation_1-auc:0.84016
[30]	validation_0-auc:0.90174	validation_1-auc:0.83996
[31]	validation_0-auc:0.90385	validation_1-auc:0.84000
[32]	validation_0-auc:0.90491	validation_1-auc:0.83999
[33]	validation_0-auc:0.90574	validation_1-auc:0.83998
[34]	validation_0-auc:0.90652	validation_1-auc:0.84020
[35]	validation_0-auc:0.90814	validation_1-auc:0.84108
[36]	validation_0-auc:0.90865	validation_1-auc:0.84106
[37]	validation_0-auc:0.90973	validation_1-auc:0.84096
[38]	validation_0-auc:0.91063	validation_1-auc:0.84142
[39]	validation_0-auc:0.91138	validation_1-auc:0.84139
[40]	validation_0-auc:0.91248	validation_1-auc:0.84131
[41]	validation_0-auc:0.91343	validation_1-auc:0.84116
[42]	validation_0-auc:0.91471	validation_1-auc:0.84167
[43]	validation_0-auc:0.91530	validation_1-auc:0.84228
[44]	validation_0-auc:0.91633	validation_1-auc:0.84211
[45]	validation_0-auc:0.91666	validation_1-auc:0.84244
[46]	validation_0-auc:0.91761	validation_1-auc:0.84240
[47]	validation_0-auc:0.91832	validation_1-auc:0.84242
[48]	validation_0-auc:0.91902	validation_1-auc:0.84245
[49]	validation_0-auc:0.91964	validation_1-auc:0.84266
[50]	validation_0-auc:0.92008	validation_1-auc:0.84270
[51]	validation_0-auc:0.92066	validation_1-auc:0.84255
[52]	validation_0-auc:0.92107	validation_1-auc:0.84255
[53]	validation_0-auc:0.92177	validation_1-auc:0.84246
[54]	validation_0-auc:0.92227	validation_1-auc:0.84252
[55]	validation_0-auc:0.92317	validation_1-auc:0.84275
[56]	validation_0-auc:0.92334	validation_1-auc:0.84291
[57]	validation_0-auc:0.92374	validation_1-auc:0.84310
[58]	validation_0-auc:0.92438	validation_1-auc:0.84316
[59]	validation_0-auc:0.92459	validation_1-auc:0.84311
[60]	validation_0-auc:0.92481	validation_1-auc:0.84291
[61]	validation_0-auc:0.92520	validation_1-auc:0.84295
[62]	validation_0-auc:0.92540	validation_1-auc:0.84288
[63]	validation_0-auc:0.92565	validation_1-auc:0.84284
[64]	validation_0-auc:0.92580	validation_1-auc:0.84282
[65]	validation_0-auc:0.92645	validation_1-auc:0.84300
[66]	validation_0-auc:0.92651	validation_1-auc:0.84302
[67]	validation_0-auc:0.92675	validation_1-auc:0.84290
[68]	validation_0-auc:0.92745	validation_1-auc:0.84274
[69]	validation_0-auc:0.92776	validation_1-auc:0.84286
[70]	validation_0-auc:0.92849	validation_1-auc:0.84262
[71]	validation_0-auc:0.92871	validation_1-auc:0.84268
[72]	validation_0-auc:0.92886	validation_1-auc:0.84268
[73]	validation_0-auc:0.92902	validation_1-auc:0.84268
[74]	validation_0-auc:0.92920	validation_1-auc:0.84259
[75]	validation_0-auc:0.92938	validation_1-auc:0.84243
[76]	validation_0-auc:0.92948	validation_1-auc:0.84234
[77]	validation_0-auc:0.92959	validation_1-auc:0.84237
[78]	validation_0-auc:0.92996	validation_1-auc:0.84263
[79]	validation_0-auc:0.93058	validation_1-auc:0.84261
[80]	validation_0-auc:0.93085	validation_1-auc:0.84261
[81]	validation_0-auc:0.93092	validation_1-auc:0.84263
[82]	validation_0-auc:0.93099	validation_1-auc:0.84295
[83]	validation_0-auc:0.93109	validation_1-auc:0.84301
[84]	validation_0-auc:0.93119	validation_1-auc:0.84301
[85]	validation_0-auc:0.93163	validation_1-auc:0.84286
[86]	validation_0-auc:0.93187	validation_1-auc:0.84279
[87]	validation_0-auc:0.93228	validation_1-auc:0.84287
 86%|████████▌ | 43/50 [09:08<01:29, 12.85s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82798	validation_1-auc:0.80768
[1]	validation_0-auc:0.83560	validation_1-auc:0.81112
[2]	validation_0-auc:0.84186	validation_1-auc:0.81559
[3]	validation_0-auc:0.84334	validation_1-auc:0.81727
[4]	validation_0-auc:0.85063	validation_1-auc:0.81966
[5]	validation_0-auc:0.85357	validation_1-auc:0.82208
[6]	validation_0-auc:0.85871	validation_1-auc:0.82430
[7]	validation_0-auc:0.86355	validation_1-auc:0.82636
[8]	validation_0-auc:0.86598	validation_1-auc:0.82619
[9]	validation_0-auc:0.87022	validation_1-auc:0.82757
[10]	validation_0-auc:0.87162	validation_1-auc:0.82688
[11]	validation_0-auc:0.87346	validation_1-auc:0.82665
[12]	validation_0-auc:0.87702	validation_1-auc:0.82804
[13]	validation_0-auc:0.88085	validation_1-auc:0.82901
[14]	validation_0-auc:0.88179	validation_1-auc:0.82971
[15]	validation_0-auc:0.88355	validation_1-auc:0.82987
[16]	validation_0-auc:0.88492	validation_1-auc:0.82992
[17]	validation_0-auc:0.88636	validation_1-auc:0.83091
[18]	validation_0-auc:0.88681	validation_1-auc:0.82968
[19]	validation_0-auc:0.89038	validation_1-auc:0.83000
[20]	validation_0-auc:0.89242	validation_1-auc:0.83106
[21]	validation_0-auc:0.89348	validation_1-auc:0.82981
[22]	validation_0-auc:0.89491	validation_1-auc:0.83095
[23]	validation_0-auc:0.89675	validation_1-auc:0.83152
[24]	validation_0-auc:0.89794	validation_1-auc:0.83254
[25]	validation_0-auc:0.89895	validation_1-auc:0.83292
[26]	validation_0-auc:0.89968	validation_1-auc:0.83248
[27]	validation_0-auc:0.90175	validation_1-auc:0.83343
[28]	validation_0-auc:0.90322	validation_1-auc:0.83384
[29]	validation_0-auc:0.90425	validation_1-auc:0.83394
[30]	validation_0-auc:0.90635	validation_1-auc:0.83404
[31]	validation_0-auc:0.90788	validation_1-auc:0.83378
[32]	validation_0-auc:0.90950	validation_1-auc:0.83361
[33]	validation_0-auc:0.91023	validation_1-auc:0.83449
[34]	validation_0-auc:0.91114	validation_1-auc:0.83469
[35]	validation_0-auc:0.91226	validation_1-auc:0.83515
[36]	validation_0-auc:0.91299	validation_1-auc:0.83413
[37]	validation_0-auc:0.91404	validation_1-auc:0.83358
[38]	validation_0-auc:0.91522	validation_1-auc:0.83272
[39]	validation_0-auc:0.91580	validation_1-auc:0.83353
[40]	validation_0-auc:0.91681	validation_1-auc:0.83345
[41]	validation_0-auc:0.91730	validation_1-auc:0.83332
[42]	validation_0-auc:0.91851	validation_1-auc:0.83296
[43]	validation_0-auc:0.91940	validation_1-auc:0.83327
[44]	validation_0-auc:0.91999	validation_1-auc:0.83359
[45]	validation_0-auc:0.92041	validation_1-auc:0.83390
[46]	validation_0-auc:0.92076	validation_1-auc:0.83431
[47]	validation_0-auc:0.92119	validation_1-auc:0.83421
[48]	validation_0-auc:0.92148	validation_1-auc:0.83442
[49]	validation_0-auc:0.92244	validation_1-auc:0.83430
[50]	validation_0-auc:0.92293	validation_1-auc:0.83426
[51]	validation_0-auc:0.92330	validation_1-auc:0.83423
[52]	validation_0-auc:0.92389	validation_1-auc:0.83398
[53]	validation_0-auc:0.92418	validation_1-auc:0.83398
[54]	validation_0-auc:0.92488	validation_1-auc:0.83378
[55]	validation_0-auc:0.92543	validation_1-auc:0.83412
[56]	validation_0-auc:0.92584	validation_1-auc:0.83407
[57]	validation_0-auc:0.92679	validation_1-auc:0.83334
[58]	validation_0-auc:0.92753	validation_1-auc:0.83313
[59]	validation_0-auc:0.92837	validation_1-auc:0.83246
[60]	validation_0-auc:0.92855	validation_1-auc:0.83241
[61]	validation_0-auc:0.92883	validation_1-auc:0.83218
[62]	validation_0-auc:0.92938	validation_1-auc:0.83189
[63]	validation_0-auc:0.92952	validation_1-auc:0.83194
[64]	validation_0-auc:0.93024	validation_1-auc:0.83183
 86%|████████▌ | 43/50 [09:12<01:29, 12.85s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82484	validation_1-auc:0.80955
[1]	validation_0-auc:0.84090	validation_1-auc:0.82269
[2]	validation_0-auc:0.84338	validation_1-auc:0.82457
[3]	validation_0-auc:0.84857	validation_1-auc:0.82703
[4]	validation_0-auc:0.85567	validation_1-auc:0.83139
[5]	validation_0-auc:0.85683	validation_1-auc:0.83060
[6]	validation_0-auc:0.86001	validation_1-auc:0.83171
[7]	validation_0-auc:0.86310	validation_1-auc:0.83358
[8]	validation_0-auc:0.86490	validation_1-auc:0.83430
[9]	validation_0-auc:0.86783	validation_1-auc:0.83419
[10]	validation_0-auc:0.86857	validation_1-auc:0.83202
[11]	validation_0-auc:0.86956	validation_1-auc:0.83105
[12]	validation_0-auc:0.87176	validation_1-auc:0.83195
[13]	validation_0-auc:0.87614	validation_1-auc:0.83391
[14]	validation_0-auc:0.87763	validation_1-auc:0.83555
[15]	validation_0-auc:0.87966	validation_1-auc:0.83669
[16]	validation_0-auc:0.88094	validation_1-auc:0.83861
[17]	validation_0-auc:0.88214	validation_1-auc:0.83952
[18]	validation_0-auc:0.88295	validation_1-auc:0.83851
[19]	validation_0-auc:0.88472	validation_1-auc:0.83830
[20]	validation_0-auc:0.88679	validation_1-auc:0.83924
[21]	validation_0-auc:0.88758	validation_1-auc:0.83778
[22]	validation_0-auc:0.88989	validation_1-auc:0.83902
[23]	validation_0-auc:0.89118	validation_1-auc:0.83883
[24]	validation_0-auc:0.89265	validation_1-auc:0.83934
[25]	validation_0-auc:0.89374	validation_1-auc:0.84021
[26]	validation_0-auc:0.89639	validation_1-auc:0.83979
[27]	validation_0-auc:0.89886	validation_1-auc:0.84011
[28]	validation_0-auc:0.90001	validation_1-auc:0.84075
[29]	validation_0-auc:0.90143	validation_1-auc:0.84103
[30]	validation_0-auc:0.90285	validation_1-auc:0.84106
[31]	validation_0-auc:0.90475	validation_1-auc:0.84195
[32]	validation_0-auc:0.90570	validation_1-auc:0.84268
[33]	validation_0-auc:0.90633	validation_1-auc:0.84246
[34]	validation_0-auc:0.90727	validation_1-auc:0.84299
[35]	validation_0-auc:0.90834	validation_1-auc:0.84263
[36]	validation_0-auc:0.90990	validation_1-auc:0.84208
[37]	validation_0-auc:0.91104	validation_1-auc:0.84166
[38]	validation_0-auc:0.91230	validation_1-auc:0.84158
[39]	validation_0-auc:0.91297	validation_1-auc:0.84186
[40]	validation_0-auc:0.91400	validation_1-auc:0.84172
[41]	validation_0-auc:0.91510	validation_1-auc:0.84112
[42]	validation_0-auc:0.91655	validation_1-auc:0.84158
[43]	validation_0-auc:0.91755	validation_1-auc:0.84166
[44]	validation_0-auc:0.91800	validation_1-auc:0.84165
[45]	validation_0-auc:0.91829	validation_1-auc:0.84223
[46]	validation_0-auc:0.91872	validation_1-auc:0.84200
[47]	validation_0-auc:0.91921	validation_1-auc:0.84228
[48]	validation_0-auc:0.91993	validation_1-auc:0.84261
[49]	validation_0-auc:0.92047	validation_1-auc:0.84285
[50]	validation_0-auc:0.92062	validation_1-auc:0.84313
[51]	validation_0-auc:0.92134	validation_1-auc:0.84314
[52]	validation_0-auc:0.92172	validation_1-auc:0.84309
[53]	validation_0-auc:0.92254	validation_1-auc:0.84289
[54]	validation_0-auc:0.92320	validation_1-auc:0.84251
[55]	validation_0-auc:0.92373	validation_1-auc:0.84229
[56]	validation_0-auc:0.92417	validation_1-auc:0.84212
[57]	validation_0-auc:0.92494	validation_1-auc:0.84185
[58]	validation_0-auc:0.92552	validation_1-auc:0.84179
[59]	validation_0-auc:0.92576	validation_1-auc:0.84178
[60]	validation_0-auc:0.92640	validation_1-auc:0.84152
[61]	validation_0-auc:0.92658	validation_1-auc:0.84139
[62]	validation_0-auc:0.92687	validation_1-auc:0.84104
[63]	validation_0-auc:0.92720	validation_1-auc:0.84100
[64]	validation_0-auc:0.92761	validation_1-auc:0.84108
[65]	validation_0-auc:0.92836	validation_1-auc:0.84097
[66]	validation_0-auc:0.92886	validation_1-auc:0.84088
[67]	validation_0-auc:0.92894	validation_1-auc:0.84095
[68]	validation_0-auc:0.92927	validation_1-auc:0.84113
[69]	validation_0-auc:0.92964	validation_1-auc:0.84100
[70]	validation_0-auc:0.92989	validation_1-auc:0.84100
[71]	validation_0-auc:0.93008	validation_1-auc:0.84100
[72]	validation_0-auc:0.93031	validation_1-auc:0.84086
[73]	validation_0-auc:0.93051	validation_1-auc:0.84074
[74]	validation_0-auc:0.93067	validation_1-auc:0.84047
[75]	validation_0-auc:0.93094	validation_1-auc:0.84043
[76]	validation_0-auc:0.93103	validation_1-auc:0.84034
[77]	validation_0-auc:0.93131	validation_1-auc:0.84024
[78]	validation_0-auc:0.93202	validation_1-auc:0.84009
[79]	validation_0-auc:0.93246	validation_1-auc:0.83999
[80]	validation_0-auc:0.93273	validation_1-auc:0.84008
[81]	validation_0-auc:0.93288	validation_1-auc:0.83998
 88%|████████▊ | 44/50 [09:17<01:19, 13.19s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83307	validation_1-auc:0.81316
[1]	validation_0-auc:0.84341	validation_1-auc:0.81516
[2]	validation_0-auc:0.85290	validation_1-auc:0.81789
[3]	validation_0-auc:0.85702	validation_1-auc:0.81782
[4]	validation_0-auc:0.86689	validation_1-auc:0.82336
[5]	validation_0-auc:0.86924	validation_1-auc:0.82446
[6]	validation_0-auc:0.87459	validation_1-auc:0.82418
[7]	validation_0-auc:0.88020	validation_1-auc:0.82593
[8]	validation_0-auc:0.88388	validation_1-auc:0.82668
[9]	validation_0-auc:0.89123	validation_1-auc:0.82971
[10]	validation_0-auc:0.89315	validation_1-auc:0.83012
[11]	validation_0-auc:0.89677	validation_1-auc:0.83010
[12]	validation_0-auc:0.90156	validation_1-auc:0.83199
[13]	validation_0-auc:0.90564	validation_1-auc:0.83257
[14]	validation_0-auc:0.90784	validation_1-auc:0.83271
[15]	validation_0-auc:0.91109	validation_1-auc:0.83478
[16]	validation_0-auc:0.91412	validation_1-auc:0.83409
[17]	validation_0-auc:0.91735	validation_1-auc:0.83347
[18]	validation_0-auc:0.91851	validation_1-auc:0.83356
[19]	validation_0-auc:0.92158	validation_1-auc:0.83467
[20]	validation_0-auc:0.92393	validation_1-auc:0.83459
[21]	validation_0-auc:0.92581	validation_1-auc:0.83384
[22]	validation_0-auc:0.92763	validation_1-auc:0.83415
[23]	validation_0-auc:0.92926	validation_1-auc:0.83363
[24]	validation_0-auc:0.93066	validation_1-auc:0.83318
[25]	validation_0-auc:0.93172	validation_1-auc:0.83332
[26]	validation_0-auc:0.93339	validation_1-auc:0.83322
[27]	validation_0-auc:0.93494	validation_1-auc:0.83229
[28]	validation_0-auc:0.93620	validation_1-auc:0.83297
[29]	validation_0-auc:0.93692	validation_1-auc:0.83388
[30]	validation_0-auc:0.93816	validation_1-auc:0.83354
[31]	validation_0-auc:0.93889	validation_1-auc:0.83413
[32]	validation_0-auc:0.93978	validation_1-auc:0.83402
[33]	validation_0-auc:0.94013	validation_1-auc:0.83485
[34]	validation_0-auc:0.94093	validation_1-auc:0.83515
[35]	validation_0-auc:0.94136	validation_1-auc:0.83550
[36]	validation_0-auc:0.94203	validation_1-auc:0.83535
[37]	validation_0-auc:0.94249	validation_1-auc:0.83511
[38]	validation_0-auc:0.94314	validation_1-auc:0.83536
[39]	validation_0-auc:0.94405	validation_1-auc:0.83511
[40]	validation_0-auc:0.94435	validation_1-auc:0.83510
[41]	validation_0-auc:0.94528	validation_1-auc:0.83470
[42]	validation_0-auc:0.94559	validation_1-auc:0.83456
[43]	validation_0-auc:0.94591	validation_1-auc:0.83454
[44]	validation_0-auc:0.94636	validation_1-auc:0.83439
[45]	validation_0-auc:0.94666	validation_1-auc:0.83430
[46]	validation_0-auc:0.94722	validation_1-auc:0.83371
[47]	validation_0-auc:0.94756	validation_1-auc:0.83352
[48]	validation_0-auc:0.94771	validation_1-auc:0.83345
[49]	validation_0-auc:0.94795	validation_1-auc:0.83340
[50]	validation_0-auc:0.94818	validation_1-auc:0.83323
[51]	validation_0-auc:0.94855	validation_1-auc:0.83302
[52]	validation_0-auc:0.94889	validation_1-auc:0.83307
[53]	validation_0-auc:0.94926	validation_1-auc:0.83306
[54]	validation_0-auc:0.94968	validation_1-auc:0.83281
[55]	validation_0-auc:0.94992	validation_1-auc:0.83274
[56]	validation_0-auc:0.95021	validation_1-auc:0.83276
[57]	validation_0-auc:0.95069	validation_1-auc:0.83260
[58]	validation_0-auc:0.95155	validation_1-auc:0.83261
[59]	validation_0-auc:0.95168	validation_1-auc:0.83240
[60]	validation_0-auc:0.95223	validation_1-auc:0.83210
[61]	validation_0-auc:0.95239	validation_1-auc:0.83215
[62]	validation_0-auc:0.95251	validation_1-auc:0.83203
[63]	validation_0-auc:0.95257	validation_1-auc:0.83216
[64]	validation_0-auc:0.95319	validation_1-auc:0.83212
[65]	validation_0-auc:0.95335	validation_1-auc:0.83172
 88%|████████▊ | 44/50 [09:23<01:19, 13.19s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83142	validation_1-auc:0.80778
[1]	validation_0-auc:0.84101	validation_1-auc:0.81315
[2]	validation_0-auc:0.84889	validation_1-auc:0.81861
[3]	validation_0-auc:0.85351	validation_1-auc:0.81871
[4]	validation_0-auc:0.86664	validation_1-auc:0.82389
[5]	validation_0-auc:0.87030	validation_1-auc:0.82479
[6]	validation_0-auc:0.87835	validation_1-auc:0.82577
[7]	validation_0-auc:0.88311	validation_1-auc:0.82640
[8]	validation_0-auc:0.88843	validation_1-auc:0.82685
[9]	validation_0-auc:0.89770	validation_1-auc:0.82634
[10]	validation_0-auc:0.90053	validation_1-auc:0.82737
[11]	validation_0-auc:0.90381	validation_1-auc:0.82507
[12]	validation_0-auc:0.90821	validation_1-auc:0.82517
[13]	validation_0-auc:0.91158	validation_1-auc:0.82576
[14]	validation_0-auc:0.91325	validation_1-auc:0.82822
[15]	validation_0-auc:0.91692	validation_1-auc:0.82960
[16]	validation_0-auc:0.91869	validation_1-auc:0.82924
[17]	validation_0-auc:0.92063	validation_1-auc:0.82969
[18]	validation_0-auc:0.92264	validation_1-auc:0.82887
[19]	validation_0-auc:0.92465	validation_1-auc:0.82926
[20]	validation_0-auc:0.92570	validation_1-auc:0.82924
[21]	validation_0-auc:0.92732	validation_1-auc:0.83004
[22]	validation_0-auc:0.92882	validation_1-auc:0.82975
[23]	validation_0-auc:0.93059	validation_1-auc:0.82996
[24]	validation_0-auc:0.93186	validation_1-auc:0.83014
[25]	validation_0-auc:0.93265	validation_1-auc:0.83125
[26]	validation_0-auc:0.93466	validation_1-auc:0.83063
[27]	validation_0-auc:0.93640	validation_1-auc:0.82995
[28]	validation_0-auc:0.93739	validation_1-auc:0.83049
[29]	validation_0-auc:0.93841	validation_1-auc:0.83015
[30]	validation_0-auc:0.93959	validation_1-auc:0.82936
[31]	validation_0-auc:0.94057	validation_1-auc:0.82878
[32]	validation_0-auc:0.94108	validation_1-auc:0.82913
[33]	validation_0-auc:0.94140	validation_1-auc:0.82981
[34]	validation_0-auc:0.94207	validation_1-auc:0.82985
[35]	validation_0-auc:0.94268	validation_1-auc:0.83012
[36]	validation_0-auc:0.94315	validation_1-auc:0.83006
[37]	validation_0-auc:0.94355	validation_1-auc:0.83014
[38]	validation_0-auc:0.94517	validation_1-auc:0.82915
[39]	validation_0-auc:0.94582	validation_1-auc:0.82921
[40]	validation_0-auc:0.94609	validation_1-auc:0.82951
[41]	validation_0-auc:0.94635	validation_1-auc:0.82897
[42]	validation_0-auc:0.94673	validation_1-auc:0.82908
[43]	validation_0-auc:0.94736	validation_1-auc:0.82910
[44]	validation_0-auc:0.94756	validation_1-auc:0.82891
[45]	validation_0-auc:0.94798	validation_1-auc:0.82828
[46]	validation_0-auc:0.94838	validation_1-auc:0.82773
[47]	validation_0-auc:0.94867	validation_1-auc:0.82784
[48]	validation_0-auc:0.94903	validation_1-auc:0.82766
[49]	validation_0-auc:0.94926	validation_1-auc:0.82736
[50]	validation_0-auc:0.94950	validation_1-auc:0.82762
[51]	validation_0-auc:0.94965	validation_1-auc:0.82748
[52]	validation_0-auc:0.94967	validation_1-auc:0.82744
[53]	validation_0-auc:0.94997	validation_1-auc:0.82697
[54]	validation_0-auc:0.95012	validation_1-auc:0.82660
 88%|████████▊ | 44/50 [09:29<01:19, 13.19s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82830	validation_1-auc:0.80901
[1]	validation_0-auc:0.84558	validation_1-auc:0.82324
[2]	validation_0-auc:0.85536	validation_1-auc:0.83087
[3]	validation_0-auc:0.86048	validation_1-auc:0.82953
[4]	validation_0-auc:0.86519	validation_1-auc:0.83043
[5]	validation_0-auc:0.86970	validation_1-auc:0.82981
[6]	validation_0-auc:0.87397	validation_1-auc:0.83038
[7]	validation_0-auc:0.87732	validation_1-auc:0.82997
[8]	validation_0-auc:0.88160	validation_1-auc:0.83170
[9]	validation_0-auc:0.89023	validation_1-auc:0.83362
[10]	validation_0-auc:0.89274	validation_1-auc:0.83048
[11]	validation_0-auc:0.89627	validation_1-auc:0.82887
[12]	validation_0-auc:0.90299	validation_1-auc:0.83235
[13]	validation_0-auc:0.90683	validation_1-auc:0.83505
[14]	validation_0-auc:0.90956	validation_1-auc:0.83628
[15]	validation_0-auc:0.91262	validation_1-auc:0.83565
[16]	validation_0-auc:0.91473	validation_1-auc:0.83652
[17]	validation_0-auc:0.91741	validation_1-auc:0.83776
[18]	validation_0-auc:0.91881	validation_1-auc:0.83585
[19]	validation_0-auc:0.92104	validation_1-auc:0.83584
[20]	validation_0-auc:0.92277	validation_1-auc:0.83650
[21]	validation_0-auc:0.92391	validation_1-auc:0.83679
[22]	validation_0-auc:0.92577	validation_1-auc:0.83802
[23]	validation_0-auc:0.92718	validation_1-auc:0.83807
[24]	validation_0-auc:0.92813	validation_1-auc:0.83826
[25]	validation_0-auc:0.92897	validation_1-auc:0.83828
[26]	validation_0-auc:0.93047	validation_1-auc:0.83825
[27]	validation_0-auc:0.93135	validation_1-auc:0.83913
[28]	validation_0-auc:0.93243	validation_1-auc:0.83823
[29]	validation_0-auc:0.93393	validation_1-auc:0.83844
[30]	validation_0-auc:0.93534	validation_1-auc:0.83812
[31]	validation_0-auc:0.93606	validation_1-auc:0.83856
[32]	validation_0-auc:0.93637	validation_1-auc:0.83880
[33]	validation_0-auc:0.93711	validation_1-auc:0.83832
[34]	validation_0-auc:0.93804	validation_1-auc:0.83838
[35]	validation_0-auc:0.93846	validation_1-auc:0.83809
[36]	validation_0-auc:0.93910	validation_1-auc:0.83839
[37]	validation_0-auc:0.93949	validation_1-auc:0.83849
[38]	validation_0-auc:0.94023	validation_1-auc:0.83814
[39]	validation_0-auc:0.94097	validation_1-auc:0.83780
[40]	validation_0-auc:0.94137	validation_1-auc:0.83789
[41]	validation_0-auc:0.94167	validation_1-auc:0.83763
[42]	validation_0-auc:0.94282	validation_1-auc:0.83723
[43]	validation_0-auc:0.94376	validation_1-auc:0.83653
[44]	validation_0-auc:0.94441	validation_1-auc:0.83650
[45]	validation_0-auc:0.94490	validation_1-auc:0.83608
[46]	validation_0-auc:0.94518	validation_1-auc:0.83618
[47]	validation_0-auc:0.94580	validation_1-auc:0.83602
[48]	validation_0-auc:0.94608	validation_1-auc:0.83578
[49]	validation_0-auc:0.94651	validation_1-auc:0.83551
[50]	validation_0-auc:0.94683	validation_1-auc:0.83512
[51]	validation_0-auc:0.94768	validation_1-auc:0.83542
[52]	validation_0-auc:0.94833	validation_1-auc:0.83503
[53]	validation_0-auc:0.94847	validation_1-auc:0.83468
[54]	validation_0-auc:0.94878	validation_1-auc:0.83463
[55]	validation_0-auc:0.94906	validation_1-auc:0.83417
[56]	validation_0-auc:0.94940	validation_1-auc:0.83331
 90%|█████████ | 45/50 [09:35<01:13, 14.68s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82921	validation_1-auc:0.81429
[1]	validation_0-auc:0.83598	validation_1-auc:0.81439
[2]	validation_0-auc:0.84555	validation_1-auc:0.81967
[3]	validation_0-auc:0.84790	validation_1-auc:0.82007
[4]	validation_0-auc:0.85120	validation_1-auc:0.82216
[5]	validation_0-auc:0.85293	validation_1-auc:0.82355
[6]	validation_0-auc:0.85508	validation_1-auc:0.82350
[7]	validation_0-auc:0.85600	validation_1-auc:0.82315
[8]	validation_0-auc:0.85945	validation_1-auc:0.82643
[9]	validation_0-auc:0.86332	validation_1-auc:0.83151
[10]	validation_0-auc:0.86425	validation_1-auc:0.83213
[11]	validation_0-auc:0.86416	validation_1-auc:0.83127
[12]	validation_0-auc:0.86828	validation_1-auc:0.83490
[13]	validation_0-auc:0.87083	validation_1-auc:0.83637
[14]	validation_0-auc:0.87296	validation_1-auc:0.83860
[15]	validation_0-auc:0.87468	validation_1-auc:0.84041
[16]	validation_0-auc:0.87596	validation_1-auc:0.84016
[17]	validation_0-auc:0.87696	validation_1-auc:0.83942
[18]	validation_0-auc:0.87760	validation_1-auc:0.84011
[19]	validation_0-auc:0.87904	validation_1-auc:0.84019
[20]	validation_0-auc:0.87999	validation_1-auc:0.84059
[21]	validation_0-auc:0.88063	validation_1-auc:0.84087
[22]	validation_0-auc:0.88312	validation_1-auc:0.84144
[23]	validation_0-auc:0.88379	validation_1-auc:0.84160
[24]	validation_0-auc:0.88476	validation_1-auc:0.84162
[25]	validation_0-auc:0.88531	validation_1-auc:0.84179
[26]	validation_0-auc:0.88680	validation_1-auc:0.84290
[27]	validation_0-auc:0.88810	validation_1-auc:0.84308
[28]	validation_0-auc:0.88899	validation_1-auc:0.84307
[29]	validation_0-auc:0.89071	validation_1-auc:0.84303
[30]	validation_0-auc:0.89178	validation_1-auc:0.84345
[31]	validation_0-auc:0.89335	validation_1-auc:0.84391
[32]	validation_0-auc:0.89428	validation_1-auc:0.84450
[33]	validation_0-auc:0.89488	validation_1-auc:0.84502
[34]	validation_0-auc:0.89578	validation_1-auc:0.84509
[35]	validation_0-auc:0.89608	validation_1-auc:0.84473
[36]	validation_0-auc:0.89689	validation_1-auc:0.84444
[37]	validation_0-auc:0.89748	validation_1-auc:0.84459
[38]	validation_0-auc:0.89867	validation_1-auc:0.84403
[39]	validation_0-auc:0.89891	validation_1-auc:0.84412
[40]	validation_0-auc:0.89926	validation_1-auc:0.84411
[41]	validation_0-auc:0.90026	validation_1-auc:0.84428
[42]	validation_0-auc:0.90054	validation_1-auc:0.84466
[43]	validation_0-auc:0.90112	validation_1-auc:0.84459
[44]	validation_0-auc:0.90156	validation_1-auc:0.84466
[45]	validation_0-auc:0.90272	validation_1-auc:0.84486
[46]	validation_0-auc:0.90319	validation_1-auc:0.84477
[47]	validation_0-auc:0.90426	validation_1-auc:0.84488
[48]	validation_0-auc:0.90467	validation_1-auc:0.84490
[49]	validation_0-auc:0.90509	validation_1-auc:0.84477
[50]	validation_0-auc:0.90529	validation_1-auc:0.84476
[51]	validation_0-auc:0.90631	validation_1-auc:0.84469
[52]	validation_0-auc:0.90678	validation_1-auc:0.84493
[53]	validation_0-auc:0.90717	validation_1-auc:0.84505
[54]	validation_0-auc:0.90741	validation_1-auc:0.84523
[55]	validation_0-auc:0.90786	validation_1-auc:0.84505
[56]	validation_0-auc:0.90817	validation_1-auc:0.84513
[57]	validation_0-auc:0.90834	validation_1-auc:0.84513
[58]	validation_0-auc:0.90865	validation_1-auc:0.84495
[59]	validation_0-auc:0.90880	validation_1-auc:0.84490
[60]	validation_0-auc:0.90912	validation_1-auc:0.84512
[61]	validation_0-auc:0.90938	validation_1-auc:0.84511
[62]	validation_0-auc:0.90950	validation_1-auc:0.84508
[63]	validation_0-auc:0.90962	validation_1-auc:0.84504
[64]	validation_0-auc:0.91058	validation_1-auc:0.84537
[65]	validation_0-auc:0.91109	validation_1-auc:0.84495
[66]	validation_0-auc:0.91136	validation_1-auc:0.84491
[67]	validation_0-auc:0.91167	validation_1-auc:0.84490
[68]	validation_0-auc:0.91274	validation_1-auc:0.84469
[69]	validation_0-auc:0.91311	validation_1-auc:0.84458
[70]	validation_0-auc:0.91332	validation_1-auc:0.84457
[71]	validation_0-auc:0.91356	validation_1-auc:0.84454
[72]	validation_0-auc:0.91379	validation_1-auc:0.84458
[73]	validation_0-auc:0.91387	validation_1-auc:0.84454
[74]	validation_0-auc:0.91394	validation_1-auc:0.84458
[75]	validation_0-auc:0.91405	validation_1-auc:0.84452
[76]	validation_0-auc:0.91413	validation_1-auc:0.84444
[77]	validation_0-auc:0.91461	validation_1-auc:0.84428
[78]	validation_0-auc:0.91493	validation_1-auc:0.84407
[79]	validation_0-auc:0.91526	validation_1-auc:0.84381
[80]	validation_0-auc:0.91602	validation_1-auc:0.84388
[81]	validation_0-auc:0.91647	validation_1-auc:0.84361
[82]	validation_0-auc:0.91656	validation_1-auc:0.84369
[83]	validation_0-auc:0.91668	validation_1-auc:0.84357
[84]	validation_0-auc:0.91679	validation_1-auc:0.84385
[85]	validation_0-auc:0.91686	validation_1-auc:0.84375
[86]	validation_0-auc:0.91764	validation_1-auc:0.84332
[87]	validation_0-auc:0.91860	validation_1-auc:0.84328
[88]	validation_0-auc:0.91909	validation_1-auc:0.84324
[89]	validation_0-auc:0.91945	validation_1-auc:0.84318
[90]	validation_0-auc:0.91998	validation_1-auc:0.84291
[91]	validation_0-auc:0.92013	validation_1-auc:0.84292
[92]	validation_0-auc:0.92021	validation_1-auc:0.84296
[93]	validation_0-auc:0.92043	validation_1-auc:0.84286
[94]	validation_0-auc:0.92107	validation_1-auc:0.84267
 90%|█████████ | 45/50 [09:40<01:13, 14.68s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82600	validation_1-auc:0.80649
[1]	validation_0-auc:0.83406	validation_1-auc:0.81403
[2]	validation_0-auc:0.83792	validation_1-auc:0.81459
[3]	validation_0-auc:0.84390	validation_1-auc:0.81914
[4]	validation_0-auc:0.84891	validation_1-auc:0.82320
[5]	validation_0-auc:0.85001	validation_1-auc:0.82352
[6]	validation_0-auc:0.85363	validation_1-auc:0.82370
[7]	validation_0-auc:0.85605	validation_1-auc:0.82407
[8]	validation_0-auc:0.85773	validation_1-auc:0.82638
[9]	validation_0-auc:0.86262	validation_1-auc:0.82854
[10]	validation_0-auc:0.86571	validation_1-auc:0.82823
[11]	validation_0-auc:0.86676	validation_1-auc:0.82744
[12]	validation_0-auc:0.87076	validation_1-auc:0.82787
[13]	validation_0-auc:0.87381	validation_1-auc:0.82820
[14]	validation_0-auc:0.87470	validation_1-auc:0.82975
[15]	validation_0-auc:0.87636	validation_1-auc:0.82985
[16]	validation_0-auc:0.87857	validation_1-auc:0.83113
[17]	validation_0-auc:0.88039	validation_1-auc:0.83304
[18]	validation_0-auc:0.88120	validation_1-auc:0.83292
[19]	validation_0-auc:0.88325	validation_1-auc:0.83474
[20]	validation_0-auc:0.88425	validation_1-auc:0.83533
[21]	validation_0-auc:0.88584	validation_1-auc:0.83625
[22]	validation_0-auc:0.88817	validation_1-auc:0.83691
[23]	validation_0-auc:0.88947	validation_1-auc:0.83702
[24]	validation_0-auc:0.89057	validation_1-auc:0.83685
[25]	validation_0-auc:0.89076	validation_1-auc:0.83713
[26]	validation_0-auc:0.89202	validation_1-auc:0.83729
[27]	validation_0-auc:0.89318	validation_1-auc:0.83761
[28]	validation_0-auc:0.89409	validation_1-auc:0.83733
[29]	validation_0-auc:0.89534	validation_1-auc:0.83741
[30]	validation_0-auc:0.89609	validation_1-auc:0.83727
[31]	validation_0-auc:0.89702	validation_1-auc:0.83776
[32]	validation_0-auc:0.89801	validation_1-auc:0.83745
[33]	validation_0-auc:0.89872	validation_1-auc:0.83746
[34]	validation_0-auc:0.89935	validation_1-auc:0.83736
[35]	validation_0-auc:0.89978	validation_1-auc:0.83738
[36]	validation_0-auc:0.90108	validation_1-auc:0.83723
[37]	validation_0-auc:0.90153	validation_1-auc:0.83714
[38]	validation_0-auc:0.90219	validation_1-auc:0.83727
[39]	validation_0-auc:0.90264	validation_1-auc:0.83759
[40]	validation_0-auc:0.90329	validation_1-auc:0.83744
[41]	validation_0-auc:0.90383	validation_1-auc:0.83768
[42]	validation_0-auc:0.90421	validation_1-auc:0.83747
[43]	validation_0-auc:0.90471	validation_1-auc:0.83744
[44]	validation_0-auc:0.90502	validation_1-auc:0.83742
[45]	validation_0-auc:0.90622	validation_1-auc:0.83685
[46]	validation_0-auc:0.90654	validation_1-auc:0.83715
[47]	validation_0-auc:0.90726	validation_1-auc:0.83677
[48]	validation_0-auc:0.90795	validation_1-auc:0.83666
[49]	validation_0-auc:0.90812	validation_1-auc:0.83671
[50]	validation_0-auc:0.90863	validation_1-auc:0.83706
[51]	validation_0-auc:0.90918	validation_1-auc:0.83702
[52]	validation_0-auc:0.90970	validation_1-auc:0.83679
[53]	validation_0-auc:0.90981	validation_1-auc:0.83661
[54]	validation_0-auc:0.90994	validation_1-auc:0.83656
[55]	validation_0-auc:0.91017	validation_1-auc:0.83643
[56]	validation_0-auc:0.91036	validation_1-auc:0.83635
[57]	validation_0-auc:0.91047	validation_1-auc:0.83638
[58]	validation_0-auc:0.91067	validation_1-auc:0.83646
[59]	validation_0-auc:0.91090	validation_1-auc:0.83653
[60]	validation_0-auc:0.91152	validation_1-auc:0.83641
[61]	validation_0-auc:0.91215	validation_1-auc:0.83636
 90%|█████████ | 45/50 [09:44<01:13, 14.68s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82223	validation_1-auc:0.81064
[1]	validation_0-auc:0.82978	validation_1-auc:0.81478
[2]	validation_0-auc:0.83989	validation_1-auc:0.82557
[3]	validation_0-auc:0.84606	validation_1-auc:0.82968
[4]	validation_0-auc:0.85028	validation_1-auc:0.83009
[5]	validation_0-auc:0.85287	validation_1-auc:0.83252
[6]	validation_0-auc:0.85418	validation_1-auc:0.83234
[7]	validation_0-auc:0.85594	validation_1-auc:0.83344
[8]	validation_0-auc:0.85721	validation_1-auc:0.83373
[9]	validation_0-auc:0.85944	validation_1-auc:0.83556
[10]	validation_0-auc:0.85908	validation_1-auc:0.83406
[11]	validation_0-auc:0.85990	validation_1-auc:0.83204
[12]	validation_0-auc:0.86386	validation_1-auc:0.83442
[13]	validation_0-auc:0.86725	validation_1-auc:0.83680
[14]	validation_0-auc:0.86871	validation_1-auc:0.83904
[15]	validation_0-auc:0.87115	validation_1-auc:0.84035
[16]	validation_0-auc:0.87346	validation_1-auc:0.84170
[17]	validation_0-auc:0.87634	validation_1-auc:0.84221
[18]	validation_0-auc:0.87726	validation_1-auc:0.84112
[19]	validation_0-auc:0.87899	validation_1-auc:0.84273
[20]	validation_0-auc:0.88049	validation_1-auc:0.84313
[21]	validation_0-auc:0.88209	validation_1-auc:0.84362
[22]	validation_0-auc:0.88377	validation_1-auc:0.84417
[23]	validation_0-auc:0.88460	validation_1-auc:0.84332
[24]	validation_0-auc:0.88644	validation_1-auc:0.84351
[25]	validation_0-auc:0.88799	validation_1-auc:0.84390
[26]	validation_0-auc:0.89004	validation_1-auc:0.84327
[27]	validation_0-auc:0.89158	validation_1-auc:0.84329
[28]	validation_0-auc:0.89275	validation_1-auc:0.84298
[29]	validation_0-auc:0.89371	validation_1-auc:0.84344
[30]	validation_0-auc:0.89524	validation_1-auc:0.84344
[31]	validation_0-auc:0.89634	validation_1-auc:0.84298
[32]	validation_0-auc:0.89691	validation_1-auc:0.84304
[33]	validation_0-auc:0.89738	validation_1-auc:0.84343
[34]	validation_0-auc:0.89804	validation_1-auc:0.84342
[35]	validation_0-auc:0.89824	validation_1-auc:0.84339
[36]	validation_0-auc:0.89865	validation_1-auc:0.84372
[37]	validation_0-auc:0.89903	validation_1-auc:0.84366
[38]	validation_0-auc:0.89993	validation_1-auc:0.84353
[39]	validation_0-auc:0.90003	validation_1-auc:0.84381
[40]	validation_0-auc:0.90038	validation_1-auc:0.84393
[41]	validation_0-auc:0.90127	validation_1-auc:0.84379
[42]	validation_0-auc:0.90168	validation_1-auc:0.84398
[43]	validation_0-auc:0.90186	validation_1-auc:0.84388
[44]	validation_0-auc:0.90206	validation_1-auc:0.84391
[45]	validation_0-auc:0.90312	validation_1-auc:0.84424
[46]	validation_0-auc:0.90340	validation_1-auc:0.84417
[47]	validation_0-auc:0.90354	validation_1-auc:0.84405
[48]	validation_0-auc:0.90391	validation_1-auc:0.84385
[49]	validation_0-auc:0.90494	validation_1-auc:0.84408
[50]	validation_0-auc:0.90508	validation_1-auc:0.84422
[51]	validation_0-auc:0.90515	validation_1-auc:0.84431
[52]	validation_0-auc:0.90621	validation_1-auc:0.84376
[53]	validation_0-auc:0.90705	validation_1-auc:0.84353
[54]	validation_0-auc:0.90763	validation_1-auc:0.84336
[55]	validation_0-auc:0.90796	validation_1-auc:0.84322
[56]	validation_0-auc:0.90840	validation_1-auc:0.84331
[57]	validation_0-auc:0.90865	validation_1-auc:0.84325
[58]	validation_0-auc:0.90889	validation_1-auc:0.84321
[59]	validation_0-auc:0.90902	validation_1-auc:0.84313
[60]	validation_0-auc:0.90954	validation_1-auc:0.84304
[61]	validation_0-auc:0.91016	validation_1-auc:0.84265
[62]	validation_0-auc:0.91026	validation_1-auc:0.84265
[63]	validation_0-auc:0.91039	validation_1-auc:0.84284
[64]	validation_0-auc:0.91112	validation_1-auc:0.84286
[65]	validation_0-auc:0.91148	validation_1-auc:0.84274
[66]	validation_0-auc:0.91168	validation_1-auc:0.84268
[67]	validation_0-auc:0.91194	validation_1-auc:0.84266
[68]	validation_0-auc:0.91207	validation_1-auc:0.84268
[69]	validation_0-auc:0.91273	validation_1-auc:0.84287
[70]	validation_0-auc:0.91291	validation_1-auc:0.84281
[71]	validation_0-auc:0.91300	validation_1-auc:0.84273
[72]	validation_0-auc:0.91314	validation_1-auc:0.84259
[73]	validation_0-auc:0.91335	validation_1-auc:0.84235
[74]	validation_0-auc:0.91370	validation_1-auc:0.84211
[75]	validation_0-auc:0.91383	validation_1-auc:0.84221
[76]	validation_0-auc:0.91390	validation_1-auc:0.84211
[77]	validation_0-auc:0.91419	validation_1-auc:0.84173
[78]	validation_0-auc:0.91426	validation_1-auc:0.84171
[79]	validation_0-auc:0.91471	validation_1-auc:0.84168
[80]	validation_0-auc:0.91482	validation_1-auc:0.84171
 92%|█████████▏| 46/50 [09:48<00:56, 14.23s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.84008	validation_1-auc:0.81437
[1]	validation_0-auc:0.84598	validation_1-auc:0.81374
[2]	validation_0-auc:0.85198	validation_1-auc:0.81310
[3]	validation_0-auc:0.85584	validation_1-auc:0.81509
[4]	validation_0-auc:0.86369	validation_1-auc:0.81861
[5]	validation_0-auc:0.86751	validation_1-auc:0.81921
[6]	validation_0-auc:0.87070	validation_1-auc:0.81888
[7]	validation_0-auc:0.87498	validation_1-auc:0.82188
[8]	validation_0-auc:0.88065	validation_1-auc:0.82506
[9]	validation_0-auc:0.88810	validation_1-auc:0.82686
[10]	validation_0-auc:0.89038	validation_1-auc:0.82733
[11]	validation_0-auc:0.89539	validation_1-auc:0.82500
[12]	validation_0-auc:0.90276	validation_1-auc:0.82795
[13]	validation_0-auc:0.90739	validation_1-auc:0.82976
[14]	validation_0-auc:0.91015	validation_1-auc:0.83126
[15]	validation_0-auc:0.91293	validation_1-auc:0.83271
[16]	validation_0-auc:0.91690	validation_1-auc:0.83282
[17]	validation_0-auc:0.92094	validation_1-auc:0.83317
[18]	validation_0-auc:0.92242	validation_1-auc:0.83415
[19]	validation_0-auc:0.92575	validation_1-auc:0.83583
[20]	validation_0-auc:0.92848	validation_1-auc:0.83625
[21]	validation_0-auc:0.93093	validation_1-auc:0.83559
[22]	validation_0-auc:0.93534	validation_1-auc:0.83525
[23]	validation_0-auc:0.93721	validation_1-auc:0.83544
[24]	validation_0-auc:0.93881	validation_1-auc:0.83557
[25]	validation_0-auc:0.94028	validation_1-auc:0.83516
[26]	validation_0-auc:0.94211	validation_1-auc:0.83516
[27]	validation_0-auc:0.94497	validation_1-auc:0.83496
[28]	validation_0-auc:0.94678	validation_1-auc:0.83496
[29]	validation_0-auc:0.94890	validation_1-auc:0.83490
[30]	validation_0-auc:0.95020	validation_1-auc:0.83514
[31]	validation_0-auc:0.95191	validation_1-auc:0.83425
[32]	validation_0-auc:0.95366	validation_1-auc:0.83359
[33]	validation_0-auc:0.95415	validation_1-auc:0.83451
[34]	validation_0-auc:0.95519	validation_1-auc:0.83473
[35]	validation_0-auc:0.95603	validation_1-auc:0.83457
[36]	validation_0-auc:0.95692	validation_1-auc:0.83481
[37]	validation_0-auc:0.95811	validation_1-auc:0.83484
[38]	validation_0-auc:0.95845	validation_1-auc:0.83479
[39]	validation_0-auc:0.95889	validation_1-auc:0.83463
[40]	validation_0-auc:0.95913	validation_1-auc:0.83495
[41]	validation_0-auc:0.95989	validation_1-auc:0.83503
[42]	validation_0-auc:0.96027	validation_1-auc:0.83503
[43]	validation_0-auc:0.96080	validation_1-auc:0.83498
[44]	validation_0-auc:0.96105	validation_1-auc:0.83501
[45]	validation_0-auc:0.96120	validation_1-auc:0.83536
[46]	validation_0-auc:0.96132	validation_1-auc:0.83557
[47]	validation_0-auc:0.96167	validation_1-auc:0.83517
[48]	validation_0-auc:0.96186	validation_1-auc:0.83514
[49]	validation_0-auc:0.96234	validation_1-auc:0.83531
 92%|█████████▏| 46/50 [09:52<00:56, 14.23s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83319	validation_1-auc:0.80736
[1]	validation_0-auc:0.84174	validation_1-auc:0.81219
[2]	validation_0-auc:0.84774	validation_1-auc:0.81414
[3]	validation_0-auc:0.85624	validation_1-auc:0.81662
[4]	validation_0-auc:0.86499	validation_1-auc:0.82102
[5]	validation_0-auc:0.86856	validation_1-auc:0.82175
[6]	validation_0-auc:0.87330	validation_1-auc:0.82153
[7]	validation_0-auc:0.87951	validation_1-auc:0.82356
[8]	validation_0-auc:0.88413	validation_1-auc:0.82424
[9]	validation_0-auc:0.89064	validation_1-auc:0.82618
[10]	validation_0-auc:0.89603	validation_1-auc:0.82513
[11]	validation_0-auc:0.89923	validation_1-auc:0.82355
[12]	validation_0-auc:0.90716	validation_1-auc:0.82290
[13]	validation_0-auc:0.91153	validation_1-auc:0.82423
[14]	validation_0-auc:0.91395	validation_1-auc:0.82605
[15]	validation_0-auc:0.91739	validation_1-auc:0.82633
[16]	validation_0-auc:0.92086	validation_1-auc:0.82651
[17]	validation_0-auc:0.92297	validation_1-auc:0.82688
[18]	validation_0-auc:0.92460	validation_1-auc:0.82563
[19]	validation_0-auc:0.92828	validation_1-auc:0.82650
[20]	validation_0-auc:0.93073	validation_1-auc:0.82679
[21]	validation_0-auc:0.93312	validation_1-auc:0.82708
[22]	validation_0-auc:0.93631	validation_1-auc:0.82760
[23]	validation_0-auc:0.93789	validation_1-auc:0.82819
[24]	validation_0-auc:0.94014	validation_1-auc:0.82846
[25]	validation_0-auc:0.94130	validation_1-auc:0.82912
[26]	validation_0-auc:0.94281	validation_1-auc:0.82877
[27]	validation_0-auc:0.94587	validation_1-auc:0.82853
[28]	validation_0-auc:0.94805	validation_1-auc:0.82811
[29]	validation_0-auc:0.94989	validation_1-auc:0.82833
[30]	validation_0-auc:0.95128	validation_1-auc:0.82687
[31]	validation_0-auc:0.95280	validation_1-auc:0.82790
[32]	validation_0-auc:0.95436	validation_1-auc:0.82720
[33]	validation_0-auc:0.95516	validation_1-auc:0.82729
[34]	validation_0-auc:0.95596	validation_1-auc:0.82705
[35]	validation_0-auc:0.95659	validation_1-auc:0.82745
[36]	validation_0-auc:0.95720	validation_1-auc:0.82759
[37]	validation_0-auc:0.95751	validation_1-auc:0.82752
[38]	validation_0-auc:0.95844	validation_1-auc:0.82721
[39]	validation_0-auc:0.95854	validation_1-auc:0.82761
[40]	validation_0-auc:0.95914	validation_1-auc:0.82738
[41]	validation_0-auc:0.95966	validation_1-auc:0.82700
[42]	validation_0-auc:0.96023	validation_1-auc:0.82705
[43]	validation_0-auc:0.96130	validation_1-auc:0.82687
[44]	validation_0-auc:0.96210	validation_1-auc:0.82643
[45]	validation_0-auc:0.96245	validation_1-auc:0.82670
[46]	validation_0-auc:0.96280	validation_1-auc:0.82723
[47]	validation_0-auc:0.96330	validation_1-auc:0.82756
[48]	validation_0-auc:0.96345	validation_1-auc:0.82732
[49]	validation_0-auc:0.96383	validation_1-auc:0.82700
[50]	validation_0-auc:0.96389	validation_1-auc:0.82682
[51]	validation_0-auc:0.96404	validation_1-auc:0.82665
[52]	validation_0-auc:0.96423	validation_1-auc:0.82667
[53]	validation_0-auc:0.96490	validation_1-auc:0.82637
[54]	validation_0-auc:0.96495	validation_1-auc:0.82645
[55]	validation_0-auc:0.96497	validation_1-auc:0.82648
 92%|█████████▏| 46/50 [09:57<00:56, 14.23s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83266	validation_1-auc:0.80866
[1]	validation_0-auc:0.84472	validation_1-auc:0.81126
[2]	validation_0-auc:0.85186	validation_1-auc:0.81948
[3]	validation_0-auc:0.85871	validation_1-auc:0.82485
[4]	validation_0-auc:0.86740	validation_1-auc:0.82930
[5]	validation_0-auc:0.87140	validation_1-auc:0.82866
[6]	validation_0-auc:0.87552	validation_1-auc:0.82877
[7]	validation_0-auc:0.87823	validation_1-auc:0.82988
[8]	validation_0-auc:0.88060	validation_1-auc:0.83112
[9]	validation_0-auc:0.88779	validation_1-auc:0.83176
[10]	validation_0-auc:0.89059	validation_1-auc:0.83035
[11]	validation_0-auc:0.89097	validation_1-auc:0.82881
[12]	validation_0-auc:0.90044	validation_1-auc:0.83032
[13]	validation_0-auc:0.90619	validation_1-auc:0.83291
[14]	validation_0-auc:0.90865	validation_1-auc:0.83455
[15]	validation_0-auc:0.91352	validation_1-auc:0.83628
[16]	validation_0-auc:0.91656	validation_1-auc:0.83737
[17]	validation_0-auc:0.92098	validation_1-auc:0.83700
[18]	validation_0-auc:0.92245	validation_1-auc:0.83467
[19]	validation_0-auc:0.92782	validation_1-auc:0.83613
[20]	validation_0-auc:0.93114	validation_1-auc:0.83587
[21]	validation_0-auc:0.93316	validation_1-auc:0.83552
[22]	validation_0-auc:0.93487	validation_1-auc:0.83670
[23]	validation_0-auc:0.93737	validation_1-auc:0.83605
[24]	validation_0-auc:0.93900	validation_1-auc:0.83573
[25]	validation_0-auc:0.93994	validation_1-auc:0.83626
[26]	validation_0-auc:0.94240	validation_1-auc:0.83554
[27]	validation_0-auc:0.94436	validation_1-auc:0.83608
[28]	validation_0-auc:0.94614	validation_1-auc:0.83548
[29]	validation_0-auc:0.94747	validation_1-auc:0.83603
[30]	validation_0-auc:0.94900	validation_1-auc:0.83561
[31]	validation_0-auc:0.95118	validation_1-auc:0.83619
[32]	validation_0-auc:0.95230	validation_1-auc:0.83594
[33]	validation_0-auc:0.95291	validation_1-auc:0.83551
[34]	validation_0-auc:0.95370	validation_1-auc:0.83562
[35]	validation_0-auc:0.95429	validation_1-auc:0.83512
[36]	validation_0-auc:0.95499	validation_1-auc:0.83552
[37]	validation_0-auc:0.95605	validation_1-auc:0.83571
[38]	validation_0-auc:0.95698	validation_1-auc:0.83613
[39]	validation_0-auc:0.95721	validation_1-auc:0.83623
[40]	validation_0-auc:0.95774	validation_1-auc:0.83556
[41]	validation_0-auc:0.95851	validation_1-auc:0.83559
[42]	validation_0-auc:0.95909	validation_1-auc:0.83578
[43]	validation_0-auc:0.95941	validation_1-auc:0.83596
[44]	validation_0-auc:0.95962	validation_1-auc:0.83639
[45]	validation_0-auc:0.96003	validation_1-auc:0.83603
 94%|█████████▍| 47/50 [10:00<00:40, 13.62s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83255	validation_1-auc:0.81346
[1]	validation_0-auc:0.83830	validation_1-auc:0.81344
[2]	validation_0-auc:0.84654	validation_1-auc:0.81593
[3]	validation_0-auc:0.85151	validation_1-auc:0.81704
[4]	validation_0-auc:0.85910	validation_1-auc:0.82016
[5]	validation_0-auc:0.86067	validation_1-auc:0.82209
[6]	validation_0-auc:0.86530	validation_1-auc:0.82265
[7]	validation_0-auc:0.86830	validation_1-auc:0.82241
[8]	validation_0-auc:0.86981	validation_1-auc:0.82189
[9]	validation_0-auc:0.87914	validation_1-auc:0.82537
[10]	validation_0-auc:0.88130	validation_1-auc:0.82638
[11]	validation_0-auc:0.88316	validation_1-auc:0.82612
[12]	validation_0-auc:0.88832	validation_1-auc:0.83043
[13]	validation_0-auc:0.89159	validation_1-auc:0.83215
[14]	validation_0-auc:0.89428	validation_1-auc:0.83387
[15]	validation_0-auc:0.89611	validation_1-auc:0.83426
[16]	validation_0-auc:0.89831	validation_1-auc:0.83393
[17]	validation_0-auc:0.89989	validation_1-auc:0.83459
[18]	validation_0-auc:0.90089	validation_1-auc:0.83480
[19]	validation_0-auc:0.90367	validation_1-auc:0.83556
[20]	validation_0-auc:0.90539	validation_1-auc:0.83574
[21]	validation_0-auc:0.90640	validation_1-auc:0.83619
[22]	validation_0-auc:0.90844	validation_1-auc:0.83629
[23]	validation_0-auc:0.91051	validation_1-auc:0.83642
[24]	validation_0-auc:0.91229	validation_1-auc:0.83664
[25]	validation_0-auc:0.91284	validation_1-auc:0.83741
[26]	validation_0-auc:0.91471	validation_1-auc:0.83747
[27]	validation_0-auc:0.91610	validation_1-auc:0.83719
[28]	validation_0-auc:0.91742	validation_1-auc:0.83667
[29]	validation_0-auc:0.91861	validation_1-auc:0.83617
[30]	validation_0-auc:0.92066	validation_1-auc:0.83605
[31]	validation_0-auc:0.92186	validation_1-auc:0.83603
[32]	validation_0-auc:0.92303	validation_1-auc:0.83698
[33]	validation_0-auc:0.92395	validation_1-auc:0.83706
[34]	validation_0-auc:0.92478	validation_1-auc:0.83707
[35]	validation_0-auc:0.92561	validation_1-auc:0.83670
[36]	validation_0-auc:0.92659	validation_1-auc:0.83616
[37]	validation_0-auc:0.92736	validation_1-auc:0.83644
[38]	validation_0-auc:0.92796	validation_1-auc:0.83657
[39]	validation_0-auc:0.92845	validation_1-auc:0.83714
[40]	validation_0-auc:0.92892	validation_1-auc:0.83701
[41]	validation_0-auc:0.92994	validation_1-auc:0.83705
[42]	validation_0-auc:0.93051	validation_1-auc:0.83756
[43]	validation_0-auc:0.93080	validation_1-auc:0.83752
[44]	validation_0-auc:0.93133	validation_1-auc:0.83775
[45]	validation_0-auc:0.93179	validation_1-auc:0.83777
[46]	validation_0-auc:0.93186	validation_1-auc:0.83806
[47]	validation_0-auc:0.93250	validation_1-auc:0.83871
[48]	validation_0-auc:0.93279	validation_1-auc:0.83891
[49]	validation_0-auc:0.93332	validation_1-auc:0.83892
[50]	validation_0-auc:0.93375	validation_1-auc:0.83896
[51]	validation_0-auc:0.93406	validation_1-auc:0.83896
[52]	validation_0-auc:0.93471	validation_1-auc:0.83910
[53]	validation_0-auc:0.93493	validation_1-auc:0.83901
[54]	validation_0-auc:0.93537	validation_1-auc:0.83908
[55]	validation_0-auc:0.93639	validation_1-auc:0.83885
[56]	validation_0-auc:0.93675	validation_1-auc:0.83901
[57]	validation_0-auc:0.93732	validation_1-auc:0.83859
[58]	validation_0-auc:0.93788	validation_1-auc:0.83843
[59]	validation_0-auc:0.93846	validation_1-auc:0.83817
[60]	validation_0-auc:0.93862	validation_1-auc:0.83829
[61]	validation_0-auc:0.93889	validation_1-auc:0.83836
[62]	validation_0-auc:0.93937	validation_1-auc:0.83823
[63]	validation_0-auc:0.93965	validation_1-auc:0.83818
[64]	validation_0-auc:0.94013	validation_1-auc:0.83799
[65]	validation_0-auc:0.94052	validation_1-auc:0.83811
[66]	validation_0-auc:0.94076	validation_1-auc:0.83812
[67]	validation_0-auc:0.94148	validation_1-auc:0.83794
[68]	validation_0-auc:0.94161	validation_1-auc:0.83778
[69]	validation_0-auc:0.94182	validation_1-auc:0.83792
[70]	validation_0-auc:0.94212	validation_1-auc:0.83772
[71]	validation_0-auc:0.94245	validation_1-auc:0.83741
[72]	validation_0-auc:0.94273	validation_1-auc:0.83721
[73]	validation_0-auc:0.94294	validation_1-auc:0.83711
[74]	validation_0-auc:0.94305	validation_1-auc:0.83725
[75]	validation_0-auc:0.94338	validation_1-auc:0.83728
[76]	validation_0-auc:0.94348	validation_1-auc:0.83712
[77]	validation_0-auc:0.94357	validation_1-auc:0.83699
[78]	validation_0-auc:0.94376	validation_1-auc:0.83714
[79]	validation_0-auc:0.94419	validation_1-auc:0.83679
[80]	validation_0-auc:0.94447	validation_1-auc:0.83666
[81]	validation_0-auc:0.94457	validation_1-auc:0.83652
 94%|█████████▍| 47/50 [10:08<00:40, 13.62s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83097	validation_1-auc:0.80728
[1]	validation_0-auc:0.83633	validation_1-auc:0.81106
[2]	validation_0-auc:0.84271	validation_1-auc:0.81612
[3]	validation_0-auc:0.84614	validation_1-auc:0.81861
[4]	validation_0-auc:0.85681	validation_1-auc:0.82114
[5]	validation_0-auc:0.85855	validation_1-auc:0.82122
[6]	validation_0-auc:0.86482	validation_1-auc:0.82320
[7]	validation_0-auc:0.87071	validation_1-auc:0.82413
[8]	validation_0-auc:0.87338	validation_1-auc:0.82507
[9]	validation_0-auc:0.88019	validation_1-auc:0.82587
[10]	validation_0-auc:0.88291	validation_1-auc:0.82725
[11]	validation_0-auc:0.88565	validation_1-auc:0.82625
[12]	validation_0-auc:0.89093	validation_1-auc:0.82758
[13]	validation_0-auc:0.89390	validation_1-auc:0.82773
[14]	validation_0-auc:0.89605	validation_1-auc:0.82802
[15]	validation_0-auc:0.89826	validation_1-auc:0.82852
[16]	validation_0-auc:0.90003	validation_1-auc:0.82956
[17]	validation_0-auc:0.90254	validation_1-auc:0.83001
[18]	validation_0-auc:0.90393	validation_1-auc:0.82966
[19]	validation_0-auc:0.90577	validation_1-auc:0.82962
[20]	validation_0-auc:0.90756	validation_1-auc:0.82998
[21]	validation_0-auc:0.90815	validation_1-auc:0.83093
[22]	validation_0-auc:0.90963	validation_1-auc:0.83156
[23]	validation_0-auc:0.91143	validation_1-auc:0.83252
[24]	validation_0-auc:0.91221	validation_1-auc:0.83257
[25]	validation_0-auc:0.91323	validation_1-auc:0.83318
[26]	validation_0-auc:0.91528	validation_1-auc:0.83271
[27]	validation_0-auc:0.91673	validation_1-auc:0.83192
[28]	validation_0-auc:0.91771	validation_1-auc:0.83175
[29]	validation_0-auc:0.91880	validation_1-auc:0.83142
[30]	validation_0-auc:0.92037	validation_1-auc:0.83045
[31]	validation_0-auc:0.92140	validation_1-auc:0.83119
[32]	validation_0-auc:0.92254	validation_1-auc:0.83084
[33]	validation_0-auc:0.92306	validation_1-auc:0.83093
[34]	validation_0-auc:0.92388	validation_1-auc:0.83124
[35]	validation_0-auc:0.92463	validation_1-auc:0.83090
[36]	validation_0-auc:0.92531	validation_1-auc:0.83133
[37]	validation_0-auc:0.92611	validation_1-auc:0.83093
[38]	validation_0-auc:0.92676	validation_1-auc:0.83114
[39]	validation_0-auc:0.92703	validation_1-auc:0.83094
[40]	validation_0-auc:0.92733	validation_1-auc:0.83074
[41]	validation_0-auc:0.92836	validation_1-auc:0.83028
[42]	validation_0-auc:0.92932	validation_1-auc:0.82978
[43]	validation_0-auc:0.92962	validation_1-auc:0.83002
[44]	validation_0-auc:0.93002	validation_1-auc:0.83017
[45]	validation_0-auc:0.93069	validation_1-auc:0.83020
[46]	validation_0-auc:0.93100	validation_1-auc:0.83016
[47]	validation_0-auc:0.93175	validation_1-auc:0.83052
[48]	validation_0-auc:0.93206	validation_1-auc:0.83069
[49]	validation_0-auc:0.93255	validation_1-auc:0.83094
[50]	validation_0-auc:0.93308	validation_1-auc:0.83105
[51]	validation_0-auc:0.93364	validation_1-auc:0.83096
[52]	validation_0-auc:0.93411	validation_1-auc:0.83071
[53]	validation_0-auc:0.93449	validation_1-auc:0.83091
[54]	validation_0-auc:0.93514	validation_1-auc:0.83063
 94%|█████████▍| 47/50 [10:13<00:40, 13.62s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82730	validation_1-auc:0.80882
[1]	validation_0-auc:0.84391	validation_1-auc:0.82381
[2]	validation_0-auc:0.84797	validation_1-auc:0.82504
[3]	validation_0-auc:0.85229	validation_1-auc:0.82679
[4]	validation_0-auc:0.86236	validation_1-auc:0.82797
[5]	validation_0-auc:0.86486	validation_1-auc:0.82783
[6]	validation_0-auc:0.86760	validation_1-auc:0.83036
[7]	validation_0-auc:0.87074	validation_1-auc:0.83068
[8]	validation_0-auc:0.87245	validation_1-auc:0.83219
[9]	validation_0-auc:0.87913	validation_1-auc:0.83318
[10]	validation_0-auc:0.88034	validation_1-auc:0.83145
[11]	validation_0-auc:0.88050	validation_1-auc:0.82837
[12]	validation_0-auc:0.88602	validation_1-auc:0.83022
[13]	validation_0-auc:0.88972	validation_1-auc:0.83164
[14]	validation_0-auc:0.89188	validation_1-auc:0.83396
[15]	validation_0-auc:0.89390	validation_1-auc:0.83473
[16]	validation_0-auc:0.89751	validation_1-auc:0.83631
[17]	validation_0-auc:0.89977	validation_1-auc:0.83651
[18]	validation_0-auc:0.90111	validation_1-auc:0.83522
[19]	validation_0-auc:0.90348	validation_1-auc:0.83524
[20]	validation_0-auc:0.90537	validation_1-auc:0.83496
[21]	validation_0-auc:0.90674	validation_1-auc:0.83558
[22]	validation_0-auc:0.90827	validation_1-auc:0.83744
[23]	validation_0-auc:0.90952	validation_1-auc:0.83689
[24]	validation_0-auc:0.91107	validation_1-auc:0.83746
[25]	validation_0-auc:0.91182	validation_1-auc:0.83761
[26]	validation_0-auc:0.91413	validation_1-auc:0.83756
[27]	validation_0-auc:0.91561	validation_1-auc:0.83723
[28]	validation_0-auc:0.91663	validation_1-auc:0.83739
[29]	validation_0-auc:0.91773	validation_1-auc:0.83814
[30]	validation_0-auc:0.91895	validation_1-auc:0.83773
[31]	validation_0-auc:0.91984	validation_1-auc:0.83787
[32]	validation_0-auc:0.92057	validation_1-auc:0.83795
[33]	validation_0-auc:0.92089	validation_1-auc:0.83727
[34]	validation_0-auc:0.92184	validation_1-auc:0.83726
[35]	validation_0-auc:0.92272	validation_1-auc:0.83685
[36]	validation_0-auc:0.92360	validation_1-auc:0.83712
[37]	validation_0-auc:0.92436	validation_1-auc:0.83708
[38]	validation_0-auc:0.92487	validation_1-auc:0.83714
[39]	validation_0-auc:0.92532	validation_1-auc:0.83699
[40]	validation_0-auc:0.92568	validation_1-auc:0.83704
[41]	validation_0-auc:0.92681	validation_1-auc:0.83693
[42]	validation_0-auc:0.92758	validation_1-auc:0.83674
[43]	validation_0-auc:0.92815	validation_1-auc:0.83716
[44]	validation_0-auc:0.92859	validation_1-auc:0.83713
[45]	validation_0-auc:0.92916	validation_1-auc:0.83694
[46]	validation_0-auc:0.92956	validation_1-auc:0.83680
[47]	validation_0-auc:0.93006	validation_1-auc:0.83684
[48]	validation_0-auc:0.93070	validation_1-auc:0.83711
[49]	validation_0-auc:0.93107	validation_1-auc:0.83723
[50]	validation_0-auc:0.93149	validation_1-auc:0.83684
[51]	validation_0-auc:0.93187	validation_1-auc:0.83678
[52]	validation_0-auc:0.93203	validation_1-auc:0.83646
[53]	validation_0-auc:0.93260	validation_1-auc:0.83652
[54]	validation_0-auc:0.93290	validation_1-auc:0.83615
[55]	validation_0-auc:0.93354	validation_1-auc:0.83623
[56]	validation_0-auc:0.93401	validation_1-auc:0.83607
[57]	validation_0-auc:0.93481	validation_1-auc:0.83607
[58]	validation_0-auc:0.93539	validation_1-auc:0.83575
 96%|█████████▌| 48/50 [10:19<00:30, 15.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82709	validation_1-auc:0.81284
[1]	validation_0-auc:0.83205	validation_1-auc:0.81380
[2]	validation_0-auc:0.84250	validation_1-auc:0.82029
[3]	validation_0-auc:0.84513	validation_1-auc:0.82117
[4]	validation_0-auc:0.84614	validation_1-auc:0.81981
[5]	validation_0-auc:0.84827	validation_1-auc:0.82287
[6]	validation_0-auc:0.84975	validation_1-auc:0.82286
[7]	validation_0-auc:0.85056	validation_1-auc:0.82272
[8]	validation_0-auc:0.85456	validation_1-auc:0.82626
[9]	validation_0-auc:0.85819	validation_1-auc:0.83074
[10]	validation_0-auc:0.85775	validation_1-auc:0.83163
[11]	validation_0-auc:0.85731	validation_1-auc:0.83078
[12]	validation_0-auc:0.86074	validation_1-auc:0.83370
[13]	validation_0-auc:0.86364	validation_1-auc:0.83598
[14]	validation_0-auc:0.86547	validation_1-auc:0.83841
[15]	validation_0-auc:0.86662	validation_1-auc:0.83916
[16]	validation_0-auc:0.86796	validation_1-auc:0.83911
[17]	validation_0-auc:0.86936	validation_1-auc:0.83888
[18]	validation_0-auc:0.87000	validation_1-auc:0.83936
[19]	validation_0-auc:0.87089	validation_1-auc:0.83961
[20]	validation_0-auc:0.87276	validation_1-auc:0.84037
[21]	validation_0-auc:0.87339	validation_1-auc:0.84048
[22]	validation_0-auc:0.87471	validation_1-auc:0.84087
[23]	validation_0-auc:0.87568	validation_1-auc:0.84140
[24]	validation_0-auc:0.87648	validation_1-auc:0.84134
[25]	validation_0-auc:0.87711	validation_1-auc:0.84148
[26]	validation_0-auc:0.87839	validation_1-auc:0.84281
[27]	validation_0-auc:0.87990	validation_1-auc:0.84257
[28]	validation_0-auc:0.88071	validation_1-auc:0.84219
[29]	validation_0-auc:0.88160	validation_1-auc:0.84277
[30]	validation_0-auc:0.88243	validation_1-auc:0.84305
[31]	validation_0-auc:0.88378	validation_1-auc:0.84396
[32]	validation_0-auc:0.88480	validation_1-auc:0.84434
[33]	validation_0-auc:0.88535	validation_1-auc:0.84478
[34]	validation_0-auc:0.88580	validation_1-auc:0.84466
[35]	validation_0-auc:0.88691	validation_1-auc:0.84452
[36]	validation_0-auc:0.88740	validation_1-auc:0.84426
[37]	validation_0-auc:0.88768	validation_1-auc:0.84474
[38]	validation_0-auc:0.88795	validation_1-auc:0.84501
[39]	validation_0-auc:0.88804	validation_1-auc:0.84508
[40]	validation_0-auc:0.88870	validation_1-auc:0.84479
[41]	validation_0-auc:0.88962	validation_1-auc:0.84459
[42]	validation_0-auc:0.88990	validation_1-auc:0.84427
[43]	validation_0-auc:0.89046	validation_1-auc:0.84396
[44]	validation_0-auc:0.89131	validation_1-auc:0.84395
[45]	validation_0-auc:0.89155	validation_1-auc:0.84378
[46]	validation_0-auc:0.89183	validation_1-auc:0.84389
[47]	validation_0-auc:0.89299	validation_1-auc:0.84425
[48]	validation_0-auc:0.89330	validation_1-auc:0.84428
[49]	validation_0-auc:0.89353	validation_1-auc:0.84396
[50]	validation_0-auc:0.89398	validation_1-auc:0.84392
[51]	validation_0-auc:0.89419	validation_1-auc:0.84386
[52]	validation_0-auc:0.89430	validation_1-auc:0.84387
[53]	validation_0-auc:0.89475	validation_1-auc:0.84376
[54]	validation_0-auc:0.89504	validation_1-auc:0.84394
[55]	validation_0-auc:0.89582	validation_1-auc:0.84375
[56]	validation_0-auc:0.89626	validation_1-auc:0.84402
[57]	validation_0-auc:0.89656	validation_1-auc:0.84399
[58]	validation_0-auc:0.89678	validation_1-auc:0.84391
[59]	validation_0-auc:0.89682	validation_1-auc:0.84390
[60]	validation_0-auc:0.89694	validation_1-auc:0.84394
[61]	validation_0-auc:0.89822	validation_1-auc:0.84383
[62]	validation_0-auc:0.89847	validation_1-auc:0.84364
[63]	validation_0-auc:0.89853	validation_1-auc:0.84367
[64]	validation_0-auc:0.89954	validation_1-auc:0.84342
[65]	validation_0-auc:0.89972	validation_1-auc:0.84343
[66]	validation_0-auc:0.90037	validation_1-auc:0.84329
[67]	validation_0-auc:0.90081	validation_1-auc:0.84371
[68]	validation_0-auc:0.90209	validation_1-auc:0.84380
 96%|█████████▌| 48/50 [10:22<00:30, 15.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82368	validation_1-auc:0.80750
[1]	validation_0-auc:0.83110	validation_1-auc:0.81431
[2]	validation_0-auc:0.83606	validation_1-auc:0.81761
[3]	validation_0-auc:0.83862	validation_1-auc:0.82004
[4]	validation_0-auc:0.84556	validation_1-auc:0.82398
[5]	validation_0-auc:0.84767	validation_1-auc:0.82454
[6]	validation_0-auc:0.85094	validation_1-auc:0.82612
[7]	validation_0-auc:0.85224	validation_1-auc:0.82552
[8]	validation_0-auc:0.85450	validation_1-auc:0.82757
[9]	validation_0-auc:0.85803	validation_1-auc:0.82848
[10]	validation_0-auc:0.85810	validation_1-auc:0.82739
[11]	validation_0-auc:0.85915	validation_1-auc:0.82661
[12]	validation_0-auc:0.86351	validation_1-auc:0.82919
[13]	validation_0-auc:0.86642	validation_1-auc:0.83175
[14]	validation_0-auc:0.86710	validation_1-auc:0.83311
[15]	validation_0-auc:0.86923	validation_1-auc:0.83275
[16]	validation_0-auc:0.87053	validation_1-auc:0.83434
[17]	validation_0-auc:0.87216	validation_1-auc:0.83520
[18]	validation_0-auc:0.87289	validation_1-auc:0.83512
[19]	validation_0-auc:0.87533	validation_1-auc:0.83629
[20]	validation_0-auc:0.87660	validation_1-auc:0.83711
[21]	validation_0-auc:0.87684	validation_1-auc:0.83686
[22]	validation_0-auc:0.87828	validation_1-auc:0.83633
[23]	validation_0-auc:0.87973	validation_1-auc:0.83616
[24]	validation_0-auc:0.88045	validation_1-auc:0.83697
[25]	validation_0-auc:0.88104	validation_1-auc:0.83756
[26]	validation_0-auc:0.88228	validation_1-auc:0.83737
[27]	validation_0-auc:0.88349	validation_1-auc:0.83707
[28]	validation_0-auc:0.88428	validation_1-auc:0.83705
[29]	validation_0-auc:0.88538	validation_1-auc:0.83720
[30]	validation_0-auc:0.88602	validation_1-auc:0.83655
[31]	validation_0-auc:0.88683	validation_1-auc:0.83704
[32]	validation_0-auc:0.88757	validation_1-auc:0.83704
[33]	validation_0-auc:0.88782	validation_1-auc:0.83725
[34]	validation_0-auc:0.88816	validation_1-auc:0.83735
[35]	validation_0-auc:0.88885	validation_1-auc:0.83752
[36]	validation_0-auc:0.88925	validation_1-auc:0.83768
[37]	validation_0-auc:0.89027	validation_1-auc:0.83760
[38]	validation_0-auc:0.89067	validation_1-auc:0.83769
[39]	validation_0-auc:0.89090	validation_1-auc:0.83773
[40]	validation_0-auc:0.89140	validation_1-auc:0.83767
[41]	validation_0-auc:0.89167	validation_1-auc:0.83766
[42]	validation_0-auc:0.89205	validation_1-auc:0.83734
[43]	validation_0-auc:0.89331	validation_1-auc:0.83721
[44]	validation_0-auc:0.89406	validation_1-auc:0.83687
[45]	validation_0-auc:0.89427	validation_1-auc:0.83652
[46]	validation_0-auc:0.89516	validation_1-auc:0.83667
[47]	validation_0-auc:0.89618	validation_1-auc:0.83623
[48]	validation_0-auc:0.89647	validation_1-auc:0.83607
[49]	validation_0-auc:0.89684	validation_1-auc:0.83623
[50]	validation_0-auc:0.89762	validation_1-auc:0.83685
[51]	validation_0-auc:0.89798	validation_1-auc:0.83685
[52]	validation_0-auc:0.89825	validation_1-auc:0.83680
[53]	validation_0-auc:0.89904	validation_1-auc:0.83673
[54]	validation_0-auc:0.89919	validation_1-auc:0.83677
[55]	validation_0-auc:0.89937	validation_1-auc:0.83661
[56]	validation_0-auc:0.89950	validation_1-auc:0.83653
[57]	validation_0-auc:0.90018	validation_1-auc:0.83641
[58]	validation_0-auc:0.90167	validation_1-auc:0.83658
[59]	validation_0-auc:0.90187	validation_1-auc:0.83640
[60]	validation_0-auc:0.90209	validation_1-auc:0.83651
[61]	validation_0-auc:0.90245	validation_1-auc:0.83665
[62]	validation_0-auc:0.90287	validation_1-auc:0.83674
[63]	validation_0-auc:0.90297	validation_1-auc:0.83674
[64]	validation_0-auc:0.90349	validation_1-auc:0.83670
[65]	validation_0-auc:0.90421	validation_1-auc:0.83648
[66]	validation_0-auc:0.90443	validation_1-auc:0.83636
[67]	validation_0-auc:0.90483	validation_1-auc:0.83633
[68]	validation_0-auc:0.90514	validation_1-auc:0.83628
[69]	validation_0-auc:0.90553	validation_1-auc:0.83610
 96%|█████████▌| 48/50 [10:26<00:30, 15.01s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82057	validation_1-auc:0.81074
[1]	validation_0-auc:0.83417	validation_1-auc:0.82603
[2]	validation_0-auc:0.84049	validation_1-auc:0.82890
[3]	validation_0-auc:0.84297	validation_1-auc:0.82985
[4]	validation_0-auc:0.84649	validation_1-auc:0.83246
[5]	validation_0-auc:0.84864	validation_1-auc:0.83258
[6]	validation_0-auc:0.85091	validation_1-auc:0.83334
[7]	validation_0-auc:0.85137	validation_1-auc:0.83440
[8]	validation_0-auc:0.85208	validation_1-auc:0.83463
[9]	validation_0-auc:0.85593	validation_1-auc:0.83492
[10]	validation_0-auc:0.85501	validation_1-auc:0.83309
[11]	validation_0-auc:0.85455	validation_1-auc:0.83117
[12]	validation_0-auc:0.86004	validation_1-auc:0.83455
[13]	validation_0-auc:0.86334	validation_1-auc:0.83682
[14]	validation_0-auc:0.86436	validation_1-auc:0.83843
[15]	validation_0-auc:0.86563	validation_1-auc:0.83903
[16]	validation_0-auc:0.86743	validation_1-auc:0.84006
[17]	validation_0-auc:0.86906	validation_1-auc:0.84183
[18]	validation_0-auc:0.86908	validation_1-auc:0.84084
[19]	validation_0-auc:0.87144	validation_1-auc:0.84194
[20]	validation_0-auc:0.87295	validation_1-auc:0.84354
[21]	validation_0-auc:0.87462	validation_1-auc:0.84307
[22]	validation_0-auc:0.87518	validation_1-auc:0.84386
[23]	validation_0-auc:0.87594	validation_1-auc:0.84393
[24]	validation_0-auc:0.87713	validation_1-auc:0.84371
[25]	validation_0-auc:0.87808	validation_1-auc:0.84393
[26]	validation_0-auc:0.87947	validation_1-auc:0.84409
[27]	validation_0-auc:0.88101	validation_1-auc:0.84417
[28]	validation_0-auc:0.88173	validation_1-auc:0.84337
[29]	validation_0-auc:0.88233	validation_1-auc:0.84376
[30]	validation_0-auc:0.88310	validation_1-auc:0.84404
[31]	validation_0-auc:0.88363	validation_1-auc:0.84399
[32]	validation_0-auc:0.88410	validation_1-auc:0.84492
[33]	validation_0-auc:0.88456	validation_1-auc:0.84529
[34]	validation_0-auc:0.88508	validation_1-auc:0.84517
[35]	validation_0-auc:0.88554	validation_1-auc:0.84555
[36]	validation_0-auc:0.88634	validation_1-auc:0.84540
[37]	validation_0-auc:0.88734	validation_1-auc:0.84506
[38]	validation_0-auc:0.88794	validation_1-auc:0.84505
[39]	validation_0-auc:0.88813	validation_1-auc:0.84517
[40]	validation_0-auc:0.88822	validation_1-auc:0.84521
[41]	validation_0-auc:0.88913	validation_1-auc:0.84502
[42]	validation_0-auc:0.88942	validation_1-auc:0.84498
[43]	validation_0-auc:0.89022	validation_1-auc:0.84497
[44]	validation_0-auc:0.89067	validation_1-auc:0.84491
[45]	validation_0-auc:0.89152	validation_1-auc:0.84478
[46]	validation_0-auc:0.89174	validation_1-auc:0.84476
[47]	validation_0-auc:0.89197	validation_1-auc:0.84481
[48]	validation_0-auc:0.89308	validation_1-auc:0.84493
[49]	validation_0-auc:0.89373	validation_1-auc:0.84480
[50]	validation_0-auc:0.89398	validation_1-auc:0.84493
[51]	validation_0-auc:0.89430	validation_1-auc:0.84483
[52]	validation_0-auc:0.89481	validation_1-auc:0.84481
[53]	validation_0-auc:0.89510	validation_1-auc:0.84464
[54]	validation_0-auc:0.89527	validation_1-auc:0.84461
[55]	validation_0-auc:0.89548	validation_1-auc:0.84470
[56]	validation_0-auc:0.89648	validation_1-auc:0.84461
[57]	validation_0-auc:0.89700	validation_1-auc:0.84475
[58]	validation_0-auc:0.89764	validation_1-auc:0.84468
[59]	validation_0-auc:0.89839	validation_1-auc:0.84457
[60]	validation_0-auc:0.89874	validation_1-auc:0.84456
[61]	validation_0-auc:0.89911	validation_1-auc:0.84439
[62]	validation_0-auc:0.89945	validation_1-auc:0.84425
[63]	validation_0-auc:0.89958	validation_1-auc:0.84412
[64]	validation_0-auc:0.89999	validation_1-auc:0.84407
 98%|█████████▊| 49/50 [10:29<00:13, 13.60s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83423	validation_1-auc:0.81355
[1]	validation_0-auc:0.84293	validation_1-auc:0.81374
[2]	validation_0-auc:0.85055	validation_1-auc:0.81438
[3]	validation_0-auc:0.85498	validation_1-auc:0.81622
[4]	validation_0-auc:0.86324	validation_1-auc:0.81979
[5]	validation_0-auc:0.86602	validation_1-auc:0.82079
[6]	validation_0-auc:0.86996	validation_1-auc:0.82118
[7]	validation_0-auc:0.87268	validation_1-auc:0.82096
[8]	validation_0-auc:0.87668	validation_1-auc:0.82082
[9]	validation_0-auc:0.88607	validation_1-auc:0.82361
[10]	validation_0-auc:0.88710	validation_1-auc:0.82464
[11]	validation_0-auc:0.89138	validation_1-auc:0.82215
[12]	validation_0-auc:0.89884	validation_1-auc:0.82735
[13]	validation_0-auc:0.90172	validation_1-auc:0.82804
[14]	validation_0-auc:0.90386	validation_1-auc:0.83029
[15]	validation_0-auc:0.90736	validation_1-auc:0.83139
[16]	validation_0-auc:0.91091	validation_1-auc:0.83196
[17]	validation_0-auc:0.91343	validation_1-auc:0.83270
[18]	validation_0-auc:0.91444	validation_1-auc:0.83201
[19]	validation_0-auc:0.91728	validation_1-auc:0.83263
[20]	validation_0-auc:0.91961	validation_1-auc:0.83302
[21]	validation_0-auc:0.92145	validation_1-auc:0.83256
[22]	validation_0-auc:0.92399	validation_1-auc:0.83267
[23]	validation_0-auc:0.92606	validation_1-auc:0.83356
[24]	validation_0-auc:0.92861	validation_1-auc:0.83345
[25]	validation_0-auc:0.92937	validation_1-auc:0.83476
[26]	validation_0-auc:0.93121	validation_1-auc:0.83424
[27]	validation_0-auc:0.93354	validation_1-auc:0.83351
[28]	validation_0-auc:0.93525	validation_1-auc:0.83298
[29]	validation_0-auc:0.93716	validation_1-auc:0.83184
[30]	validation_0-auc:0.93959	validation_1-auc:0.83206
[31]	validation_0-auc:0.94097	validation_1-auc:0.83199
[32]	validation_0-auc:0.94201	validation_1-auc:0.83243
[33]	validation_0-auc:0.94275	validation_1-auc:0.83273
[34]	validation_0-auc:0.94364	validation_1-auc:0.83262
[35]	validation_0-auc:0.94529	validation_1-auc:0.83210
[36]	validation_0-auc:0.94678	validation_1-auc:0.83264
[37]	validation_0-auc:0.94742	validation_1-auc:0.83287
[38]	validation_0-auc:0.94809	validation_1-auc:0.83320
[39]	validation_0-auc:0.94843	validation_1-auc:0.83338
[40]	validation_0-auc:0.94872	validation_1-auc:0.83363
[41]	validation_0-auc:0.94956	validation_1-auc:0.83332
[42]	validation_0-auc:0.94981	validation_1-auc:0.83332
[43]	validation_0-auc:0.95029	validation_1-auc:0.83357
[44]	validation_0-auc:0.95095	validation_1-auc:0.83357
[45]	validation_0-auc:0.95128	validation_1-auc:0.83376
[46]	validation_0-auc:0.95151	validation_1-auc:0.83377
[47]	validation_0-auc:0.95186	validation_1-auc:0.83389
[48]	validation_0-auc:0.95223	validation_1-auc:0.83365
[49]	validation_0-auc:0.95260	validation_1-auc:0.83368
[50]	validation_0-auc:0.95309	validation_1-auc:0.83385
[51]	validation_0-auc:0.95385	validation_1-auc:0.83407
[52]	validation_0-auc:0.95408	validation_1-auc:0.83388
[53]	validation_0-auc:0.95438	validation_1-auc:0.83393
[54]	validation_0-auc:0.95460	validation_1-auc:0.83350
 98%|█████████▊| 49/50 [10:34<00:13, 13.60s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.83150	validation_1-auc:0.80846
[1]	validation_0-auc:0.84124	validation_1-auc:0.81425
[2]	validation_0-auc:0.84528	validation_1-auc:0.81542
[3]	validation_0-auc:0.85383	validation_1-auc:0.81856
[4]	validation_0-auc:0.86314	validation_1-auc:0.81914
[5]	validation_0-auc:0.86843	validation_1-auc:0.82049
[6]	validation_0-auc:0.87498	validation_1-auc:0.82083
[7]	validation_0-auc:0.87921	validation_1-auc:0.82193
[8]	validation_0-auc:0.88388	validation_1-auc:0.82333
[9]	validation_0-auc:0.88990	validation_1-auc:0.82388
[10]	validation_0-auc:0.89184	validation_1-auc:0.82505
[11]	validation_0-auc:0.89521	validation_1-auc:0.82404
[12]	validation_0-auc:0.90020	validation_1-auc:0.82576
[13]	validation_0-auc:0.90530	validation_1-auc:0.82641
[14]	validation_0-auc:0.90631	validation_1-auc:0.82815
[15]	validation_0-auc:0.90896	validation_1-auc:0.82757
[16]	validation_0-auc:0.91091	validation_1-auc:0.82822
[17]	validation_0-auc:0.91342	validation_1-auc:0.82874
[18]	validation_0-auc:0.91482	validation_1-auc:0.82873
[19]	validation_0-auc:0.91851	validation_1-auc:0.82927
[20]	validation_0-auc:0.92026	validation_1-auc:0.82869
[21]	validation_0-auc:0.92225	validation_1-auc:0.82940
[22]	validation_0-auc:0.92483	validation_1-auc:0.82991
[23]	validation_0-auc:0.92630	validation_1-auc:0.83020
[24]	validation_0-auc:0.92828	validation_1-auc:0.82925
[25]	validation_0-auc:0.92941	validation_1-auc:0.83025
[26]	validation_0-auc:0.93252	validation_1-auc:0.82851
[27]	validation_0-auc:0.93422	validation_1-auc:0.82839
[28]	validation_0-auc:0.93631	validation_1-auc:0.82847
[29]	validation_0-auc:0.93790	validation_1-auc:0.82847
[30]	validation_0-auc:0.93957	validation_1-auc:0.82782
[31]	validation_0-auc:0.94120	validation_1-auc:0.82806
[32]	validation_0-auc:0.94265	validation_1-auc:0.82749
[33]	validation_0-auc:0.94335	validation_1-auc:0.82783
[34]	validation_0-auc:0.94431	validation_1-auc:0.82744
[35]	validation_0-auc:0.94512	validation_1-auc:0.82869
[36]	validation_0-auc:0.94571	validation_1-auc:0.82850
[37]	validation_0-auc:0.94657	validation_1-auc:0.82811
[38]	validation_0-auc:0.94731	validation_1-auc:0.82825
[39]	validation_0-auc:0.94756	validation_1-auc:0.82859
[40]	validation_0-auc:0.94776	validation_1-auc:0.82866
[41]	validation_0-auc:0.94847	validation_1-auc:0.82902
[42]	validation_0-auc:0.94913	validation_1-auc:0.82877
[43]	validation_0-auc:0.94981	validation_1-auc:0.82826
[44]	validation_0-auc:0.95023	validation_1-auc:0.82820
[45]	validation_0-auc:0.95056	validation_1-auc:0.82778
[46]	validation_0-auc:0.95083	validation_1-auc:0.82771
[47]	validation_0-auc:0.95144	validation_1-auc:0.82774
[48]	validation_0-auc:0.95181	validation_1-auc:0.82763
[49]	validation_0-auc:0.95219	validation_1-auc:0.82767
[50]	validation_0-auc:0.95287	validation_1-auc:0.82809
[51]	validation_0-auc:0.95319	validation_1-auc:0.82815
[52]	validation_0-auc:0.95384	validation_1-auc:0.82779
[53]	validation_0-auc:0.95435	validation_1-auc:0.82818
[54]	validation_0-auc:0.95482	validation_1-auc:0.82809
[55]	validation_0-auc:0.95508	validation_1-auc:0.82783
 98%|█████████▊| 49/50 [10:40<00:13, 13.60s/trial, best loss: -0.8439228763989378]

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(

c:\Users\Win11Pro\Documents\ML\.venv-machineLearning\lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

[0]	validation_0-auc:0.82866	validation_1-auc:0.80796
[1]	validation_0-auc:0.84650	validation_1-auc:0.82096
[2]	validation_0-auc:0.85159	validation_1-auc:0.82314
[3]	validation_0-auc:0.85577	validation_1-auc:0.82624
[4]	validation_0-auc:0.86516	validation_1-auc:0.82871
[5]	validation_0-auc:0.86778	validation_1-auc:0.82867
[6]	validation_0-auc:0.87207	validation_1-auc:0.82955
[7]	validation_0-auc:0.87614	validation_1-auc:0.83037
[8]	validation_0-auc:0.87908	validation_1-auc:0.83137
[9]	validation_0-auc:0.88687	validation_1-auc:0.83161
[10]	validation_0-auc:0.88909	validation_1-auc:0.83024
[11]	validation_0-auc:0.89052	validation_1-auc:0.82751
[12]	validation_0-auc:0.89655	validation_1-auc:0.82842
[13]	validation_0-auc:0.90078	validation_1-auc:0.83054
[14]	validation_0-auc:0.90262	validation_1-auc:0.83208
[15]	validation_0-auc:0.90536	validation_1-auc:0.83423
[16]	validation_0-auc:0.90956	validation_1-auc:0.83598
[17]	validation_0-auc:0.91182	validation_1-auc:0.83710
[18]	validation_0-auc:0.91358	validation_1-auc:0.83471
[19]	validation_0-auc:0.91656	validation_1-auc:0.83631
[20]	validation_0-auc:0.91882	validation_1-auc:0.83706
[21]	validation_0-auc:0.92054	validation_1-auc:0.83740
[22]	validation_0-auc:0.92242	validation_1-auc:0.83829
[23]	validation_0-auc:0.92465	validation_1-auc:0.83765
[24]	validation_0-auc:0.92669	validation_1-auc:0.83771
[25]	validation_0-auc:0.92813	validation_1-auc:0.83817
[26]	validation_0-auc:0.93049	validation_1-auc:0.83626
[27]	validation_0-auc:0.93228	validation_1-auc:0.83713
[28]	validation_0-auc:0.93385	validation_1-auc:0.83684
[29]	validation_0-auc:0.93542	validation_1-auc:0.83670
[30]	validation_0-auc:0.93741	validation_1-auc:0.83644
[31]	validation_0-auc:0.93864	validation_1-auc:0.83663
[32]	validation_0-auc:0.93945	validation_1-auc:0.83665
[33]	validation_0-auc:0.94023	validation_1-auc:0.83671
[34]	validation_0-auc:0.94110	validation_1-auc:0.83661
[35]	validation_0-auc:0.94187	validation_1-auc:0.83687
[36]	validation_0-auc:0.94256	validation_1-auc:0.83765
[37]	validation_0-auc:0.94404	validation_1-auc:0.83761
[38]	validation_0-auc:0.94465	validation_1-auc:0.83748
[39]	validation_0-auc:0.94494	validation_1-auc:0.83797
[40]	validation_0-auc:0.94525	validation_1-auc:0.83786
[41]	validation_0-auc:0.94602	validation_1-auc:0.83723
[42]	validation_0-auc:0.94665	validation_1-auc:0.83699
[43]	validation_0-auc:0.94710	validation_1-auc:0.83683
[44]	validation_0-auc:0.94758	validation_1-auc:0.83729
[45]	validation_0-auc:0.94815	validation_1-auc:0.83769
[46]	validation_0-auc:0.94851	validation_1-auc:0.83732
[47]	validation_0-auc:0.94918	validation_1-auc:0.83757
[48]	validation_0-auc:0.94979	validation_1-auc:0.83751
[49]	validation_0-auc:0.95004	validation_1-auc:0.83757
[50]	validation_0-auc:0.95045	validation_1-auc:0.83736
[51]	validation_0-auc:0.95060	validation_1-auc:0.83758
[52]	validation_0-auc:0.95147	validation_1-auc:0.83731
100%|██████████| 50/50 [10:45<00:00, 12.91s/trial, best loss: -0.8439228763989378]
{'colsample_bytree': 0.5829020839311067, 'learning_rate': 0.15025601599862265, 'max_depth': 5.0, 'min_child_weight': 6.0}

In [21]:
xgb_clf = XGBClassifier(n_estimators = 500,
                        learning_rate  = round(best [ "learning_arte"],5),
                        max_depth = int (best [ "max_depth"]),
                        min_child_weight = int (best ["min_child_weight"]),
                        colsample_bytree = round(best [ "colsample_bytree"],5))

xgb_clf.fit(X_tr, y_tr , early_stopping_rounds = 100 , 
            eval_metric = "auc", eval_set = [(X_tr, y_tr), (X_val ,y_val)])

xgb_auc_score = roc_auc_score(y_test , xgb_clf.predict_proba(X_test)[:,1])

print(xgb_auc_score)

KeyError: 'learning_arte'

In [22]:
from xgboost import plot_importance
import matplotlib.pyplot as plt

fig, ax = plt.subplot(1,1,figsize = (10,8))
plot_importance(xgb_clf, ax = ax , max_num_features= 20 , height =0.4)

TypeError: subplot() takes 1 or 3 positional arguments but 2 were given